-- BG — Bulgaria — 85 venues, 13 cities
-- Idempotent: safe to run multiple times. Source: OpenStreetMap via Overture Maps + GeoNames.
-- STAGED: cities active=false, expansion_status='community_review' (hidden in-app until activated — see DEPLOYMENT.md). Venues approved=true.
BEGIN;
INSERT INTO countries (code,name,active) VALUES ('BG','Bulgaria',true) ON CONFLICT (code) DO NOTHING;
INSERT INTO cities (name,country_code,country_name,admin_area,county,lat,lng,zoom,active,expansion_status) VALUES
  ('Aksakovo','BG','Bulgaria','Varna','Obshtina Aksakovo',43.25907,27.81755,12,false,'community_review'),
  ('Blagoevgrad','BG','Bulgaria','Blagoevgrad','Obshtina Blagoevgrad',42.01457,23.09804,12,false,'community_review'),
  ('Botevgrad','BG','Bulgaria','Sofia','Obshtina Botevgrad',42.90799,23.79274,12,false,'community_review'),
  ('Buhovo','BG','Bulgaria','Sofia-Capital','Stolichna Obshtina',42.76667,23.56667,12,false,'community_review'),
  ('Dupnitsa','BG','Bulgaria','Kyustendil','Obshtina Dupnitsa',42.26478,23.11723,12,false,'community_review'),
  ('Lozen','BG','Bulgaria','Sofia-Capital','Stolichna Obshtina',42.6027,23.47589,12,false,'community_review'),
  ('Pazardzhik','BG','Bulgaria','Pazardzhik','Obshtina Pazardzhik',42.19934,24.33318,12,false,'community_review'),
  ('Pleven','BG','Bulgaria','Pleven','Obshtina Pleven',43.41791,24.61666,12,false,'community_review'),
  ('Plovdiv','BG','Bulgaria','Plovdiv','Obshtina Plovdiv',42.15387,24.75001,12,false,'community_review'),
  ('Sofia','BG','Bulgaria','Sofia-Capital','Stolichna Obshtina',42.69751,23.32415,12,false,'community_review'),
  ('Sozopol','BG','Bulgaria','Burgas','Obshtina Sozopol',42.41801,27.6956,12,false,'community_review'),
  ('Sveti Vlas','BG','Bulgaria','Burgas','Obshtina Nesebar',42.7136,27.75867,12,false,'community_review'),
  ('Varna','BG','Bulgaria','Varna','Obshtina Varna',43.21912,27.91024,12,false,'community_review')
ON CONFLICT (country_code,name) DO NOTHING;
INSERT INTO venues (name,type,city,city_id,county,sector,address,lat,lng,tables_count,free_access,night_lighting,hours,description,tags,approved,verified,submitted_by)
SELECT v.name,v.type,v.city,c.id,v.county::text,v.sector::text,v.address,v.lat::double precision,v.lng::double precision,v.tables_count::int,v.free_access::boolean,v.night_lighting::boolean,v.hours::text,v.description::text,v.tags::text[],v.approved::boolean,v.verified::boolean,NULL
FROM (VALUES
  ('Кайлъка','parc_exterior','Pleven','Obshtina Pleven',NULL,'Кайлъка, Pleven',43.38306,24.63091,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('ФА Средец','parc_exterior','Sofia','Stolichna Obshtina',NULL,'ФА Средец, Sofia',42.66634,23.28576,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Парк Заимов','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Парк Заимов, Sofia',42.697295,23.342575,2,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('парк Свети Николай','parc_exterior','Sofia','Stolichna Obshtina',NULL,'парк Свети Николай, Sofia',42.70217,23.30879,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Парк Надежда','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Парк Надежда, Sofia',42.72189,23.30876,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Парк Надежда (2)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Парк Надежда, Sofia',42.72254,23.31064,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Южен парк','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Южен парк, Sofia',42.6682425,23.3060725,4,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Морска градина','parc_exterior','Varna','Obshtina Varna',NULL,'Морска градина, Varna',43.20737,27.93308,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Парк Борисова градина','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Парк Борисова градина, Sofia',42.6858175,23.338185,4,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Crown Fort Club','parc_exterior','Sveti Vlas','Obshtina Nesebar',NULL,'Crown Fort Club, Sveti Vlas',42.70441,27.7935,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Santa Marina Holiday Village','parc_exterior','Sozopol','Obshtina Sozopol',NULL,'Santa Marina Holiday Village, Sozopol',42.40857,27.67775,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('153. спортно училище "Неофит Рилски"','parc_exterior','Sofia','Stolichna Obshtina',NULL,'153. спортно училище "Неофит Рилски", Sofia',42.73541,23.31106,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('споко','parc_exterior','Sofia','Stolichna Obshtina',NULL,'споко, Sofia',42.67413,23.28913,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('"Спирка 2009 "Костенски водопад""','parc_exterior','Sofia','Stolichna Obshtina',NULL,'"Спирка 2009 "Костенски водопад"", Sofia',42.66551,23.30094,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Primazon','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Primazon, Sofia',42.70512,23.29224,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Детски Клуб Теди','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Детски Клуб Теди, Sofia',42.708505,23.29049,2,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Детски Клуб Теди (2)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Детски Клуб Теди, Sofia',42.70706,23.28979,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Гедон','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Гедон, Sofia',42.71174,23.29887,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Двете Халби (Dvete halbi)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Двете Халби (Dvete halbi), Sofia',42.67565,23.29275,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Южный Парк','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Южный Парк, Sofia',42.69151,23.31394,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Party Taxi','parc_exterior','Sveti Vlas','Obshtina Nesebar',NULL,'Party Taxi, Sveti Vlas',42.70216,27.71839,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('EMS Zone Sofia (i-motion EMS)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'EMS Zone Sofia (i-motion EMS), Sofia',42.70795,23.30222,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('R-sport','parc_exterior','Sofia','Stolichna Obshtina',NULL,'R-sport, Sofia',42.70491,23.30416,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('градина Майчин дом','parc_exterior','Sofia','Stolichna Obshtina',NULL,'градина Майчин дом, Sofia',42.7091133,23.3176467,3,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Северен парк','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Северен парк, Sofia',42.7414533,23.3038433,3,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('164. ГПИЕ "Мигел де Сервантес"','parc_exterior','Sofia','Stolichna Obshtina',NULL,'164. ГПИЕ "Мигел де Сервантес", Sofia',42.693815,23.347295,4,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Студентски парк','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Студентски парк, Sofia',42.65448,23.35079,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Парк Сеславци','parc_exterior','Buhovo','Stolichna Obshtina',NULL,'Парк Сеславци, Buhovo',42.78544,23.51991,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Райска градина','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Райска градина, Sofia',42.66105,23.24992,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Райска градина (2)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Райска градина, Sofia',42.66049,23.24807,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Лаута','parc_exterior','Plovdiv','Obshtina Plovdiv',NULL,'Лаута, Plovdiv',42.13824,24.77717,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Парк Заимов (2)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Парк Заимов, Sofia',42.69686,23.344865,2,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Парк "Гъбките"','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Парк "Гъбките", Sofia',42.685,23.29207,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Княжеска градина','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Княжеска градина, Sofia',42.69032,23.333874,5,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Парк „Хиподрума“','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Парк „Хиподрума“, Sofia',42.679505,23.297575,2,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Стадион "Юнак"','parc_exterior','Pazardzhik','Obshtina Pazardzhik',NULL,'Стадион "Юнак", Pazardzhik',42.1826867,24.3287,3,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Стадион "Юнак" (2)','parc_exterior','Pazardzhik','Obshtina Pazardzhik',NULL,'Стадион "Юнак", Pazardzhik',42.18188,24.32948,3,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Парк "Гъбките" (2)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Парк "Гъбките", Sofia',42.683825,23.293305,2,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Парк „Хиподрума“ (2)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Парк „Хиподрума“, Sofia',42.68184,23.29642,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Комплекс „Цариградски“','parc_exterior','Lozen','Stolichna Obshtina',NULL,'Комплекс „Цариградски“, Lozen',42.64765,23.40028,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('градина Тбилиси','parc_exterior','Sofia','Stolichna Obshtina',NULL,'градина Тбилиси, Sofia',42.672395,23.33439,2,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Улица Люле Бургас','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Улица Люле Бургас, Sofia',42.69608,23.35125,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Парк Здраве','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Парк Здраве, Sofia',42.67703,23.30066,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Demetra Transport Ltd.','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Demetra Transport Ltd., Sofia',42.6767,23.29681,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pegasus Europe','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Pegasus Europe, Sofia',42.69196,23.36742,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Карате Клуб Нихон','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Карате Клуб Нихон, Sofia',42.64249,23.37089,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Дино - Спортни облекла','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Дино - Спортни облекла, Sofia',42.7044,23.30022,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('מונית בורגס','parc_exterior','Sveti Vlas','Obshtina Nesebar',NULL,'מונית בורגס, Sveti Vlas',42.70332,27.71908,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('парк Ботевград','parc_exterior','Botevgrad','Obshtina Botevgrad',NULL,'парк Ботевград, Botevgrad',42.90355,23.78498,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Парк „Сухото дере“','parc_exterior','Lozen','Stolichna Obshtina',NULL,'Парк „Сухото дере“, Lozen',42.630905,23.37895,2,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Северен парк (2)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Северен парк, Sofia',42.7401433,23.29779,3,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Летищен център София','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Летищен център София, Sofia',42.67902,23.404925,2,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Слатинска река','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Слатинска река, Sofia',42.68267,23.37501,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Парк Сеславци (2)','parc_exterior','Buhovo','Stolichna Obshtina',NULL,'Парк Сеславци, Buhovo',42.783015,23.51819,2,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('ОУ Стоян Михайловски','parc_exterior','Aksakovo','Obshtina Aksakovo',NULL,'ОУ Стоян Михайловски, Aksakovo',43.236925,27.861025,2,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Sofia Airport Center Park','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Sofia Airport Center Park, Sofia',42.68168,23.40318,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Tetris Logistic LTD','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Tetris Logistic LTD, Sofia',42.676465,23.31187,2,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('pratki.De','parc_exterior','Sofia','Stolichna Obshtina',NULL,'pratki.De, Sofia',42.68269,23.28784,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Бирария При Водната Кула','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Бирария При Водната Кула, Sofia',42.67296,23.32604,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('В училищния двор','parc_exterior','Sofia','Stolichna Obshtina',NULL,'В училищния двор, Sofia',42.67118,23.28565,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Под липата','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Под липата, Sofia',42.71216,23.37614,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Арсеналски','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Арсеналски, Sofia',42.675,23.31501,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Adidas Outlet Store','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Adidas Outlet Store, Sofia',42.65672,23.27256,2,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('lauta','parc_exterior','Plovdiv','Obshtina Plovdiv',NULL,'lauta, Plovdiv',42.13985,24.76597,3,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Sofia Tech Park','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Sofia Tech Park, Sofia',42.66728,23.37449,2,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Парк „Гео Милев“','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Парк „Гео Милев“, Sofia',42.686735,23.36285,2,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('парк Света Троица','parc_exterior','Sofia','Stolichna Obshtina',NULL,'парк Света Троица, Sofia',42.70397,23.29518,2,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('градина „Площад Родина“','parc_exterior','Sofia','Stolichna Obshtina',NULL,'градина „Площад Родина“, Sofia',42.69988,23.35247,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('ОУ "Цар Симеон I"','parc_exterior','Varna','Obshtina Varna',NULL,'ОУ "Цар Симеон I", Varna',43.21147,27.90285,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('125 СОУ „Проф. Боян Пенев“','parc_exterior','Sofia','Stolichna Obshtina',NULL,'125 СОУ „Проф. Боян Пенев“, Sofia',42.65378,23.37866,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Street Fitness Strelbishte','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Street Fitness Strelbishte, Sofia',42.67351,23.29943,2,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Karate Club Ronin','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Karate Club Ronin, Sofia',42.66944,23.31731,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Rio','parc_exterior','Plovdiv','Obshtina Plovdiv',NULL,'Rio, Plovdiv',42.15201,24.7579567,3,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('детска площадка','parc_exterior','Plovdiv','Obshtina Plovdiv',NULL,'детска площадка, Plovdiv',42.151278,24.760904,5,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Бирария Гладен','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Бирария Гладен, Sofia',42.6722233,23.29953,3,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Do daskaloto','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Do daskaloto, Sofia',42.70996,23.25262,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Площадката на Ния','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Площадката на Ния, Sofia',42.67528,23.30237,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('СКТМ Пирин Благоевград','parc_exterior','Blagoevgrad','Obshtina Blagoevgrad',NULL,'Blagoevgrad',42.01348,23.07746,1,false,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Парк "Рила" (Дупница)','parc_exterior','Dupnitsa','Obshtina Dupnitsa',NULL,'Парк "Рила" (Дупница), Dupnitsa',42.24808,23.1457,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Софийска математическа гимназия „Паисий Хилендарски“','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Софийска математическа гимназия „Паисий Хилендарски“, Sofia',42.701355,23.333315,2,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Западна порта към Западен парк','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Западна порта към Западен парк, Sofia',42.712155,23.27463,2,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('IV ЕГ Жолио Кюри','parc_exterior','Varna','Obshtina Varna',NULL,'IV ЕГ Жолио Кюри, Varna',43.21893,27.95187,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Западен парк','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Западен парк, Sofia',42.7120729,23.2833171,7,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Парк Младост 2','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Парк Младост 2, Sofia',42.64516,23.37247,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Vibro Fit Bulgaria','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Vibro Fit Bulgaria, Sofia',42.69265,23.28399,1,true,false,NULL,NULL,ARRAY['exterior'],true,false)
) AS v(name,type,city,county,sector,address,lat,lng,tables_count,free_access,night_lighting,hours,description,tags,approved,verified)
JOIN cities c ON c.country_code='BG' AND c.name=v.city
ON CONFLICT (name,city_id) DO NOTHING;
COMMIT;
