-- BG — Bulgaria — 142 venues, 13 cities
-- Idempotent: safe to run multiple times. Source: OpenStreetMap via Overture Maps + GeoNames.
-- STAGED: cities active=false, expansion_status='community_review' (hidden in-app until activated — see DEPLOYMENT.md). Venues approved=true.
BEGIN;
INSERT INTO countries (code,name,active) VALUES ('BG','Bulgaria',true) ON CONFLICT (code) DO NOTHING;
INSERT INTO cities (name,country_code,country_name,admin_area,county,lat,lng,zoom,active,expansion_status) VALUES
  ('Aksakovo','BG','Bulgaria','Varna','Obshtina Aksakovo',43.25907,27.81755,12,false,'community_review'),
  ('Blagoevgrad','BG','Bulgaria','Blagoevgrad','Obshtina Blagoevgrad',42.01457,23.09804,12,false,'community_review'),
  ('Botevgrad','BG','Bulgaria','Sofia','Obshtina Botevgrad',42.90799,23.79274,12,false,'community_review'),
  ('Buhovo','BG','Bulgaria','Sofia-Capital','Stolichna Obshtina',42.76667,23.56667,12,false,'community_review'),
  ('Dupnitsa','BG','Bulgaria','Kyustendil','Obshtina Dupnitsa',42.26478,23.11723,12,false,'community_review'),
  ('Lozen','BG','Bulgaria','Sofia-Capital','Stolichna Obshtina',42.6027,23.47589,12,false,'community_review'),
  ('Pazardzhik','BG','Bulgaria','Pazardzhik','Obshtina Pazardzhik',42.19934,24.33318,12,false,'community_review'),
  ('Pleven','BG','Bulgaria','Pleven','Obshtina Pleven',43.41791,24.61666,12,false,'community_review'),
  ('Plovdiv','BG','Bulgaria','Plovdiv','Obshtina Plovdiv',42.15387,24.75001,12,false,'community_review'),
  ('Sofia','BG','Bulgaria','Sofia-Capital','Stolichna Obshtina',42.69751,23.32415,12,false,'community_review'),
  ('Sozopol','BG','Bulgaria','Burgas','Obshtina Sozopol',42.41801,27.6956,12,false,'community_review'),
  ('Sveti Vlas','BG','Bulgaria','Burgas','Obshtina Nesebar',42.7136,27.75867,12,false,'community_review'),
  ('Varna','BG','Bulgaria','Varna','Obshtina Varna',43.21912,27.91024,12,false,'community_review')
ON CONFLICT (country_code,name) DO NOTHING;
INSERT INTO venues (name,type,city,city_id,county,sector,address,lat,lng,tables_count,free_access,night_lighting,hours,description,tags,approved,verified,submitted_by)
SELECT v.name,v.type,v.city,c.id,v.county::text,v.sector::text,v.address,v.lat::double precision,v.lng::double precision,v.tables_count::int,v.free_access::boolean,v.night_lighting::boolean,v.hours::text,v.description::text,v.tags::text[],v.approved::boolean,v.verified::boolean,NULL
FROM (VALUES
  ('Тенис на маса Кайлъка','parc_exterior','Pleven','Obshtina Pleven',NULL,'Кайлъка, Pleven',43.38306,24.63091,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса ФА Средец','parc_exterior','Sofia','Stolichna Obshtina',NULL,'ФА Средец, Sofia',42.66634,23.28576,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Парк Заимов','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Парк Заимов, Sofia',42.69732,23.34257,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Парк Заимов (2)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Парк Заимов, Sofia',42.69727,23.34258,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса парк Свети Николай','parc_exterior','Sofia','Stolichna Obshtina',NULL,'парк Свети Николай, Sofia',42.70217,23.30879,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Парк Надежда','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Парк Надежда, Sofia',42.72189,23.30876,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Парк Надежда (2)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Парк Надежда, Sofia',42.72254,23.31064,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Южен парк','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Южен парк, Sofia',42.66807,23.30605,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Южен парк (2)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Южен парк, Sofia',42.6681,23.30606,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Южен парк (3)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Южен парк, Sofia',42.66812,23.30606,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Морска градина','parc_exterior','Varna','Obshtina Varna',NULL,'Морска градина, Varna',43.20737,27.93308,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Парк Борисова градина','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Парк Борисова градина, Sofia',42.68578,23.33814,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Crown Fort Club','parc_exterior','Sveti Vlas','Obshtina Nesebar',NULL,'Crown Fort Club, Sveti Vlas',42.70441,27.7935,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Santa Marina Holiday Village','parc_exterior','Sozopol','Obshtina Sozopol',NULL,'Santa Marina Holiday Village, Sozopol',42.40857,27.67775,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса 153. спортно училище "Неофит Рилски"','parc_exterior','Sofia','Stolichna Obshtina',NULL,'153. спортно училище "Неофит Рилски", Sofia',42.73541,23.31106,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса споко','parc_exterior','Sofia','Stolichna Obshtina',NULL,'споко, Sofia',42.67413,23.28913,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса "Спирка 2009 "Костенски водопад""','parc_exterior','Sofia','Stolichna Obshtina',NULL,'"Спирка 2009 "Костенски водопад"", Sofia',42.66551,23.30094,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Primazon','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Primazon, Sofia',42.70512,23.29224,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Детски Клуб Теди','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Детски Клуб Теди, Sofia',42.70825,23.29074,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Детски Клуб Теди (2)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Детски Клуб Теди, Sofia',42.70706,23.28979,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Детски Клуб Теди (3)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Детски Клуб Теди, Sofia',42.70876,23.29024,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Гедон','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Гедон, Sofia',42.71174,23.29887,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Двете Халби (Dvete halbi)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Двете Халби (Dvete halbi), Sofia',42.67565,23.29275,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Южный Парк','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Южный Парк, Sofia',42.69151,23.31394,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Party Taxi','parc_exterior','Sveti Vlas','Obshtina Nesebar',NULL,'Party Taxi, Sveti Vlas',42.70216,27.71839,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса EMS Zone Sofia (i-motion EMS)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'EMS Zone Sofia (i-motion EMS), Sofia',42.70795,23.30222,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса R-sport','parc_exterior','Sofia','Stolichna Obshtina',NULL,'R-sport, Sofia',42.70491,23.30416,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса градина Майчин дом','parc_exterior','Sofia','Stolichna Obshtina',NULL,'градина Майчин дом, Sofia',42.70912,23.31758,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса градина Майчин дом (2)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'градина Майчин дом, Sofia',42.70912,23.31765,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса градина Майчин дом (3)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'градина Майчин дом, Sofia',42.7091,23.31771,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Северен парк','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Северен парк, Sofia',42.74145,23.30384,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса 164. ГПИЕ "Мигел де Сервантес"','parc_exterior','Sofia','Stolichna Obshtina',NULL,'164. ГПИЕ "Мигел де Сервантес", Sofia',42.69382,23.34724,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса 164. ГПИЕ "Мигел де Сервантес" (2)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'164. ГПИЕ "Мигел де Сервантес", Sofia',42.69382,23.34728,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса 164. ГПИЕ "Мигел де Сервантес" (3)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'164. ГПИЕ "Мигел де Сервантес", Sofia',42.69381,23.34731,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса 164. ГПИЕ "Мигел де Сервантес" (4)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'164. ГПИЕ "Мигел де Сервантес", Sofia',42.69381,23.34735,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Студентски парк','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Студентски парк, Sofia',42.65448,23.35079,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Парк Сеславци','parc_exterior','Buhovo','Stolichna Obshtina',NULL,'Парк Сеславци, Buhovo',42.78544,23.51991,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Райска градина','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Райска градина, Sofia',42.66105,23.24992,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Райска градина (2)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Райска градина, Sofia',42.66049,23.24807,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Лаута','parc_exterior','Plovdiv','Obshtina Plovdiv',NULL,'Лаута, Plovdiv',42.13824,24.77717,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Парк Борисова градина (2)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Парк Борисова градина, Sofia',42.6858,23.33816,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Парк Борисова градина (3)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Парк Борисова градина, Sofia',42.68583,23.3382,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Парк Борисова градина (4)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Парк Борисова градина, Sofia',42.68586,23.33824,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Парк Заимов (3)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Парк Заимов, Sofia',42.69686,23.34503,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Парк "Гъбките"','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Парк "Гъбките", Sofia',42.685,23.29207,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Княжеска градина','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Княжеска градина, Sofia',42.69026,23.33401,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Княжеска градина (2)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Княжеска градина, Sofia',42.69023,23.33396,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Княжеска градина (3)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Княжеска градина, Sofia',42.6904,23.33385,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Княжеска градина (4)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Княжеска градина, Sofia',42.69037,23.3338,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Княжеска градина (5)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Княжеска градина, Sofia',42.69034,23.33375,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Парк „Хиподрума“','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Парк „Хиподрума“, Sofia',42.67949,23.29755,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Парк „Хиподрума“ (2)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Парк „Хиподрума“, Sofia',42.67952,23.2976,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Стадион "Юнак"','parc_exterior','Pazardzhik','Obshtina Pazardzhik',NULL,'Стадион "Юнак", Pazardzhik',42.18265,24.32864,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Стадион "Юнак" (2)','parc_exterior','Pazardzhik','Obshtina Pazardzhik',NULL,'Стадион "Юнак", Pazardzhik',42.18268,24.32868,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Стадион "Юнак" (3)','parc_exterior','Pazardzhik','Obshtina Pazardzhik',NULL,'Стадион "Юнак", Pazardzhik',42.18273,24.32878,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Стадион "Юнак" (4)','parc_exterior','Pazardzhik','Obshtina Pazardzhik',NULL,'Стадион "Юнак", Pazardzhik',42.18184,24.32938,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Стадион "Юнак" (5)','parc_exterior','Pazardzhik','Obshtina Pazardzhik',NULL,'Стадион "Юнак", Pazardzhik',42.18187,24.32948,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Стадион "Юнак" (6)','parc_exterior','Pazardzhik','Obshtina Pazardzhik',NULL,'Стадион "Юнак", Pazardzhik',42.18193,24.32958,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Парк "Гъбките" (2)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Парк "Гъбките", Sofia',42.6838,23.29333,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Парк Заимов (4)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Парк Заимов, Sofia',42.69686,23.3447,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Парк „Хиподрума“ (3)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Парк „Хиподрума“, Sofia',42.68184,23.29642,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Комплекс „Цариградски“','parc_exterior','Lozen','Stolichna Obshtina',NULL,'Комплекс „Цариградски“, Lozen',42.64765,23.40028,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса градина Тбилиси','parc_exterior','Sofia','Stolichna Obshtina',NULL,'градина Тбилиси, Sofia',42.67243,23.33443,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса градина Тбилиси (2)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'градина Тбилиси, Sofia',42.67236,23.33435,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Улица Люле Бургас','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Улица Люле Бургас, Sofia',42.69608,23.35125,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Парк Здраве','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Парк Здраве, Sofia',42.67703,23.30066,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Demetra Transport Ltd.','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Demetra Transport Ltd., Sofia',42.6767,23.29681,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Pegasus Europe','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Pegasus Europe, Sofia',42.69196,23.36742,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Карате Клуб Нихон','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Карате Клуб Нихон, Sofia',42.64249,23.37089,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Дино - Спортни облекла','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Дино - Спортни облекла, Sofia',42.7044,23.30022,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса מונית בורגס','parc_exterior','Sveti Vlas','Obshtina Nesebar',NULL,'מונית בורגס, Sveti Vlas',42.70332,27.71908,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Парк "Гъбките" (3)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Парк "Гъбките", Sofia',42.68385,23.29328,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса парк Ботевград','parc_exterior','Botevgrad','Obshtina Botevgrad',NULL,'парк Ботевград, Botevgrad',42.90355,23.78498,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Парк „Сухото дере“','parc_exterior','Lozen','Stolichna Obshtina',NULL,'Парк „Сухото дере“, Lozen',42.63093,23.37895,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Парк „Сухото дере“ (2)','parc_exterior','Lozen','Stolichna Obshtina',NULL,'Парк „Сухото дере“, Lozen',42.63088,23.37895,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Северен парк (2)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Северен парк, Sofia',42.73997,23.2979,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Северен парк (3)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Северен парк, Sofia',42.74029,23.29768,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Летищен център София','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Летищен център София, Sofia',42.67903,23.40487,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Летищен център София (2)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Летищен център София, Sofia',42.67901,23.40498,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Слатинска река','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Слатинска река, Sofia',42.68267,23.37501,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Парк Сеславци (2)','parc_exterior','Buhovo','Stolichna Obshtina',NULL,'Парк Сеславци, Buhovo',42.78317,23.51865,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Парк Сеславци (3)','parc_exterior','Buhovo','Stolichna Obshtina',NULL,'Парк Сеславци, Buhovo',42.78286,23.51773,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса ОУ Стоян Михайловски','parc_exterior','Aksakovo','Obshtina Aksakovo',NULL,'ОУ Стоян Михайловски, Aksakovo',43.23692,27.86085,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса ОУ Стоян Михайловски (2)','parc_exterior','Aksakovo','Obshtina Aksakovo',NULL,'ОУ Стоян Михайловски, Aksakovo',43.23693,27.8612,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Sofia Airport Center Park','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Sofia Airport Center Park, Sofia',42.68168,23.40318,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Tetris Logistic LTD','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Tetris Logistic LTD, Sofia',42.67647,23.31185,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Tetris Logistic LTD (2)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Tetris Logistic LTD, Sofia',42.67646,23.31189,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса pratki.De','parc_exterior','Sofia','Stolichna Obshtina',NULL,'pratki.De, Sofia',42.68269,23.28784,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Бирария При Водната Кула','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Бирария При Водната Кула, Sofia',42.67296,23.32604,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса В училищния двор','parc_exterior','Sofia','Stolichna Obshtina',NULL,'В училищния двор, Sofia',42.67118,23.28565,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Под липата','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Под липата, Sofia',42.71216,23.37614,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Арсеналски','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Арсеналски, Sofia',42.675,23.31501,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Adidas Outlet Store','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Adidas Outlet Store, Sofia',42.65674,23.2725,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Adidas Outlet Store (2)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Adidas Outlet Store, Sofia',42.6567,23.27262,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса lauta','parc_exterior','Plovdiv','Obshtina Plovdiv',NULL,'lauta, Plovdiv',42.13985,24.76599,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса lauta (2)','parc_exterior','Plovdiv','Obshtina Plovdiv',NULL,'lauta, Plovdiv',42.13982,24.76596,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса lauta (3)','parc_exterior','Plovdiv','Obshtina Plovdiv',NULL,'lauta, Plovdiv',42.13988,24.76596,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Северен парк (4)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Северен парк, Sofia',42.74146,23.30378,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Северен парк (5)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Северен парк, Sofia',42.74145,23.30391,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Северен парк (6)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Северен парк, Sofia',42.74017,23.29779,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Южен парк (4)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Южен парк, Sofia',42.66868,23.30612,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Sofia Tech Park','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Sofia Tech Park, Sofia',42.6673,23.37453,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Sofia Tech Park (2)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Sofia Tech Park, Sofia',42.66726,23.37445,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Парк „Гео Милев“','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Парк „Гео Милев“, Sofia',42.68669,23.36291,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Парк „Гео Милев“ (2)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Парк „Гео Милев“, Sofia',42.68678,23.36279,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса парк Света Троица','parc_exterior','Sofia','Stolichna Obshtina',NULL,'парк Света Троица, Sofia',42.70394,23.29517,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса парк Света Троица (2)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'парк Света Троица, Sofia',42.704,23.29519,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса градина „Площад Родина“','parc_exterior','Sofia','Stolichna Obshtina',NULL,'градина „Площад Родина“, Sofia',42.69988,23.35247,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса ОУ "Цар Симеон I"','parc_exterior','Varna','Obshtina Varna',NULL,'ОУ "Цар Симеон I", Varna',43.21147,27.90285,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса 125 СОУ „Проф. Боян Пенев“','parc_exterior','Sofia','Stolichna Obshtina',NULL,'125 СОУ „Проф. Боян Пенев“, Sofia',42.65378,23.37866,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Street Fitness Strelbishte','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Street Fitness Strelbishte, Sofia',42.67349,23.29941,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Karate Club Ronin','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Karate Club Ronin, Sofia',42.66944,23.31731,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Rio (2)','parc_exterior','Plovdiv','Obshtina Plovdiv',NULL,'Rio, Plovdiv',42.152,24.75791,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Rio (3)','parc_exterior','Plovdiv','Obshtina Plovdiv',NULL,'Rio, Plovdiv',42.15202,24.758,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса детска площадка (2)','parc_exterior','Plovdiv','Obshtina Plovdiv',NULL,'детска площадка, Plovdiv',42.15133,24.76094,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса детска площадка (3)','parc_exterior','Plovdiv','Obshtina Plovdiv',NULL,'детска площадка, Plovdiv',42.15122,24.76094,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса детска площадка (4)','parc_exterior','Plovdiv','Obshtina Plovdiv',NULL,'детска площадка, Plovdiv',42.15122,24.76087,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса детска площадка (5)','parc_exterior','Plovdiv','Obshtina Plovdiv',NULL,'детска площадка, Plovdiv',42.15134,24.76087,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Бирария Гладен','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Бирария Гладен, Sofia',42.67219,23.29956,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Бирария Гладен (2)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Бирария Гладен, Sofia',42.67225,23.29953,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Бирария Гладен (3)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Бирария Гладен, Sofia',42.67223,23.2995,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Street Fitness Strelbishte (2)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Street Fitness Strelbishte, Sofia',42.67353,23.29945,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Do daskaloto','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Do daskaloto, Sofia',42.70996,23.25262,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Площадката на Ния','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Площадката на Ния, Sofia',42.67528,23.30237,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('СКТМ Пирин Благоевград','parc_exterior','Blagoevgrad','Obshtina Blagoevgrad',NULL,'Blagoevgrad',42.01348,23.07746,1,false,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Парк "Рила" (Дупница)','parc_exterior','Dupnitsa','Obshtina Dupnitsa',NULL,'Парк "Рила" (Дупница), Dupnitsa',42.24808,23.1457,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Софийска математическа гимназия „Паисий Хилендарски“','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Софийска математическа гимназия „Паисий Хилендарски“, Sofia',42.7013,23.33308,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Софийска математическа гимназия „Паисий Хилендарски“ (2)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Софийска математическа гимназия „Паисий Хилендарски“, Sofia',42.70141,23.33355,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Западна порта към Западен парк','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Западна порта към Западен парк, Sofia',42.71219,23.27465,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Западна порта към Западен парк (2)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Западна порта към Западен парк, Sofia',42.71212,23.27461,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса IV ЕГ Жолио Кюри','parc_exterior','Varna','Obshtina Varna',NULL,'IV ЕГ Жолио Кюри, Varna',43.21893,27.95187,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Западен парк','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Западен парк, Sofia',42.7121,23.28321,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Западен парк (2)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Западен парк, Sofia',42.71208,23.28326,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Западен парк (3)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Западен парк, Sofia',42.71203,23.28334,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Западен парк (4)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Западен парк, Sofia',42.71201,23.28339,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Западен парк (5)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Западен парк, Sofia',42.71215,23.28329,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Западен парк (6)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Западен парк, Sofia',42.71208,23.28343,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Западен парк (7)','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Западен парк, Sofia',42.71206,23.2833,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Парк Младост 2','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Парк Младост 2, Sofia',42.64516,23.37247,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Vibro Fit Bulgaria','parc_exterior','Sofia','Stolichna Obshtina',NULL,'Vibro Fit Bulgaria, Sofia',42.69265,23.28399,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса Rio','parc_exterior','Plovdiv','Obshtina Plovdiv',NULL,'Rio, Plovdiv',42.15201,24.75796,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенис на маса детска площадка','parc_exterior','Plovdiv','Obshtina Plovdiv',NULL,'детска площадка, Plovdiv',42.15128,24.7609,1,true,false,NULL,NULL,ARRAY['exterior'],true,false)
) AS v(name,type,city,county,sector,address,lat,lng,tables_count,free_access,night_lighting,hours,description,tags,approved,verified)
JOIN cities c ON c.country_code='BG' AND c.name=v.city
ON CONFLICT (name,city_id) DO NOTHING;
COMMIT;
