-- DK — Denmark — 117 venues, 52 cities
-- Idempotent: safe to run multiple times. Source: OpenStreetMap via Overture Maps + GeoNames.
-- STAGED: cities active=false, expansion_status='community_review' (hidden in-app until activated — see DEPLOYMENT.md). Venues approved=true.
BEGIN;
INSERT INTO countries (code,name,active) VALUES ('DK','Denmark',true) ON CONFLICT (code) DO NOTHING;
INSERT INTO cities (name,country_code,country_name,admin_area,county,lat,lng,zoom,active,expansion_status) VALUES
  ('Aalborg','DK','Denmark','North Denmark','Ålborg Kommune',57.048,9.9187,12,false,'community_review'),
  ('Allinge','DK','Denmark','Capital Region','Bornholm Kommune',55.27589,14.80236,12,false,'community_review'),
  ('Århus','DK','Denmark','Central Jutland','Aarhus Kommune',56.15674,10.21076,12,false,'community_review'),
  ('Augustenborg','DK','Denmark','South Denmark','Sønderborg Kommune',54.95201,9.87216,12,false,'community_review'),
  ('Ballerup','DK','Denmark','Capital Region','Ballerup Kommune',55.73165,12.36328,12,false,'community_review'),
  ('Buddinge','DK','Denmark','Capital Region','Gladsaxe Municipality',55.74818,12.49532,12,false,'community_review'),
  ('Farum','DK','Denmark','Capital Region','Furesø Kommune',55.80858,12.36066,12,false,'community_review'),
  ('Fløng','DK','Denmark','Capital Region','Høje-Taastrup Kommune',55.66212,12.18698,12,false,'community_review'),
  ('Fredericia','DK','Denmark','South Denmark','Fredericia Kommune',55.56568,9.75257,12,false,'community_review'),
  ('Frederiksberg','DK','Denmark','Capital Region','Frederiksberg Kommune',55.67938,12.53463,12,false,'community_review'),
  ('Gjellerup','DK','Denmark','Central Jutland','Aarhus Kommune',56.15683,10.13008,12,false,'community_review'),
  ('Gjern','DK','Denmark','Central Jutland','Silkeborg Kommune',56.23023,9.73912,12,false,'community_review'),
  ('Gråsten','DK','Denmark','South Denmark','Sønderborg Kommune',54.91918,9.59523,12,false,'community_review'),
  ('Hadsten','DK','Denmark','Central Jutland','Favrskov Kommune',56.32819,10.04931,12,false,'community_review'),
  ('Herlev','DK','Denmark','Capital Region','Herlev Kommune',55.72366,12.43998,12,false,'community_review'),
  ('Hjørring','DK','Denmark','North Denmark','Hjørring Kommune',57.46417,9.98229,12,false,'community_review'),
  ('Hornslet','DK','Denmark','Central Jutland','Syddjurs Kommune',56.3155,10.32041,12,false,'community_review'),
  ('Humlebæk','DK','Denmark','Capital Region','Fredensborg Kommune',55.9618,12.5341,12,false,'community_review'),
  ('Hvidovre','DK','Denmark','Capital Region','Hvidovre Kommune',55.64297,12.47708,12,false,'community_review'),
  ('Kerteminde','DK','Denmark','South Denmark','Kerteminde Kommune',55.44903,10.65769,12,false,'community_review'),
  ('København','DK','Denmark','Capital Region','København',55.67594,12.56553,12,false,'community_review'),
  ('Kokkedal','DK','Denmark','Capital Region','Fredensborg Kommune',55.91179,12.49952,12,false,'community_review'),
  ('Kolding','DK','Denmark','South Denmark','Kolding Kommune',55.4904,9.47216,12,false,'community_review'),
  ('Korsør','DK','Denmark','Zealand','Slagelse Kommune',55.32993,11.13857,12,false,'community_review'),
  ('Langeskov','DK','Denmark','South Denmark','Kerteminde Kommune',55.35655,10.58447,12,false,'community_review'),
  ('Løjt Kirkeby','DK','Denmark','South Denmark','Aabenraa Kommune',55.08959,9.46084,12,false,'community_review'),
  ('Lunderskov','DK','Denmark','South Denmark','Kolding Kommune',55.48375,9.29917,12,false,'community_review'),
  ('Lystrup','DK','Denmark','Central Jutland','Aarhus Kommune',56.2375,10.23778,12,false,'community_review'),
  ('Neder Holluf','DK','Denmark','South Denmark','Odense Kommune',55.36451,10.44824,12,false,'community_review'),
  ('Nørre Broby','DK','Denmark','South Denmark','Faaborg-Midtfyn Kommune',55.25164,10.22953,12,false,'community_review'),
  ('Odense','DK','Denmark','South Denmark','Odense Kommune',55.39594,10.38831,12,false,'community_review'),
  ('Oksbøl','DK','Denmark','South Denmark','Varde Kommune',55.6268,8.28757,12,false,'community_review'),
  ('Ringe','DK','Denmark','South Denmark','Faaborg-Midtfyn Kommune',55.23828,10.4786,12,false,'community_review'),
  ('Rønne','DK','Denmark','Capital Region','Bornholm Kommune',55.10091,14.70664,12,false,'community_review'),
  ('Skaerbaek','DK','Denmark','South Denmark','Tønder Kommune',55.15735,8.76901,12,false,'community_review'),
  ('Skovby','DK','Denmark','Central Jutland','Skanderborg Kommune',56.15672,9.94523,12,false,'community_review'),
  ('Snejbjerg','DK','Denmark','Central Jutland','Herning Kommune',56.13291,8.90353,12,false,'community_review'),
  ('Søften','DK','Denmark','Central Jutland','Favrskov Kommune',56.23801,10.0851,12,false,'community_review'),
  ('Solrød','DK','Denmark','Zealand','Solrød Kommune',55.53628,12.1827,12,false,'community_review'),
  ('Sønder Bjert','DK','Denmark','South Denmark','Kolding Kommune',55.45272,9.56741,12,false,'community_review'),
  ('Sønderborg','DK','Denmark','South Denmark','Sønderborg Kommune',54.90896,9.78917,12,false,'community_review'),
  ('Store Merløse','DK','Denmark','Zealand','Holbæk Kommune',55.54382,11.71303,12,false,'community_review'),
  ('Struer','DK','Denmark','Central Jutland','Struer Kommune',56.49205,8.59397,12,false,'community_review'),
  ('Svendborg','DK','Denmark','South Denmark','Svendborg Kommune',55.05982,10.60677,12,false,'community_review'),
  ('Tårnby','DK','Denmark','Capital Region','Tårnby Kommune',55.6303,12.60035,12,false,'community_review'),
  ('Værløse','DK','Denmark','Capital Region','Furesø Kommune',55.78251,12.36856,12,false,'community_review'),
  ('Vallensbæk','DK','Denmark','Capital Region','Vallensbæk Kommune',55.62199,12.38511,12,false,'community_review'),
  ('Vejen','DK','Denmark','South Denmark','Vejen Kommune',55.48117,9.13795,12,false,'community_review'),
  ('Vemb','DK','Denmark','Central Jutland','Holstebro Kommune',56.3423,8.33749,12,false,'community_review'),
  ('Viby','DK','Denmark','Central Jutland','Aarhus Kommune',56.12259,10.15145,12,false,'community_review'),
  ('Vinderup','DK','Denmark','Central Jutland','Holstebro Kommune',56.48176,8.77991,12,false,'community_review'),
  ('Vordingborg','DK','Denmark','Zealand','Vordingborg Kommune',55.00801,11.91057,12,false,'community_review')
ON CONFLICT (country_code,name) DO NOTHING;
INSERT INTO venues (name,type,city,city_id,county,sector,address,lat,lng,tables_count,free_access,night_lighting,hours,description,tags,approved,verified,submitted_by)
SELECT v.name,v.type,v.city,c.id,v.county::text,v.sector::text,v.address,v.lat::double precision,v.lng::double precision,v.tables_count::int,v.free_access::boolean,v.night_lighting::boolean,v.hours::text,v.description::text,v.tags::text[],v.approved::boolean,v.verified::boolean,NULL
FROM (VALUES
  ('Bordtennis First Camp Lakolk Strand-Rømø','parc_exterior','Skaerbaek','Tønder Kommune',NULL,'Lakolk Butikscenter 5, Skaerbaek',55.14679,8.49421,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Dalby Skole','parc_exterior','Kolding','Kolding Kommune',NULL,'Dalbyvej 120, Kolding',55.47363,9.513,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Dalby Skole (2)','parc_exterior','Kolding','Kolding Kommune',NULL,'Dalbyvej 118, Kolding',55.47357,9.51301,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Sjølund-Hejls Skole','parc_exterior','Sønder Bjert','Kolding Kommune',NULL,'Skamlingvejen 161, Sønder Bjert',55.40445,9.53168,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Sjølund-Hejls Skole (2)','parc_exterior','Sønder Bjert','Kolding Kommune',NULL,'Skamlingvejen 161, Sønder Bjert',55.40443,9.5316,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Herskindskolen','parc_exterior','Skovby','Skanderborg Kommune',NULL,'Ladingvej 16B, Skovby',56.19016,9.96533,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Herskindskolen (2)','parc_exterior','Skovby','Skanderborg Kommune',NULL,'Ladingvej 16B, Skovby',56.19018,9.96492,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Herskindskolen (3)','parc_exterior','Skovby','Skanderborg Kommune',NULL,'Ladingvej 16B, Skovby',56.19029,9.96598,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('SISU MBK','parc_exterior','Århus','Aarhus Kommune',NULL,'Skt. Pauls Gade 51, Århus',56.14612,10.19842,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Legepladsen i Skydebanehaven','parc_exterior','København','København',NULL,'Absalonsgade 28A, København',55.67019,12.55402,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis BaNanna Park','parc_exterior','Frederiksberg','Frederiksberg Kommune',NULL,'Nannasgade 6, Frederiksberg',55.69985,12.54937,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Balders Plads','parc_exterior','Frederiksberg','Frederiksberg Kommune',NULL,'Balders Plads 1, Frederiksberg',55.70124,12.54893,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Munkebjerg Park','parc_exterior','Neder Holluf','Odense Kommune',NULL,'Munkebjergvænget 3, Neder Holluf',55.37298,10.40762,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Øster Farimagsgade Skole','parc_exterior','København','København',NULL,'Upsalagade 23, København',55.69258,12.5782,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Mimersparken (2)','parc_exterior','Frederiksberg','Frederiksberg Kommune',NULL,'Mjølnerparken 52A, Frederiksberg',55.70381,12.54116,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Mølleparken','parc_exterior','Århus','Aarhus Kommune',NULL,'Møllegade 3A, Århus',56.1561,10.20018,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Ørstedsparken','parc_exterior','København','København',NULL,'Ahlefeldtsgade 18A, København',55.68279,12.5666,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Lundgårdskolen','parc_exterior','Snejbjerg','Herning Kommune',NULL,'Tjelevej 25, Snejbjerg',56.15138,8.92933,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Lundgårdskolen (2)','parc_exterior','Snejbjerg','Herning Kommune',NULL,'Tjelevej 25, Snejbjerg',56.15147,8.92955,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Nationalpark Vadehavet','parc_exterior','Skaerbaek','Tønder Kommune',NULL,'Vestergade 3A, Skaerbaek',55.08534,8.559,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Nationalpark Vadehavet (2)','parc_exterior','Skaerbaek','Tønder Kommune',NULL,'Vestergade 3A, Skaerbaek',55.08536,8.55899,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Limfjords Camping','parc_exterior','Vinderup','Holstebro Kommune',NULL,'Ålbæk Strandvej 7, Vinderup',56.62304,8.72897,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Limfjords Camping (2)','parc_exterior','Vinderup','Holstebro Kommune',NULL,'Ålbæk Strandvej 9A, Vinderup',56.62211,8.72725,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Lunderskov Efterskole','parc_exterior','Lunderskov','Kolding Kommune',NULL,'Skolevej 19, Lunderskov',55.47366,9.29737,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Augustenborg Yachthavn','parc_exterior','Augustenborg','Sønderborg Kommune',NULL,'Langdel 6C, Augustenborg',54.94166,9.87034,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Borgerlunden','parc_exterior','Struer','Struer Kommune',NULL,'Åparken 192, Struer',56.48204,8.5858,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Holmeskov','parc_exterior','Kerteminde','Kerteminde Kommune',NULL,'Skovvej 45, Kerteminde',55.44369,10.66416,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Søndermarkskolen','parc_exterior','Frederiksberg','Frederiksberg Kommune',NULL,'Troels-Lunds Vej 9, Frederiksberg',55.6751,12.50307,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Ho Ferie- og Aktivitetscenter','parc_exterior','Oksbøl','Varde Kommune',NULL,'Sønderballevej 9A, Oksbøl',55.5485,8.22915,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Coast 2 Coast','parc_exterior','Hjørring','Hjørring Kommune',NULL,'Nordre Klitvej 918, Hjørring',57.49376,9.83677,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Aalborg Sundhedscenter - Haraldslund','parc_exterior','Aalborg','Ålborg Kommune',NULL,'Kastetvej 72, Aalborg',57.05424,9.89984,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Skodborg Hallen','parc_exterior','Vejen','Vejen Kommune',NULL,'Parkvej 4A, Vejen',55.41869,9.15424,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Motionscenteret Rådhuset','parc_exterior','Fredericia','Fredericia Kommune',NULL,'Vendersgade 25, Fredericia',55.56584,9.75473,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Sport 24 Team','parc_exterior','Fredericia','Fredericia Kommune',NULL,'Gothersgade 2A, Fredericia',55.56699,9.75666,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Anlægget i Forfatterkvarteret','parc_exterior','Frederiksberg','Frederiksberg Kommune',NULL,'Strindbergsvej 39, Frederiksberg',55.6566,12.52165,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Litauens Plads (3)','parc_exterior','København','København',NULL,'Sønder Boulevard 48, København',55.66669,12.55286,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Shen Mao','parc_exterior','Århus','Aarhus Kommune',NULL,'Skt. Clemens Torv 17, Århus',56.15567,10.20833,1,true,false,'21:30+, Su-We off',NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Litauens Plads (4)','parc_exterior','København','København',NULL,'Dannebrogsgade 50, København',55.66784,12.55297,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Q-Park Frederiks Brygge','parc_exterior','København','København',NULL,'Flydedokken 7, København',55.65525,12.55157,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Q-Park Frederiks Brygge (2)','parc_exterior','København','København',NULL,'Flydedokken 7, København',55.65527,12.55133,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Holmgårdvej','parc_exterior','Vemb','Holstebro Kommune',NULL,'Holmgårdvej 46, Vemb',56.42099,8.33424,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Marina Fiskenæs Feriepark','parc_exterior','Gråsten','Sønderborg Kommune',NULL,'Marina Fiskenæs Feriepark 48, Gråsten',54.91736,9.60641,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Sandskær Strandvej','parc_exterior','Løjt Kirkeby','Aabenraa Kommune',NULL,'Sandskær Strandvej 22, Løjt Kirkeby',55.11379,9.4968,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Lille Amerika','parc_exterior','Gjern','Silkeborg Kommune',NULL,'Lille Amerika 12H, Gjern',56.21797,9.729,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Ringbakken','parc_exterior','Sønderborg','Sønderborg Kommune',NULL,'Ringbakken 6, Sønderborg',54.92083,9.79169,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Ringbakken (2)','parc_exterior','Sønderborg','Sønderborg Kommune',NULL,'Ringbakken 6, Sønderborg',54.92075,9.7917,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Skovbovænget','parc_exterior','Ballerup','Ballerup Kommune',NULL,'Skovbovænget 124, Ballerup',55.75628,12.38869,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Roersvej','parc_exterior','Odense','Odense Kommune',NULL,'Roersvej 10, Odense',55.39362,10.37407,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Roersvej (2)','parc_exterior','Odense','Odense Kommune',NULL,'Roersvej 1A, Odense',55.39365,10.37433,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Lille Værløsevej','parc_exterior','Værløse','Furesø Kommune',NULL,'Lille Værløsevej 73, Værløse',55.7818,12.38328,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Akacieparken','parc_exterior','Frederiksberg','Frederiksberg Kommune',NULL,'Carl Th. Dreyers Vej 262, Frederiksberg',55.66929,12.50287,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Blågårds Plads','parc_exterior','København','København',NULL,'Blågårds Plads 5B, København',55.6863,12.55694,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Hornslet Skole','parc_exterior','Hornslet','Syddjurs Kommune',NULL,'Ballesvej 6, Hornslet',56.31527,10.31603,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Vor Frue Kirkeplads','parc_exterior','Århus','Aarhus Kommune',NULL,'Vestergade 22, Århus',56.15779,10.20507,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Tangloppen Camping','parc_exterior','Vallensbæk','Vallensbæk Kommune',NULL,'Tangloppen 2, Vallensbæk',55.60787,12.38006,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Solvangskolen','parc_exterior','Farum','Furesø Kommune',NULL,'Nordtoftevej 60, Farum',55.8126,12.35703,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Præstemarkskolen','parc_exterior','Søften','Favrskov Kommune',NULL,'Kvottrupvej 9, Søften',56.2343,10.0843,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Præstemarkskolen (2)','parc_exterior','Søften','Favrskov Kommune',NULL,'Æbleparken 1A, Søften',56.23351,10.08768,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Fløng Skole','parc_exterior','Fløng','Høje-Taastrup Kommune',NULL,'Fløng Byvej 24, Fløng',55.66171,12.17902,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Ernst B. Sunds Plads','parc_exterior','Hadsten','Favrskov Kommune',NULL,'Evald Tangs Alle 34B, Hadsten',56.32607,10.04541,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Ernst B. Sunds Plads (2)','parc_exterior','Hadsten','Favrskov Kommune',NULL,'Evald Tangs Alle 34B, Hadsten',56.32608,10.04537,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Ørestad Bypark','parc_exterior','Tårnby','Tårnby Kommune',NULL,'Ørestads Boulevard 66, Tårnby',55.63354,12.57899,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Blågårds Plads (2)','parc_exterior','København','København',NULL,'Blågårds Plads 5B, København',55.68617,12.55718,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Blågårds Plads (3)','parc_exterior','København','København',NULL,'Blågårds Plads 5B, København',55.68619,12.55722,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Sandkaas Familiecamping','parc_exterior','Allinge','Bornholm Kommune',NULL,'Tejnvej 27A, Allinge',55.26332,14.81073,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Tietgens Plads','parc_exterior','Århus','Aarhus Kommune',NULL,'Tietgens Plads 5, Århus',56.14452,10.20354,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Enghave Plads','parc_exterior','Frederiksberg','Frederiksberg Kommune',NULL,'Enghave Plads 21, Frederiksberg',55.66676,12.54484,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Grøndalsvængets Skole','parc_exterior','Frederiksberg','Frederiksberg Kommune',NULL,'Rørsangervej 29, Frederiksberg',55.69863,12.52717,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Bagsværd Skole','parc_exterior','Buddinge','Gladsaxe Municipality',NULL,'Hjaltesvej 5, Buddinge',55.75895,12.46242,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Midtfyns Gymnasium','parc_exterior','Ringe','Faaborg-Midtfyn Kommune',NULL,'Holmehøjvej 4, Ringe',55.2411,10.46752,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Midtfyns Gymnasium (2)','parc_exterior','Ringe','Faaborg-Midtfyn Kommune',NULL,'Holmehøjvej 4, Ringe',55.24105,10.46752,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Rådhusparken','parc_exterior','Vordingborg','Vordingborg Kommune',NULL,'Vognmandsmarken 7, Vordingborg',55.01338,11.90887,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Aarhus Universitet','parc_exterior','Århus','Aarhus Kommune',NULL,'Finlandsgade 20B, Århus',56.17149,10.19147,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Aarhus Universitet (2)','parc_exterior','Århus','Aarhus Kommune',NULL,'Peter Sabroes Gade 33, Århus',56.16887,10.20902,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Nymarkskolen','parc_exterior','Svendborg','Svendborg Kommune',NULL,'Marslevvej 1, Svendborg',55.07393,10.63854,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ballerup Bordtennis Klub','parc_exterior','Ballerup','Ballerup Kommune',NULL,'Magleparken 7, Ballerup',55.71952,12.36427,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Refshalevej','parc_exterior','København','København',NULL,'Refshalevej 169M, København',55.69395,12.60907,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Korsør Spejderne','parc_exterior','Korsør','Slagelse Kommune',NULL,'Korsør Lystskov 2, Korsør',55.32348,11.18682,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Sisu/MBK','parc_exterior','Århus','Aarhus Kommune',NULL,'Nørre Boulevard 1D, Århus',56.1651,10.2101,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Cortex Park','parc_exterior','Neder Holluf','Odense Kommune',NULL,'Cortex Park 22, Neder Holluf',55.3742,10.43142,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Cortex Park (2)','parc_exterior','Neder Holluf','Odense Kommune',NULL,'Cortex Park 22, Neder Holluf',55.37424,10.43137,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis PAN Volleyball','parc_exterior','Hvidovre','Hvidovre Kommune',NULL,'Julius Andersens Vej 1A, Hvidovre',55.64925,12.51553,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis PAN Volleyball (2)','parc_exterior','Hvidovre','Hvidovre Kommune',NULL,'Julius Andersens Vej 1A, Hvidovre',55.64938,12.51566,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Strandklubben','parc_exterior','Solrød','Solrød Kommune',NULL,'Højagervænget 33, Solrød',55.53706,12.20431,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Merløse Fritidscenter','parc_exterior','Store Merløse','Holbæk Kommune',NULL,'Holbækvej 30F, Store Merløse',55.54657,11.70896,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Ferritslev Bypark','parc_exterior','Langeskov','Kerteminde Kommune',NULL,'Ådalen 2H, Langeskov',55.3105,10.58181,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis OGF Cycling exercise','parc_exterior','Odense','Odense Kommune',NULL,'Stadionvej 31, Odense',55.39771,10.3523,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Tante Olgas Børnehus','parc_exterior','København','København',NULL,'Sønder Boulevard 66, København',55.66583,12.55087,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Storebæltshallen','parc_exterior','Korsør','Slagelse Kommune',NULL,'Birchnersgade 2, Korsør',55.32908,11.14229,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Søndersø Park','parc_exterior','Værløse','Furesø Kommune',NULL,'Søndersø Park 64, Værløse',55.78057,12.35163,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Nygårdterrasserne','parc_exterior','Farum','Furesø Kommune',NULL,'Nygårdterrasserne 204, Farum',55.81913,12.37673,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Elstedhøj','parc_exterior','Lystrup','Aarhus Kommune',NULL,'Elstedhøj 37, Lystrup',56.24037,10.23111,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('table tennis','parc_exterior','København','København',NULL,'Willemoesgade 36, København',55.69759,12.58357,1,true,false,'24/7',NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Poppelhaven','parc_exterior','Værløse','Furesø Kommune',NULL,'Poppelhaven 25, Værløse',55.78854,12.34537,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Persillehaven','parc_exterior','Herlev','Herlev Kommune',NULL,'Persillehaven 40, Herlev',55.74004,12.436,1,false,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Arsenalvej','parc_exterior','Rønne','Bornholm Kommune',NULL,'Arsenalvej 12, Rønne',55.09094,14.70047,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Birkevej','parc_exterior','Allinge','Bornholm Kommune',NULL,'Birkevej 1, Allinge',55.27073,14.80444,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Skovengen','parc_exterior','Kokkedal','Fredensborg Kommune',NULL,'Skovengen 174, Kokkedal',55.90973,12.49506,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Ved Sønderport','parc_exterior','København','København',NULL,'Ved Sønderport 14, København',55.66635,12.6023,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Ved Sønderport (2)','parc_exterior','København','København',NULL,'Ved Sønderport 14, København',55.66638,12.60227,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Den Grønne Park','parc_exterior','Frederiksberg','Frederiksberg Kommune',NULL,'Heimdalsgade 31, Frederiksberg',55.70242,12.54341,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Den Grønne Park (2)','parc_exterior','Frederiksberg','Frederiksberg Kommune',NULL,'Heimdalsgade 33, Frederiksberg',55.70248,12.54344,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Den Grønne Park (3)','parc_exterior','Frederiksberg','Frederiksberg Kommune',NULL,'Heimdalsgade 33, Frederiksberg',55.70254,12.54347,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Mimersparken','parc_exterior','Frederiksberg','Frederiksberg Kommune',NULL,'Mjølnerparken 54B, Frederiksberg',55.70426,12.54114,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Guldbergs Plads','parc_exterior','Frederiksberg','Frederiksberg Kommune',NULL,'Guldbergs Plads 12, Frederiksberg',55.69718,12.55444,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Guldbergs Plads (2)','parc_exterior','Frederiksberg','Frederiksberg Kommune',NULL,'Guldbergs Plads 11, Frederiksberg',55.69715,12.55432,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Folkets Park','parc_exterior','København','København',NULL,'Stengade 50, København',55.68736,12.55438,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Holme Skole','parc_exterior','Viby','Aarhus Kommune',NULL,'M.P. Hansens Vej 22, Viby',56.11536,10.17817,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Brobyskolerne Afd. Allested-Vejle','parc_exterior','Nørre Broby','Faaborg-Midtfyn Kommune',NULL,'Skolevej 2, Nørre Broby',55.26724,10.31989,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Lille Nok','parc_exterior','København','København',NULL,'Kardinalgangen 4, København',55.64951,12.56434,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Skovtoften','parc_exterior','Århus','Aarhus Kommune',NULL,'Dronning Margrethes Vej 16, Århus',56.1696,10.22122,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Litauens Plads','parc_exterior','København','København',NULL,'Sønder Boulevard 48, København',55.66669,12.55286,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Litauens Plads (2)','parc_exterior','København','København',NULL,'Dannebrogsgade 50, København',55.66784,12.55297,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Ingerslev Plads','parc_exterior','Århus','Aarhus Kommune',NULL,'Ingerslevs Plads 9, Århus',56.14462,10.19969,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Baunebjergvej','parc_exterior','Humlebæk','Fredensborg Kommune',NULL,'Baunebjergvej 339, Humlebæk',55.96159,12.52147,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Struenseegade','parc_exterior','Frederiksberg','Frederiksberg Kommune',NULL,'Struenseegade 50, Frederiksberg',55.68921,12.54466,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Inger Christensens Gade','parc_exterior','Gjellerup','Aarhus Kommune',NULL,'Inger Christensens Gade 72, Gjellerup',56.1616,10.13554,1,true,false,NULL,NULL,ARRAY['exterior'],true,false)
) AS v(name,type,city,county,sector,address,lat,lng,tables_count,free_access,night_lighting,hours,description,tags,approved,verified)
JOIN cities c ON c.country_code='DK' AND c.name=v.city
ON CONFLICT (name,city_id) DO NOTHING;
COMMIT;
