-- EE — Estonia — 284 venues, 44 cities
-- Idempotent: safe to run multiple times. Source: OpenStreetMap via Overture Maps + GeoNames.
-- STAGED: cities active=false, expansion_status='community_review' (hidden in-app until activated — see DEPLOYMENT.md). Venues approved=true.
BEGIN;
INSERT INTO countries (code,name,active) VALUES ('EE','Estonia',true) ON CONFLICT (code) DO NOTHING;
INSERT INTO cities (name,country_code,country_name,admin_area,county,lat,lng,zoom,active,expansion_status) VALUES
  ('Alatskivi','EE','Estonia','Tartu','Peipsiääre vald',58.59806,27.13361,12,false,'community_review'),
  ('Aseri','EE','Estonia','Lääne-Virumaa','Viru-Nigula vald',59.45256,26.87163,12,false,'community_review'),
  ('Elva','EE','Estonia','Tartu','Elva vald',58.2225,26.42111,12,false,'community_review'),
  ('Haabneeme','EE','Estonia','Harjumaa','Viimsi vald',59.51358,24.82225,12,false,'community_review'),
  ('Harku','EE','Estonia','Harjumaa','Harku vald',59.38641,24.57176,12,false,'community_review'),
  ('Järva-Jaani','EE','Estonia','Järvamaa','Järva vald',59.03861,25.88639,12,false,'community_review'),
  ('Jõhvi','EE','Estonia','Ida-Virumaa','Jõhvi vald',59.35917,27.42111,12,false,'community_review'),
  ('Jüri','EE','Estonia','Harjumaa','Rae vald',59.35974,24.92099,12,false,'community_review'),
  ('Kadrina','EE','Estonia','Lääne-Virumaa','Kadrina vald',59.33472,26.145,12,false,'community_review'),
  ('Kanepi','EE','Estonia','Põlvamaa','Kanepi vald',57.98306,26.75639,12,false,'community_review'),
  ('Kehtna','EE','Estonia','Raplamaa','Kehtna vald',58.93028,24.87806,12,false,'community_review'),
  ('Keila','EE','Estonia','Harjumaa','Keila linn',59.30361,24.41306,12,false,'community_review'),
  ('Kiili','EE','Estonia','Harjumaa','Kiili vald',59.30775,24.83776,12,false,'community_review'),
  ('Kiviõli','EE','Estonia','Ida-Virumaa','Lüganuse vald',59.35306,26.97111,12,false,'community_review'),
  ('Kohila','EE','Estonia','Raplamaa','Kohila vald',59.16806,24.7575,12,false,'community_review'),
  ('Kohtla-Järve','EE','Estonia','Ida-Virumaa','Kohtla-Järve linn',59.39861,27.27306,12,false,'community_review'),
  ('Kõrveküla','EE','Estonia','Tartu','Tartu vald',58.42417,26.78222,12,false,'community_review'),
  ('Kunda','EE','Estonia','Lääne-Virumaa','Viru-Nigula vald',59.49861,26.52611,12,false,'community_review'),
  ('Kuressaare','EE','Estonia','Saare','Saaremaa vald',58.25382,22.49217,12,false,'community_review'),
  ('Laagri','EE','Estonia','Harjumaa','Saue vald',59.35083,24.61418,12,false,'community_review'),
  ('Linaküla','EE','Estonia','Pärnumaa','Kihnu vald',58.13722,23.97444,12,false,'community_review'),
  ('Loo','EE','Estonia','Harjumaa','Jõelähtme vald',59.43123,24.94949,12,false,'community_review'),
  ('Maardu','EE','Estonia','Harjumaa','Maardu linn',59.46529,24.98215,12,false,'community_review'),
  ('Narva','EE','Estonia','Ida-Virumaa','Narva linn',59.37722,28.19028,12,false,'community_review'),
  ('Nõo','EE','Estonia','Tartu','Nõo vald',58.27556,26.5375,12,false,'community_review'),
  ('Paide','EE','Estonia','Järvamaa','Paide linn',58.88768,25.54042,12,false,'community_review'),
  ('Pajusti','EE','Estonia','Lääne-Virumaa','Vinni vald',59.27444,26.42333,12,false,'community_review'),
  ('Põlva','EE','Estonia','Põlvamaa','Põlva vald',58.06028,27.06944,12,false,'community_review'),
  ('Pringi','EE','Estonia','Harjumaa','Viimsi vald',59.53459,24.79726,12,false,'community_review'),
  ('Puhja','EE','Estonia','Tartu','Elva vald',58.34194,26.31472,12,false,'community_review'),
  ('Rakvere','EE','Estonia','Lääne-Virumaa','Rakvere linn',59.34808,26.35784,12,false,'community_review'),
  ('Rapla','EE','Estonia','Raplamaa','Rapla vald',59.00759,24.79386,12,false,'community_review'),
  ('Rõuge','EE','Estonia','Võrumaa','Rõuge vald',57.72778,26.90972,12,false,'community_review'),
  ('Saku','EE','Estonia','Harjumaa','Saku vald',59.30354,24.66382,12,false,'community_review'),
  ('Saue','EE','Estonia','Harjumaa','Saue vald',59.32258,24.54967,12,false,'community_review'),
  ('Sillamäe','EE','Estonia','Ida-Virumaa','Sillamäe linn',59.39697,27.76331,12,false,'community_review'),
  ('Soinaste','EE','Estonia','Tartu','Kambja vald',58.33889,26.68972,12,false,'community_review'),
  ('Tabasalu','EE','Estonia','Harjumaa','Harku vald',59.42607,24.5533,12,false,'community_review'),
  ('Tallinn','EE','Estonia','Harjumaa','Tallinn',59.43696,24.75353,12,false,'community_review'),
  ('Tartu','EE','Estonia','Tartu','Tartu linn',58.38062,26.72509,12,false,'community_review'),
  ('Värska','EE','Estonia','Võrumaa','Setomaa vald',57.95806,27.63806,12,false,'community_review'),
  ('Viimsi','EE','Estonia','Harjumaa','Viimsi vald',59.50086,24.86254,12,false,'community_review'),
  ('Viljandi','EE','Estonia','Viljandimaa','Viljandi linn',58.36319,25.59159,12,false,'community_review'),
  ('Võru','EE','Estonia','Võrumaa','Võru linn',57.83389,27.01944,12,false,'community_review')
ON CONFLICT (country_code,name) DO NOTHING;
INSERT INTO venues (name,type,city,city_id,county,sector,address,lat,lng,tables_count,free_access,night_lighting,hours,description,tags,approved,verified,submitted_by)
SELECT v.name,v.type,v.city,c.id,v.county::text,v.sector::text,v.address,v.lat::double precision,v.lng::double precision,v.tables_count::int,v.free_access::boolean,v.night_lighting::boolean,v.hours::text,v.description::text,v.tags::text[],v.approved::boolean,v.verified::boolean,NULL
FROM (VALUES
  ('Lauatennis Keskpark','parc_exterior','Tartu','Tartu linn',NULL,'Uueturu tänav, Tartu',58.37814,26.72604,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Toomemägi','parc_exterior','Tartu','Tartu linn',NULL,'Ülikooli tänav 8, Tartu',58.37854,26.7219,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Telliskivi Loomelinnak','parc_exterior','Tallinn','Tallinn',NULL,'Telliskivi tänav 60a, Tallinn',59.43878,24.72867,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Priisle park','parc_exterior','Loo','Jõelähtme vald',NULL,'Läänemere tee 56, Loo',59.45189,24.88234,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tondiloo park','parc_exterior','Loo','Jõelähtme vald',NULL,'Kivila tänav 46, Loo',59.44787,24.87521,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tondiloo park (2)','parc_exterior','Loo','Jõelähtme vald',NULL,'Muhu tänav 10b, Loo',59.4472,24.87206,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Kase park','parc_exterior','Tallinn','Tallinn',NULL,'Sepa tänav 8a, Tallinn',59.45949,24.67706,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Kase park (2)','parc_exterior','Tallinn','Tallinn',NULL,'Kopli tänav 106, Tallinn',59.45815,24.67745,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Kase park (3)','parc_exterior','Tallinn','Tallinn',NULL,'Kopli tänav 106, Tallinn',59.4581,24.6773,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Kase park (4)','parc_exterior','Tallinn','Tallinn',NULL,'Kopli tänav 104, Tallinn',59.45747,24.67781,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Peetri park','parc_exterior','Tallinn','Tallinn',NULL,'Kuldala tee 28, Tallinn',59.40078,24.7995,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Peetri park (2)','parc_exterior','Tallinn','Tallinn',NULL,'Kuldala tee 28, Tallinn',59.40073,24.79956,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tallinna Saksa Gümnaasium','parc_exterior','Tallinn','Tallinn',NULL,'Juhan Sütiste tee 26a/2, Tallinn',59.39769,24.69309,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Toompark','parc_exterior','Tallinn','Tallinn',NULL,'Toompuiestee 24, Tallinn',59.43623,24.73401,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Männi park','parc_exterior','Tallinn','Tallinn',NULL,'Keskuse tänav, Tallinn',59.40028,24.67648,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Politseiaed','parc_exterior','Tallinn','Tallinn',NULL,'Juhan Kunderi tänav 10, Tallinn',59.43377,24.76655,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Politseiaed (2)','parc_exterior','Tallinn','Tallinn',NULL,'Juhan Kunderi tänav 10, Tallinn',59.43386,24.76659,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tamme staadion','parc_exterior','Tartu','Tartu linn',NULL,'Tamme puiestee 1, Tartu',58.36726,26.71197,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tartu Mart Reiniku Kool','parc_exterior','Tartu','Tartu linn',NULL,'Riia tänav 25, Tartu',58.37236,26.71595,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tartu Mart Reiniku Kool (2)','parc_exterior','Tartu','Tartu linn',NULL,'Kastani tänav 30a, Tartu',58.37228,26.71574,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Vanemuise park','parc_exterior','Tartu','Tartu linn',NULL,'Vanemuise tänav 45b, Tartu',58.37431,26.71529,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Vaksali park','parc_exterior','Tartu','Tartu linn',NULL,'Julius Kuperjanovi tänav 11, Tartu',58.37583,26.70945,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tartu Kesklinna Kool','parc_exterior','Tartu','Tartu linn',NULL,'Kroonuaia tänav 7a, Tartu',58.38282,26.71541,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tartu Hansa Kool','parc_exterior','Tartu','Tartu linn',NULL,'Anne tänav 63, Tartu',58.37656,26.75727,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tartu Hansa Kool (2)','parc_exterior','Tartu','Tartu linn',NULL,'Anne tänav 63, Tartu',58.37652,26.75737,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Kalaranna kvartal','parc_exterior','Tallinn','Tallinn',NULL,'Kalaranna tänav 6a, Tallinn',59.44743,24.74854,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Jüri gümnaasium','parc_exterior','Jüri','Rae vald',NULL,'Laste tänav 3a, Jüri',59.35589,24.90814,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Koidu park','parc_exterior','Tallinn','Tallinn',NULL,'Koidu tänav 112, Tallinn',59.42159,24.7381,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Koidu park (2)','parc_exterior','Tallinn','Tallinn',NULL,'Koidu tänav 112, Tallinn',59.42154,24.73802,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tiigiveski park','parc_exterior','Tallinn','Tallinn',NULL,'Juhkentali tänav 10a, Tallinn',59.42796,24.75965,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Hiiu park','parc_exterior','Laagri','Saue vald',NULL,'Hiiu tänav 30, Laagri',59.3765,24.67805,1,true,true,'24/7',NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Kohtla-Järve Metsapark','parc_exterior','Kohtla-Järve','Kohtla-Järve linn',NULL,'Metsapargi tänav 10a, Kohtla-Järve',59.41172,27.28293,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Lembitu park','parc_exterior','Paide','Paide linn',NULL,'Pärnu tänav 18/1, Paide',58.88698,25.56142,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Lembitu park (2)','parc_exterior','Paide','Paide linn',NULL,'Pärnu tänav 18/1, Paide',58.88692,25.56143,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tartu Tamme Gümnaasium','parc_exterior','Tartu','Tartu linn',NULL,'Nooruse tänav 9, Tartu',58.36448,26.68912,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tartu Tamme Gümnaasium (2)','parc_exterior','Tartu','Tartu linn',NULL,'Nooruse tänav 9, Tartu',58.36446,26.68907,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tartu Ülikooli Delta keskus','parc_exterior','Tartu','Tartu linn',NULL,'Narva maantee 18, Tartu',58.385,26.72503,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tartu Kivilinna Kool','parc_exterior','Tartu','Tartu linn',NULL,'Kaunase puiestee 71, Tartu',58.37871,26.76838,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tartu Kivilinna Kool (2)','parc_exterior','Tartu','Tartu linn',NULL,'Kaunase puiestee 71, Tartu',58.3787,26.76856,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tartu Kivilinna Kool (3)','parc_exterior','Tartu','Tartu linn',NULL,'Kaunase puiestee 71, Tartu',58.3786,26.76853,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tartu Kivilinna Kool (4)','parc_exterior','Tartu','Tartu linn',NULL,'Kaunase puiestee 71, Tartu',58.37861,26.76836,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tartu Kristjan Jaak Petersoni Gümnaasium','parc_exterior','Tartu','Tartu linn',NULL,'Kaunase puiestee 70, Tartu',58.37645,26.77176,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tartu Kristjan Jaak Petersoni Gümnaasium (2)','parc_exterior','Tartu','Tartu linn',NULL,'Kaunase puiestee 70, Tartu',58.37647,26.77198,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Kulli kiigeplats','parc_exterior','Linaküla','Kihnu vald',NULL,'Kulli kiigeplats, Linaküla',58.37482,23.79999,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Lille Maja','parc_exterior','Tartu','Tartu linn',NULL,'Kalevi tänav 17a, Tartu',58.37437,26.72809,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Päeva Park','parc_exterior','Tartu','Tartu linn',NULL,'Tähe tänav 14, Tartu',58.3712,26.72713,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tallinn Roller Derby','parc_exterior','Laagri','Saue vald',NULL,'Valdeku tänav 20, Laagri',59.38383,24.69248,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis EuroPark','parc_exterior','Tallinn','Tallinn',NULL,'Filmi tänav 5, Tallinn',59.44073,24.77919,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis EuroPark (2)','parc_exterior','Tallinn','Tallinn',NULL,'Reidi tee 9/1, Tallinn',59.44235,24.77343,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Õismäe Tiik','parc_exterior','Harku','Harku vald',NULL,'Õismäe tee 28e, Harku',59.4141,24.6496,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Süsta park','parc_exterior','Tallinn','Tallinn',NULL,'Kopli tänav 101, Tallinn',59.46132,24.66668,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Süsta park (2)','parc_exterior','Tallinn','Tallinn',NULL,'Kopli tänav 101, Tallinn',59.46122,24.66646,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis EuroPark (3)','parc_exterior','Tallinn','Tallinn',NULL,'Tatari tänav 13a, Tallinn',59.43108,24.74829,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis EuroPark (4)','parc_exterior','Tallinn','Tallinn',NULL,'Vana-Lõuna tänav 13, Tallinn',59.42418,24.74803,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Aura Keskus','parc_exterior','Tartu','Tartu linn',NULL,'Sadama tänav 1, Tartu',58.37608,26.73444,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tartumaa Omavalitsuste Liit','parc_exterior','Tartu','Tartu linn',NULL,'Pepleri tänav 1a, Tartu',58.37643,26.71628,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Postimehe park (2)','parc_exterior','Tartu','Tartu linn',NULL,'Munga tänav 7, Tartu',58.38212,26.722,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tartu Ülikooli botaanikaaed','parc_exterior','Tartu','Tartu linn',NULL,'Magasini tänav 5, Tartu',58.38359,26.72227,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Raadi','parc_exterior','Tartu','Tartu linn',NULL,'Muuseumi tee, Tartu',58.39418,26.74357,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Aljona Company OÜ','parc_exterior','Tartu','Tartu linn',NULL,'Jaamamõisa tänav 9b, Tartu',58.38281,26.75046,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis EuroPark','parc_exterior','Tartu','Tartu linn',NULL,'Anne tänav 55a, Tartu',58.37443,26.75589,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Mõisavahe mänguväljak','parc_exterior','Tartu','Tartu linn',NULL,'Kaunase puiestee 58, Tartu',58.37262,26.7743,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Lõunakeskuse Seikluspark','parc_exterior','Soinaste','Kambja vald',NULL,'Lääneringtee 39, Soinaste',58.3588,26.67709,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis EuroPark (5)','parc_exterior','Tallinn','Tallinn',NULL,'Lastekodu tänav 40a, Tallinn',59.42816,24.7719,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Vana-Lõuna tänav','parc_exterior','Tallinn','Tallinn',NULL,'Vana-Lõuna tänav 39a, Tallinn',59.42007,24.74574,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis EuroPark (6)','parc_exterior','Tallinn','Tallinn',NULL,'Retke tee 26, Tallinn',59.40052,24.70408,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Vormsi park (2)','parc_exterior','Loo','Jõelähtme vald',NULL,'Vormsi tänav, Loo',59.45434,24.87355,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Reidi tee','parc_exterior','Tallinn','Tallinn',NULL,'Reidi tee, Tallinn',59.44295,24.7761,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Reidi tee (2)','parc_exterior','Tallinn','Tallinn',NULL,'Reidi tee, Tallinn',59.44298,24.77622,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Soosepa tee','parc_exterior','Viimsi','Viimsi vald',NULL,'Soosepa tee 22, Viimsi',59.50055,24.85747,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Liilia tee','parc_exterior','Viimsi','Viimsi vald',NULL,'Liilia tee 26a, Viimsi',59.48907,24.88583,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Rakvere põik','parc_exterior','Jõhvi','Jõhvi vald',NULL,'Rakvere põik 4, Jõhvi',59.35901,27.41103,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Siili tänav','parc_exterior','Tallinn','Tallinn',NULL,'Siili tänav 9a, Tallinn',59.40753,24.70711,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Kurtna tee','parc_exterior','Saku','Saku vald',NULL,'Kurtna tee 8, Saku',59.23439,24.68933,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Munakivi tee','parc_exterior','Tabasalu','Harku vald',NULL,'Munakivi tee 14, Tabasalu',59.4708,24.39305,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Kaunase puiestee','parc_exterior','Tartu','Tartu linn',NULL,'Kaunase puiestee 69, Tartu',58.37586,26.76966,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Kaunase puiestee (2)','parc_exterior','Tartu','Tartu linn',NULL,'Kaunase puiestee 69, Tartu',58.3759,26.76966,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Rapla keskväljak','parc_exterior','Rapla','Rapla vald',NULL,'Taara tänav 3, Rapla',59.00417,24.7926,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Rapla Vesiroosi Kool','parc_exterior','Rapla','Rapla vald',NULL,'Viljandi maantee 69a, Rapla',58.99764,24.81321,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Mustamäe Humanitaargümnaasium','parc_exterior','Tallinn','Tallinn',NULL,'A. H. Tammsaare tee 145, Tallinn',59.40952,24.67269,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Kadrioru lastepark','parc_exterior','Tallinn','Tallinn',NULL,'Lydia Koidula tänav 21c, Tallinn',59.43623,24.78903,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tornide väljak','parc_exterior','Tallinn','Tallinn',NULL,'Gümnaasiumi tänav 5, Tallinn',59.44035,24.74136,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Teaduspark Tehnopol','parc_exterior','Harku','Harku vald',NULL,'Mäealuse tänav 2, Harku',59.39644,24.6582,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Teaduspark Tehnopol (2)','parc_exterior','Harku','Harku vald',NULL,'Mäealuse tänav 2, Harku',59.39638,24.65823,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Kakumäe jahisadam','parc_exterior','Tabasalu','Harku vald',NULL,'Nooda tee 8/3, Tabasalu',59.45133,24.60278,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Kadrina keskkool','parc_exterior','Kadrina','Kadrina vald',NULL,'Rakvere tee 1a, Kadrina',59.3436,26.13308,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Jüri gümnaasium (2)','parc_exterior','Jüri','Rae vald',NULL,'Laste tänav 3a, Jüri',59.3558,24.90893,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Räägu park','parc_exterior','Tallinn','Tallinn',NULL,'Räägu tänav, Tallinn',59.4146,24.71736,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Metsakasti külaplats','parc_exterior','Viimsi','Viimsi vald',NULL,'Hansuniidu tee 3, Viimsi',59.49296,24.89492,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Elva promenaad','parc_exterior','Elva','Elva vald',NULL,'Kesk tänav 30, Elva',58.22401,26.41612,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Elva promenaad (2)','parc_exterior','Elva','Elva vald',NULL,'Kesk tänav 30, Elva',58.22398,26.41611,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Telliskivi Loomelinnak (2)','parc_exterior','Tallinn','Tallinn',NULL,'Telliskivi tänav 60a/5, Tallinn',59.43862,24.729,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Telliskivi Loomelinnak (3)','parc_exterior','Tallinn','Tallinn',NULL,'Telliskivi tänav 60a/5, Tallinn',59.43855,24.7291,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Depoo','parc_exterior','Tallinn','Tallinn',NULL,'Telliskivi tänav 62/3, Tallinn',59.44088,24.73315,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Viljandi Jakobsoni Kool','parc_exterior','Viljandi','Viljandi linn',NULL,'Riia maantee 91, Viljandi',58.34659,25.58178,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Viljandi Jakobsoni Kool (2)','parc_exterior','Viljandi','Viljandi linn',NULL,'Riia maantee 91, Viljandi',58.34659,25.58161,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Vana-Kalamaja väljak','parc_exterior','Tallinn','Tallinn',NULL,'Kotzebue tänav, Tallinn',59.4432,24.73816,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Männi park (2)','parc_exterior','Tallinn','Tallinn',NULL,'Keskuse tänav, Tallinn',59.40026,24.67646,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tartu Karlova Kool','parc_exterior','Tartu','Tartu linn',NULL,'Eha tänav 43, Tartu',58.3707,26.73104,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tartu Karlova Kool (2)','parc_exterior','Tartu','Tartu linn',NULL,'Eha tänav 43, Tartu',58.37064,26.73102,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Rae Gümnaasium','parc_exterior','Jüri','Rae vald',NULL,'Aruküla tee 22, Jüri',59.35811,24.90475,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Räägu park (2)','parc_exterior','Tallinn','Tallinn',NULL,'Nõmme tee 52, Tallinn',59.41437,24.71742,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Teaduspark Tehnopol (3)','parc_exterior','Harku','Harku vald',NULL,'Akadeemia tee 21/3, Harku',59.39813,24.65899,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Mustamäe Riigigümnaasium','parc_exterior','Harku','Harku vald',NULL,'Akadeemia tee 29a, Harku',59.39987,24.65953,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Narva Vanalinna Riigikool','parc_exterior','Narva','Narva linn',NULL,'Hariduse tänav 1, Narva',59.38086,28.19849,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Räägu park (3)','parc_exterior','Tallinn','Tallinn',NULL,'Räägu tänav, Tallinn',59.41458,24.71747,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Kodulahe','parc_exterior','Tallinn','Tallinn',NULL,'Lammi tänav 2, Tallinn',59.43315,24.68426,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Ilo park','parc_exterior','Tallinn','Tallinn',NULL,'Vabaduse puiestee 4, Tallinn',59.38802,24.71703,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Rae Gümnaasium (2)','parc_exterior','Jüri','Rae vald',NULL,'Aruküla tee 22, Jüri',59.35815,24.90489,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Kadrioru lastepark (2)','parc_exterior','Tallinn','Tallinn',NULL,'Lydia Koidula tänav 21c, Tallinn',59.43643,24.7889,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Rae Gümnaasium (3)','parc_exterior','Jüri','Rae vald',NULL,'Aruküla tee 22, Jüri',59.35817,24.9048,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tallinna Pelgulinna Riigigümnaasium','parc_exterior','Tallinn','Tallinn',NULL,'Kolde puiestee 67a, Tallinn',59.43828,24.70332,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tallinna Pelgulinna Riigigümnaasium (2)','parc_exterior','Tallinn','Tallinn',NULL,'Kolde puiestee 67a, Tallinn',59.43835,24.70354,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Löwenruh'' park (2)','parc_exterior','Tallinn','Tallinn',NULL,'Mustamäe tee 59b, Tallinn',59.41736,24.69696,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tallinna Kristiine Gümnaasium','parc_exterior','Tallinn','Tallinn',NULL,'Nõmme tee 32, Tallinn',59.41795,24.7204,1,false,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Vana-Kalamaja väljak (2)','parc_exterior','Tallinn','Tallinn',NULL,'Kotzebue tänav, Tallinn',59.44323,24.73825,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tallinna Järveotsa Gümnaasium','parc_exterior','Harku','Harku vald',NULL,'Järveotsa tee 31, Harku',59.40965,24.63919,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Priisle park (2)','parc_exterior','Loo','Jõelähtme vald',NULL,'Läänemere tee 56, Loo',59.45186,24.88245,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Karjamaa park','parc_exterior','Tallinn','Tallinn',NULL,'Karjamaa tänav 3, Tallinn',59.45247,24.70938,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Kodulahe (3)','parc_exterior','Tallinn','Tallinn',NULL,'Pagi tänav 5, Tallinn',59.43191,24.68381,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Sitsi õunaaed','parc_exterior','Tallinn','Tallinn',NULL,'Manufaktuuri tänav 22, Tallinn',59.44808,24.70059,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Vilde Spordipark','parc_exterior','Tallinn','Tallinn',NULL,'Eduard Vilde tee 69/2, Tallinn',59.40201,24.68442,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tallinna Tehnikaülikool','parc_exterior','Harku','Harku vald',NULL,'Ehitajate tee 5, Harku',59.39554,24.67095,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Männi park','parc_exterior','Harku','Harku vald',NULL,'Keskuse tänav 1, Harku',59.39916,24.6729,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Männi park (2)','parc_exterior','Harku','Harku vald',NULL,'Keskuse tänav 1, Harku',59.39914,24.67296,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Valtu Põhikool','parc_exterior','Kehtna','Kehtna vald',NULL,'Saare tänav 4, Kehtna',58.96254,24.84063,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tallinna 53. keskkool','parc_exterior','Tallinn','Tallinn',NULL,'Juhan Sütiste tee 42/1, Tallinn',59.39691,24.6862,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Lennula plats','parc_exterior','Maardu','Maardu linn',NULL,'Pirnipuu puiestee 208, Maardu',59.46667,24.95898,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tallinna Kadaka Põhikool','parc_exterior','Harku','Harku vald',NULL,'Eduard Vilde tee 120, Harku',59.40495,24.66594,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tallinna Tehnikagümnaasium','parc_exterior','Tallinn','Tallinn',NULL,'A. H. Tammsaare tee 65b, Tallinn',59.40216,24.70286,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tallinna Tehnikagümnaasium (2)','parc_exterior','Tallinn','Tallinn',NULL,'A. H. Tammsaare tee 65b, Tallinn',59.40207,24.70308,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Sisekaitseakadeemia Narva õppekeskus','parc_exterior','Narva','Narva linn',NULL,'Paul Kerese tänav 14, Narva',59.37512,28.18354,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Vaela külaplats','parc_exterior','Kiili','Kiili vald',NULL,'Lepiku tee 11, Kiili',59.32676,24.82603,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Ääsmäe külaplats','parc_exterior','Keila','Keila linn',NULL,'Pärtlemäe tee 2, Keila',59.24295,24.49969,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Haanja looduspark','parc_exterior','Rõuge','Rõuge vald',NULL,'Haanja maantee 12, Rõuge',57.73129,26.93036,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Rõuge park','parc_exterior','Rõuge','Rõuge vald',NULL,'Nursi maantee 5, Rõuge',57.73023,26.91129,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Seli metsa perepark','parc_exterior','Loo','Jõelähtme vald',NULL,'Ümera tänav 27, Loo',59.44436,24.8939,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Seli metsa perepark (2)','parc_exterior','Loo','Jõelähtme vald',NULL,'Ümera tänav 27, Loo',59.44446,24.89376,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Viljandi Paalalinna Kool','parc_exterior','Viljandi','Viljandi linn',NULL,'Suur-Kaare tänav 33, Viljandi',58.37197,25.5745,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Viljandi Paalalinna Kool (2)','parc_exterior','Viljandi','Viljandi linn',NULL,'Suur-Kaare tänav 33, Viljandi',58.37195,25.57461,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tallinna Euroopa Kool (3)','parc_exterior','Tallinn','Tallinn',NULL,'Tehnika tänav 18/1, Tallinn',59.43697,24.72858,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tartu Aleksander Puškini Kool','parc_exterior','Tartu','Tartu linn',NULL,'Uus tänav 54, Tartu',58.37926,26.74513,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Krootuse mõisa park','parc_exterior','Kanepi','Kanepi vald',NULL,'Pargi tänav 3, Kanepi',58.07218,26.83291,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Kohtla-Järve Gümnaasium','parc_exterior','Kohtla-Järve','Kohtla-Järve linn',NULL,'Pärna tänav 47, Kohtla-Järve',59.40513,27.28919,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Peetri kool','parc_exterior','Järva-Jaani','Järva vald',NULL,'Kesktee 11, Järva-Jaani',58.94398,25.83558,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Peetri kool (2)','parc_exterior','Järva-Jaani','Järva vald',NULL,'Kesktee 11, Järva-Jaani',58.94395,25.83636,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tartu Ülikooli Delta keskus (2)','parc_exterior','Tartu','Tartu linn',NULL,'Raatuse tänav 2, Tartu',58.38456,26.72555,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tartu Variku Kool','parc_exterior','Soinaste','Kambja vald',NULL,'Aianduse tänav 4, Soinaste',58.35112,26.714,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tartu Variku Kool (2)','parc_exterior','Soinaste','Kambja vald',NULL,'Aianduse tänav 4, Soinaste',58.3511,26.71428,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Eurogümnaasium','parc_exterior','Tallinn','Tallinn',NULL,'Eduard Vilde tee 72, Tallinn',59.40489,24.68909,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Cederhelmi park','parc_exterior','Tallinn','Tallinn',NULL,'Mooni tänav 30b, Tallinn',59.42677,24.71129,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Lähte Ühisgümnaasium','parc_exterior','Kõrveküla','Tartu vald',NULL,'Õpetaja tänav 8/1, Kõrveküla',58.49406,26.68503,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Koreli park','parc_exterior','Võru','Võru linn',NULL,'Kooli tänav 8, Võru',57.8465,27.00571,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Kodulahe (2)','parc_exterior','Tallinn','Tallinn',NULL,'Lammi tänav 8, Tallinn',59.43323,24.68148,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tallinna Tehnikaülikool (2)','parc_exterior','Harku','Harku vald',NULL,'Akadeemia tee 3, Harku',59.39636,24.67011,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Roela kool','parc_exterior','Pajusti','Vinni vald',NULL,'Uus tänav 1, Pajusti',59.17115,26.59418,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tallinna Pelgulinna Riigigümnaasium (3)','parc_exterior','Tallinn','Tallinn',NULL,'Kolde puiestee 67a, Tallinn',59.439,24.70439,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Ülemiste City','parc_exterior','Tallinn','Tallinn',NULL,'Valukoja tänav 9, Tallinn',59.42088,24.80883,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Hõbemetsa','parc_exterior','Harku','Harku vald',NULL,'Kadaka tee 191d, Harku',59.39762,24.6434,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Pelgulinna Gümnaasium','parc_exterior','Tallinn','Tallinn',NULL,'Sõle tänav 21, Tallinn',59.43423,24.71438,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Astangu Kutserehabilitatsiooni Keskus','parc_exterior','Harku','Harku vald',NULL,'Astangu tänav 27d, Harku',59.4055,24.63782,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Rohu kvartal','parc_exterior','Tallinn','Tallinn',NULL,'Telliskivi tänav 50b, Tallinn',59.43771,24.72653,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Pae park','parc_exterior','Tallinn','Tallinn',NULL,'Paepargi tänav 29, Tallinn',59.43253,24.80664,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Pae park (2)','parc_exterior','Tallinn','Tallinn',NULL,'Pallasti tänav 54, Tallinn',59.43352,24.80314,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tartu observatoorium','parc_exterior','Nõo','Nõo vald',NULL,'Observatooriumi tänav 9, Nõo',58.26641,26.4684,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Röa külaplats','parc_exterior','Kohila','Kohila vald',NULL,'Röa külaplats, Kohila',59.10034,24.79836,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Ohtu külaplats','parc_exterior','Keila','Keila linn',NULL,'Ohtu külaplats, Keila',59.26981,24.36773,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis EuroPark (7)','parc_exterior','Tallinn','Tallinn',NULL,'Paekalda tänav 16a, Tallinn',59.45118,24.82159,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Hundioa tee','parc_exterior','Maardu','Maardu linn',NULL,'Hundioa tee 1/1, Maardu',59.47424,24.94291,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis EuroPark (8)','parc_exterior','Tallinn','Tallinn',NULL,'Tatari tänav 13a, Tallinn',59.43106,24.74827,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis New Lasnamäe Park','parc_exterior','Tallinn','Tallinn',NULL,'Liikuri tänav 62, Tallinn',59.44368,24.83254,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Viimsi Lauatenniseklubi','parc_exterior','Viimsi','Viimsi vald',NULL,'Karulaugu tee 13, Viimsi',59.50962,24.8365,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Fansurf Surfikool','parc_exterior','Tabasalu','Harku vald',NULL,'Räime tänav 52, Tabasalu',59.44753,24.575,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis EuroPark','parc_exterior','Jüri','Rae vald',NULL,'Krati tee 3, Jüri',59.38791,24.82554,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Aedik OÜ','parc_exterior','Tallinn','Tallinn',NULL,'Rabaküla tänav 15, Tallinn',59.41331,24.68346,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Kloogaranna Rannatennis','parc_exterior','Keila','Keila linn',NULL,'Mere põik 4, Keila',59.34539,24.24715,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis EuroPark','parc_exterior','Laagri','Saue vald',NULL,'Jaama tänav 7, Laagri',59.38671,24.68518,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Pääsküla Indoor Skate Park','parc_exterior','Laagri','Saue vald',NULL,'Rännaku puiestee 1, Laagri',59.3689,24.64182,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Taksopark','parc_exterior','Tallinn','Tallinn',NULL,'Sõpruse puiestee 3a, Tallinn',59.42675,24.72028,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis EuroPark (9)','parc_exterior','Tallinn','Tallinn',NULL,'Paekalda tänav 16a, Tallinn',59.45117,24.82178,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Viljandi ranna mänguväljak','parc_exterior','Viljandi','Viljandi linn',NULL,'Vesiflirdi allee 3, Viljandi',58.36034,25.6069,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Friedrich Reinhold Kreutzwaldi tänav','parc_exterior','Tartu','Tartu linn',NULL,'Friedrich Reinhold Kreutzwaldi tänav 52, Tartu',58.38734,26.69505,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Veixride OÜ','parc_exterior','Tallinn','Tallinn',NULL,'Angerja tänav 3a, Tallinn',59.45119,24.70938,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Jürka parkla','parc_exterior','Kuressaare','Saaremaa vald',NULL,'Tallinna tänav 2, Kuressaare',58.25274,22.48569,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis EKA Pop-up','parc_exterior','Tallinn','Tallinn',NULL,'Põhja puiestee 7, Tallinn',59.44222,24.74075,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Mänguväljak','parc_exterior','Kuressaare','Saaremaa vald',NULL,'Lasteaia tänav 1, Kuressaare',58.25212,22.48429,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis McLouis Motorhomes','parc_exterior','Tabasalu','Harku vald',NULL,'Teenuste tänav 3, Tabasalu',59.428,24.54493,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Spordi tänav','parc_exterior','Tallinn','Tallinn',NULL,'Spordi tänav 17a, Tallinn',59.41657,24.73055,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Capoeira Berimba Estonia','parc_exterior','Viimsi','Viimsi vald',NULL,'Rummu tee 3, Viimsi',59.46265,24.83042,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Veeriku mänguväljak','parc_exterior','Tartu','Tartu linn',NULL,'Veeriku tänav 41, Tartu',58.37545,26.68753,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Veeriku mänguväljak (2)','parc_exterior','Tartu','Tartu linn',NULL,'Veeriku tänav 41, Tartu',58.37543,26.68757,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis ArtSmart prindistuudio','parc_exterior','Tallinn','Tallinn',NULL,'Türi tänav 9/4, Tallinn',59.40886,24.74137,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis EastPole Kayaks','parc_exterior','Haabneeme','Viimsi vald',NULL,'Varju tee 6, Haabneeme',59.50014,24.81994,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Capoeira Berimba Estonia (2)','parc_exterior','Viimsi','Viimsi vald',NULL,'Rummu tee 3, Viimsi',59.46269,24.83033,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Karjamaa mänguväljak','parc_exterior','Tallinn','Tallinn',NULL,'Karjamaa tänav 9a, Tallinn',59.45262,24.7128,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Karjamaa mänguväljak (2)','parc_exterior','Tallinn','Tallinn',NULL,'Karjamaa tänav 9a, Tallinn',59.45269,24.71288,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis EuroPark (10)','parc_exterior','Tallinn','Tallinn',NULL,'Pärnu maantee 59, Tallinn',59.42663,24.74418,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis EuroPark (11)','parc_exterior','Tallinn','Tallinn',NULL,'Liivalaia tänav 2, Tallinn',59.42671,24.74424,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Kadaka Staadion','parc_exterior','Harku','Harku vald',NULL,'Eduard Vilde tee 120, Harku',59.40428,24.6636,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Kadaka Staadion (2)','parc_exterior','Harku','Harku vald',NULL,'Eduard Vilde tee 120, Harku',59.40431,24.66356,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Postimehe park (3)','parc_exterior','Tartu','Tartu linn',NULL,'Rüütli tänav 15, Tartu',58.38246,26.72145,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Ehte koertepark','parc_exterior','Tallinn','Tallinn',NULL,'Puhangu tänav 41, Tallinn',59.44264,24.69619,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Ehte koertepark (2)','parc_exterior','Tallinn','Tallinn',NULL,'Ehte tänav 36, Tallinn',59.44261,24.69626,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tip-Top Klub','parc_exterior','Tallinn','Tallinn',NULL,'Kalevipoja tänav 8, Tallinn',59.43689,24.83192,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Jõhvi Linnapark','parc_exterior','Jõhvi','Jõhvi vald',NULL,'Hariduse tänav 5b, Jõhvi',59.34933,27.41758,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Jõhvi Spordihall','parc_exterior','Jõhvi','Jõhvi vald',NULL,'Hariduse tänav 5b, Jõhvi',59.34942,27.41737,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Jõhvi Spordihall (2)','parc_exterior','Jõhvi','Jõhvi vald',NULL,'Hariduse tänav 5d, Jõhvi',59.35077,27.41644,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Jõhvi Spordihall (3)','parc_exterior','Jõhvi','Jõhvi vald',NULL,'Hariduse tänav 5d, Jõhvi',59.35078,27.41654,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Jõhvi Linnapark (2)','parc_exterior','Jõhvi','Jõhvi vald',NULL,'Puru tee 7c, Jõhvi',59.34916,27.42099,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Ehte','parc_exterior','Tallinn','Tallinn',NULL,'Puhangu tänav 13, Tallinn',59.4452,24.69964,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Ehte (2)','parc_exterior','Tallinn','Tallinn',NULL,'Puhangu tänav 13, Tallinn',59.4452,24.69964,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Franz Krulli Tennisemaja','parc_exterior','Tallinn','Tallinn',NULL,'Kopli tänav 68a, Tallinn',59.44557,24.72197,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Kiviõli linnastaadion','parc_exterior','Kiviõli','Lüganuse vald',NULL,'Spordi tänav 9, Kiviõli',59.35389,26.95779,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Kalju FC','parc_exterior','Laagri','Saue vald',NULL,'Harku tänav 63, Laagri',59.38502,24.66053,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Ehte koertepark (3)','parc_exterior','Tallinn','Tallinn',NULL,'Kolde puiestee 92, Tallinn',59.44399,24.69845,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis EuroPark','parc_exterior','Tabasalu','Harku vald',NULL,'Õismäe tee 118a, Tabasalu',59.41863,24.64491,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Toompargi Koerteplats','parc_exterior','Tallinn','Tallinn',NULL,'Toompuiestee 24a, Tallinn',59.43617,24.73545,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Vaskjala veehoidla','parc_exterior','Jüri','Rae vald',NULL,'Vaskjala veehoidla, Jüri',59.35376,24.93963,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Akadeemia tee','parc_exterior','Harku','Harku vald',NULL,'Akadeemia tee 32b, Harku',59.39918,24.66377,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Kuukressi tee','parc_exterior','Loo','Jõelähtme vald',NULL,'Kuukressi tee 1, Loo',59.45502,24.88756,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Neeme tee','parc_exterior','Maardu','Maardu linn',NULL,'Neeme tee 4, Maardu',59.52881,25.1581,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tudra tee','parc_exterior','Maardu','Maardu linn',NULL,'Tudra tee 12, Maardu',59.48272,24.93329,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Spinmaster MTÜ','parc_exterior','Tallinn','Tallinn',NULL,'Mustamäe tee 5a, Tallinn',59.42759,24.70378,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Sõpruse puiestee','parc_exterior','Tallinn','Tallinn',NULL,'Sõpruse puiestee 238, Tallinn',59.40009,24.68653,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Illimari tänav','parc_exterior','Põlva','Põlva vald',NULL,'Illimari tänav 6, Põlva',58.20711,27.07003,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Pikk tänav','parc_exterior','Värska','Setomaa vald',NULL,'Pikk tänav 30, Värska',57.95576,27.63813,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Koondise tänav','parc_exterior','Saue','Saue vald',NULL,'Koondise tänav, Saue',59.32465,24.5594,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Koondise tänav (2)','parc_exterior','Saue','Saue vald',NULL,'Koondise tänav 7, Saue',59.32393,24.55769,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Mere põik','parc_exterior','Keila','Keila linn',NULL,'Mere põik 4, Keila',59.34546,24.2472,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Valge tänav','parc_exterior','Tallinn','Tallinn',NULL,'Valge tänav 18, Tallinn',59.4392,24.80566,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Vahtra tee','parc_exterior','Haabneeme','Viimsi vald',NULL,'Vahtra tee 13, Haabneeme',59.5124,24.81492,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Pelguranna tänav','parc_exterior','Tallinn','Tallinn',NULL,'Pelguranna tänav 58, Tallinn',59.44284,24.68469,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Pelguranna tänav (2)','parc_exterior','Tallinn','Tallinn',NULL,'Pelguranna tänav 58, Tallinn',59.44308,24.68484,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Koidu tee','parc_exterior','Pringi','Viimsi vald',NULL,'Koidu tee 42, Pringi',59.55321,24.84,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Uus tänav','parc_exterior','Tartu','Tartu linn',NULL,'Uus tänav 63b, Tartu',58.37894,26.74446,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Uus tänav (2)','parc_exterior','Tartu','Tartu linn',NULL,'Uus tänav 63b, Tartu',58.37891,26.74446,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Kaabli tänav','parc_exterior','Tallinn','Tallinn',NULL,'Kaabli tänav 25, Tallinn',59.40499,24.82037,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Kaabli tänav (2)','parc_exterior','Tallinn','Tallinn',NULL,'Kaabli tänav 25, Tallinn',59.40493,24.82025,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Siili tänav (2)','parc_exterior','Tallinn','Tallinn',NULL,'Siili tänav 9a, Tallinn',59.40759,24.70713,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Astangu tänav','parc_exterior','Harku','Harku vald',NULL,'Astangu tänav 74, Harku',59.4032,24.64093,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Annikoru tee','parc_exterior','Puhja','Elva vald',NULL,'Annikoru tee 15, Puhja',58.26773,26.30666,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Pärnu maantee','parc_exterior','Tallinn','Tallinn',NULL,'Pärnu maantee 62/1, Tallinn',59.42675,24.7416,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Taverni tee','parc_exterior','Tabasalu','Harku vald',NULL,'Taverni tee 3, Tabasalu',59.43024,24.5884,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Taverni tee (2)','parc_exterior','Tabasalu','Harku vald',NULL,'Taverni tee 3, Tabasalu',59.43025,24.5883,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Iirise tänav','parc_exterior','Tartu','Tartu linn',NULL,'Iirise tänav 5, Tartu',58.3558,26.76842,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Pähklimänni tee','parc_exterior','Maardu','Maardu linn',NULL,'Pähklimänni tee 20, Maardu',59.46707,24.92274,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Kasvandu tee','parc_exterior','Kehtna','Kehtna vald',NULL,'Kasvandu tee 15, Kehtna',59.01401,25.05367,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Teaduse tänav','parc_exterior','Saku','Saku vald',NULL,'Teaduse tänav 3a, Saku',59.29932,24.65927,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Paljassaare tee','parc_exterior','Tallinn','Tallinn',NULL,'Paljassaare tee 46, Tallinn',59.47345,24.72293,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Paljassaare tee (2)','parc_exterior','Tallinn','Tallinn',NULL,'Paljassaare tee 46, Tallinn',59.47344,24.72286,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Kapsa tänav','parc_exterior','Tartu','Tartu linn',NULL,'Kapsa tänav 5, Tartu',58.39061,26.70731,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Ujula tänav','parc_exterior','Tartu','Tartu linn',NULL,'Ujula tänav 102, Tartu',58.39218,26.71188,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Ranna tee','parc_exterior','Kunda','Viru-Nigula vald',NULL,'Ranna tee, Kunda',59.52013,26.53829,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Päikese tänav','parc_exterior','Rakvere','Rakvere linn',NULL,'Päikese tänav 8, Rakvere',59.33738,26.37727,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Võidu tänav','parc_exterior','Alatskivi','Peipsiääre vald',NULL,'Võidu tänav 111, Alatskivi',58.66747,27.16641,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Aianduse tee','parc_exterior','Viimsi','Viimsi vald',NULL,'Aianduse tee 29, Viimsi',59.48695,24.87242,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Pärnu maantee (2)','parc_exterior','Tallinn','Tallinn',NULL,'Pärnu maantee 129c, Tallinn',59.41118,24.73976,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Seebi tänav','parc_exterior','Tallinn','Tallinn',NULL,'Seebi tänav 30a, Tallinn',59.40359,24.7252,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Neeme tee (2)','parc_exterior','Maardu','Maardu linn',NULL,'Neeme tee 4, Maardu',59.52902,25.15729,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Kolde puiestee','parc_exterior','Tallinn','Tallinn',NULL,'Kolde puiestee 72, Tallinn',59.44029,24.70505,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Kaselaane tänav','parc_exterior','Laagri','Saue vald',NULL,'Kaselaane tänav 6a, Laagri',59.35248,24.64053,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Vilisuu tänav','parc_exterior','Tallinn','Tallinn',NULL,'Vilisuu tänav 4, Tallinn',59.43701,24.84519,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Lagedi tee','parc_exterior','Loo','Jõelähtme vald',NULL,'Lagedi tee 21, Loo',59.43318,24.92135,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Kesk tänav','parc_exterior','Sillamäe','Sillamäe linn',NULL,'Kesk tänav 35a, Sillamäe',59.3956,27.76494,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tondimõisa park','parc_exterior','Tallinn','Tallinn',NULL,'Tondi tänav 84/6, Tallinn',59.40424,24.7101,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Löwenruh'' park','parc_exterior','Tallinn','Tallinn',NULL,'Mustamäe tee 59a, Tallinn',59.41736,24.69438,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Kose park','parc_exterior','Viimsi','Viimsi vald',NULL,'Puhkekodu tee 54, Viimsi',59.45944,24.87637,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Mähe park','parc_exterior','Viimsi','Viimsi vald',NULL,'Mugula tee 17a, Viimsi',59.49022,24.87015,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Rannu park','parc_exterior','Aseri','Viru-Nigula vald',NULL,'Sireli tänav 3, Aseri',59.43952,26.83949,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tallinna Euroopa Kool','parc_exterior','Tallinn','Tallinn',NULL,'Tehnika tänav 18, Tallinn',59.4367,24.72814,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tallinna Euroopa Kool (2)','parc_exterior','Tallinn','Tallinn',NULL,'Tehnika tänav 18, Tallinn',59.43675,24.72815,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tildri minimets','parc_exterior','Tallinn','Tallinn',NULL,'Algi tänav 36, Tallinn',59.41415,24.69502,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Tildri minimets (2)','parc_exterior','Tallinn','Tallinn',NULL,'Algi tänav 36, Tallinn',59.4141,24.695,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Vaarika Mänguväljak','parc_exterior','Tallinn','Tallinn',NULL,'Vaarika tänav 15a, Tallinn',59.42937,24.70959,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Vaarika Mänguväljak (2)','parc_exterior','Tallinn','Tallinn',NULL,'Vaarika tänav 15, Tallinn',59.42934,24.70931,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Arkaadia Aed','parc_exterior','Viljandi','Viljandi linn',NULL,'Lossi tänav 21, Viljandi',58.36448,25.59929,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Vormsi park','parc_exterior','Loo','Jõelähtme vald',NULL,'Vormsi tänav, Loo',59.45436,24.87355,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Postimehe park','parc_exterior','Tartu','Tartu linn',NULL,'Rüütli tänav 15, Tartu',58.38246,26.72145,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Pirita Jõesuu Puhkeala','parc_exterior','Viimsi','Viimsi vald',NULL,'Jõesuu tee 7, Viimsi',59.46834,24.8288,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Pirita Jõesuu Puhkeala (2)','parc_exterior','Viimsi','Viimsi vald',NULL,'Jõesuu tee 7, Viimsi',59.46838,24.82884,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Pirita Jõesuu Puhkeala (3)','parc_exterior','Viimsi','Viimsi vald',NULL,'Merivälja tee 3a, Viimsi',59.46825,24.82899,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Pirita Jõesuu Puhkeala (4)','parc_exterior','Viimsi','Viimsi vald',NULL,'Jõesuu tee, Viimsi',59.46777,24.83013,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Paldiski maantee','parc_exterior','Harku','Harku vald',NULL,'Paldiski maantee 124a, Harku',59.41298,24.63254,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lauatennis Kooli tänav','parc_exterior','Rapla','Rapla vald',NULL,'Kooli tänav 1/1, Rapla',59.06457,24.80889,1,true,false,NULL,NULL,ARRAY['exterior'],true,false)
) AS v(name,type,city,county,sector,address,lat,lng,tables_count,free_access,night_lighting,hours,description,tags,approved,verified)
JOIN cities c ON c.country_code='EE' AND c.name=v.city
ON CONFLICT (name,city_id) DO NOTHING;
COMMIT;
