-- FI — Finland — 77 venues, 40 cities
-- Idempotent: safe to run multiple times. Source: OpenStreetMap via Overture Maps + GeoNames.
-- STAGED: cities active=false, expansion_status='community_review' (hidden in-app until activated — see DEPLOYMENT.md). Venues approved=true.
BEGIN;
INSERT INTO countries (code,name,active) VALUES ('FI','Finland',true) ON CONFLICT (code) DO NOTHING;
INSERT INTO cities (name,country_code,country_name,admin_area,county,lat,lng,zoom,active,expansion_status) VALUES
  ('Asikkala','FI','Finland','Paijat-Hame','Lahti',61.21667,25.5,12,false,'community_review'),
  ('Espoo','FI','Finland','Uusimaa','Helsinki sub-region',60.2052,24.6522,12,false,'community_review'),
  ('Hämeenlinna','FI','Finland','Kanta-Häme','Hämeenlinna',60.99596,24.46434,12,false,'community_review'),
  ('Haukilahti','FI','Finland','Uusimaa','Helsinki sub-region',60.15889,24.77057,12,false,'community_review'),
  ('Helsinki','FI','Finland','Uusimaa','Helsinki sub-region',60.16952,24.93545,12,false,'community_review'),
  ('Hyvinge','FI','Finland','Uusimaa','Helsinki sub-region',60.63333,24.86667,12,false,'community_review'),
  ('Järvenpää','FI','Finland','Uusimaa','Helsinki sub-region',60.47369,25.08992,12,false,'community_review'),
  ('Järvenperä','FI','Finland','Uusimaa','Helsinki sub-region',60.24169,24.71357,12,false,'community_review'),
  ('Jyväskylä','FI','Finland','Central Finland','Jyväskylä',62.24147,25.72088,12,false,'community_review'),
  ('Kaivoksela','FI','Finland','Uusimaa','Helsinki sub-region',60.26767,24.86871,12,false,'community_review'),
  ('Kallahti','FI','Finland','Uusimaa','Uusimaa',60.19289,25.13682,12,false,'community_review'),
  ('Kannelmäki','FI','Finland','Uusimaa','Helsinki sub-region',60.24181,24.88575,12,false,'community_review'),
  ('Karkkila','FI','Finland','Uusimaa','Helsinki sub-region',60.53418,24.20977,12,false,'community_review'),
  ('Kauniainen','FI','Finland','Uusimaa','Helsinki sub-region',60.21209,24.72756,12,false,'community_review'),
  ('Kaupunginkallio','FI','Finland','Uusimaa','Helsinki sub-region',60.19847,24.64722,12,false,'community_review'),
  ('Kello','FI','Finland','North Ostrobothnia','Oulu',65.1285,25.3567,12,false,'community_review'),
  ('Kerava','FI','Finland','Uusimaa','Helsinki sub-region',60.40338,25.105,12,false,'community_review'),
  ('Kilo','FI','Finland','Uusimaa','Helsinki sub-region',60.21746,24.78151,12,false,'community_review'),
  ('Kurkimäki','FI','Finland','Uusimaa','Helsinki sub-region',60.23325,25.06745,12,false,'community_review'),
  ('Kuurinniitty','FI','Finland','Uusimaa','Helsinki sub-region',60.19778,24.70039,12,false,'community_review'),
  ('Laajalahti','FI','Finland','Uusimaa','Helsinki sub-region',60.20076,24.80352,12,false,'community_review'),
  ('Lahti','FI','Finland','Paijat-Hame','Lahti',60.98267,25.66151,12,false,'community_review'),
  ('Länsi-Pakila','FI','Finland','Uusimaa','Helsinki sub-region',60.24152,24.92695,12,false,'community_review'),
  ('Länsimäki','FI','Finland','Uusimaa','Helsinki sub-region',60.24633,25.11775,12,false,'community_review'),
  ('Lappeenranta','FI','Finland','South Karelia','Lappeenranta',61.05871,28.18871,12,false,'community_review'),
  ('Latokaski','FI','Finland','Uusimaa','Helsinki sub-region',60.17785,24.65813,12,false,'community_review'),
  ('Lintuvaara','FI','Finland','Uusimaa','Helsinki sub-region',60.2344,24.81348,12,false,'community_review'),
  ('Malminkartano','FI','Finland','Uusimaa','Helsinki sub-region',60.24739,24.86163,12,false,'community_review'),
  ('Masku','FI','Finland','Southwest Finland','Turku',60.57082,22.09883,12,false,'community_review'),
  ('Meri-Rastila','FI','Finland','Uusimaa','Helsinki sub-region',60.19972,25.11857,12,false,'community_review'),
  ('Ojakkala','FI','Finland','Uusimaa','Helsinki sub-region',60.36881,24.38425,12,false,'community_review'),
  ('Oulu','FI','Finland','North Ostrobothnia','Oulu',65.01236,25.46816,12,false,'community_review'),
  ('Pihlajisto','FI','Finland','Uusimaa','Helsinki sub-region',60.23102,25.00134,12,false,'community_review'),
  ('Pirkkala','FI','Finland','Pirkanmaa','Tampere',61.46125,23.63228,12,false,'community_review'),
  ('Pohjois-Tapiola','FI','Finland','Uusimaa','Helsinki sub-region',60.18694,24.797,12,false,'community_review'),
  ('Raahe','FI','Finland','North Ostrobothnia','Raahe',64.68333,24.48333,12,false,'community_review'),
  ('Tampere','FI','Finland','Pirkanmaa','Tampere',61.49911,23.78712,12,false,'community_review'),
  ('Turku','FI','Finland','Southwest Finland','Turku',60.45148,22.26869,12,false,'community_review'),
  ('Valkeakoski','FI','Finland','Pirkanmaa','Etelä-Pirkanmaa',61.26421,24.03122,12,false,'community_review'),
  ('Vihti','FI','Finland','Uusimaa','Helsinki sub-region',60.41699,24.31965,12,false,'community_review')
ON CONFLICT (country_code,name) DO NOTHING;
INSERT INTO venues (name,type,city,city_id,county,sector,address,lat,lng,tables_count,free_access,night_lighting,hours,description,tags,approved,verified,submitted_by)
SELECT v.name,v.type,v.city,c.id,v.county::text,v.sector::text,v.address,v.lat::double precision,v.lng::double precision,v.tables_count::int,v.free_access::boolean,v.night_lighting::boolean,v.hours::text,v.description::text,v.tags::text[],v.approved::boolean,v.verified::boolean,NULL
FROM (VALUES
  ('Pirkkolan liikuntapuisto / Pöytätennistila','parc_exterior','Länsi-Pakila','Helsinki sub-region',NULL,'Pirkkolan metsätie 6, Länsi-Pakila',60.23223,24.91062,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Hämeensaarenpuisto','parc_exterior','Hämeenlinna','Hämeenlinna',NULL,'Uimarinkatu 12, Hämeenlinna',60.99141,24.46492,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Hämeensaarenpuisto (2)','parc_exterior','Hämeenlinna','Hämeenlinna',NULL,'Uimarinkatu 12, Hämeenlinna',60.99141,24.46452,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Vaskipelto','parc_exterior','Kaivoksela','Helsinki sub-region',NULL,'Vaskipellontie 10, Kaivoksela',60.25796,24.86751,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Oravapuisto','parc_exterior','Pihlajisto','Helsinki sub-region',NULL,'Karhutie 11, Pihlajisto',60.19832,25.03296,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Ristipellonpuisto','parc_exterior','Malminkartano','Helsinki sub-region',NULL,'Limonadikuja 3, Malminkartano',60.23704,24.85133,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Paasikivenpuisto','parc_exterior','Lappeenranta','Lappeenranta',NULL,'Pormestarinkatu 10, Lappeenranta',61.05844,28.19307,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Helsingin yhteislyseo','parc_exterior','Kurkimäki','Helsinki sub-region',NULL,'Rintinpolku 2, Kurkimäki',60.2302,25.08979,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Helsingin yhteislyseo (2)','parc_exterior','Kurkimäki','Helsinki sub-region',NULL,'Rintinpolku 2, Kurkimäki',60.23015,25.08998,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Puolalan koulu','parc_exterior','Turku','Turku',NULL,'Puutarhakatu 5, Turku',60.45286,22.26039,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Leikkipuisto Nuoli','parc_exterior','Kannelmäki','Helsinki sub-region',NULL,'Nuolitie 5, Kannelmäki',60.22906,24.86273,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Ahvenispuisto','parc_exterior','Tampere','Tampere',NULL,'Lindforsinkatu 5, Tampere',61.44933,23.84708,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Riuttarannan leirikeskus','parc_exterior','Vihti','Helsinki sub-region',NULL,'Moksintie 365a, Vihti',60.48193,24.41593,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Kaskenkaatajanpuiston leikkipaikka','parc_exterior','Pohjois-Tapiola','Helsinki sub-region',NULL,'Kaskenkaatajantie 22, Pohjois-Tapiola',60.18191,24.79137,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Rantapuisto','parc_exterior','Karkkila','Helsinki sub-region',NULL,'Vattolantie 7, Karkkila',60.53661,24.19113,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Kirkkojärven koulu','parc_exterior','Espoo','Helsinki sub-region',NULL,'Kotikyläntie 4, Espoo',60.20874,24.66494,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Tietotie','parc_exterior','Pohjois-Tapiola','Helsinki sub-region',NULL,'Tietotie 6, Pohjois-Tapiola',60.18358,24.81857,1,false,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Tietotie (2)','parc_exterior','Pohjois-Tapiola','Helsinki sub-region',NULL,'Tekniikantie 15, Pohjois-Tapiola',60.18357,24.81836,1,false,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Sankarla','parc_exterior','Ojakkala','Helsinki sub-region',NULL,'Kappelitie 5, Ojakkala',60.33546,24.31609,1,true,false,NULL,'Vihdin seurakunta',ARRAY['exterior'],true,false),
  ('Pöytätennis Kisatie','parc_exterior','Raahe','Raahe',NULL,'Kisatie 5, Raahe',64.65481,24.46884,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Luostarivuoren koulun Martin yksikkö','parc_exterior','Turku','Turku',NULL,'Betaniankatu 10, Turku',60.4407,22.26075,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Perkkaan asukaspuisto','parc_exterior','Laajalahti','Helsinki sub-region',NULL,'Perkkaanpuisto, Laajalahti',60.21478,24.82276,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Turun Suomalaisen Yhteiskoulun lukio','parc_exterior','Turku','Turku',NULL,'Tuureporinkatu 16, Turku',60.45439,22.26528,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Turun Suomalaisen Yhteiskoulun lukio (2)','parc_exterior','Turku','Turku',NULL,'Brahenkatu 16, Turku',60.45471,22.26591,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Kauppatori','parc_exterior','Turku','Turku',NULL,'Kauppatori 2, Turku',60.45224,22.26677,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Juhannuskylän koulu - Tammerkosken koulutalo','parc_exterior','Tampere','Tampere',NULL,'Vuorikatu 6, Tampere',61.50337,23.77067,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Tammelan koulu','parc_exterior','Tampere','Tampere',NULL,'Ilmarinkatu 17, Tampere',61.50158,23.7855,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Soukkapuisto','parc_exterior','Tampere','Tampere',NULL,'Tampellan esplanadi 19, Tampere',61.50766,23.76769,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Stoan aukio','parc_exterior','Kurkimäki','Helsinki sub-region',NULL,'Turunlinnantie 1, Kurkimäki',60.21232,25.07938,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Stoan aukio (2)','parc_exterior','Kurkimäki','Helsinki sub-region',NULL,'Turunlinnantie 1, Kurkimäki',60.21233,25.07943,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Thurmaninpuiston pöytätennis','parc_exterior','Kauniainen','Helsinki sub-region',NULL,'Kirkkotie 25, Kauniainen',60.20968,24.72149,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lepänkorvanpuiston Pingispöytä','parc_exterior','Valkeakoski','Etelä-Pirkanmaa',NULL,'Kauppatori 4, Valkeakoski',61.26689,24.03198,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Nauriskasken koulu','parc_exterior','Latokaski','Helsinki sub-region',NULL,'Kaskihaka 5, Latokaski',60.17128,24.65016,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Nauriskasken koulu (2)','parc_exterior','Latokaski','Helsinki sub-region',NULL,'Kaskihaka 6, Latokaski',60.17094,24.65071,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Nurmilinnunpuisto','parc_exterior','Kilo','Helsinki sub-region',NULL,'Nurmilinnuntie 3, Kilo',60.23192,24.78338,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Von Glanin puisto','parc_exterior','Malminkartano','Helsinki sub-region',NULL,'Luutnantinpolku 7, Malminkartano',60.24661,24.86679,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Laajasuonpuisto','parc_exterior','Kannelmäki','Helsinki sub-region',NULL,'Poutunkuja 7, Kannelmäki',60.22266,24.89857,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Piianpuisto','parc_exterior','Malminkartano','Helsinki sub-region',NULL,'Piianpolku 7, Malminkartano',60.24415,24.85718,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Unelmien kannas','parc_exterior','Turku','Turku',NULL,'Paavo Nurmen puistotie 15, Turku',60.44054,22.26262,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Aurinkovuoren koulu','parc_exterior','Asikkala','Lahti',NULL,'Asikkalantie 12, Asikkala',61.1762,25.52564,1,false,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Latokasken koulu','parc_exterior','Latokaski','Helsinki sub-region',NULL,'Kulolaakso 1, Latokaski',60.17724,24.65272,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Kantokasken koulu','parc_exterior','Latokaski','Helsinki sub-region',NULL,'Kaskisavu 4, Latokaski',60.18121,24.6615,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Ritaharjun koulu','parc_exterior','Kello','Oulu',NULL,'Ansareitti 6, Kello',65.08181,25.45709,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Hästmyrinpiha','parc_exterior','Kaupunginkallio','Helsinki sub-region',NULL,'Heisipuunkuja 5, Kaupunginkallio',60.19712,24.66303,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Keravanjoen koulu','parc_exterior','Kerava','Helsinki sub-region',NULL,'Jurvalantie 8, Kerava',60.40333,25.11904,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Keravanjoen koulu (2)','parc_exterior','Kerava','Helsinki sub-region',NULL,'Jurvalantie 8, Kerava',60.40333,25.1191,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Yhteiskoulun Kampus','parc_exterior','Järvenpää','Helsinki sub-region',NULL,'Kansakoulunkatu 1, Järvenpää',60.4656,25.09232,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Yhteiskoulun Kampus (2)','parc_exterior','Järvenpää','Helsinki sub-region',NULL,'Kansakoulunkatu 1, Järvenpää',60.46555,25.09237,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Opinmäen kampus','parc_exterior','Kuurinniitty','Helsinki sub-region',NULL,'Lillhemtintie 1, Kuurinniitty',60.19044,24.73736,1,false,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Opinmäen kampus (2)','parc_exterior','Kuurinniitty','Helsinki sub-region',NULL,'Lillhemtintie 1, Kuurinniitty',60.19042,24.73744,1,false,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Opinmäen kampus (3)','parc_exterior','Kuurinniitty','Helsinki sub-region',NULL,'Lillhemtintie 1, Kuurinniitty',60.1904,24.73753,1,false,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Laajasalon peruskoulu','parc_exterior','Meri-Rastila','Helsinki sub-region',NULL,'Koulutanhua 1, Meri-Rastila',60.17894,25.05685,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Sakarinmäen peruskoulu','parc_exterior','Länsimäki','Helsinki sub-region',NULL,'Knutersintie 924, Länsimäki',60.26163,25.21204,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Järvenperän koulu','parc_exterior','Järvenperä','Helsinki sub-region',NULL,'Auroranmäki 1, Järvenperä',60.23925,24.704,1,false,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Lintumetsän koulu','parc_exterior','Lintuvaara','Helsinki sub-region',NULL,'Lintumetsäntie 12, Lintuvaara',60.23743,24.81848,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Lintumetsän koulu (2)','parc_exterior','Lintuvaara','Helsinki sub-region',NULL,'Lintumetsäntie 10, Lintuvaara',60.23817,24.81914,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Lintumetsän koulu (3)','parc_exterior','Lintuvaara','Helsinki sub-region',NULL,'Lintumetsäntie 10, Lintuvaara',60.23817,24.819,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Tampereen Pallo-Veikot','parc_exterior','Tampere','Tampere',NULL,'Kalevan puistotie 25, Tampere',61.49817,23.788,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Aimo Park','parc_exterior','Helsinki','Helsinki sub-region',NULL,'Mechelininkatu 32b, Helsinki',60.17754,24.91585,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Kurikanvainion leikkipuisto','parc_exterior','Pirkkala','Tampere',NULL,'Kullaantie 6, Pirkkala',61.46246,23.65538,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Nunnavuoren palloiluhalli','parc_exterior','Turku','Turku',NULL,'Piiparinpolku 21, Turku',60.48944,22.26459,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Kartanonhaan puisto','parc_exterior','Malminkartano','Helsinki sub-region',NULL,'Puustellinpolku 13, Malminkartano',60.24576,24.8609,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Köydenpunojankatu','parc_exterior','Helsinki','Helsinki sub-region',NULL,'Köydenpunojankatu 10, Helsinki',60.16432,24.92267,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Pikku-Vesijärvi Park','parc_exterior','Lahti','Lahti',NULL,'Kariniemenkatu, Lahti',60.98784,25.64254,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Pikku-Vesijärvi Park (2)','parc_exterior','Lahti','Lahti',NULL,'Kariniemenkatu, Lahti',60.98787,25.64257,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Oulun Pöytätennis -86 ry','parc_exterior','Oulu','Oulu',NULL,'Ratamotie 22, Oulu',65.06918,25.43069,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Herttoniemen Urheilupuisto','parc_exterior','Pihlajisto','Helsinki sub-region',NULL,'Siilitie 12, Pihlajisto',60.20778,25.03487,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Ruskontie','parc_exterior','Masku','Turku',NULL,'Ruskontie 45, Masku',60.54678,22.13104,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Iso Leikosaari','parc_exterior','Kallahti','Uusimaa',NULL,'Iso Leikosaari, Kallahti',60.1717,25.1543,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Kuikkulankatu','parc_exterior','Turku','Turku',NULL,'Kuikkulankatu 5a, Turku',60.46382,22.29704,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Lutakon satamakortteli','parc_exterior','Jyväskylä','Jyväskylä',NULL,'Uno Savolan katu 19, Jyväskylä',62.2383,25.7561,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Rantapuisto','parc_exterior','Järvenpää','Helsinki sub-region',NULL,'Kasinokuja 5, Järvenpää',60.46634,25.08399,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Kalevan liikuntapuisto','parc_exterior','Tampere','Tampere',NULL,'Salhojankatu 56, Tampere',61.49592,23.7863,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Kalevan liikuntapuisto (2)','parc_exterior','Tampere','Tampere',NULL,'Salhojankatu 56, Tampere',61.49599,23.78627,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Kalevan liikuntapuisto (3)','parc_exterior','Tampere','Tampere',NULL,'Salhojankatu 56, Tampere',61.49605,23.78626,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Hyvinkään lukio','parc_exterior','Hyvinge','Helsinki sub-region',NULL,'Kenkätehtaankatu 1, Hyvinge',60.62892,24.85227,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pöytätennis Iso Vasikkasaari','parc_exterior','Haukilahti','Helsinki sub-region',NULL,'Iso Vasikkasaari, Haukilahti',60.14095,24.76013,1,true,false,NULL,NULL,ARRAY['exterior'],true,false)
) AS v(name,type,city,county,sector,address,lat,lng,tables_count,free_access,night_lighting,hours,description,tags,approved,verified)
JOIN cities c ON c.country_code='FI' AND c.name=v.city
ON CONFLICT (name,city_id) DO NOTHING;
COMMIT;
