-- HR — Croatia — 266 venues, 54 cities
-- Idempotent: safe to run multiple times. Source: OpenStreetMap via Overture Maps + GeoNames.
-- STAGED: cities active=false, expansion_status='community_review' (hidden in-app until activated — see DEPLOYMENT.md). Venues approved=true.
BEGIN;
INSERT INTO countries (code,name,active) VALUES ('HR','Croatia',true) ON CONFLICT (code) DO NOTHING;
INSERT INTO cities (name,country_code,country_name,admin_area,county,lat,lng,zoom,active,expansion_status) VALUES
  ('Baška','HR','Croatia','Primorje-Gorski Kotar','Baška',44.97028,14.75333,12,false,'community_review'),
  ('Bestovje','HR','Croatia','Zagreb County','Sveta Nedelja',45.80833,15.81667,12,false,'community_review'),
  ('Bjelovar','HR','Croatia','Bjelovar-Bilogora','Grad Bjelovar',45.89789,16.85071,12,false,'community_review'),
  ('Buzdohanj','HR','Croatia','Primorje-Gorski Kotar','Čavle',45.34528,14.48833,12,false,'community_review'),
  ('Buzin','HR','Croatia','Zagreb','Novi Zagreb – istok',45.75,16,12,false,'community_review'),
  ('Cavtat','HR','Croatia','Dubrovnik-Neretva','Općina Konavle',42.58111,18.21806,12,false,'community_review'),
  ('Cres','HR','Croatia','Primorje-Gorski Kotar','Cres',44.96092,14.41246,12,false,'community_review'),
  ('Crikvenica','HR','Croatia','Primorje-Gorski Kotar','Grad Crikvenica',45.17722,14.69278,12,false,'community_review'),
  ('Daruvar','HR','Croatia','Bjelovar-Bilogora','Grad Daruvar',45.59056,17.225,12,false,'community_review'),
  ('Dobrinj','HR','Croatia','Primorje-Gorski Kotar','Dobrinj',45.12999,14.60381,12,false,'community_review'),
  ('Dramalj','HR','Croatia','Primorje-Gorski Kotar','Grad Crikvenica',45.19326,14.66851,12,false,'community_review'),
  ('Fažana','HR','Croatia','Istria','Fažana-Fasana',44.92742,13.80349,12,false,'community_review'),
  ('Funtana','HR','Croatia','Istria','Funtana-Fontane',45.17472,13.605,12,false,'community_review'),
  ('Ivanić-Grad','HR','Croatia','Zagreb County','Grad Ivanić-Grad',45.70833,16.39694,12,false,'community_review'),
  ('Ivanja Reka','HR','Croatia','Zagreb','Peščenica – Žitnjak',45.80222,16.11889,12,false,'community_review'),
  ('Jankomir','HR','Croatia','Zagreb','Stenjevec',45.79167,15.9,12,false,'community_review'),
  ('Jelsa','HR','Croatia','Split-Dalmatia','Jelsa',43.16139,16.69306,12,false,'community_review'),
  ('Josipdol','HR','Croatia','Karlovac','Općina Josipdol',45.1937,15.28924,12,false,'community_review'),
  ('Kašina','HR','Croatia','Zagreb','Sesvete',45.91134,16.12436,12,false,'community_review'),
  ('Kopčevec','HR','Croatia','Zagreb County','Grad Dugo Selo',45.80375,16.21347,12,false,'community_review'),
  ('Kotoriba','HR','Croatia','Međimurje','Općina Kotoriba',46.355,16.81806,12,false,'community_review'),
  ('Krk','HR','Croatia','Primorje-Gorski Kotar','Grad Krk',45.02744,14.57542,12,false,'community_review'),
  ('Labin','HR','Croatia','Istria','Grad Labin',45.095,14.11972,12,false,'community_review'),
  ('Ližnjan','HR','Croatia','Istria','Ližnjan-Lisignano',44.82833,13.95694,12,false,'community_review'),
  ('Mali Lošinj','HR','Croatia','Primorje-Gorski Kotar','Mali Lošinj',44.53056,14.46861,12,false,'community_review'),
  ('Malinska','HR','Croatia','Primorje-Gorski Kotar','Malinska-Dubašnica',45.12417,14.52828,12,false,'community_review'),
  ('Marinići','HR','Croatia','Primorje-Gorski Kotar','Viškovo',45.365,14.39389,12,false,'community_review'),
  ('Medulin','HR','Croatia','Istria','Medulin',44.8225,13.935,12,false,'community_review'),
  ('Mičevec','HR','Croatia','Zagreb County','Grad Velika Gorica',45.7521,16.05831,12,false,'community_review'),
  ('Novalja','HR','Croatia','Lika-Senj','Novalja',44.55778,14.88667,12,false,'community_review'),
  ('Novigrad','HR','Croatia','Istria','Novigrad-Cittanova',45.315,13.55806,12,false,'community_review'),
  ('Opatija','HR','Croatia','Primorje-Gorski Kotar','Grad Opatija',45.33658,14.30782,12,false,'community_review'),
  ('Osijek','HR','Croatia','County of Osijek-Baranja','Grad Osijek',45.55066,18.6942,12,false,'community_review'),
  ('Pakoštane','HR','Croatia','Zadar','Pakoštane',43.91222,15.50889,12,false,'community_review'),
  ('Poreč','HR','Croatia','Istria','Grad Poreč',45.22567,13.59511,12,false,'community_review'),
  ('Pula','HR','Croatia','Istria','Grad Pula',44.86833,13.84806,12,false,'community_review'),
  ('Punat','HR','Croatia','Primorje-Gorski Kotar','Punat',45.01472,14.62889,12,false,'community_review'),
  ('Rijeka','HR','Croatia','Primorje-Gorski Kotar','Grad Rijeka',45.32673,14.44241,12,false,'community_review'),
  ('Rovinj','HR','Croatia','Istria','Grad Rovinj',45.08268,13.63457,12,false,'community_review'),
  ('Rubeši','HR','Croatia','Primorje-Gorski Kotar','Kastav',45.36694,14.34806,12,false,'community_review'),
  ('Selca','HR','Croatia','Split-Dalmatia','Selca',43.29722,16.85083,12,false,'community_review'),
  ('Sesvete','HR','Croatia','Zagreb','Sesvete',45.83111,16.11639,12,false,'community_review'),
  ('Šibenik','HR','Croatia','Šibenik-Knin','Grad Šibenik',43.73429,15.8942,12,false,'community_review'),
  ('Sisak','HR','Croatia','Sisak-Moslavina','Grad Sisak',45.46608,16.37748,12,false,'community_review'),
  ('Split','HR','Croatia','Split-Dalmatia','Grad Split',43.50891,16.43915,12,false,'community_review'),
  ('Tar','HR','Croatia','Istria','Tar-Vabriga-Torre Abrega',45.30083,13.62528,12,false,'community_review'),
  ('Tisno','HR','Croatia','Šibenik-Knin','Tisno',43.80417,15.64333,12,false,'community_review'),
  ('Tkon','HR','Croatia','Zadar','Tkon',43.92096,15.41761,12,false,'community_review'),
  ('Topusko','HR','Croatia','Sisak-Moslavina','Općina Topusko',45.29306,15.97222,12,false,'community_review'),
  ('Umag','HR','Croatia','Istria','Umag-Umago',45.43139,13.52389,12,false,'community_review'),
  ('Valbandon','HR','Croatia','Istria','Fažana-Fasana',44.91879,13.81344,12,false,'community_review'),
  ('Zadar','HR','Croatia','Zadar','Zadar',44.11578,15.22514,12,false,'community_review'),
  ('Zagreb','HR','Croatia','Zagreb','Zagreb',45.81444,15.97798,12,false,'community_review'),
  ('Zaprešić','HR','Croatia','Zagreb County','Grad Zaprešić',45.85639,15.80778,12,false,'community_review')
ON CONFLICT (country_code,name) DO NOTHING;
INSERT INTO venues (name,type,city,city_id,county,sector,address,lat,lng,tables_count,free_access,night_lighting,hours,description,tags,approved,verified,submitted_by)
SELECT v.name,v.type,v.city,c.id,v.county::text,v.sector::text,v.address,v.lat::double precision,v.lng::double precision,v.tables_count::int,v.free_access::boolean,v.night_lighting::boolean,v.hours::text,v.description::text,v.tags::text[],v.approved::boolean,v.verified::boolean,NULL
FROM (VALUES
  ('Stolni tenis Resort Stella Maris','parc_exterior','Umag','Umag-Umago',NULL,'Monterol - Monterol 14, Umag',45.45139,13.51289,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Autocamp Bijela Uvala','parc_exterior','Funtana','Funtana-Fontane',NULL,'Bijela uvala 6, Funtana',45.18913,13.59254,1,true,false,'Apr Fr[-1] - Sep 30',NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Camping Bijar','parc_exterior','Mali Lošinj','Mali Lošinj',NULL,'Camping Bijar, Mali Lošinj',44.69973,14.39428,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis NK Josipdol','parc_exterior','Josipdol','Općina Josipdol',NULL,'Karlovačka 6, Josipdol',45.18918,15.28608,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis HNK Daruvar','parc_exterior','Daruvar','Grad Daruvar',NULL,'Julijev park 11, Daruvar',45.59882,17.2272,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('STK Kotoriba','parc_exterior','Kotoriba','Općina Kotoriba',NULL,'Trg slobode 1A, Kotoriba',46.36013,16.82456,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Lanterna','parc_exterior','Novigrad','Novigrad-Cittanova',NULL,'Lanterna 13, Novigrad',45.29428,13.57566,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Arena Stoja','parc_exterior','Pula','Grad Pula',NULL,'Arena Stoja, Pula',44.85637,13.81377,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Aleja Antuna Augustinčića','parc_exterior','Zagreb','Zagreb',NULL,'Aleja Antuna Augustinčića 8, Zagreb',45.81815,16.02518,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Aleja Antuna Augustinčića (2)','parc_exterior','Zagreb','Zagreb',NULL,'Aleja Antuna Augustinčića 8, Zagreb',45.81824,16.02514,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Aleja Antuna Augustinčića (3)','parc_exterior','Zagreb','Zagreb',NULL,'Aleja Antuna Augustinčića 8, Zagreb',45.81823,16.02507,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis BPM - Centar za grupne fitnes programe','parc_exterior','Zagreb','Zagreb',NULL,'Selska cesta 121E, Zagreb',45.80099,15.94555,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Aleja Matije Ljubeka (17)','parc_exterior','Jankomir','Stenjevec',NULL,'Aleja Matije Ljubeka 11, Jankomir',45.7799,15.91146,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Aleja Matije Ljubeka (18)','parc_exterior','Jankomir','Stenjevec',NULL,'Aleja Matije Ljubeka 19, Jankomir',45.77879,15.93741,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Ružmarinska','parc_exterior','Krk','Grad Krk',NULL,'Ružmarinska 2, Krk',45.02557,14.58077,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Aleja Antuna Augustinčića (4)','parc_exterior','Zagreb','Zagreb',NULL,'Aleja Antuna Augustinčića 8, Zagreb',45.81814,16.02512,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Put Bajla','parc_exterior','Zadar','Zadar',NULL,'Put Bajla 50, Zadar',44.09437,15.24992,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Put Bajla (2)','parc_exterior','Zadar','Zadar',NULL,'Put Bajla 50, Zadar',44.09442,15.24999,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Sportski park Zelenjak','parc_exterior','Ivanić-Grad','Grad Ivanić-Grad',NULL,'Omladinska ulica 21, Ivanić-Grad',45.70441,16.38635,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Sportski park Zelenjak (2)','parc_exterior','Ivanić-Grad','Grad Ivanić-Grad',NULL,'Omladinska ulica 21, Ivanić-Grad',45.70439,16.3861,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Sportski park Zelenjak (3)','parc_exterior','Ivanić-Grad','Grad Ivanić-Grad',NULL,'Omladinska ulica 21, Ivanić-Grad',45.7044,16.38621,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Sportski park Zelenjak (4)','parc_exterior','Ivanić-Grad','Grad Ivanić-Grad',NULL,'Omladinska ulica 21, Ivanić-Grad',45.70459,16.38629,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Punta Jerta','parc_exterior','Krk','Grad Krk',NULL,'Put svete Fuske 101, Krk',45.04149,14.47109,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Kamp Slamni Klimno','parc_exterior','Dobrinj','Dobrinj',NULL,'Klimno 8A, Dobrinj',45.15381,14.61753,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Autokamp Slatina','parc_exterior','Cres','Cres',NULL,'Vidovići 29, Cres',44.82218,14.34024,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Autokamp Slatina (2)','parc_exterior','Cres','Cres',NULL,'Vidovići 29, Cres',44.82227,14.34007,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Park Dinka Fija','parc_exterior','Jankomir','Stenjevec',NULL,'Remetinečki gaj 11A, Jankomir',45.76918,15.94683,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Park Dinka Fija (2)','parc_exterior','Jankomir','Stenjevec',NULL,'Remetinečki gaj 11A, Jankomir',45.76917,15.94678,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Zelenice','parc_exterior','Labin','Grad Labin',NULL,'Zelenice 30, Labin',45.09307,14.12345,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Rođendaonica i igraonica "Malo kraljevstvo"','parc_exterior','Zagreb','Zagreb',NULL,'Južna obala VI. 7, Zagreb',45.78439,15.96273,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Glavica','parc_exterior','Pula','Grad Pula',NULL,'Glavica 44, Pula',44.82202,13.86525,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Ulica Milovana Kovačevića','parc_exterior','Buzin','Novi Zagreb – istok',NULL,'Ulica Milovana Kovačevića 20, Buzin',45.7733,15.98731,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Ulica Milovana Kovačevića (2)','parc_exterior','Buzin','Novi Zagreb – istok',NULL,'Ulica Milovana Kovačevića 20, Buzin',45.77331,15.98741,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Ulica Milovana Kovačevića (3)','parc_exterior','Buzin','Novi Zagreb – istok',NULL,'Ulica Milovana Kovačevića 20, Buzin',45.77331,15.98752,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Osnovna škola Antuna Mihanovića (2)','parc_exterior','Sesvete','Sesvete',NULL,'Prominska ulica 1, Sesvete',45.83066,16.07802,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Osnovna škola Antuna Mihanovića (3)','parc_exterior','Sesvete','Sesvete',NULL,'Prominska ulica 1, Sesvete',45.83065,16.07808,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Osnovna škola Antuna Mihanovića (4)','parc_exterior','Sesvete','Sesvete',NULL,'Ulica Rudolfa Ivankovića 1, Sesvete',45.83064,16.07814,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Park Vinka Tomljanovića','parc_exterior','Zagreb','Zagreb',NULL,'Nova cesta 1, Zagreb',45.80844,15.95422,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Osnovna škola Matije Gupca','parc_exterior','Zagreb','Zagreb',NULL,'Ulica Davorina Bazjanca 2, Zagreb',45.79318,15.95033,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Bi Village','parc_exterior','Valbandon','Fažana-Fasana',NULL,'Ulica Dragonja - Via Dragogna 115, Valbandon',44.9176,13.80979,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Aminess Maravea Camping Resort','parc_exterior','Novigrad','Novigrad-Cittanova',NULL,'Ulica Laguna - Via Laguna 2A, Novigrad',45.34218,13.54428,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Kamp Straško','parc_exterior','Novalja','Novalja',NULL,'Zeleni put 9, Novalja',44.54428,14.87878,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Kamp Straško (2)','parc_exterior','Novalja','Novalja',NULL,'Zeleni put 9, Novalja',44.54426,14.87882,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Kamp Straško (3)','parc_exterior','Novalja','Novalja',NULL,'Zeleni put 9, Novalja',44.54424,14.87885,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Krk Premium Camping Resort','parc_exterior','Krk','Grad Krk',NULL,'Narodnog preporoda 80, Krk',45.02412,14.59246,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Djecje igraliste u Dalmatinskoj','parc_exterior','Zagreb','Zagreb',NULL,'Dalmatinska ulica 12/1, Zagreb',45.81199,15.96803,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis MVPiz','parc_exterior','Zagreb','Zagreb',NULL,'Miramarska cesta 85, Zagreb',45.79712,15.97383,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis MVPiz (2)','parc_exterior','Zagreb','Zagreb',NULL,'Miramarska cesta 83, Zagreb',45.79712,15.97397,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Kyudo društvo Zagreb','parc_exterior','Zagreb','Zagreb',NULL,'Voćarska cesta 71, Zagreb',45.81824,15.98746,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Kendo klub Zagreb','parc_exterior','Zagreb','Zagreb',NULL,'Voćarska cesta 71, Zagreb',45.81818,15.98746,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Aleja Matije Ljubeka (19)','parc_exterior','Jankomir','Stenjevec',NULL,'Aleja Matije Ljubeka 3B, Jankomir',45.78201,15.91967,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Grdine','parc_exterior','Malinska','Malinska-Dubašnica',NULL,'Grdine 10, Malinska',45.12047,14.53412,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Draga Bašćanska','parc_exterior','Baška','Baška',NULL,'Draga Bašćanska 252A, Baška',44.99495,14.71575,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Glavotok','parc_exterior','Malinska','Malinska-Dubašnica',NULL,'Glavotok 7, Malinska',45.09337,14.43903,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Trg Ivana Kukuljevića','parc_exterior','Jankomir','Stenjevec',NULL,'Trg Ivana Kukuljevića 7, Jankomir',45.80558,15.8959,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Park Emila Cossetta','parc_exterior','Jankomir','Stenjevec',NULL,'Ulica Marijane Radev 8, Jankomir',45.79504,15.9019,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Osnovna škola Tin Ujević','parc_exterior','Osijek','Grad Osijek',NULL,'Opatijska 46, Osijek',45.54521,18.72364,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Osnovna škola Tin Ujević (2)','parc_exterior','Osijek','Grad Osijek',NULL,'Opatijska 46, Osijek',45.54525,18.72363,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Dom zdravlja','parc_exterior','Osijek','Grad Osijek',NULL,'Biševska 31, Osijek',45.54723,18.71282,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Terra Park Phalaris','parc_exterior','Novalja','Novalja',NULL,'Škuncini stani - samorašnji 100, Novalja',44.57989,14.8513,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Terra Park Phalaris (2)','parc_exterior','Novalja','Novalja',NULL,'Škuncini stani - samorašnji 100, Novalja',44.57991,14.85134,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Istra Premium Camping Resort','parc_exterior','Funtana','Funtana-Fontane',NULL,'Grgeti 35, Funtana',45.17489,13.59659,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Istra Premium Camping Resort (2)','parc_exterior','Funtana','Funtana-Fontane',NULL,'Grgeti 35, Funtana',45.17492,13.59652,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Istra Premium Camping Resort (3)','parc_exterior','Funtana','Funtana-Fontane',NULL,'Grgeti 35, Funtana',45.17488,13.59649,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Istra Premium Camping Resort (4)','parc_exterior','Funtana','Funtana-Fontane',NULL,'Grgeti 35, Funtana',45.1746,13.59705,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Istra Premium Camping Resort (5)','parc_exterior','Funtana','Funtana-Fontane',NULL,'Grgeti 35, Funtana',45.17485,13.59655,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Gradsko kupalište','parc_exterior','Crikvenica','Grad Crikvenica',NULL,'Bana Jelačića 1A, Crikvenica',45.17834,14.68429,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Nacionalni park Brijuni','parc_exterior','Fažana','Fažana-Fasana',NULL,'Nacionalni park Brijuni, Fažana',44.91682,13.77689,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis MEGATON','parc_exterior','Zagreb','Zagreb',NULL,'Ilica 235/1, Zagreb',45.81367,15.93527,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Hrvatski akademski stolnoteniski klub Mladost','parc_exterior','Jankomir','Stenjevec',NULL,'Jarunska ulica 3, Jankomir',45.78273,15.94669,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Jiu Jitsu 3j2','parc_exterior','Osijek','Grad Osijek',NULL,'Šibenska 21, Osijek',45.54626,18.7237,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Senjska','parc_exterior','Osijek','Grad Osijek',NULL,'Senjska 28, Osijek',45.54741,18.72523,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Park Za Pse Savica','parc_exterior','Zagreb','Zagreb',NULL,'Lastovska ulica 40, Zagreb',45.78952,15.99924,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Park Za Pse Savica (2)','parc_exterior','Zagreb','Zagreb',NULL,'Lastovska ulica 40, Zagreb',45.78952,15.99931,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Amazona Fitness Club','parc_exterior','Jankomir','Stenjevec',NULL,'Ulica Majke Terezije 14, Jankomir',45.81474,15.89777,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Gajnice','parc_exterior','Jankomir','Stenjevec',NULL,'Gajnice 17, Jankomir',45.81613,15.8723,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Malonogometni turnir Jarun','parc_exterior','Jankomir','Stenjevec',NULL,'Ulica Hrvoja Macanovića 5A, Jankomir',45.78882,15.93469,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Šetalište Rajka Štambuka','parc_exterior','Selca','Selca',NULL,'Šetalište Rajka Štambuka 13, Selca',43.29685,16.84874,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Mate Balote','parc_exterior','Rubeši','Kastav',NULL,'Mate Balote 35, Rubeši',45.34603,14.36671,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Ratka Petrovića','parc_exterior','Buzdohanj','Čavle',NULL,'Ratka Petrovića 54B, Buzdohanj',45.32235,14.48272,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Ivana Žorža','parc_exterior','Rijeka','Grad Rijeka',NULL,'Ivana Žorža 5A, Rijeka',45.35264,14.43011,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Mukalba','parc_exterior','Medulin','Medulin',NULL,'Mukalba 78, Medulin',44.82706,13.92419,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Šibenska','parc_exterior','Osijek','Grad Osijek',NULL,'Šibenska 9, Osijek',45.54659,18.72268,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Stonska','parc_exterior','Osijek','Grad Osijek',NULL,'Stonska 7, Osijek',45.54421,18.72661,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Getaldićeva','parc_exterior','Split','Grad Split',NULL,'Getaldićeva 3, Split',43.50919,16.4687,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Ružmarinska (2)','parc_exterior','Krk','Grad Krk',NULL,'Ružmarinska 2, Krk',45.02545,14.58074,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Obala','parc_exterior','Punat','Punat',NULL,'Obala 103, Punat',45.01809,14.62794,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Obala (2)','parc_exterior','Punat','Punat',NULL,'Obala 103, Punat',45.01808,14.62786,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Osnovna škola Zapruđe','parc_exterior','Buzin','Novi Zagreb – istok',NULL,'Meštrovićev trg 8, Buzin',45.78059,15.99551,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Osnovna škola Zapruđe (2)','parc_exterior','Buzin','Novi Zagreb – istok',NULL,'Meštrovićev trg 8, Buzin',45.78054,15.99551,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Osnovna škola Zapruđe (3)','parc_exterior','Buzin','Novi Zagreb – istok',NULL,'Meštrovićev trg 8, Buzin',45.78055,15.99562,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Osnovna škola Zapruđe (4)','parc_exterior','Buzin','Novi Zagreb – istok',NULL,'Meštrovićev trg 8, Buzin',45.78055,15.99571,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Osnovna škola Augusta Cesarca','parc_exterior','Zagreb','Zagreb',NULL,'Ferenščica I. 84, Zagreb',45.80228,16.02485,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Osnovna škola Augusta Cesarca (2)','parc_exterior','Zagreb','Zagreb',NULL,'Ferenščica I. 84, Zagreb',45.80228,16.02475,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Osnovna škola Augusta Cesarca (3)','parc_exterior','Zagreb','Zagreb',NULL,'Ferenščica I. 84, Zagreb',45.80228,16.0248,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Top Terme Topusko','parc_exterior','Topusko','Općina Topusko',NULL,'Trg Josipa bana Jelačića 30, Topusko',45.29457,15.97478,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Dubravkin trg','parc_exterior','Zagreb','Zagreb',NULL,'Dubravkin trg 2, Zagreb',45.80295,15.99571,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Dubravkin trg (2)','parc_exterior','Zagreb','Zagreb',NULL,'Dubravkin trg 7, Zagreb',45.80252,15.99601,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Dubravkin trg (3)','parc_exterior','Zagreb','Zagreb',NULL,'Dubravkin trg 3, Zagreb',45.80288,15.99596,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Dječje igralište Boćarski dom','parc_exterior','Zagreb','Zagreb',NULL,'Prisavlje 6, Zagreb',45.78963,15.96415,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Perivoj Središće','parc_exterior','Buzin','Novi Zagreb – istok',NULL,'Ulica Brune Bušića 28, Buzin',45.7797,15.98788,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Zeleni trg','parc_exterior','Zagreb','Zagreb',NULL,'Zeleni trg 3A, Zagreb',45.79534,15.96203,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Zeleni trg (2)','parc_exterior','Zagreb','Zagreb',NULL,'Zeleni trg 3A, Zagreb',45.79535,15.96197,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Kalimero','parc_exterior','Zagreb','Zagreb',NULL,'Kninski trg 1, Zagreb',45.7964,15.96706,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Osnovna škola Julija Klovića','parc_exterior','Zagreb','Zagreb',NULL,'Nova cesta 136, Zagreb',45.79753,15.95549,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Osnovna škola Julija Klovića (2)','parc_exterior','Zagreb','Zagreb',NULL,'Nova cesta 136, Zagreb',45.79753,15.95558,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Osnovna škola bana Josipa Jelačića','parc_exterior','Bestovje','Sveta Nedelja',NULL,'Podgradski odvojak 1, Bestovje',45.81772,15.83434,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Osnovna škola bana Josipa Jelačića (2)','parc_exterior','Bestovje','Sveta Nedelja',NULL,'Podgradski odvojak 1, Bestovje',45.81772,15.8343,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Osnovna škola Galdovo','parc_exterior','Sisak','Grad Sisak',NULL,'Ulica Brezovičkog odreda 1B, Sisak',45.47835,16.39973,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Osnovna škola Galdovo (2)','parc_exterior','Sisak','Grad Sisak',NULL,'Ulica Brezovičkog odreda 1B, Sisak',45.47841,16.39976,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Dječje igralište "Tržnica"','parc_exterior','Zaprešić','Grad Zaprešić',NULL,'Trg žrtava fašizma 11, Zaprešić',45.85601,15.8044,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Dječje igralište "Tržnica" (2)','parc_exterior','Zaprešić','Grad Zaprešić',NULL,'Trg žrtava fašizma 11, Zaprešić',45.85602,15.80443,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Jezera Village','parc_exterior','Tisno','Tisno',NULL,'Uvala Lovišća 1A, Tisno',43.79231,15.62732,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Jezera Village (2)','parc_exterior','Tisno','Tisno',NULL,'Uvala Lovišća 1A, Tisno',43.79231,15.62739,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Lanterna','parc_exterior','Tar','Tar-Vabriga-Torre Abrega',NULL,'Lanterna 7, Tar',45.30279,13.58995,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Lanterna (2)','parc_exterior','Tar','Tar-Vabriga-Torre Abrega',NULL,'Lanterna 7, Tar',45.30277,13.58994,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Lanterna (3)','parc_exterior','Tar','Tar-Vabriga-Torre Abrega',NULL,'Lanterna 7, Tar',45.30274,13.58994,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Lanterna (4)','parc_exterior','Tar','Tar-Vabriga-Torre Abrega',NULL,'Lanterna 7, Tar',45.30271,13.58993,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Lanterna (5)','parc_exterior','Tar','Tar-Vabriga-Torre Abrega',NULL,'Lanterna 7, Tar',45.30268,13.58992,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis KK Dinamo Zagreb','parc_exterior','Jankomir','Stenjevec',NULL,'Oriovačka ulica 9, Jankomir',45.79764,15.9216,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis KK Dinamo Zagreb (2)','parc_exterior','Jankomir','Stenjevec',NULL,'Oriovačka ulica 9, Jankomir',45.79764,15.92167,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Hrvatska Unija Tenisača','parc_exterior','Zagreb','Zagreb',NULL,'Ulica grada Vukovara 236E, Zagreb',45.79831,15.99393,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Hrvatska Unija Tenisača (2)','parc_exterior','Zagreb','Zagreb',NULL,'Ulica grada Vukovara 236E, Zagreb',45.79831,15.99399,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Hrvatska Unija Tenisača (3)','parc_exterior','Zagreb','Zagreb',NULL,'Ulica grada Vukovara 236E, Zagreb',45.79831,15.99405,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Hrvatska Unija Tenisača (4)','parc_exterior','Zagreb','Zagreb',NULL,'Ulica grada Vukovara 236E, Zagreb',45.79831,15.99411,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Tennis Camp','parc_exterior','Funtana','Funtana-Fontane',NULL,'Zelena laguna 19, Funtana',45.19657,13.59113,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Simon Emanuel Travel','parc_exterior','Ivanja Reka','Peščenica – Žitnjak',NULL,'Ulica Petra Dumičića 16, Ivanja Reka',45.80996,16.11266,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Simon Emanuel Travel (2)','parc_exterior','Ivanja Reka','Peščenica – Žitnjak',NULL,'Ulica Petra Dumičića 16, Ivanja Reka',45.80996,16.11259,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Simon Emanuel Travel (3)','parc_exterior','Ivanja Reka','Peščenica – Žitnjak',NULL,'Ulica Mladena Pozajića 15, Ivanja Reka',45.80991,16.112,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Ulica Mladena Pozajića','parc_exterior','Ivanja Reka','Peščenica – Žitnjak',NULL,'Ulica Mladena Pozajića 15, Ivanja Reka',45.80993,16.11171,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Domjanićeva','parc_exterior','Zagreb','Zagreb',NULL,'Ulica Dragutina Domjanića 14/1, Zagreb',45.81602,15.99731,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis IKTUS Rowing Club','parc_exterior','Osijek','Grad Osijek',NULL,'Šetalište kardinala Franje Šepera 1D, Osijek',45.56255,18.69031,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Bazeni Copacabana','parc_exterior','Osijek','Grad Osijek',NULL,'Biljska cesta 1D, Osijek',45.5659,18.69722,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Ulica Josipa Runjanina','parc_exterior','Zagreb','Zagreb',NULL,'Ulica Josipa Runjanina 3, Zagreb',45.80416,15.96908,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Ulica Josipa Runjanina (2)','parc_exterior','Zagreb','Zagreb',NULL,'Ulica Josipa Runjanina 3, Zagreb',45.80413,15.96908,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Autodrom Ayrton Senna','parc_exterior','Zagreb','Zagreb',NULL,'Ulica Ćire Truhelke 35, Zagreb',45.79068,15.95421,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Autodrom Ayrton Senna (2)','parc_exterior','Zagreb','Zagreb',NULL,'Ulica Ćire Truhelke 35, Zagreb',45.79066,15.95429,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis ŠK Vrustun 1252 -Vurnovec','parc_exterior','Kašina','Sesvete',NULL,'Vurnovečka ulica 11, Kašina',45.88846,16.13627,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Caffe Bar Sunshine','parc_exterior','Zagreb','Zagreb',NULL,'Poljička ulica 6, Zagreb',45.7959,15.96383,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Dječje igralište Puntice','parc_exterior','Ližnjan','Ližnjan-Lisignano',NULL,'Puntice 2D, Ližnjan',44.81924,13.97395,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Pikado klub "Zapad" Zagreb','parc_exterior','Jankomir','Stenjevec',NULL,'Ulica Dragutina Golika 44, Jankomir',45.79932,15.9297,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Pikado klub "Zapad" Zagreb (2)','parc_exterior','Jankomir','Stenjevec',NULL,'Ulica Dragutina Golika 44A, Jankomir',45.79932,15.92984,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Pikado klub "Zapad" Zagreb (3)','parc_exterior','Jankomir','Stenjevec',NULL,'Ulica Dragutina Golika 44, Jankomir',45.79932,15.92977,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Vojski do','parc_exterior','Cavtat','Općina Konavle',NULL,'Vojski do 1, Cavtat',42.57645,18.29961,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Ferenščica I.','parc_exterior','Zagreb','Zagreb',NULL,'Ferenščica I. 68, Zagreb',45.80332,16.02393,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Ferenščica I. (2)','parc_exterior','Zagreb','Zagreb',NULL,'Ferenščica I. 68, Zagreb',45.80331,16.02401,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Hrgovići','parc_exterior','Jankomir','Stenjevec',NULL,'Hrgovići 73, Jankomir',45.78535,15.92812,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Trnjanska struga','parc_exterior','Zagreb','Zagreb',NULL,'Trnjanska struga 34, Zagreb',45.79105,15.97679,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Kolodvorska ulica','parc_exterior','Zaprešić','Grad Zaprešić',NULL,'Kolodvorska ulica 4, Zaprešić',45.84319,15.80994,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Kolodvorska ulica (2)','parc_exterior','Zaprešić','Grad Zaprešić',NULL,'Kolodvorska ulica 4, Zaprešić',45.8432,15.81004,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Plava laguna','parc_exterior','Poreč','Grad Poreč',NULL,'Plava laguna 21, Poreč',45.20827,13.59271,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Petra Jurčića','parc_exterior','Marinići','Viškovo',NULL,'Petra Jurčića 4, Marinići',45.34223,14.38953,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Kačjak','parc_exterior','Dramalj','Grad Crikvenica',NULL,'Kačjak 12, Dramalj',45.20248,14.64975,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Kačjak (2)','parc_exterior','Dramalj','Grad Crikvenica',NULL,'Kačjak 12, Dramalj',45.20224,14.65,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Ulica jasena','parc_exterior','Sesvete','Sesvete',NULL,'Ulica jasena 1, Sesvete',45.82689,16.06909,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Ivanićgradska ulica','parc_exterior','Zagreb','Zagreb',NULL,'Ivanićgradska ulica 66, Zagreb',45.80148,16.01991,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Ivanićgradska ulica (2)','parc_exterior','Zagreb','Zagreb',NULL,'Ivanićgradska ulica 66, Zagreb',45.80148,16.01998,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Aleja Matije Ljubeka','parc_exterior','Jankomir','Stenjevec',NULL,'Aleja Matije Ljubeka 19, Jankomir',45.77886,15.93789,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Aleja Matije Ljubeka (2)','parc_exterior','Jankomir','Stenjevec',NULL,'Aleja Matije Ljubeka 19, Jankomir',45.77885,15.93797,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Aleja Matije Ljubeka (3)','parc_exterior','Jankomir','Stenjevec',NULL,'Aleja Matije Ljubeka 19, Jankomir',45.77885,15.93805,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Aleja Matije Ljubeka (4)','parc_exterior','Jankomir','Stenjevec',NULL,'Aleja Matije Ljubeka 19, Jankomir',45.77895,15.93789,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Aleja Matije Ljubeka (5)','parc_exterior','Jankomir','Stenjevec',NULL,'Aleja Matije Ljubeka 19, Jankomir',45.77889,15.93822,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Aleja Matije Ljubeka (6)','parc_exterior','Jankomir','Stenjevec',NULL,'Aleja Matije Ljubeka 19, Jankomir',45.77889,15.93831,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Aleja Matije Ljubeka (7)','parc_exterior','Jankomir','Stenjevec',NULL,'Aleja Matije Ljubeka 19, Jankomir',45.77903,15.93806,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Aleja Matije Ljubeka (8)','parc_exterior','Jankomir','Stenjevec',NULL,'Aleja Matije Ljubeka 19, Jankomir',45.77904,15.93789,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Radnička cesta','parc_exterior','Mičevec','Grad Velika Gorica',NULL,'Radnička cesta 280A, Mičevec',45.77205,16.0632,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Radnička cesta (2)','parc_exterior','Mičevec','Grad Velika Gorica',NULL,'Radnička cesta 280A, Mičevec',45.77195,16.06318,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Skokov prilaz','parc_exterior','Buzin','Novi Zagreb – istok',NULL,'Skokov prilaz 11, Buzin',45.77402,15.99759,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Fancevljev prilaz','parc_exterior','Buzin','Novi Zagreb – istok',NULL,'Fancevljev prilaz 12, Buzin',45.77402,15.99752,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Poljačka ulica','parc_exterior','Jankomir','Stenjevec',NULL,'Poljačka ulica 1, Jankomir',45.81047,15.92361,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Poljačka ulica (2)','parc_exterior','Jankomir','Stenjevec',NULL,'Poljačka ulica 1, Jankomir',45.81051,15.92357,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Novska ulica','parc_exterior','Zagreb','Zagreb',NULL,'Novska ulica 4, Zagreb',45.79101,15.99069,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Jelsa','parc_exterior','Jelsa','Jelsa',NULL,'Jelsa 893, Jelsa',43.16305,16.70172,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Trnsko','parc_exterior','Buzin','Novi Zagreb – istok',NULL,'Trnsko 1E, Buzin',45.77644,15.96421,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Ulica Ante Jakšića','parc_exterior','Zagreb','Zagreb',NULL,'Ulica Ante Jakšića 17, Zagreb',45.81352,16.02262,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Ulica Ante Jakšića (2)','parc_exterior','Zagreb','Zagreb',NULL,'Ulica Ante Jakšića 17, Zagreb',45.81342,16.02266,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Aleja Matije Ljubeka (9)','parc_exterior','Jankomir','Stenjevec',NULL,'Aleja Matije Ljubeka 19, Jankomir',45.77894,15.93805,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Aleja Matije Ljubeka (10)','parc_exterior','Jankomir','Stenjevec',NULL,'Aleja Matije Ljubeka 19, Jankomir',45.77895,15.93797,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Aleja Matije Ljubeka (11)','parc_exterior','Jankomir','Stenjevec',NULL,'Aleja Matije Ljubeka 19, Jankomir',45.77903,15.93798,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Aleja Matije Ljubeka (12)','parc_exterior','Jankomir','Stenjevec',NULL,'Aleja Matije Ljubeka 19, Jankomir',45.77889,15.93814,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Aleja Matije Ljubeka (13)','parc_exterior','Jankomir','Stenjevec',NULL,'Aleja Matije Ljubeka 11, Jankomir',45.77984,15.91156,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Aleja Matije Ljubeka (14)','parc_exterior','Jankomir','Stenjevec',NULL,'Aleja Matije Ljubeka 11, Jankomir',45.77984,15.91164,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Aleja Matije Ljubeka (15)','parc_exterior','Jankomir','Stenjevec',NULL,'Aleja Matije Ljubeka 13, Jankomir',45.77986,15.91189,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Park Stanke Kovačić in der Mühlen','parc_exterior','Jankomir','Stenjevec',NULL,'Srednjaci 21, Jankomir',45.78971,15.94166,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Osnovna škola Vrbani','parc_exterior','Jankomir','Stenjevec',NULL,'Rudeška cesta 152, Jankomir',45.79322,15.91745,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Osnovna škola Vrbani (2)','parc_exterior','Jankomir','Stenjevec',NULL,'Rudeška cesta 152, Jankomir',45.79318,15.91747,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Namsko igralište','parc_exterior','Buzin','Novi Zagreb – istok',NULL,'Trnsko 38A, Buzin',45.77169,15.96528,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Namsko igralište (2)','parc_exterior','Buzin','Novi Zagreb – istok',NULL,'Trnsko 38B, Buzin',45.77163,15.96528,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Osnovna škola Rikard Katalinić Jeretov','parc_exterior','Opatija','Grad Opatija',NULL,'Nova cesta 55, Opatija',45.34399,14.31233,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Park Dugave','parc_exterior','Buzin','Novi Zagreb – istok',NULL,'Ulica sv. Mateja 1, Buzin',45.76504,15.99708,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Park Dugave (2)','parc_exterior','Buzin','Novi Zagreb – istok',NULL,'Ulica sv. Mateja 1, Buzin',45.76504,15.99681,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Park Dugave (3)','parc_exterior','Buzin','Novi Zagreb – istok',NULL,'Ulica sv. Mateja 49, Buzin',45.76351,15.99524,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Park Fontana','parc_exterior','Sisak','Grad Sisak',NULL,'Ulica kneza Branimira 5, Sisak',45.45832,16.38691,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Park Fontana (2)','parc_exterior','Sisak','Grad Sisak',NULL,'Ulica kneza Branimira 9, Sisak',45.45827,16.38681,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Osnovna škola Antuna Mihanovića','parc_exterior','Sesvete','Sesvete',NULL,'Prominska ulica 1, Sesvete',45.83064,16.07809,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Kalimero (2)','parc_exterior','Zagreb','Zagreb',NULL,'Kninski trg 1, Zagreb',45.7964,15.96711,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Kalimero (3)','parc_exterior','Zagreb','Zagreb',NULL,'Kninski trg 1, Zagreb',45.7964,15.96716,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Osnovna škola Nikole Tesle','parc_exterior','Jankomir','Stenjevec',NULL,'Bezdanska ulica 62, Jankomir',45.79328,15.89763,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Osnovna škola Nikole Tesle (2)','parc_exterior','Jankomir','Stenjevec',NULL,'Bezdanska ulica 62, Jankomir',45.79326,15.89761,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Osnovna škola Cvjetno naselje','parc_exterior','Zagreb','Zagreb',NULL,'Cvjetna cesta 17, Zagreb',45.79093,15.96334,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Učenički dom Novi Zagreb','parc_exterior','Buzin','Novi Zagreb – istok',NULL,'Avenija Većeslava Holjevca 9, Buzin',45.77447,15.9813,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Učenički dom Novi Zagreb (2)','parc_exterior','Buzin','Novi Zagreb – istok',NULL,'Avenija Većeslava Holjevca 9, Buzin',45.77447,15.98134,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Camping Ulika','parc_exterior','Poreč','Grad Poreč',NULL,'Kolombera 7, Poreč',45.25451,13.58366,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis FKK Sovinje','parc_exterior','Tkon','Tkon',NULL,'Plažine 100, Tkon',43.9091,15.43563,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Park Bulgaria','parc_exterior','Opatija','Grad Opatija',NULL,'Maršala Tita 27, Opatija',45.3423,14.31353,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Osnovna škola Dragutina Tadijanovića','parc_exterior','Jankomir','Stenjevec',NULL,'Bolnička cesta 60A, Jankomir',45.8176,15.89044,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Osnovna škola Dragutina Tadijanovića (2)','parc_exterior','Jankomir','Stenjevec',NULL,'Bolnička cesta 60A, Jankomir',45.81764,15.89044,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Kupalište Jadrija','parc_exterior','Šibenik','Grad Šibenik',NULL,'Jadrija IX 44, Šibenik',43.72325,15.84763,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Resort Amarin','parc_exterior','Rovinj','Grad Rovinj',NULL,'T. n. "Monsena" 4, Rovinj',45.10428,13.61998,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Pine Beach Pakoštane Adriatic Eco Resort','parc_exterior','Pakoštane','Pakoštane',NULL,'Pine Beach Pakoštane Adriatic Eco Resort, Pakoštane',43.91028,15.49564,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Kažela','parc_exterior','Medulin','Medulin',NULL,'Kažela, Medulin',44.80526,13.95358,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Športski centar Višnjik','parc_exterior','Zadar','Zadar',NULL,'Splitska ulica 1, Zadar',44.11875,15.24356,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Park Bužanova','parc_exterior','Zagreb','Zagreb',NULL,'Ulica Dragojla Kušlana 52A, Zagreb',45.81203,16.00738,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Polleo Sport Tower Centar Rijeka','parc_exterior','Rijeka','Grad Rijeka',NULL,'Drage Gervaisa 64, Rijeka',45.3184,14.46987,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Radmanovačka ulica (2)','parc_exterior','Buzin','Novi Zagreb – istok',NULL,'Radmanovačka ulica 39, Buzin',45.77103,15.96959,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Radmanovačka ulica (3)','parc_exterior','Buzin','Novi Zagreb – istok',NULL,'Radmanovačka ulica 39, Buzin',45.77103,15.96967,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Radmanovačka ulica (6)','parc_exterior','Buzin','Novi Zagreb – istok',NULL,'Radmanovačka ulica 39, Buzin',45.77091,15.96968,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis GymB','parc_exterior','Zagreb','Zagreb',NULL,'Ulica Franje Petračića 17, Zagreb',45.806,15.95736,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Park Gajnice Pabla Nerude','parc_exterior','Jankomir','Stenjevec',NULL,'Ulica Pabla Nerude 3, Jankomir',45.8183,15.87339,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Pacific Hrvatska','parc_exterior','Zagreb','Zagreb',NULL,'Čiovska ulica 27, Zagreb',45.79673,16.0009,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Parking ispred zgrade','parc_exterior','Jankomir','Stenjevec',NULL,'Ulica Ante Topić - Mimare 11, Jankomir',45.80783,15.89296,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Parking ispred zgrade (2)','parc_exterior','Jankomir','Stenjevec',NULL,'Ulica Ante Topić - Mimare 11, Jankomir',45.8078,15.8931,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolnoteniski klub Bjelovar','parc_exterior','Bjelovar','Grad Bjelovar',NULL,'Janka Draškovića 1A, Bjelovar',45.89489,16.84076,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Rent a Boat Porec Sport Mediteran','parc_exterior','Poreč','Grad Poreč',NULL,'Plava laguna 4, Poreč',45.21349,13.59231,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Športski centar Višnjik (2)','parc_exterior','Zadar','Zadar',NULL,'Ulica Domovinskog rata 7, Zadar',44.11898,15.24331,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Kauzlarićev prilaz','parc_exterior','Buzin','Novi Zagreb – istok',NULL,'Kauzlarićev prilaz 17, Buzin',45.76566,16.00461,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis SAM Professional j.d.o.o','parc_exterior','Zagreb','Zagreb',NULL,'Trg Stjepana Konzula 5, Zagreb',45.80639,16.02116,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis SAM Professional j.d.o.o (2)','parc_exterior','Zagreb','Zagreb',NULL,'Zapoljska ulica 14, Zagreb',45.80634,16.02121,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Prilaz sv. Josipa Radnika','parc_exterior','Zagreb','Zagreb',NULL,'Prilaz sv. Josipa Radnika 14, Zagreb',45.8065,16.02108,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Prilaz sv. Josipa Radnika (2)','parc_exterior','Zagreb','Zagreb',NULL,'Prilaz sv. Josipa Radnika 14, Zagreb',45.80655,16.02104,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Prilaz sv. Josipa Radnika (3)','parc_exterior','Zagreb','Zagreb',NULL,'Prilaz sv. Josipa Radnika 14, Zagreb',45.80659,16.021,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis KKBosco','parc_exterior','Buzin','Novi Zagreb – istok',NULL,'Trnsko 14A, Buzin',45.77477,15.96278,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Taekwondo klub Velebit','parc_exterior','Rijeka','Grad Rijeka',NULL,'Franje Matkovića 7A, Rijeka',45.32025,14.47409,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Fitness Club by Martina Balent','parc_exterior','Jankomir','Stenjevec',NULL,'Bolnička cesta 96, Jankomir',45.81988,15.88241,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Zagreb Prečko','parc_exterior','Jankomir','Stenjevec',NULL,'Ulica Dore Pejačević 2, Jankomir',45.79068,15.9017,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Boćarski Klub Špansko','parc_exterior','Jankomir','Stenjevec',NULL,'Ulica Slavka Batušića 2A, Jankomir',45.80053,15.89947,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Boćarski Klub Špansko (2)','parc_exterior','Jankomir','Stenjevec',NULL,'Ulica Slavka Batušića 2A, Jankomir',45.80053,15.89952,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Boćarski Klub Špansko (3)','parc_exterior','Jankomir','Stenjevec',NULL,'Ulica Slavka Batušića 2A, Jankomir',45.80053,15.89958,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Boćarski Klub Špansko (4)','parc_exterior','Jankomir','Stenjevec',NULL,'Ulica Slavka Batušića 2A, Jankomir',45.80052,15.89963,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Boksački klub Zagreb - Zagreb Boxing Club','parc_exterior','Jankomir','Stenjevec',NULL,'Ulica Vlade Gotovca 1, Jankomir',45.80004,15.90661,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Opatijski Trg','parc_exterior','Jankomir','Stenjevec',NULL,'Fallerovo šetalište 37, Jankomir',45.79968,15.93635,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Kanalski put','parc_exterior','Mičevec','Grad Velika Gorica',NULL,'Kanalski put 64, Mičevec',45.79258,16.04527,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Kanalski put (2)','parc_exterior','Mičevec','Grad Velika Gorica',NULL,'Kanalski put 64, Mičevec',45.79258,16.04536,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Aleja Matije Ljubeka (16)','parc_exterior','Jankomir','Stenjevec',NULL,'Aleja Matije Ljubeka 13, Jankomir',45.7797,15.91179,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Radmanovačka ulica','parc_exterior','Buzin','Novi Zagreb – istok',NULL,'Radmanovačka ulica 39, Buzin',45.77103,15.96952,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Radmanovačka ulica (4)','parc_exterior','Buzin','Novi Zagreb – istok',NULL,'Radmanovačka ulica 39, Buzin',45.77091,15.96954,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Radmanovačka ulica (5)','parc_exterior','Buzin','Novi Zagreb – istok',NULL,'Radmanovačka ulica 39, Buzin',45.77091,15.96961,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Ulica Bedema ljubavi','parc_exterior','Kopčevec','Grad Dugo Selo',NULL,'Ulica Bedema ljubavi 11, Kopčevec',45.80992,16.18058,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Ulica Bedema ljubavi (2)','parc_exterior','Kopčevec','Grad Dugo Selo',NULL,'Ulica Bedema ljubavi 11, Kopčevec',45.80995,16.18061,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Kozari I. odvojak','parc_exterior','Mičevec','Grad Velika Gorica',NULL,'Kozari I. odvojak 20A, Mičevec',45.79358,16.05626,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Kozari I. odvojak (2)','parc_exterior','Mičevec','Grad Velika Gorica',NULL,'Kozari I. odvojak 26, Mičevec',45.79358,16.05636,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Savski gaj II.','parc_exterior','Buzin','Novi Zagreb – istok',NULL,'Savski gaj II. 2, Buzin',45.77503,15.95407,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Bachova ulica','parc_exterior','Zagreb','Zagreb',NULL,'Bachova ulica 1, Zagreb',45.79147,16.00487,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Bachova ulica (2)','parc_exterior','Zagreb','Zagreb',NULL,'Bachova ulica 1, Zagreb',45.79145,16.00488,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Antuna Barca','parc_exterior','Marinići','Viškovo',NULL,'Antuna Barca 1, Marinići',45.34143,14.41042,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Androv breg','parc_exterior','Marinići','Viškovo',NULL,'Androv breg 16, Marinići',45.35804,14.4025,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Ćićarijska','parc_exterior','Marinići','Viškovo',NULL,'Ćićarijska 15C, Marinići',45.35182,14.39592,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Oranice','parc_exterior','Jankomir','Stenjevec',NULL,'Oranice 27A, Jankomir',45.80822,15.90843,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Ulica Augusta Cilića','parc_exterior','Zagreb','Zagreb',NULL,'Ulica Augusta Cilića 12, Zagreb',45.79266,16.00949,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Ulica Augusta Cilića (2)','parc_exterior','Zagreb','Zagreb',NULL,'Ulica Augusta Cilića 11, Zagreb',45.7929,16.0094,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Ulica Augusta Cilića (3)','parc_exterior','Zagreb','Zagreb',NULL,'Ulica Augusta Cilića 11, Zagreb',45.79282,16.00975,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Zametskog korena','parc_exterior','Marinići','Viškovo',NULL,'Zametskog korena 17, Marinići',45.35164,14.39607,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis Jankomir','parc_exterior','Jankomir','Stenjevec',NULL,'Jankomir 8/1, Jankomir',45.80951,15.87719,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis IV. Kozari put','parc_exterior','Mičevec','Grad Velika Gorica',NULL,'IV. Kozari put 167, Mičevec',45.78521,16.04799,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis IV. Kozari put (2)','parc_exterior','Mičevec','Grad Velika Gorica',NULL,'IV. Kozari put 167, Mičevec',45.78523,16.04802,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Stolni tenis VII. Kozari put','parc_exterior','Mičevec','Grad Velika Gorica',NULL,'VII. Kozari put 8/1, Mičevec',45.78697,16.04929,1,true,false,NULL,NULL,ARRAY['exterior'],true,false)
) AS v(name,type,city,county,sector,address,lat,lng,tables_count,free_access,night_lighting,hours,description,tags,approved,verified)
JOIN cities c ON c.country_code='HR' AND c.name=v.city
ON CONFLICT (name,city_id) DO NOTHING;
COMMIT;
