-- HU — Hungary — 355 venues, 70 cities
-- Idempotent: safe to run multiple times. Source: OpenStreetMap via Overture Maps + GeoNames.
-- STAGED: cities active=false, expansion_status='community_review' (hidden in-app until activated — see DEPLOYMENT.md). Venues approved=true.
BEGIN;
INSERT INTO countries (code,name,active) VALUES ('HU','Hungary',true) ON CONFLICT (code) DO NOTHING;
INSERT INTO cities (name,country_code,country_name,admin_area,county,lat,lng,zoom,active,expansion_status) VALUES
  ('Alsóörs','HU','Hungary','Veszprém','Veszprém',46.99126,17.97562,12,false,'community_review'),
  ('Baj','HU','Hungary','Komárom-Esztergom','Komárom-Esztergom',47.64593,18.3641,12,false,'community_review'),
  ('Balatonalmádi','HU','Hungary','Veszprém','Veszprém',47.03526,18.02076,12,false,'community_review'),
  ('Balatonboglár','HU','Hungary','Somogy County','Somogy County',46.77525,17.64415,12,false,'community_review'),
  ('Balatonfenyves','HU','Hungary','Somogy County','Somogy County',46.71542,17.49223,12,false,'community_review'),
  ('Balatonfüred','HU','Hungary','Veszprém','Veszprém',46.96188,17.87187,12,false,'community_review'),
  ('Balatonvilágos','HU','Hungary','Somogy County','Somogy County',46.96268,18.16043,12,false,'community_review'),
  ('Bátaszék','HU','Hungary','Tolna County','Tolna County',46.19373,18.72307,12,false,'community_review'),
  ('Berettyóújfalu','HU','Hungary','Hajdú-Bihar','Berettyóújfalui Járás',47.22362,21.53656,12,false,'community_review'),
  ('Biatorbágy','HU','Hungary','Pest County','Pest County',47.4706,18.81892,12,false,'community_review'),
  ('Budakalász','HU','Hungary','Pest County','Pest County',47.61667,19.05,12,false,'community_review'),
  ('Budakeszi','HU','Hungary','Pest County','Pest County',47.51083,18.92717,12,false,'community_review'),
  ('Budaörs','HU','Hungary','Pest County','Pest County',47.46181,18.95845,12,false,'community_review'),
  ('Budapest','HU','Hungary','Budapest','Budapest',47.49835,19.04045,12,false,'community_review'),
  ('Cegléd','HU','Hungary','Pest County','Pest County',47.17266,19.79952,12,false,'community_review'),
  ('Ceglédbercel','HU','Hungary','Pest County','Pest County',47.2237,19.66828,12,false,'community_review'),
  ('Celldömölk','HU','Hungary','Vas County','Vas County',47.25713,17.15027,12,false,'community_review'),
  ('Csömör','HU','Hungary','Pest County','Pest County',47.55,19.23333,12,false,'community_review'),
  ('Dávod','HU','Hungary','Bács-Kiskun','Bács-Kiskun',45.995,18.91722,12,false,'community_review'),
  ('Debrecen','HU','Hungary','Hajdú-Bihar','Hajdú-Bihar',47.53167,21.62444,12,false,'community_review'),
  ('Diósd','HU','Hungary','Pest County','Pest County',47.4095,18.94898,12,false,'community_review'),
  ('Domaszék','HU','Hungary','Csongrád','Csongrád',46.24917,20.01111,12,false,'community_review'),
  ('Dombóvár','HU','Hungary','Tolna County','Tolna County',46.37657,18.13696,12,false,'community_review'),
  ('Dunaharaszti','HU','Hungary','Pest County','Pest County',47.3545,19.09822,12,false,'community_review'),
  ('Dunakeszi','HU','Hungary','Pest County','Pest County',47.63641,19.13864,12,false,'community_review'),
  ('Ecser','HU','Hungary','Pest County','Pest County',47.44389,19.3245,12,false,'community_review'),
  ('Esztergom','HU','Hungary','Komárom-Esztergom','Komárom-Esztergom',47.7928,18.74148,12,false,'community_review'),
  ('Fót','HU','Hungary','Pest County','Pest County',47.6177,19.1887,12,false,'community_review'),
  ('Gödöllő','HU','Hungary','Pest County','Pest County',47.59657,19.35515,12,false,'community_review'),
  ('Gönc','HU','Hungary','Borsod-Abaúj-Zemplén','Borsod-Abaúj-Zemplén',48.46667,21.28333,12,false,'community_review'),
  ('Gyál','HU','Hungary','Pest County','Pest County',47.38449,19.2214,12,false,'community_review'),
  ('Gyenesdiás','HU','Hungary','Zala County','Zala County',46.77058,17.2866,12,false,'community_review'),
  ('Győr','HU','Hungary','Győr-Moson-Sopron','Győr-Moson-Sopron',47.68333,17.63512,12,false,'community_review'),
  ('Győrújbarát','HU','Hungary','Győr-Moson-Sopron','Győr-Moson-Sopron',47.60643,17.64875,12,false,'community_review'),
  ('Hajdúböszörmény','HU','Hungary','Hajdú-Bihar','Hajdú-Bihar',47.66667,21.51667,12,false,'community_review'),
  ('Kaposvár','HU','Hungary','Somogy County','Somogy County',46.36667,17.8,12,false,'community_review'),
  ('Kazincbarcika','HU','Hungary','Borsod-Abaúj-Zemplén','Borsod-Abaúj-Zemplén',48.25,20.63333,12,false,'community_review'),
  ('Kecskemét','HU','Hungary','Bács-Kiskun','Bács-Kiskun',46.90618,19.69128,12,false,'community_review'),
  ('Kótaj','HU','Hungary','Szabolcs-Szatmár-Bereg','Nyíregyházi Járás',48.05,21.71667,12,false,'community_review'),
  ('Lakihegy','HU','Hungary','Pest County','Pest County',47.37765,19.01034,12,false,'community_review'),
  ('Miskolc','HU','Hungary','Borsod-Abaúj-Zemplén','Borsod-Abaúj-Zemplén',48.10327,20.77806,12,false,'community_review'),
  ('Nagykanizsa','HU','Hungary','Zala County','Zala County',46.45347,16.99104,12,false,'community_review'),
  ('Nagytarcsa','HU','Hungary','Pest County','Pest County',47.53128,19.28343,12,false,'community_review'),
  ('Ózd','HU','Hungary','Borsod-Abaúj-Zemplén','Borsod-Abaúj-Zemplén',48.21667,20.3,12,false,'community_review'),
  ('Pázmánd','HU','Hungary','Fejér','Fejér',47.28755,18.65356,12,false,'community_review'),
  ('Pécs','HU','Hungary','Baranya','Baranya',46.07617,18.22814,12,false,'community_review'),
  ('Pellérd','HU','Hungary','Baranya','Baranya',46.03438,18.15403,12,false,'community_review'),
  ('Pilismarót','HU','Hungary','Komárom-Esztergom','Komárom-Esztergom',47.78464,18.87539,12,false,'community_review'),
  ('Sajóörös','HU','Hungary','Borsod-Abaúj-Zemplén','Borsod-Abaúj-Zemplén',47.95,21.03333,12,false,'community_review'),
  ('Salgótarján','HU','Hungary','Nógrád','Nógrád',48.09872,19.80303,12,false,'community_review'),
  ('Sióagárd','HU','Hungary','Tolna County','Tolna County',46.39272,18.65336,12,false,'community_review'),
  ('Solymár','HU','Hungary','Pest County','Pest County',47.59246,18.93212,12,false,'community_review'),
  ('Somogyvár','HU','Hungary','Somogy County','Somogy County',46.5814,17.66289,12,false,'community_review'),
  ('Sopron','HU','Hungary','Győr-Moson-Sopron','Győr-Moson-Sopron',47.68501,16.59049,12,false,'community_review'),
  ('Százhalombatta','HU','Hungary','Pest County','Pest County',47.32949,18.93878,12,false,'community_review'),
  ('Szeged','HU','Hungary','Csongrád','Csongrád',46.253,20.14824,12,false,'community_review'),
  ('Székesfehérvár','HU','Hungary','Fejér','Fejér',47.18995,18.41034,12,false,'community_review'),
  ('Szigetújfalu','HU','Hungary','Pest County','Pest County',47.23417,18.92746,12,false,'community_review'),
  ('Szombathely','HU','Hungary','Vas County','Vas County',47.23088,16.62155,12,false,'community_review'),
  ('Törökbálint','HU','Hungary','Pest County','Pest County',47.42931,18.91356,12,false,'community_review'),
  ('Üllő','HU','Hungary','Pest County','Pest County',47.38771,19.35533,12,false,'community_review'),
  ('Üröm','HU','Hungary','Pest County','Pest County',47.59674,19.01583,12,false,'community_review'),
  ('Vác','HU','Hungary','Pest County','Pest County',47.77591,19.13612,12,false,'community_review'),
  ('Vál','HU','Hungary','Fejér','Fejér',47.36264,18.67931,12,false,'community_review'),
  ('Verőce','HU','Hungary','Pest County','Pest County',47.82468,19.03484,12,false,'community_review'),
  ('Vonyarcvashegy','HU','Hungary','Zala County','Zala County',46.75742,17.31172,12,false,'community_review'),
  ('Zalaegerszeg','HU','Hungary','Zala County','Zala County',46.83695,16.84401,12,false,'community_review'),
  ('Zalalövő','HU','Hungary','Zala County','Zala County',46.84802,16.5875,12,false,'community_review'),
  ('Zánka','HU','Hungary','Veszprém','Veszprém',46.87146,17.68473,12,false,'community_review'),
  ('Zsámbék','HU','Hungary','Pest County','Pest County',47.54814,18.72011,12,false,'community_review')
ON CONFLICT (country_code,name) DO NOTHING;
INSERT INTO venues (name,type,city,city_id,county,sector,address,lat,lng,tables_count,free_access,night_lighting,hours,description,tags,approved,verified,submitted_by)
SELECT v.name,v.type,v.city,c.id,v.county::text,v.sector::text,v.address,v.lat::double precision,v.lng::double precision,v.tables_count::int,v.free_access::boolean,v.night_lighting::boolean,v.hours::text,v.description::text,v.tags::text[],v.approved::boolean,v.verified::boolean,NULL
FROM (VALUES
  ('Asztalitenisz Mátyásdomb tér','parc_exterior','Csömör','Pest County',NULL,'Mátyásdomb tér, Csömör',47.51956,19.18228,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Cica park','parc_exterior','Budapest','Budapest',NULL,'Cica park, Budapest',47.48595,19.06584,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Centrum','parc_exterior','Csömör','Pest County',NULL,'World Mall, Csömör',47.547,19.14545,1,true,false,NULL,'Magyar - Kínai Asztalitenisz Klub',ARRAY['exterior'],true,false),
  ('Asztalitenisz Hableány játszótér','parc_exterior','Budaörs','Pest County',NULL,'Hableány játszótér, Budaörs',47.44399,19.02692,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Hunyadi tér','parc_exterior','Budapest','Budapest',NULL,'Hunyadi tér, Budapest',47.50623,19.06714,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz II. János Pál pápa tér','parc_exterior','Budapest','Budapest',NULL,'II. János Pál pápa tér, Budapest',47.49675,19.07953,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Silvanus játszótér','parc_exterior','Üröm','Pest County',NULL,'Silvanus játszótér, Üröm',47.56958,19.05644,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Szent István park','parc_exterior','Budapest','Budapest',NULL,'Szent István park, Budapest',47.51818,19.05221,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Óhegy park','parc_exterior','Budapest','Budapest',NULL,'Óhegy park, Budapest',47.48133,19.1463,1,true,false,'24/7',NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Meixner Ildikó tér','parc_exterior','Budapest','Budapest',NULL,'Meixner Ildikó tér, Budapest',47.54119,19.1141,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Heltai tér','parc_exterior','Nagytarcsa','Pest County',NULL,'Heltai tér, Nagytarcsa',47.49037,19.24993,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Dávodi Gyógy- és Strandfürdő','parc_exterior','Dávod','Bács-Kiskun',NULL,'Dávodi Gyógy- és Strandfürdő, Dávod',46.005,18.89473,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Játszótér','parc_exterior','Budakalász','Pest County',NULL,'Játszótér, Budakalász',47.59982,19.05168,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Budai Pingpong Klub','parc_exterior','Budapest','Budapest',NULL,'Budai Pingpong Klub, Budapest',47.51486,19.01063,1,true,false,'Mo-Fr 08:00-20:00; Sa-Su 14:00-18:00',NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Újváros park játszótér','parc_exterior','Csömör','Pest County',NULL,'Újváros park játszótér, Csömör',47.51276,19.14443,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Solymár, Kerekhegy (157)','parc_exterior','Solymár','Pest County',NULL,'Solymár, Kerekhegy (157), Solymár',47.58153,18.92653,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz ATSK Szeged','parc_exterior','Szeged','Csongrád',NULL,'ATSK Szeged, Szeged',46.26857,20.16712,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Újvidék Tér','parc_exterior','Budapest','Budapest',NULL,'Újvidék Tér, Budapest',47.51171,19.10756,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Burger Bár','parc_exterior','Csömör','Pest County',NULL,'Kerék Korcsma, Csömör',47.55152,19.22685,1,true,false,'Tu-Su 11:00-20:00','Jánosi Anett',ARRAY['exterior'],true,false),
  ('Asztalitenisz Zakatoló játszótér','parc_exterior','Budapest','Budapest',NULL,'Zakatoló játszótér, Budapest',47.47159,19.0389,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Katonadomb','parc_exterior','Dunakeszi','Pest County',NULL,'Katonadomb, Dunakeszi',47.65052,19.12262,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Brázay kastélypark','parc_exterior','Pellérd','Baranya',NULL,'Brázay kastélypark, Pellérd',46.03405,18.15933,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Szabadstrand','parc_exterior','Balatonfenyves','Somogy County',NULL,'Szabadstrand, Balatonfenyves',46.71691,17.48697,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Karolina Óvoda, Általános Iskola, Gimnázium, Alapfokú Művészeti Iskola és Kollégium','parc_exterior','Szeged','Csongrád',NULL,'Karolina Óvoda, Általános Iskola, Gimnázium, Alapfokú Művészeti Iskola és Kollégium, Szeged',46.24234,20.13907,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Karolina Óvoda, Általános Iskola, Gimnázium, Alapfokú Művészeti Iskola és Kollégium (2)','parc_exterior','Szeged','Csongrád',NULL,'Karolina Óvoda, Általános Iskola, Gimnázium, Alapfokú Művészeti Iskola és Kollégium, Szeged',46.24245,20.13916,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Kertvárosi Olimpikonok Parkja','parc_exterior','Csömör','Pest County',NULL,'Kertvárosi Olimpikonok Parkja, Csömör',47.51454,19.16814,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Kertvárosi Olimpikonok Parkja (2)','parc_exterior','Csömör','Pest County',NULL,'Kertvárosi Olimpikonok Parkja, Csömör',47.51457,19.16825,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Vérhalom tér','parc_exterior','Budapest','Budapest',NULL,'Vérhalom tér, Budapest',47.5214,19.02415,1,true,false,'24/7',NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Cziffra György park','parc_exterior','Budapest','Budapest',NULL,'Cziffra György park, Budapest',47.54783,19.07999,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Óhegy park (2)','parc_exterior','Budapest','Budapest',NULL,'Óhegy park, Budapest',47.48031,19.14343,1,true,false,'24/7',NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Városmajor','parc_exterior','Budapest','Budapest',NULL,'Városmajor, Budapest',47.50763,19.01844,1,true,false,'24/7',NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Mészkő park','parc_exterior','Üröm','Pest County',NULL,'Mészkő park, Üröm',47.58048,19.03199,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Boldog Sándor István park','parc_exterior','Budapest','Budapest',NULL,'Boldog Sándor István park, Budapest',47.54522,19.03797,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Gyarmati Dezső park','parc_exterior','Budapest','Budapest',NULL,'Gyarmati Dezső park, Budapest',47.54284,19.04571,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Ajtósi park','parc_exterior','Pécs','Baranya',NULL,'Ajtósi park, Pécs',46.06701,18.20564,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Levendula játszótér','parc_exterior','Budapest','Budapest',NULL,'Levendula játszótér, Budapest',47.465,19.03778,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Levendula játszótér (2)','parc_exterior','Budapest','Budapest',NULL,'Levendula játszótér, Budapest',47.46495,19.03777,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Holdudvar park','parc_exterior','Budapest','Budapest',NULL,'Holdudvar park, Budapest',47.54534,19.03091,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Hidasi Pingpongasztal','parc_exterior','Budapest','Budapest',NULL,'Holdudvar park, Budapest',47.54534,19.03093,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Csicseri-dombos játszótér','parc_exterior','Budapest','Budapest',NULL,'Csicseri-dombos játszótér, Budapest',47.51258,19.14173,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Sóstói szabadidőpark','parc_exterior','Kótaj','Nyíregyházi Járás',NULL,'Sóstói szabadidőpark, Kótaj',48.00468,21.73015,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Sóstói szabadidőpark (2)','parc_exterior','Kótaj','Nyíregyházi Járás',NULL,'Sóstói szabadidőpark, Kótaj',48.0048,21.73007,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Sziksósfürdő Naturista Strand és Kemping','parc_exterior','Domaszék','Csongrád',NULL,'Sziksósfürdő Naturista Strand és Kemping, Domaszék',46.26779,20.01585,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Sport tér','parc_exterior','Üllő','Pest County',NULL,'Sport tér, Üllő',47.39145,19.35177,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Cigri','parc_exterior','Üllő','Pest County',NULL,'Cigri, Üllő',47.38372,19.35369,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Kerékpáros kultúrkert, pihenőhely és szabadidő park','parc_exterior','Vál','Fejér',NULL,'Kerékpáros kultúrkert, pihenőhely és szabadidő park, Vál',47.35968,18.67964,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Széchenyi park','parc_exterior','Törökbálint','Pest County',NULL,'Széchenyi park, Törökbálint',47.43988,18.90089,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Tóth László park','parc_exterior','Százhalombatta','Pest County',NULL,'Tóth László park, Százhalombatta',47.31307,18.90788,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Hermina Sports and Leisure Park','parc_exterior','Csömör','Pest County',NULL,'Hermina Sports and Leisure Park, Csömör',47.52871,19.19348,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Turozsaki Uti Szabadidopark es Setany','parc_exterior','Székesfehérvár','Fejér',NULL,'Turozsaki Uti Szabadidopark es Setany, Székesfehérvár',47.20635,18.44281,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Elmű Sporttelep','parc_exterior','Budapest','Budapest',NULL,'Elmű Sporttelep, Budapest',47.53201,19.05906,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz JamSport','parc_exterior','Budapest','Budapest',NULL,'JamSport, Budapest',47.53337,19.06122,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Újlak Utca Lakópark','parc_exterior','Nagytarcsa','Pest County',NULL,'Újlak Utca Lakópark, Nagytarcsa',47.47938,19.24298,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Avastetői Sportpálya','parc_exterior','Miskolc','Borsod-Abaúj-Zemplén',NULL,'Avastetői Sportpálya, Miskolc',48.09601,20.77049,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Avasi Ifjúsági Park','parc_exterior','Miskolc','Borsod-Abaúj-Zemplén',NULL,'Avasi Ifjúsági Park, Miskolc',48.09733,20.77068,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Avasi Ifjúsági Park (2)','parc_exterior','Miskolc','Borsod-Abaúj-Zemplén',NULL,'Avasi Ifjúsági Park, Miskolc',48.09739,20.77081,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Avasi Ifjúsági Park (3)','parc_exterior','Miskolc','Borsod-Abaúj-Zemplén',NULL,'Avasi Ifjúsági Park, Miskolc',48.09744,20.77094,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Zichy Péter utca (222, 922)','parc_exterior','Budakeszi','Pest County',NULL,'Zichy Péter utca (222, 922), Budakeszi',47.51396,18.92173,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Asztalitenisz','parc_exterior','Csömör','Pest County',NULL,'Asztalitenisz, Csömör',47.54587,19.14422,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Asztalitenisz (2)','parc_exterior','Csömör','Pest County',NULL,'Asztalitenisz, Csömör',47.54581,19.14414,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz FlightZone Palota','parc_exterior','Csömör','Pest County',NULL,'FlightZone Palota, Csömör',47.54512,19.14559,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz FlightZone Palota (2)','parc_exterior','Csömör','Pest County',NULL,'FlightZone Palota, Csömör',47.54507,19.14569,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz FlightZone Palota (3)','parc_exterior','Csömör','Pest County',NULL,'FlightZone Palota, Csömör',47.54504,19.14573,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Marianna Apartman Telkibánya','parc_exterior','Gönc','Borsod-Abaúj-Zemplén',NULL,'Marianna Apartman Telkibánya, Gönc',48.48518,21.36055,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Pécs','parc_exterior','Pécs','Baranya',NULL,'Pécs, Pécs',46.07709,18.2291,1,false,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Szent Adalbert tér','parc_exterior','Budapest','Budapest',NULL,'Szent Adalbert tér, Budapest',47.47396,19.01114,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Szabó Ervin Tér','parc_exterior','Pécs','Baranya',NULL,'Szabó Ervin Tér, Pécs',46.03611,18.2239,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Szabó Ervin Tér (2)','parc_exterior','Pécs','Baranya',NULL,'Szabó Ervin Tér, Pécs',46.03597,18.22528,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Mecsek Áruház parkoló','parc_exterior','Pécs','Baranya',NULL,'Mecsek Áruház parkoló, Pécs',46.06447,18.19704,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Angster József utca (36, 37, 932) (2)','parc_exterior','Pécs','Baranya',NULL,'Angster József utca (36, 37, 932), Pécs',46.08191,18.21362,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Árnyas playground','parc_exterior','Budapest','Budapest',NULL,'Árnyas playground, Budapest',47.46747,19.03548,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Lábtenisz asztal','parc_exterior','Pilismarót','Komárom-Esztergom',NULL,'Pilismaróti Játszotér, Pilismarót',47.78358,18.88145,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Gidófalvy Játszótér','parc_exterior','Budapest','Budapest',NULL,'Gidófalvy Játszótér, Budapest',47.52669,19.07167,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Honvéd Kézilabdacsarnok','parc_exterior','Budapest','Budapest',NULL,'Honvéd Kézilabdacsarnok, Budapest',47.52625,19.07041,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz EZ Opera Parkoló','parc_exterior','Budapest','Budapest',NULL,'EZ Opera Parkoló, Budapest',47.50341,19.05591,1,true,false,'10:00-22:00',NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Újváros Park Kutya Játszótér','parc_exterior','Budapest','Budapest',NULL,'Újváros Park Kutya Játszótér, Budapest',47.51467,19.14243,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Újváros Park Kutya Játszótér','parc_exterior','Csömör','Pest County',NULL,'Újváros Park Kutya Játszótér, Csömör',47.51467,19.14248,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Máltai Játszótér és Játszóház','parc_exterior','Szeged','Csongrád',NULL,'Máltai Játszótér és Játszóház, Szeged',46.2658,20.16466,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Máltai Játszótér és Játszóház (2)','parc_exterior','Szeged','Csongrád',NULL,'Máltai Játszótér és Játszóház, Szeged',46.2658,20.16459,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Sötétvölgy','parc_exterior','Sióagárd','Tolna County',NULL,'Sötétvölgy, Sióagárd',46.33907,18.62138,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Sötétvölgy (2)','parc_exterior','Sióagárd','Tolna County',NULL,'Sötétvölgy, Sióagárd',46.33909,18.62141,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz SPX Trade Korlátolt Felelősségű Társaság','parc_exterior','Budapest','Budapest',NULL,'SPX Trade Korlátolt Felelősségű Társaság, Budapest',47.5293,19.06907,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Brassó úti játszótér','parc_exterior','Budapest','Budapest',NULL,'Brassó úti játszótér, Budapest',47.48044,19.00623,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Kecskeméti Spartacus Sportkör','parc_exterior','Kecskemét','Bács-Kiskun',NULL,'Kecskemét',46.91245,19.676,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Budapesti Német Általános Iskola és Gimnázium','parc_exterior','Budakeszi','Pest County',NULL,'Budapesti Német Általános Iskola és Gimnázium, Budakeszi',47.5102,18.98367,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Budapesti Német Általános Iskola és Gimnázium (2)','parc_exterior','Budakeszi','Pest County',NULL,'Budapesti Német Általános Iskola és Gimnázium, Budakeszi',47.51026,18.9837,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Katicabogár játszótér','parc_exterior','Budapest','Budapest',NULL,'Katicabogár játszótér, Budapest',47.46258,19.01783,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Katicabogár játszótér (2)','parc_exterior','Budapest','Budapest',NULL,'Katicabogár játszótér, Budapest',47.46258,19.01776,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Rönkvár','parc_exterior','Gödöllő','Pest County',NULL,'Rönkvár, Gödöllő',47.60286,19.35065,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Budapest Garden','parc_exterior','Budapest','Budapest',NULL,'Budapest Garden, Budapest',47.53145,19.0431,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Budapest Garden (2)','parc_exterior','Budapest','Budapest',NULL,'Budapest Garden, Budapest',47.53147,19.04298,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Bethlen Gábor Általános Iskola Montessori Tagiskolája','parc_exterior','Budapest','Budapest',NULL,'Bethlen Gábor Általános Iskola Montessori Tagiskolája, Budapest',47.46757,19.02726,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Bethlen Gábor Általános Iskola Montessori Tagiskolája (2)','parc_exterior','Budapest','Budapest',NULL,'Bethlen Gábor Általános Iskola Montessori Tagiskolája, Budapest',47.46759,19.0271,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Szentivánéj park','parc_exterior','Budaörs','Pest County',NULL,'Szentivánéj park, Budaörs',47.4732,18.9947,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Kicsik játszótere','parc_exterior','Budapest','Budapest',NULL,'Kicsik játszótere, Budapest',47.45612,19.12563,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Kerekerdő park','parc_exterior','Budapest','Budapest',NULL,'Kerekerdő park, Budapest',47.47996,19.07994,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Platán Strand','parc_exterior','Balatonboglár','Somogy County',NULL,'Platán Strand, Balatonboglár',46.78157,17.6541,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Hankovszky Zsigmond liget','parc_exterior','Kecskemét','Bács-Kiskun',NULL,'Hankovszky Zsigmond liget, Kecskemét',46.92026,19.70305,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Bezerédj park','parc_exterior','Győrújbarát','Győr-Moson-Sopron',NULL,'Bezerédj park, Győrújbarát',47.62469,17.6061,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Rákóczi Kert Civil és Közösségi Ház','parc_exterior','Lakihegy','Pest County',NULL,'Rákóczi Kert Civil és Közösségi Ház, Lakihegy',47.42391,19.07991,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Rákóczi Kert Civil és Közösségi Ház (2)','parc_exterior','Lakihegy','Pest County',NULL,'Rákóczi Kert Civil és Közösségi Ház, Lakihegy',47.42391,19.07996,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Manófalva játszótér','parc_exterior','Budapest','Budapest',NULL,'Manófalva játszótér, Budapest',47.4639,19.03827,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Csörsz park','parc_exterior','Budapest','Budapest',NULL,'Csörsz park, Budapest',47.48892,19.0295,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Csörsz park (2)','parc_exterior','Budapest','Budapest',NULL,'Csörsz park, Budapest',47.48889,19.02944,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Tejút park','parc_exterior','Lakihegy','Pest County',NULL,'Tejút park, Lakihegy',47.40968,19.0564,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Vasvár Úti Általános Iskola','parc_exterior','Ózd','Borsod-Abaúj-Zemplén',NULL,'Vasvár Úti Általános Iskola, Ózd',48.21811,20.27986,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Vasvár Úti Általános Iskola (2)','parc_exterior','Ózd','Borsod-Abaúj-Zemplén',NULL,'Vasvár Úti Általános Iskola, Ózd',48.21822,20.28038,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Építők parkja','parc_exterior','Baj','Komárom-Esztergom',NULL,'Építők parkja, Baj',47.64163,18.34006,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Építők parkja (2)','parc_exterior','Baj','Komárom-Esztergom',NULL,'Építők parkja, Baj',47.64168,18.34007,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Rekortán futókör 555 m (2)','parc_exterior','Debrecen','Hajdú-Bihar',NULL,'Rekortán futókör 555 m, Debrecen',47.53756,21.65212,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Városliget (4)','parc_exterior','Budapest','Budapest',NULL,'Városliget, Budapest',47.51457,19.0855,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Városliget (5)','parc_exterior','Budapest','Budapest',NULL,'Városliget, Budapest',47.51465,19.08566,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Labirintus játszótér','parc_exterior','Budapest','Budapest',NULL,'Labirintus játszótér, Budapest',47.46421,19.04441,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Labirintus játszótér (2)','parc_exterior','Budapest','Budapest',NULL,'Labirintus játszótér, Budapest',47.46424,19.04442,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Mikkamakka játszótér','parc_exterior','Budapest','Budapest',NULL,'Mikkamakka játszótér, Budapest',47.45239,19.03766,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Kresz park','parc_exterior','Cegléd','Pest County',NULL,'Kresz park, Cegléd',47.16104,19.79162,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Baranyai III. udvar','parc_exterior','Budapest','Budapest',NULL,'Baranyai III. udvar, Budapest',47.47232,19.04654,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Nagykikinda játszótér','parc_exterior','Budapest','Budapest',NULL,'Nagykikinda játszótér, Budapest',47.46142,19.0405,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Petzvál Park','parc_exterior','Budapest','Budapest',NULL,'Petzvál Park, Budapest',47.46837,19.04355,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Harangos játszótér','parc_exterior','Budapest','Budapest',NULL,'Harangos játszótér, Budapest',47.47356,19.04446,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Mazsola játszótér','parc_exterior','Budapest','Budapest',NULL,'Mazsola játszótér, Budapest',47.4589,19.03976,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Mazsola játszótér (2)','parc_exterior','Budapest','Budapest',NULL,'Mazsola játszótér, Budapest',47.45888,19.03982,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Kacagó játszótér','parc_exterior','Budapest','Budapest',NULL,'Kacagó játszótér, Budapest',47.46309,19.02743,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Kacagó játszótér (2)','parc_exterior','Budapest','Budapest',NULL,'Kacagó játszótér, Budapest',47.46311,19.02735,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Margaréta Játszótér','parc_exterior','Budapest','Budapest',NULL,'Margaréta Játszótér, Budapest',47.4929,19.01594,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Építők parkja (3)','parc_exterior','Baj','Komárom-Esztergom',NULL,'Építők parkja, Baj',47.64164,18.34006,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Építők parkja (4)','parc_exterior','Baj','Komárom-Esztergom',NULL,'Építők parkja, Baj',47.64168,18.34007,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Vidám Vidék Játszótér','parc_exterior','Budapest','Budapest',NULL,'Vidám Vidék Játszótér, Budapest',47.45765,19.03763,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Zsombóka játszótér','parc_exterior','Budapest','Budapest',NULL,'Zsombóka játszótér, Budapest',47.45481,19.03879,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Zsombóka játszótér (2)','parc_exterior','Budapest','Budapest',NULL,'Zsombóka játszótér, Budapest',47.45485,19.0388,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Bulgárkert','parc_exterior','Csömör','Pest County',NULL,'Bulgárkert, Csömör',47.54628,19.23402,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Kölyökvár játszótér','parc_exterior','Budapest','Budapest',NULL,'Kölyökvár játszótér, Budapest',47.45454,19.03191,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Kölyökvár játszótér (2)','parc_exterior','Budapest','Budapest',NULL,'Kölyökvár játszótér, Budapest',47.45461,19.03191,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Somogyvári Módszertani Központ','parc_exterior','Somogyvár','Somogy County',NULL,'Somogyvári Módszertani Központ, Somogyvár',46.57967,17.64571,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Óbudai-sziget','parc_exterior','Budapest','Budapest',NULL,'Óbudai-sziget, Budapest',47.54852,19.05498,1,true,false,'24/7',NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Bem tér','parc_exterior','Győr','Győr-Moson-Sopron',NULL,'Bem tér, Győr',47.67792,17.63506,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Köszörűs téri játszótér','parc_exterior','Ecser','Pest County',NULL,'Köszörűs téri játszótér, Ecser',47.46974,19.30145,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Wesselényi strand','parc_exterior','Balatonalmádi','Veszprém',NULL,'Wesselényi strand, Balatonalmádi',47.02558,18.01243,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Merse Leader kultúrpark','parc_exterior','Alsóörs','Veszprém',NULL,'Merse Leader kultúrpark, Alsóörs',46.99195,17.97688,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Bihar Termálliget Strand- és Termálfürdő','parc_exterior','Berettyóújfalu','Berettyóújfalui Járás',NULL,'Bihar Termálliget Strand- és Termálfürdő, Berettyóújfalu',47.22196,21.53833,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Bihar Termálliget Strand- és Termálfürdő (2)','parc_exterior','Berettyóújfalu','Berettyóújfalui Járás',NULL,'Bihar Termálliget Strand- és Termálfürdő, Berettyóújfalu',47.2219,21.53837,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz SZTE JGYPK Hattyas sori Sportkomplexum','parc_exterior','Szeged','Csongrád',NULL,'SZTE JGYPK Hattyas sori Sportkomplexum, Szeged',46.23572,20.14045,1,true,false,NULL,'SZTE Egyetemi Sportközpont',ARRAY['exterior'],true,false),
  ('Asztalitenisz Táncsics Mihály park','parc_exterior','Budakalász','Pest County',NULL,'Táncsics Mihály park, Budakalász',47.60137,19.0545,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Tétény-rét Családi Park','parc_exterior','Diósd','Pest County',NULL,'Tétény-rét Családi Park, Diósd',47.39683,18.9777,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Tétény-rét Családi Park (2)','parc_exterior','Diósd','Pest County',NULL,'Tétény-rét Családi Park, Diósd',47.39689,18.9776,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Sziget strand','parc_exterior','Balatonboglár','Somogy County',NULL,'Sziget strand, Balatonboglár',46.7788,17.64532,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Malom liget','parc_exterior','Győr','Győr-Moson-Sopron',NULL,'Malom liget, Győr',47.67968,17.64446,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Pázmándi mezítlábas park','parc_exterior','Pázmánd','Fejér',NULL,'Pázmándi mezítlábas park, Pázmánd',47.28384,18.6539,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Újváros park játszótér (2)','parc_exterior','Csömör','Pest County',NULL,'Újváros park játszótér, Csömör',47.51315,19.14409,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Adyliget játszótér','parc_exterior','Budakeszi','Pest County',NULL,'Adyliget játszótér, Budakeszi',47.54722,18.93938,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz FirstPhone Bikás Park','parc_exterior','Budapest','Budapest',NULL,'FirstPhone Bikás Park, Budapest',47.46491,19.03498,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz FirstPhone Bikás Park (2)','parc_exterior','Budapest','Budapest',NULL,'FirstPhone Bikás Park, Budapest',47.46494,19.03498,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Asztalitenisz (3)','parc_exterior','Csömör','Pest County',NULL,'Asztalitenisz, Csömör',47.54584,19.14418,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Ceglédfürdői Diáktábor - Erdei Iskola, Osztálykirándulás','parc_exterior','Ceglédbercel','Pest County',NULL,'Ceglédfürdői Diáktábor - Erdei Iskola, Osztálykirándulás, Ceglédbercel',47.19781,19.73346,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Játék Utca','parc_exterior','Lakihegy','Pest County',NULL,'Játék Utca, Lakihegy',47.43049,19.03958,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Szegedi Biliárd SE','parc_exterior','Szeged','Csongrád',NULL,'Szegedi Biliárd SE, Szeged',46.26878,20.16705,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz ATSK Szeged (2)','parc_exterior','Szeged','Csongrád',NULL,'ATSK Szeged, Szeged',46.26874,20.16706,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz ATSK Szeged (3)','parc_exterior','Szeged','Csongrád',NULL,'ATSK Szeged, Szeged',46.2687,20.16708,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz ATSK Szeged (4)','parc_exterior','Szeged','Csongrád',NULL,'ATSK Szeged, Szeged',46.26866,20.16709,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz ATSK Szeged (5)','parc_exterior','Szeged','Csongrád',NULL,'ATSK Szeged, Szeged',46.26862,20.16711,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Kutyafuttató','parc_exterior','Salgótarján','Nógrád',NULL,'Kutyafuttató, Salgótarján',48.12908,19.8123,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Kutyafuttató (2)','parc_exterior','Salgótarján','Nógrád',NULL,'Kutyafuttató, Salgótarján',48.12905,19.81239,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Pókhálós játszótér','parc_exterior','Budapest','Budapest',NULL,'Pókhálós játszótér, Budapest',47.4458,19.03762,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Garden Esztergom','parc_exterior','Esztergom','Komárom-Esztergom',NULL,'Garden Esztergom, Esztergom',47.79321,18.73787,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Jakab József Utcai Kis játszótér','parc_exterior','Budapest','Budapest',NULL,'Jakab József Utcai Kis játszótér, Budapest',47.53617,19.06527,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Menyecske Aréna','parc_exterior','Budaörs','Pest County',NULL,'Menyecske Aréna, Budaörs',47.46162,19.01419,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Menyecske Aréna (2)','parc_exterior','Budaörs','Pest County',NULL,'Menyecske Aréna, Budaörs',47.46167,19.01419,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Csúszkás játszótér','parc_exterior','Budapest','Budapest',NULL,'Csúszkás játszótér, Budapest',47.46561,19.02786,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Baráti Bőrlabda FC','parc_exterior','Budapest','Budapest',NULL,'Baráti Bőrlabda FC, Budapest',47.45972,19.0403,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Baráti Bőrlabda FC (2)','parc_exterior','Budapest','Budapest',NULL,'Baráti Bőrlabda FC, Budapest',47.45972,19.04019,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Nyírfaliget playground','parc_exterior','Budapest','Budapest',NULL,'Nyírfaliget playground, Budapest',47.46049,19.0389,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz BikasTenisz.hu klub','parc_exterior','Budapest','Budapest',NULL,'BikasTenisz.hu klub, Budapest',47.46749,19.03103,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Konténerpest.hu','parc_exterior','Budapest','Budapest',NULL,'Konténerpest.hu, Budapest',47.47252,19.05084,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Kontyfa Utcai Játszótér','parc_exterior','Csömör','Pest County',NULL,'Kontyfa Utcai Játszótér, Csömör',47.54878,19.1392,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Vidám vidék játszótér','parc_exterior','Budapest','Budapest',NULL,'Vidám vidék játszótér, Budapest',47.45757,19.0374,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Zsombóka playground','parc_exterior','Budapest','Budapest',NULL,'Zsombóka playground, Budapest',47.45496,19.03785,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Zsombóka playground (2)','parc_exterior','Budapest','Budapest',NULL,'Zsombóka playground, Budapest',47.45497,19.03779,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Budaixi.se.asztalitenisz','parc_exterior','Budapest','Budapest',NULL,'Budaixi.se.asztalitenisz, Budapest',47.44943,19.03616,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Orsolya Vendégház','parc_exterior','Vonyarcvashegy','Zala County',NULL,'Orsolya Vendégház, Vonyarcvashegy',46.75478,17.35502,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Orsolya Vendégház (2)','parc_exterior','Vonyarcvashegy','Zala County',NULL,'Orsolya Vendégház, Vonyarcvashegy',46.75478,17.35498,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Derkovits Tér','parc_exterior','Ecser','Pest County',NULL,'Derkovits Tér, Ecser',47.47496,19.28343,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Ifjúsági Park','parc_exterior','Ózd','Borsod-Abaúj-Zemplén',NULL,'Ifjúsági Park, Ózd',48.22466,20.26691,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Ifjúsági Park (2)','parc_exterior','Ózd','Borsod-Abaúj-Zemplén',NULL,'Ifjúsági Park, Ózd',48.22448,20.26688,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Móra Ferenc Általános Iskola','parc_exterior','Csömör','Pest County',NULL,'Móra Ferenc Általános Iskola, Csömör',47.51277,19.14362,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Móra Ferenc Általános Iskola (2)','parc_exterior','Csömör','Pest County',NULL,'Móra Ferenc Általános Iskola, Csömör',47.51282,19.14361,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Budatava Strand','parc_exterior','Balatonalmádi','Veszprém',NULL,'Budatava Strand, Balatonalmádi',47.03105,18.02807,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Kiserdő','parc_exterior','Lakihegy','Pest County',NULL,'Kiserdő, Lakihegy',47.42162,19.02185,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Marczibányi tér','parc_exterior','Budapest','Budapest',NULL,'Marczibányi tér, Budapest',47.51319,19.02234,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Süsü játszótér','parc_exterior','Budapest','Budapest',NULL,'Süsü játszótér, Budapest',47.50869,19.03725,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Hunyadi Mátyás Általános Iskola','parc_exterior','Budapest','Budapest',NULL,'Hunyadi Mátyás Általános Iskola, Budapest',47.5361,19.06687,1,false,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Beregszász tér','parc_exterior','Budapest','Budapest',NULL,'Beregszász tér, Budapest',47.46928,19.01012,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Egyetemisták parkja','parc_exterior','Budapest','Budapest',NULL,'Egyetemisták parkja, Budapest',47.47578,19.06095,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Egyetemisták parkja (2)','parc_exterior','Budapest','Budapest',NULL,'Egyetemisták parkja, Budapest',47.47582,19.06088,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Vizafogó park','parc_exterior','Budapest','Budapest',NULL,'Vizafogó park, Budapest',47.53249,19.06203,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Vizafogó park (2)','parc_exterior','Budapest','Budapest',NULL,'Vizafogó park, Budapest',47.53245,19.06202,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Sportliget (2)','parc_exterior','Gyál','Pest County',NULL,'Sportliget, Gyál',47.46425,19.16798,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Sportliget (3)','parc_exterior','Gyál','Pest County',NULL,'Sportliget, Gyál',47.4643,19.168,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Sportliget (4)','parc_exterior','Gyál','Pest County',NULL,'Sportliget, Gyál',47.46434,19.16802,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Sportsziget','parc_exterior','Dunaharaszti','Pest County',NULL,'Sportsziget, Dunaharaszti',47.35953,19.08141,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Sportsziget (2)','parc_exterior','Dunaharaszti','Pest County',NULL,'Sportsziget, Dunaharaszti',47.35961,19.08144,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Sportliget','parc_exterior','Szombathely','Vas County',NULL,'Sportliget, Szombathely',47.23834,16.59969,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Diási Játékstrand','parc_exterior','Gyenesdiás','Zala County',NULL,'Diási Játékstrand, Gyenesdiás',46.76054,17.28836,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Diási Játékstrand (2)','parc_exterior','Gyenesdiás','Zala County',NULL,'Diási Játékstrand, Gyenesdiás',46.76075,17.28993,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Szent Lőrinc Katolikus Általános Iskola','parc_exterior','Gyál','Pest County',NULL,'Szent Lőrinc Katolikus Általános Iskola, Gyál',47.45079,19.18406,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Mátyás király tér','parc_exterior','Szeged','Csongrád',NULL,'Mátyás király tér, Szeged',46.24167,20.13626,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Városliget (6)','parc_exterior','Budapest','Budapest',NULL,'Városliget, Budapest',47.51806,19.07934,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Városliget (7)','parc_exterior','Budapest','Budapest',NULL,'Városliget, Budapest',47.51816,19.07926,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Fő tér','parc_exterior','Biatorbágy','Pest County',NULL,'Fő tér, Biatorbágy',47.4745,18.82299,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Barátság park','parc_exterior','Győr','Győr-Moson-Sopron',NULL,'Barátság park, Győr',47.67679,17.65581,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Cica park (2)','parc_exterior','Budapest','Budapest',NULL,'Cica park, Budapest',47.48598,19.06586,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Városkapu park','parc_exterior','Üröm','Pest County',NULL,'Városkapu park, Üröm',47.55854,19.0804,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Városkapu park (2)','parc_exterior','Üröm','Pest County',NULL,'Városkapu park, Üröm',47.55858,19.08044,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz II. János Pál pápa tér (2)','parc_exterior','Budapest','Budapest',NULL,'II. János Pál pápa tér, Budapest',47.49679,19.07967,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Gyermek tér','parc_exterior','Budapest','Budapest',NULL,'Gyermek tér, Budapest',47.54452,19.08549,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Kassák Park játszótér','parc_exterior','Budapest','Budapest',NULL,'Kassák Park játszótér, Budapest',47.52103,19.06586,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Nagy Lajos tér','parc_exterior','Budapest','Budapest',NULL,'Nagy Lajos tér, Budapest',47.5209,19.00006,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Hullám utcai szabadstrand','parc_exterior','Balatonfenyves','Somogy County',NULL,'Hullám utcai szabadstrand, Balatonfenyves',46.70627,17.43385,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Kőbányai Bem József Általános Iskola','parc_exterior','Budapest','Budapest',NULL,'Kőbányai Bem József Általános Iskola, Budapest',47.49224,19.11165,1,false,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Kőbányász park','parc_exterior','Diósd','Pest County',NULL,'Kőbányász park, Diósd',47.41174,18.99887,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Csattogó Völgyi Üdülőházak','parc_exterior','Verőce','Pest County',NULL,'Csattogó Völgyi Üdülőházak, Verőce',47.8327,19.02543,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Tétény-rét Családi Park (3)','parc_exterior','Diósd','Pest County',NULL,'Tétény-rét Családi Park, Diósd',47.39711,18.9775,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Mézesfehér utcai játszótér','parc_exterior','Lakihegy','Pest County',NULL,'Mézesfehér utcai játszótér, Lakihegy',47.41864,19.03854,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Dunakeszi Diáknegyed','parc_exterior','Dunakeszi','Pest County',NULL,'Dunakeszi Diáknegyed, Dunakeszi',47.65305,19.13792,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Dunakeszi Diáknegyed (2)','parc_exterior','Dunakeszi','Pest County',NULL,'Dunakeszi Diáknegyed, Dunakeszi',47.65193,19.13981,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Dunakeszi Diáknegyed (3)','parc_exterior','Dunakeszi','Pest County',NULL,'Dunakeszi Diáknegyed, Dunakeszi',47.65201,19.13955,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Dunakeszi Diáknegyed (4)','parc_exterior','Dunakeszi','Pest County',NULL,'Dunakeszi Diáknegyed, Dunakeszi',47.65289,19.13773,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Műegyetemi Lacrosse Sportkör','parc_exterior','Budapest','Budapest',NULL,'Műegyetemi Lacrosse Sportkör, Budapest',47.52414,19.03434,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Faápoló, Favizsgálat, Favágás,Kertápolás','parc_exterior','Gyál','Pest County',NULL,'Faápoló, Favizsgálat, Favágás,Kertápolás, Gyál',47.42821,19.12922,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Kaposvári Judócsarnok','parc_exterior','Kaposvár','Somogy County',NULL,'Kaposvári Judócsarnok, Kaposvár',46.37198,17.78002,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Avar utcai kutya sétáltató','parc_exterior','Budapest','Budapest',NULL,'Avar utcai kutya sétáltató, Budapest',47.49375,19.02702,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Decathlon','parc_exterior','Dunakeszi','Pest County',NULL,'Decathlon, Dunakeszi',47.60669,19.11177,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz SPX Trade Korlátolt Felelősségű Társaság (2)','parc_exterior','Budapest','Budapest',NULL,'SPX Trade Korlátolt Felelősségű Társaság, Budapest',47.52926,19.06907,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Zalaegerszeg','parc_exterior','Zalaegerszeg','Zala County',NULL,'Zalaegerszeg, Zalaegerszeg',46.84392,16.84885,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Ju Jitsu Óbuda','parc_exterior','Üröm','Pest County',NULL,'Ju Jitsu Óbuda, Üröm',47.57481,19.06533,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Falco KC Szombathely Kft.','parc_exterior','Szombathely','Vas County',NULL,'Falco KC Szombathely Kft., Szombathely',47.24204,16.61906,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Budafoki elágazás (41, 47, 56)','parc_exterior','Budaörs','Pest County',NULL,'Budafoki elágazás (41, 47, 56), Budaörs',47.43449,19.0363,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Jeet Kune Do / Kali','parc_exterior','Nagykanizsa','Zala County',NULL,'Jeet Kune Do / Kali, Nagykanizsa',46.4499,16.98613,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Konténerpest.hu (2)','parc_exterior','Budapest','Budapest',NULL,'Konténerpest.hu, Budapest',47.47249,19.05089,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Újlipót Pingpong Klub és Rendezvényterem','parc_exterior','Budapest','Budapest',NULL,'Újlipót Pingpong Klub, Budapest',47.51483,19.05723,1,true,false,'Mo-Fr 13:00-21:00; Sa 10:00-18:00',NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Megathlon SE - Nyéki Imre','parc_exterior','Budapest','Budapest',NULL,'Megathlon SE - Nyéki Imre, Budapest',47.45064,19.03572,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Bókay-gödör Játszótér','parc_exterior','Gyál','Pest County',NULL,'Bókay-gödör Játszótér, Gyál',47.4371,19.18156,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Kaposvár Városliget','parc_exterior','Kaposvár','Somogy County',NULL,'Kaposvár Városliget, Kaposvár',46.36744,17.78209,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Kaposvár Városliget (2)','parc_exterior','Kaposvár','Somogy County',NULL,'Kaposvár Városliget, Kaposvár',46.36743,17.78199,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Zöldváros Lakópark','parc_exterior','Budapest','Budapest',NULL,'Zöldváros Lakópark, Budapest',47.5356,19.10942,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Fenyves park','parc_exterior','Balatonfüred','Veszprém',NULL,'Fenyves park, Balatonfüred',46.95892,17.89293,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Újpalota liget','parc_exterior','Csömör','Pest County',NULL,'Újpalota liget, Csömör',47.53654,19.13723,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Kőrakás park 44. Játszótér','parc_exterior','Csömör','Pest County',NULL,'Kőrakás park 44. Játszótér, Csömör',47.54347,19.1479,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Városliget (8)','parc_exterior','Budapest','Budapest',NULL,'Városliget, Budapest',47.51545,19.08765,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Csalit-Csatárka park','parc_exterior','Budapest','Budapest',NULL,'Csalit-Csatárka park, Budapest',47.53043,19.01465,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Csalit-Csatárka park (2)','parc_exterior','Budapest','Budapest',NULL,'Csalit-Csatárka park, Budapest',47.53039,19.01472,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Jakab József utcai nagy játszótér','parc_exterior','Budapest','Budapest',NULL,'Jakab József utcai nagy játszótér, Budapest',47.53702,19.06318,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Jakab József utcai nagy játszótér (2)','parc_exterior','Budapest','Budapest',NULL,'Jakab József utcai nagy játszótér, Budapest',47.53696,19.06315,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Károlyi kert','parc_exterior','Budapest','Budapest',NULL,'Károlyi kert, Budapest',47.49194,19.05955,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Sipos Pál tér','parc_exterior','Fót','Pest County',NULL,'Sipos Pál tér, Fót',47.61776,19.18227,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Szilas park','parc_exterior','Budakalász','Pest County',NULL,'Szilas park, Budakalász',47.57915,19.10903,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Szilas park (2)','parc_exterior','Budakalász','Pest County',NULL,'Szilas park, Budakalász',47.57911,19.10899,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Megyeri Úti Általános Iskola','parc_exterior','Budakalász','Pest County',NULL,'Megyeri Úti Általános Iskola, Budakalász',47.58099,19.08856,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Kresz park (2)','parc_exterior','Cegléd','Pest County',NULL,'Kresz park, Cegléd',47.16101,19.79167,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Magyar Testnevelési és Sporttudományi Egyetem','parc_exterior','Budapest','Budapest',NULL,'Magyar Testnevelési és Sporttudományi Egyetem, Budapest',47.49106,19.02642,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Torockó tér','parc_exterior','Budapest','Budapest',NULL,'Torockó tér, Budapest',47.51495,19.00379,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Herman Ottó Általános Iskola','parc_exterior','Budapest','Budapest',NULL,'Herman Ottó Általános Iskola, Budapest',47.51604,19.05117,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Szivárvány utcai park','parc_exterior','Balatonfüred','Veszprém',NULL,'Szivárvány utcai park, Balatonfüred',46.95283,17.87496,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Borostyán-tó Strand','parc_exterior','Zalalövő','Zala County',NULL,'Borostyán-tó Strand, Zalalövő',46.85223,16.56932,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Liget lakótelep','parc_exterior','Dombóvár','Tolna County',NULL,'Liget lakótelep, Dombóvár',46.34995,18.12499,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Cséplő utcai szabadidőpark','parc_exterior','Ecser','Pest County',NULL,'Cséplő utcai szabadidőpark, Ecser',47.47534,19.26098,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Szabadstrand','parc_exterior','Balatonvilágos','Somogy County',NULL,'Szabadstrand, Balatonvilágos',46.97903,18.16377,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Ozmán Utcai Játszótér','parc_exterior','Budapest','Budapest',NULL,'Ozmán Utcai Játszótér, Budapest',47.54479,19.11789,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz IntegraBus','parc_exterior','Budapest','Budapest',NULL,'IntegraBus, Budapest',47.45598,19.05028,1,false,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Wass Albert Tér','parc_exterior','Budapest','Budapest',NULL,'Wass Albert Tér, Budapest',47.51042,19.12443,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Zárdakert','parc_exterior','Zsámbék','Pest County',NULL,'Zárdakert, Zsámbék',47.54804,18.71731,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Zárdakert (2)','parc_exterior','Zsámbék','Pest County',NULL,'Zárdakert, Zsámbék',47.54801,18.71722,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Kontyfa Utcai Játszótér (2)','parc_exterior','Csömör','Pest County',NULL,'Kontyfa Utcai Játszótér, Csömör',47.54742,19.13886,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Kontyfa Utcai Játszótér (3)','parc_exterior','Csömör','Pest County',NULL,'Kontyfa Utcai Játszótér, Csömör',47.54742,19.13892,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Sportpark','parc_exterior','Budakalász','Pest County',NULL,'Sportpark, Budakalász',47.60306,19.06275,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz The Gym Club','parc_exterior','Budapest','Budapest',NULL,'The Gym Club, Budapest',47.54852,19.04523,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Lövölde tér','parc_exterior','Budapest','Budapest',NULL,'Lövölde tér, Budapest',47.5076,19.07221,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Lakihegyi Akácliget Óvoda','parc_exterior','Lakihegy','Pest County',NULL,'Lakihegyi Akácliget Óvoda, Lakihegy',47.37496,19.00792,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Podmaniczky Kastély, Park','parc_exterior','Nagytarcsa','Pest County',NULL,'Podmaniczky Kastély, Park, Nagytarcsa',47.48045,19.24917,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Podmaniczky Kastély, Park (2)','parc_exterior','Nagytarcsa','Pest County',NULL,'Podmaniczky Kastély, Park, Nagytarcsa',47.4803,19.24905,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Fürj u.(362, 364, 365)','parc_exterior','Vác','Pest County',NULL,'Fürj u.(362, 364, 365), Vác',47.79275,19.13012,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Játszótér - Aradi u.','parc_exterior','Üröm','Pest County',NULL,'Játszótér - Aradi u., Üröm',47.5572,19.08561,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('teqball asztal','parc_exterior','Budapest','Budapest',NULL,'Fehér Marcell Emlékpark, Budapest',47.47302,19.06091,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Almássy téri játszótér','parc_exterior','Budapest','Budapest',NULL,'Almássy téri játszótér, Budapest',47.50173,19.07177,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Vad Kelet Kft Matula Vadászbolt','parc_exterior','Sajóörös','Borsod-Abaúj-Zemplén',NULL,'Vad Kelet Kft Matula Vadászbolt, Sajóörös',47.93508,21.03363,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Címer utcai játszótér','parc_exterior','Gödöllő','Pest County',NULL,'Címer utcai játszótér, Gödöllő',47.61156,19.36776,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Integrált közösségi és szolgáltató tér','parc_exterior','Bátaszék','Tolna County',NULL,'Bátaszék',46.20244,18.73681,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Zoltán utcai sportpark','parc_exterior','Budapest','Budapest',NULL,'Zoltán utcai sportpark, Budapest',47.45192,19.12921,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Zoltán utcai sportpark (2)','parc_exterior','Budapest','Budapest',NULL,'Zoltán utcai sportpark, Budapest',47.45189,19.12925,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Zoltán utcai sportpark (3)','parc_exterior','Budapest','Budapest',NULL,'Zoltán utcai sportpark, Budapest',47.45187,19.12929,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Óhegy park (3)','parc_exterior','Budapest','Budapest',NULL,'Óhegy park, Budapest',47.48003,19.14772,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Óhegy park (4)','parc_exterior','Budapest','Budapest',NULL,'Óhegy park, Budapest',47.48005,19.14757,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Városliget','parc_exterior','Budapest','Budapest',NULL,'Városliget, Budapest',47.50858,19.08553,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ormai László Asztalitenisz Csarnok','parc_exterior','Budapest','Budapest',NULL,'Marczibányi tér, Budapest',47.51227,19.02221,1,true,false,NULL,'Nemzeti Sportközpontok',ARRAY['exterior'],true,false),
  ('Asztalitenisz Barátság park','parc_exterior','Debrecen','Hajdú-Bihar',NULL,'Barátság park, Debrecen',47.54565,21.61655,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Toldy Ferenc Gimnázium','parc_exterior','Budapest','Budapest',NULL,'Toldy Ferenc Gimnázium, Budapest',47.50447,19.03608,1,false,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Csillebérci Szabadidő és Ifjúsági Központ','parc_exterior','Budakeszi','Pest County',NULL,'Csillebérci Szabadidő és Ifjúsági Központ, Budakeszi',47.4961,18.95991,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Bikás park','parc_exterior','Budapest','Budapest',NULL,'Bikás park, Budapest',47.46677,19.03073,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Gesztenyés játszótér','parc_exterior','Budapest','Budapest',NULL,'Gesztenyés játszótér, Budapest',47.47823,19.03685,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Gesztenyés játszótér (2)','parc_exterior','Budapest','Budapest',NULL,'Gesztenyés játszótér, Budapest',47.47829,19.03689,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Melinda park','parc_exterior','Pécs','Baranya',NULL,'Melinda park, Pécs',46.04561,18.21284,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Semsey Aladár park','parc_exterior','Budakalász','Pest County',NULL,'Semsey Aladár park, Budakalász',47.56324,19.09578,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Dzsungel park','parc_exterior','Budaörs','Pest County',NULL,'Dzsungel park, Budaörs',47.46986,18.99861,1,true,false,'07:00-20:00',NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Dzsungel park (2)','parc_exterior','Budaörs','Pest County',NULL,'Dzsungel park, Budaörs',47.46985,18.99866,1,true,false,'07:00-20:00',NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Dzsungel park (3)','parc_exterior','Budaörs','Pest County',NULL,'Dzsungel park, Budaörs',47.47112,18.99955,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Dzsungel park (4)','parc_exterior','Budaörs','Pest County',NULL,'Dzsungel park, Budaörs',47.47114,18.99951,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Dzsungel park (5)','parc_exterior','Budaörs','Pest County',NULL,'Dzsungel park, Budaörs',47.46988,18.99852,1,true,false,'07:00-20:00',NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Dzsungel park (6)','parc_exterior','Budaörs','Pest County',NULL,'Dzsungel park, Budaörs',47.46987,18.99857,1,true,false,'07:00-20:00',NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Lidicei tér','parc_exterior','Szeged','Csongrád',NULL,'Lidicei tér, Szeged',46.27164,20.17252,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Bezerédi Sport- és Szabadidőpark','parc_exterior','Dunaharaszti','Pest County',NULL,'Bezerédi Sport- és Szabadidőpark, Dunaharaszti',47.34359,19.10275,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Bezerédi Sport- és Szabadidőpark (2)','parc_exterior','Dunaharaszti','Pest County',NULL,'Bezerédi Sport- és Szabadidőpark, Dunaharaszti',47.34356,19.1028,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Bezerédi Sport- és Szabadidőpark (3)','parc_exterior','Dunaharaszti','Pest County',NULL,'Bezerédi Sport- és Szabadidőpark, Dunaharaszti',47.34353,19.10285,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Levendula kemping (FKK)','parc_exterior','Zánka','Veszprém',NULL,'Levendula kemping (FKK), Zánka',46.87964,17.74036,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Tűzoltó játszótér','parc_exterior','Szigetújfalu','Pest County',NULL,'Tűzoltó játszótér, Szigetújfalu',47.23094,18.95756,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Királyok parkja','parc_exterior','Székesfehérvár','Fejér',NULL,'Királyok parkja, Székesfehérvár',47.19121,18.39537,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Turozsaki Uti Szabadidopark es Setany (2)','parc_exterior','Székesfehérvár','Fejér',NULL,'Turozsaki Uti Szabadidopark es Setany, Székesfehérvár',47.2063,18.44282,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('ping-pong','parc_exterior','Dunakeszi','Pest County',NULL,'Csíkszentiván játszótér, Dunakeszi',47.5968,19.12027,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Játszótér Kresz Pálya','parc_exterior','Budapest','Budapest',NULL,'Játszótér Kresz Pálya, Budapest',47.45651,19.14058,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Játszótér Kresz Pálya (2)','parc_exterior','Budapest','Budapest',NULL,'Játszótér Kresz Pálya, Budapest',47.45644,19.14066,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Kutyafuttató','parc_exterior','Dunaharaszti','Pest County',NULL,'Kutyafuttató, Dunaharaszti',47.40442,19.07639,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Olasz Dísznövény lerakat','parc_exterior','Sajóörös','Borsod-Abaúj-Zemplén',NULL,'Olasz Dísznövény lerakat, Sajóörös',47.93126,21.03018,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Olasz Dísznövény lerakat (2)','parc_exterior','Sajóörös','Borsod-Abaúj-Zemplén',NULL,'Olasz Dísznövény lerakat, Sajóörös',47.93119,21.03015,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Toscana Lakópark','parc_exterior','Budapest','Budapest',NULL,'Toscana Lakópark, Budapest',47.52777,19.11189,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Agrár Buszmegálló','parc_exterior','Debrecen','Hajdú-Bihar',NULL,'Agrár Buszmegálló, Debrecen',47.54892,21.61148,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Etele Park','parc_exterior','Budapest','Budapest',NULL,'Etele Park, Budapest',47.46265,19.03152,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('ATSK Asztalitenisz Terem','parc_exterior','Szeged','Csongrád',NULL,'ATSK Szeged, Szeged',46.26868,20.16709,1,false,false,'Mo,We,Fr 18:00-21:00; PH off',NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Sportmarket','parc_exterior','Budapest','Budapest',NULL,'Sportmarket, Budapest',47.54411,19.0319,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('ping-pong','parc_exterior','Pécs','Baranya',NULL,'Multigames, Pécs',46.0407,18.2262,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Kinizsi TTK','parc_exterior','Fót','Pest County',NULL,'Kinizsi TTK, Fót',47.5671,19.12241,1,true,false,'Mo 19:00-21:00; Tu 18:00-20:00; We 19:00-21:00; Th 19:00-21:00',NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Angster József utca (36, 37, 932)','parc_exterior','Pécs','Baranya',NULL,'Angster József utca (36, 37, 932), Pécs',46.08189,18.21363,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Bessenyei park játszótér','parc_exterior','Budapest','Budapest',NULL,'Bessenyei park játszótér, Budapest',47.52157,19.06123,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Bem tér (1)','parc_exterior','Debrecen','Hajdú-Bihar',NULL,'Bem tér (1), Debrecen',47.54202,21.62384,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz csarnok','parc_exterior','Kaposvár','Somogy County',NULL,'Kaposvár',46.37241,17.79669,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('TURRIS SE Asztalitenisz Csarnok','parc_exterior','Sopron','Győr-Moson-Sopron',NULL,'Sopron',47.67506,16.59372,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('ping-pong (2)','parc_exterior','Pécs','Baranya',NULL,'Pécs',46.04081,18.22687,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('ping-pong','parc_exterior','Pellérd','Baranya',NULL,'Pellérd',46.03104,18.21463,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Egérlyuk játszótér','parc_exterior','Budapest','Budapest',NULL,'Egérlyuk játszótér, Budapest',47.45668,19.03764,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Dynamic park','parc_exterior','Üröm','Pest County',NULL,'Dynamic park, Üröm',47.55904,19.09183,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Abádi tér','parc_exterior','Budapest','Budapest',NULL,'Abádi tér, Budapest',47.44605,19.04022,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Közösségi Liget','parc_exterior','Solymár','Pest County',NULL,'Közösségi Liget, Solymár',47.56489,18.9528,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Rakéta játszótér','parc_exterior','Budakalász','Pest County',NULL,'Rakéta játszótér, Budakalász',47.57866,19.10558,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Rakéta játszótér (2)','parc_exterior','Budakalász','Pest County',NULL,'Rakéta játszótér, Budakalász',47.57868,19.10563,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Kolorplatz','parc_exterior','Kazincbarcika','Borsod-Abaúj-Zemplén',NULL,'Kolorplatz, Kazincbarcika',48.24558,20.61389,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Szitakötő játszótér','parc_exterior','Budapest','Budapest',NULL,'Szitakötő játszótér, Budapest',47.49861,19.02977,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Sportliget','parc_exterior','Gyál','Pest County',NULL,'Sportliget, Gyál',47.46431,19.168,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Melinda park (2)','parc_exterior','Pécs','Baranya',NULL,'Melinda park, Pécs',46.04561,18.21268,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Városliget (2)','parc_exterior','Budapest','Budapest',NULL,'Városliget, Budapest',47.51812,19.0793,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Városliget (3)','parc_exterior','Budapest','Budapest',NULL,'Városliget, Budapest',47.51324,19.0901,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Rekortán futókör 555 m','parc_exterior','Debrecen','Hajdú-Bihar',NULL,'Rekortán futókör 555 m, Debrecen',47.53756,21.65212,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Honvéd tér','parc_exterior','Budapest','Budapest',NULL,'Honvéd tér, Budapest',47.50978,19.05017,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Józsa Grund Sportpark','parc_exterior','Hajdúböszörmény','Hajdú-Bihar',NULL,'Józsa Grund Sportpark, Hajdúböszörmény',47.59569,21.55552,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Miskolci Egyetem','parc_exterior','Miskolc','Borsod-Abaúj-Zemplén',NULL,'Miskolci Egyetem, Miskolc',48.08163,20.77041,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz csarnok','parc_exterior','Budapest','Budapest',NULL,'BVSC Zugló Handball Facility, Budapest',47.52385,19.08945,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('OPÁL Asztalitenisz csarnok','parc_exterior','Celldömölk','Vas County',NULL,'CVSE Sporttelep, Celldömölk',47.25459,17.14642,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Kis Hunyad Miskolc','parc_exterior','Miskolc','Borsod-Abaúj-Zemplén',NULL,'Kis Hunyad Miskolc, Miskolc',48.10584,20.77113,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Asztalitenisz Danko Pista utca','parc_exterior','Miskolc','Borsod-Abaúj-Zemplén',NULL,'Danko Pista utca, Miskolc',48.09931,20.79023,1,true,false,NULL,NULL,ARRAY['exterior'],true,false)
) AS v(name,type,city,county,sector,address,lat,lng,tables_count,free_access,night_lighting,hours,description,tags,approved,verified)
JOIN cities c ON c.country_code='HU' AND c.name=v.city
ON CONFLICT (name,city_id) DO NOTHING;
COMMIT;
