-- PT — Portugal — 74 venues, 50 cities
-- Idempotent: safe to run multiple times. Source: OpenStreetMap via Overture Maps + GeoNames.
-- STAGED: cities active=false, expansion_status='community_review' (hidden in-app until activated — see DEPLOYMENT.md). Venues approved=true.
BEGIN;
INSERT INTO countries (code,name,active) VALUES ('PT','Portugal',true) ON CONFLICT (code) DO NOTHING;
INSERT INTO cities (name,country_code,country_name,admin_area,county,lat,lng,zoom,active,expansion_status) VALUES
  ('Abrigada','PT','Portugal','Lisbon','Alenquer',39.14416,-9.01853,12,false,'community_review'),
  ('Água Longa','PT','Portugal','Porto','Santo Tirso',41.24972,-8.49285,12,false,'community_review'),
  ('Albufeira','PT','Portugal','Faro','Albufeira',37.08819,-8.2503,12,false,'community_review'),
  ('Aldoar','PT','Portugal','Porto','Porto',41.1671,-8.6691,12,false,'community_review'),
  ('Alfragide','PT','Portugal','Lisbon','Amadora',38.73203,-9.2192,12,false,'community_review'),
  ('Ansião','PT','Portugal','Leiria','Ansião',39.91177,-8.43568,12,false,'community_review'),
  ('Arcos de Valdevez','PT','Portugal','Viana do Castelo','Arcos de Valdevez',41.84668,-8.41905,12,false,'community_review'),
  ('Armação de Pêra','PT','Portugal','Faro','Silves',37.10256,-8.35695,12,false,'community_review'),
  ('Bairro do Loreto','PT','Portugal','Coimbra','Coimbra',40.23333,-8.45,12,false,'community_review'),
  ('Barcelos','PT','Portugal','Braga','Barcelos',41.53174,-8.61843,12,false,'community_review'),
  ('Beja','PT','Portugal','Beja','Beja',38.01469,-7.86284,12,false,'community_review'),
  ('Belém','PT','Portugal','Lisbon','Lisbon',38.69875,-9.19289,12,false,'community_review'),
  ('Caneças','PT','Portugal','Lisbon','Odivelas',38.81321,-9.22679,12,false,'community_review'),
  ('Carvoeiro','PT','Portugal','Faro','Lagoa',37.09736,-8.46846,12,false,'community_review'),
  ('Castelo Branco','PT','Portugal','Castelo Branco','Castelo Branco',39.82364,-7.49101,12,false,'community_review'),
  ('Charneca','PT','Portugal','Lisbon','Lisbon',38.78351,-9.14348,12,false,'community_review'),
  ('Charneca de Caparica','PT','Portugal','Setúbal','Almada',38.62032,-9.19426,12,false,'community_review'),
  ('Chaves','PT','Portugal','Vila Real','Chaves',41.74019,-7.46879,12,false,'community_review'),
  ('Condeixa-a-Nova','PT','Portugal','Coimbra','Condeixa-A-Nova',40.11283,-8.49804,12,false,'community_review'),
  ('Faro','PT','Portugal','Faro','Faro',37.01869,-7.92716,12,false,'community_review'),
  ('Figueira de Castelo Rodrigo','PT','Portugal','Guarda','Figueira de Castelo Rodrigo',40.89262,-6.9635,12,false,'community_review'),
  ('Figueiró dos Vinhos','PT','Portugal','Leiria','Figueiró Dos Vinhos',39.90413,-8.27511,12,false,'community_review'),
  ('Lisboa','PT','Portugal','Lisbon','Lisbon',38.72509,-9.1498,12,false,'community_review'),
  ('Lourosa','PT','Portugal','Aveiro','Santa Maria da Feira',40.9842,-8.55142,12,false,'community_review'),
  ('Lousada','PT','Portugal','Porto','Lousada',41.27822,-8.27993,12,false,'community_review'),
  ('Maia','PT','Portugal','Porto','Maia',41.23574,-8.6199,12,false,'community_review'),
  ('Marco da Oliveirinha','PT','Portugal','Aveiro','Aveiro',40.6146,-8.61944,12,false,'community_review'),
  ('Massamá','PT','Portugal','Lisbon','Sintra',38.75279,-9.2811,12,false,'community_review'),
  ('Mindelo','PT','Portugal','Porto','Vila do Conde',41.31527,-8.72124,12,false,'community_review'),
  ('Mondim de Basto','PT','Portugal','Vila Real','Mondim de Basto',41.41157,-7.95441,12,false,'community_review'),
  ('Moura','PT','Portugal','Beja','Moura',38.1401,-7.44856,12,false,'community_review'),
  ('Odivelas','PT','Portugal','Lisbon','Odivelas',38.79269,-9.1838,12,false,'community_review'),
  ('Oliveirinha','PT','Portugal','Aveiro','Aveiro',40.60715,-8.59198,12,false,'community_review'),
  ('Paços','PT','Portugal','Porto','Porto',41.16207,-8.67053,12,false,'community_review'),
  ('Pampilhosa','PT','Portugal','Aveiro','Mealhada',40.3358,-8.42738,12,false,'community_review'),
  ('Pataias','PT','Portugal','Leiria','Alcobaça',39.66978,-8.9958,12,false,'community_review'),
  ('Pontinha','PT','Portugal','Lisbon','Odivelas',38.76771,-9.19935,12,false,'community_review'),
  ('Queluz','PT','Portugal','Lisbon','Sintra',38.75657,-9.25451,12,false,'community_review'),
  ('Ramada','PT','Portugal','Lisbon','Odivelas',38.80368,-9.1877,12,false,'community_review'),
  ('Rio de Mouro','PT','Portugal','Lisbon','Sintra',38.76613,-9.32804,12,false,'community_review'),
  ('Samouco','PT','Portugal','Setúbal','Alcochete',38.72035,-9.00471,12,false,'community_review'),
  ('Santa Maria de Avioso','PT','Portugal','Porto','Maia',41.2679,-8.60586,12,false,'community_review'),
  ('Santo António dos Olivais','PT','Portugal','Coimbra','Coimbra',40.21805,-8.40523,12,false,'community_review'),
  ('São João','PT','Portugal','Aveiro','Ovar',40.86802,-8.60672,12,false,'community_review'),
  ('São Luis','PT','Portugal','Beja','Odemira',37.71556,-8.66472,12,false,'community_review'),
  ('Sertã','PT','Portugal','Castelo Branco','Sertã',39.80205,-8.09589,12,false,'community_review'),
  ('Sever do Vouga','PT','Portugal','Aveiro','Sever do Vouga',40.73459,-8.36722,12,false,'community_review'),
  ('Vieira do Minho','PT','Portugal','Braga','Vieira do Minho',41.63292,-8.14252,12,false,'community_review'),
  ('Vila Nova de Cerveira','PT','Portugal','Viana do Castelo','Vila Nova de Cerveira',41.94118,-8.7423,12,false,'community_review'),
  ('Vila Praia de Âncora','PT','Portugal','Viana do Castelo','Caminha',41.81098,-8.85255,12,false,'community_review')
ON CONFLICT (country_code,name) DO NOTHING;
INSERT INTO venues (name,type,city,city_id,county,sector,address,lat,lng,tables_count,free_access,night_lighting,hours,description,tags,approved,verified,submitted_by)
SELECT v.name,v.type,v.city,c.id,v.county::text,v.sector::text,v.address,v.lat::double precision,v.lng::double precision,v.tables_count::int,v.free_access::boolean,v.night_lighting::boolean,v.hours::text,v.description::text,v.tags::text[],v.approved::boolean,v.verified::boolean,NULL
FROM (VALUES
  ('Ténis de mesa Aldeamento Hapimag','parc_exterior','Albufeira','Albufeira',NULL,'R TORRE VELHA 282, Albufeira',37.07546,-8.29508,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Escola Básica n.º 2 da Pampilhosa','parc_exterior','Pampilhosa','Mealhada',NULL,'R RIO DE CIMA 16, Pampilhosa',40.33871,-8.42174,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Escola Básica n.º 2 da Pampilhosa (2)','parc_exterior','Pampilhosa','Mealhada',NULL,'R RIO DE CIMA 16, Pampilhosa',40.3387,-8.42184,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('ping-pong','parc_exterior','Vila Nova de Cerveira','Vila Nova de Cerveira',NULL,'PC D DINIS, Vila Nova de Cerveira',41.9431,-8.74193,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Parque de Merendas do Samouco','parc_exterior','Samouco','Alcochete',NULL,'AL PRAIA, Samouco',38.7276,-9.00941,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Quinta do Paraíso','parc_exterior','Carvoeiro','Lagoa',NULL,'URB QUINTA DO PARAÍSO, Carvoeiro',37.10507,-8.47678,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Parque Alameda da Juventude','parc_exterior','Ramada','Odivelas',NULL,'R JOÃO VILLARET 20, Ramada',38.80451,-9.18752,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Escola Secundária de Garcia de Orta','parc_exterior','Paços','Porto',NULL,'R PINHO LEAL 47, Paços',41.16206,-8.66803,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Escola Secundária de Garcia de Orta (2)','parc_exterior','Paços','Porto',NULL,'R PINHO LEAL 47, Paços',41.16198,-8.66824,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa R COMBATENTES DO ULTRAMAR','parc_exterior','Odivelas','Odivelas',NULL,'R COMBATENTES DO ULTRAMAR 10, Odivelas',38.79431,-9.18365,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Escola Básica dos 2º e 3º Ciclos Manoel de Oliveira','parc_exterior','Aldoar','Porto',NULL,'LG 3 DE FEVEREIRO, Aldoar',41.16883,-8.66575,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Escola Básica dos 2º e 3º Ciclos Manoel de Oliveira (2)','parc_exterior','Aldoar','Porto',NULL,'R PINTOR VELOSO SALGADO 5, Aldoar',41.16874,-8.66566,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Rossio do Trigache','parc_exterior','Caneças','Odivelas',NULL,'AV LIBERDADE 199, Caneças',38.80443,-9.21074,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Jardim do Sol','parc_exterior','Odivelas','Odivelas',NULL,'R LAURA AIRES, Odivelas',38.79517,-9.19303,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Jardim do Sol (2)','parc_exterior','Odivelas','Odivelas',NULL,'R LAURA AIRES, Odivelas',38.79523,-9.19294,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Jardim do Sol (3)','parc_exterior','Odivelas','Odivelas',NULL,'R LAURA AIRES, Odivelas',38.79518,-9.19291,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Reserva da Biosfera Transfronteira Gerês-Xurés','parc_exterior','Vieira do Minho','Vieira do Minho',NULL,'EN 103 15, Vieira do Minho',41.68134,-7.95027,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Yacht Charter Lisbon','parc_exterior','Belém','Lisbon',NULL,'R TEN VALADIM LISBOA LOFTS 6, Belém',38.70242,-9.169,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa R GAGO COUTINHO','parc_exterior','Charneca','Lisbon',NULL,'R GAGO COUTINHO 1, Charneca',38.79173,-9.13487,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa R GAGO COUTINHO (2)','parc_exterior','Charneca','Lisbon',NULL,'R GAGO COUTINHO 3, Charneca',38.79174,-9.13496,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa MTE DO CERRO','parc_exterior','São Luis','Odemira',NULL,'MTE DO CERRO 3, São Luis',37.71761,-8.51772,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Parque Urbano Quinta das Flores','parc_exterior','Massamá','Sintra',NULL,'R DR FRANCISCO RIBEIRO SPÍNOLA 3, Massamá',38.75754,-9.28004,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Parque Urbano Quinta das Flores (2)','parc_exterior','Massamá','Sintra',NULL,'R DR FRANCISCO RIBEIRO SPÍNOLA 3, Massamá',38.75756,-9.27998,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Parque Urbano Quinta das Flores (3)','parc_exterior','Massamá','Sintra',NULL,'R DR FRANCISCO RIBEIRO SPÍNOLA 3, Massamá',38.75758,-9.27992,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Parque Urbano Quinta das Flores (4)','parc_exterior','Massamá','Sintra',NULL,'R DR FRANCISCO RIBEIRO SPÍNOLA 3, Massamá',38.75761,-9.27986,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Parque Urbano Fernando Pinto de Moura','parc_exterior','Mondim de Basto','Mondim de Basto',NULL,'AV 25 DE ABRIL, Mondim de Basto',41.41052,-7.95617,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Parque Urbano Fernando Pinto de Moura (2)','parc_exterior','Mondim de Basto','Mondim de Basto',NULL,'AV 25 DE ABRIL, Mondim de Basto',41.41054,-7.95615,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Parque Ribeirinho','parc_exterior','Faro','Faro',NULL,'MOINHO DO GRELLHA, Faro',37.02562,-7.94729,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Bairro Padre Cruz','parc_exterior','Pontinha','Odivelas',NULL,'R PROF ALMEIDA LIMA, Pontinha',38.76887,-9.19323,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Bairro Padre Cruz (2)','parc_exterior','Pontinha','Odivelas',NULL,'R PROF ARSENIO NUNES, Pontinha',38.76887,-9.19329,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Parque Urbano da Cruz do Montalvão','parc_exterior','Castelo Branco','Castelo Branco',NULL,'EN 18 1I, Castelo Branco',39.81516,-7.50421,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Parque Urbano da Cruz do Montalvão (2)','parc_exterior','Castelo Branco','Castelo Branco',NULL,'ESTR MONTALVAO 5, Castelo Branco',39.81455,-7.50509,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa R PADRE CÂNDIDO TEIXEIRA','parc_exterior','Sertã','Sertã',NULL,'R PADRE CÂNDIDO TEIXEIRA, Sertã',39.81861,-8.18499,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Academia de Ténis de Mesa de Coimbra','parc_exterior','Santo António dos Olivais','Coimbra',NULL,'AV CALOUSTE GULBENKIAN, Santo António dos Olivais',40.21477,-8.41526,1,true,false,'Mo-Fr 10:00-13:00, 14:00-20:30',NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Parque da Cidade de Lourosa','parc_exterior','Lourosa','Santa Maria da Feira',NULL,'R 1 DE MAIO 2249, Lourosa',40.97627,-8.54177,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa AV ALMEIDA GARRETT','parc_exterior','Alfragide','Amadora',NULL,'AV ALMEIDA GARRETT 6, Alfragide',38.73799,-9.21843,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Escola Básica de Moura','parc_exterior','Moura','Moura',NULL,'AV POETA JOAQUIM COSTA, Moura',38.14234,-7.44353,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Escola Básica de Moura (2)','parc_exterior','Moura','Moura',NULL,'AV POETA JOAQUIM COSTA, Moura',38.14233,-7.44364,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Parque Urbano da Cruz do Montalvão (3)','parc_exterior','Castelo Branco','Castelo Branco',NULL,'EN 18 1I, Castelo Branco',39.81514,-7.50419,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Centro Hospitalar e Universitário de Coimbra - Bloco Central','parc_exterior','Santo António dos Olivais','Coimbra',NULL,'PCT PROF MOTA PINTO, Santo António dos Olivais',40.22038,-8.41109,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa R CASTELINHO','parc_exterior','Odivelas','Odivelas',NULL,'R CASTELINHO 1, Odivelas',38.79431,-9.1836,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Go Up Solutions','parc_exterior','Faro','Faro',NULL,'PCT ENG DUARTE PACHECO 9, Faro',37.01943,-7.92448,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Parque Urbano Novo Rumo','parc_exterior','Maia','Maia',NULL,'R VITORINO NEMÉSIO 130, Maia',41.22848,-8.62583,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Parque Vale da Pipa','parc_exterior','Figueiró dos Vinhos','Figueiró Dos Vinhos',NULL,'R DR FERNANDO LACERDA, Figueiró dos Vinhos',39.89791,-8.28406,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Escola Secundária Fernando Namora','parc_exterior','Condeixa-a-Nova','Condeixa-A-Nova',NULL,'R LONGJUMEAU POSTO DA GNR, Condeixa-a-Nova',40.10836,-8.49797,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Reserva da Biosfera Transfronteira Gerês-Xurés','parc_exterior','Arcos de Valdevez','Arcos de Valdevez',NULL,'LG AUGUSTO CRISTINA - MAESTRO, Arcos de Valdevez',41.84997,-8.4163,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Reserva da Biosfera Transfronteira Gerês-Xurés (2)','parc_exterior','Arcos de Valdevez','Arcos de Valdevez',NULL,'LG AUGUSTO CRISTINA - MAESTRO, Arcos de Valdevez',41.84997,-8.41608,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Parque infantil de São Bernardo','parc_exterior','Marco da Oliveirinha','Aveiro',NULL,'R CASTELA 79, Marco da Oliveirinha',40.61707,-8.62184,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa AV GIL EANES','parc_exterior','Rio de Mouro','Sintra',NULL,'AV GIL EANES 1, Rio de Mouro',38.77978,-9.32225,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Parque do Casal da Barota','parc_exterior','Massamá','Sintra',NULL,'R D AMÉLIA 19, Massamá',38.7633,-9.27802,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Parque do Casal da Barota (2)','parc_exterior','Massamá','Sintra',NULL,'R D AMELIA 17, Massamá',38.76316,-9.27787,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Universidade do Algarve','parc_exterior','Faro','Faro',NULL,'SIT PISCINAS, Faro',37.02928,-7.92174,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Escola Básica Dom Pedro IV','parc_exterior','Mindelo','Vila do Conde',NULL,'R FONTE 750, Mindelo',41.30828,-8.71919,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa URB SANTO ANTONIO DO ALTO','parc_exterior','Faro','Faro',NULL,'URB SANTO ANTONIO DO ALTO, Faro',37.01783,-7.91743,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa R VALE MERRICO','parc_exterior','Abrigada','Alenquer',NULL,'R VALE MERRICO, Abrigada',39.13481,-9.02444,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa R MIMOS','parc_exterior','Pataias','Alcobaça',NULL,'R MIMOS, Pataias',39.72488,-9.04261,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa R TEN COR GUSTAVO ADOLFO DE GOUVEIA','parc_exterior','Figueira de Castelo Rodrigo','Figueira de Castelo Rodrigo',NULL,'R TEN COR GUSTAVO ADOLFO DE GOUVEIA 7, Figueira de Castelo Rodrigo',40.8909,-6.96197,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Mesa Ping-Pong','parc_exterior','Vila Praia de Âncora','Caminha',NULL,'PQ DR LUCIANO AMORIM PEREIRA DA SILVA, Vila Praia de Âncora',41.87702,-8.83573,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Parque Desportivo da Verdizela','parc_exterior','Charneca de Caparica','Almada',NULL,'AV VERDIZELA 38, Charneca de Caparica',38.57973,-9.15539,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de Mesa','parc_exterior','Bairro do Loreto','Coimbra',NULL,'R CIDADE DE POITIERS SERRACAO, Bairro do Loreto',40.21949,-8.43699,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Largo Primeiro de Dezembro','parc_exterior','São João','Ovar',NULL,'R VISC OVAR 385, São João',40.85379,-8.60672,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Escola Básica Dom Pedro IV (2)','parc_exterior','Mindelo','Vila do Conde',NULL,'R FONTE 750, Mindelo',41.30831,-8.71914,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Casa do Cato - Suculentas e Catos','parc_exterior','Barcelos','Barcelos',NULL,'R BARTOLOMEU DIAS 14, Barcelos',41.54072,-8.617,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa URB MONTES MOURINHOS','parc_exterior','Armação de Pêra','Silves',NULL,'URB MONTES MOURINHOS B13, Armação de Pêra',37.1181,-8.37067,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa AV D JOÃO I','parc_exterior','Chaves','Chaves',NULL,'AV D JOÃO I 142, Chaves',41.73023,-7.46903,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Parque Verde do Nabão','parc_exterior','Ansião','Ansião',NULL,'R POMBAL, Ansião',39.91511,-8.43854,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('ténis de mesa','parc_exterior','Queluz','Sintra',NULL,'R JOSE AFONSO, Queluz',38.75795,-9.24881,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Parque da Vila','parc_exterior','Sever do Vouga','Sever do Vouga',NULL,'AV COMEND AUGUSTO MARTINS PEREIRA, Sever do Vouga',40.73372,-8.36958,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Campo dos Mártires da Pátria','parc_exterior','Lisboa','Lisbon',NULL,'CPO MARTIRES DA PATRIA 67, Lisboa',38.72266,-9.14012,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa R PABLO NERUDA','parc_exterior','Beja','Beja',NULL,'R PABLO NERUDA 3, Beja',38.01516,-7.87156,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Clube Ténis de Mesa de Oliveirinha','parc_exterior','Oliveirinha','Aveiro',NULL,'R CASA DO POVO 6, Oliveirinha',40.60178,-8.60586,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Escola Básica do 1º Ciclo e Jardim de Infância do Castêlo da Maia','parc_exterior','Santa Maria de Avioso','Maia',NULL,'R SERAFIM DA CRUZ 729, Santa Maria de Avioso',41.25931,-8.61371,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Ténis de mesa Escola Básica da Agrela e Vale do Leça','parc_exterior','Água Longa','Santo Tirso',NULL,'R LIBERDADE, Água Longa',41.26438,-8.4834,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Clube Ténis de Mesa de Lousada','parc_exterior','Lousada','Lousada',NULL,'Lousada',41.2852,-8.29195,1,true,false,NULL,NULL,ARRAY['exterior'],true,false)
) AS v(name,type,city,county,sector,address,lat,lng,tables_count,free_access,night_lighting,hours,description,tags,approved,verified)
JOIN cities c ON c.country_code='PT' AND c.name=v.city
ON CONFLICT (name,city_id) DO NOTHING;
COMMIT;
