-- SE — Sweden — 101 venues, 47 cities
-- Idempotent: safe to run multiple times. Source: OpenStreetMap via Overture Maps + GeoNames.
-- STAGED: cities active=false, expansion_status='community_review' (hidden in-app until activated — see DEPLOYMENT.md). Venues approved=true.
BEGIN;
INSERT INTO countries (code,name,active) VALUES ('SE','Sweden',true) ON CONFLICT (code) DO NOTHING;
INSERT INTO cities (name,country_code,country_name,admin_area,county,lat,lng,zoom,active,expansion_status) VALUES
  ('Älta','SE','Sweden','Stockholm','Nacka Kommun',59.26667,18.18333,12,false,'community_review'),
  ('Arlöv','SE','Sweden','Skåne','Burlövs Kommun',55.63248,13.07141,12,false,'community_review'),
  ('Bankeryd','SE','Sweden','Jönköping','Jönköpings Kommun',57.86021,14.124,12,false,'community_review'),
  ('Bergshamra','SE','Sweden','Stockholm','Solna Kommun',59.38083,18.03427,12,false,'community_review'),
  ('Braås','SE','Sweden','Kronoberg','Växjö Kommun',57.06667,15.05,12,false,'community_review'),
  ('Dals Långed','SE','Sweden','Västra Götaland','Bengtsfors Kommun',58.92555,12.30865,12,false,'community_review'),
  ('Enebyberg','SE','Sweden','Stockholm','Täby Kommun',59.43333,18.05,12,false,'community_review'),
  ('Eslöv','SE','Sweden','Skåne','Eslövs Kommun',55.83928,13.30393,12,false,'community_review'),
  ('Göteborg','SE','Sweden','Västra Götaland','Göteborgs stad',57.70716,11.96679,12,false,'community_review'),
  ('Gustavsberg','SE','Sweden','Stockholm','Värmdö Kommun',59.32684,18.38975,12,false,'community_review'),
  ('Halmstad','SE','Sweden','Halland','Halmstads Kommun',56.67446,12.85676,12,false,'community_review'),
  ('Hässleholm','SE','Sweden','Skåne','Hässleholms Kommun',56.15905,13.76638,12,false,'community_review'),
  ('Huddinge','SE','Sweden','Stockholm','Huddinge Kommun',59.23705,17.98192,12,false,'community_review'),
  ('Jakobsberg','SE','Sweden','Stockholm','Järfälla kommun',59.42268,17.83508,12,false,'community_review'),
  ('Jönköping','SE','Sweden','Jönköping','Jönköpings Kommun',57.78145,14.15618,12,false,'community_review'),
  ('Jordbro','SE','Sweden','Stockholm','Haninge Kommun',59.14972,18.11667,12,false,'community_review'),
  ('Karlsborg','SE','Sweden','Västra Götaland','Karlsborgs Kommun',58.53724,14.5047,12,false,'community_review'),
  ('Karlstad','SE','Sweden','Värmland','Karlstads Kommun',59.3793,13.50357,12,false,'community_review'),
  ('Katrineholm','SE','Sweden','Södermanland','Katrineholms Kommun',58.99587,16.20721,12,false,'community_review'),
  ('Kinna','SE','Sweden','Västra Götaland','Marks Kommun',57.50728,12.69463,12,false,'community_review'),
  ('Knivsta','SE','Sweden','Uppsala','Knivsta muncipality',59.72564,17.78753,12,false,'community_review'),
  ('Köping','SE','Sweden','Västmanland','Köpings Kommun',59.51404,15.99255,12,false,'community_review'),
  ('Linköping','SE','Sweden','Östergötland','Linköpings Kommun',58.41086,15.62157,12,false,'community_review'),
  ('Lomma','SE','Sweden','Skåne','Lomma Kommun',55.67244,13.06849,12,false,'community_review'),
  ('Ludvika','SE','Sweden','Dalarna','Ludvika Kommun',60.14959,15.18776,12,false,'community_review'),
  ('Lund','SE','Sweden','Skåne','Lunds Kommun',55.70584,13.19321,12,false,'community_review'),
  ('Malmslätt','SE','Sweden','Östergötland','Linköpings Kommun',58.41102,15.51647,12,false,'community_review'),
  ('Nacka','SE','Sweden','Stockholm','Nacka Kommun',59.31053,18.16372,12,false,'community_review'),
  ('Norrköping','SE','Sweden','Östergötland','Norrköpings Kommun',58.59419,16.1826,12,false,'community_review'),
  ('Nybro','SE','Sweden','Kalmar','Nybro Kommun',56.74461,15.90714,12,false,'community_review'),
  ('Rinkeby','SE','Sweden','Stockholm','Stockholms Kommun',59.38708,17.92754,12,false,'community_review'),
  ('Sävja','SE','Sweden','Uppsala','Uppsala Kommun',59.81872,17.69958,12,false,'community_review'),
  ('Sollentuna','SE','Sweden','Stockholm','Sollentuna Kommun',59.42804,17.95093,12,false,'community_review'),
  ('Staffanstorp','SE','Sweden','Skåne','Staffanstorps Kommun',55.64277,13.20638,12,false,'community_review'),
  ('Stångby','SE','Sweden','Skåne','Lunds Kommun',55.7503,13.19797,12,false,'community_review'),
  ('Stockholm','SE','Sweden','Stockholm','Stockholms Kommun',59.32938,18.06871,12,false,'community_review'),
  ('Sundbyberg','SE','Sweden','Stockholm','Sundbybergs Kommun',59.36128,17.97114,12,false,'community_review'),
  ('Svanesund','SE','Sweden','Västra Götaland','Orust',58.14292,11.81821,12,false,'community_review'),
  ('Tibro','SE','Sweden','Västra Götaland','Tibro Kommun',58.42453,14.16162,12,false,'community_review'),
  ('Trollhättan','SE','Sweden','Västra Götaland','Trollhättan',58.28365,12.28864,12,false,'community_review'),
  ('Tumba','SE','Sweden','Stockholm','Botkyrka Kommun',59.19858,17.83317,12,false,'community_review'),
  ('Uddevalla','SE','Sweden','Västra Götaland','Uddevalla Kommun',58.34784,11.9424,12,false,'community_review'),
  ('Ulricehamn','SE','Sweden','Västra Götaland','Ulricehamns Kommun',57.79159,13.41422,12,false,'community_review'),
  ('Umeå','SE','Sweden','Västerbotten','Umeå Kommun',63.82842,20.25972,12,false,'community_review'),
  ('Uppsala','SE','Sweden','Uppsala','Uppsala Kommun',59.85882,17.63889,12,false,'community_review'),
  ('Västerås','SE','Sweden','Västmanland','Västerås',59.61617,16.55276,12,false,'community_review'),
  ('Vikingstad','SE','Sweden','Östergötland','Linköpings Kommun',58.38304,15.43201,12,false,'community_review')
ON CONFLICT (country_code,name) DO NOTHING;
INSERT INTO venues (name,type,city,city_id,county,sector,address,lat,lng,tables_count,free_access,night_lighting,hours,description,tags,approved,verified,submitted_by)
SELECT v.name,v.type,v.city,c.id,v.county::text,v.sector::text,v.address,v.lat::double precision,v.lng::double precision,v.tables_count::int,v.free_access::boolean,v.night_lighting::boolean,v.hours::text,v.description::text,v.tags::text[],v.approved::boolean,v.verified::boolean,NULL
FROM (VALUES
  ('Bordtennis Beckombergaskolan','parc_exterior','Rinkeby','Stockholms Kommun',NULL,'Beckombergaskolan, Rinkeby',59.36049,17.90007,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Årstadalsskolan','parc_exterior','Stockholm','Stockholms Kommun',NULL,'Årstadalsskolan, Stockholm',59.30338,18.03104,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Stordammens skola','parc_exterior','Sävja','Uppsala Kommun',NULL,'Stordammens skola, Sävja',59.81123,17.7021,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Tivedens nationalpark','parc_exterior','Karlsborg','Karlsborgs Kommun',NULL,'Tivedens nationalpark, Karlsborg',58.71543,14.59226,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Humlans utepingis','parc_exterior','Stockholm','Stockholms Kommun',NULL,'Humlegården, Stockholm',59.34011,18.07067,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Zachrisbergsparken','parc_exterior','Stockholm','Stockholms Kommun',NULL,'Zachrisbergsparken, Stockholm',59.30185,18.02895,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Zachrisbergsparken (2)','parc_exterior','Stockholm','Stockholms Kommun',NULL,'Zachrisbergsparken, Stockholm',59.30182,18.029,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Solvallsparken','parc_exterior','Uppsala','Uppsala Kommun',NULL,'Solvallsparken, Uppsala',59.83057,17.63254,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Fagerlidsparken','parc_exterior','Huddinge','Huddinge Kommun',NULL,'Fagerlidsparken, Huddinge',59.25281,18.07843,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Gjuteriparken','parc_exterior','Uppsala','Uppsala Kommun',NULL,'Gjuteriparken, Uppsala',59.86631,17.60612,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Bäcken','parc_exterior','Linköping','Linköpings Kommun',NULL,'Bäcken, Linköping',58.39119,15.64188,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Skälby','parc_exterior','Sollentuna','Sollentuna Kommun',NULL,'Skälby, Sollentuna',59.44189,17.93935,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis MOMOS Camping Orrefors','parc_exterior','Nybro','Nybro Kommun',NULL,'MOMOS Camping Orrefors, Nybro',56.84451,15.70893,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Bergslagsparken','parc_exterior','Västerås','Västerås',NULL,'Bergslagsparken, Västerås',59.62621,16.55503,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Raoul Wallenbergskolan','parc_exterior','Rinkeby','Stockholms Kommun',NULL,'Raoul Wallenbergskolan, Rinkeby',59.35677,17.90099,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Tumba Gymnasium','parc_exterior','Tumba','Botkyrka Kommun',NULL,'Tumba Gymnasium, Tumba',59.20253,17.83604,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Tumba Gymnasium (2)','parc_exterior','Tumba','Botkyrka Kommun',NULL,'Tumba Gymnasium, Tumba',59.20253,17.83611,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Tumba Gymnasium (3)','parc_exterior','Tumba','Botkyrka Kommun',NULL,'Tumba Gymnasium, Tumba',59.20253,17.83618,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Lilla Alby skola','parc_exterior','Sundbyberg','Sundbybergs Kommun',NULL,'Lilla Alby skola, Sundbyberg',59.35798,17.96873,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Lilla Alby skola (2)','parc_exterior','Sundbyberg','Sundbybergs Kommun',NULL,'Lilla Alby skola, Sundbyberg',59.35801,17.96868,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Västra Socionomparken','parc_exterior','Umeå','Umeå Kommun',NULL,'Västra Socionomparken, Umeå',63.80946,20.31004,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Bandhagens skola','parc_exterior','Huddinge','Huddinge Kommun',NULL,'Bandhagens skola, Huddinge',59.26478,18.05128,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Stamparkens parklek','parc_exterior','Stockholm','Stockholms Kommun',NULL,'Stamparkens parklek, Stockholm',59.28486,18.03868,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Norrstrandsskolan','parc_exterior','Karlstad','Karlstads Kommun',NULL,'Norrstrandsskolan, Karlstad',59.38978,13.52481,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Elsa Eschelssons park','parc_exterior','Uppsala','Uppsala Kommun',NULL,'Elsa Eschelssons park, Uppsala',59.8337,17.63393,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Tureborgcastles Gångbana','parc_exterior','Uddevalla','Uddevalla Kommun',NULL,'Tureborgcastles Gångbana, Uddevalla',58.34304,11.95008,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Simklubben Laxen','parc_exterior','Halmstad','Halmstads Kommun',NULL,'Simklubben Laxen, Halmstad',56.67389,12.88864,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Simklubben Laxen (2)','parc_exterior','Halmstad','Halmstads Kommun',NULL,'Simklubben Laxen, Halmstad',56.67385,12.88865,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Björnkärrsgatan 6','parc_exterior','Malmslätt','Linköpings Kommun',NULL,'Björnkärrsgatan 6, Malmslätt',58.41053,15.56275,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Pingis','parc_exterior','Stockholm','Stockholms Kommun',NULL,'Humlegården, Stockholm',59.34035,18.07445,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Lilla Blecktornsparken','parc_exterior','Stockholm','Stockholms Kommun',NULL,'Lilla Blecktornsparken, Stockholm',59.30916,18.08608,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Lilla Blecktornsparken (2)','parc_exterior','Stockholm','Stockholms Kommun',NULL,'Lilla Blecktornsparken, Stockholm',59.30913,18.08617,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Axel Landquists Park','parc_exterior','Stockholm','Stockholms Kommun',NULL,'Axel Landquists Park, Stockholm',59.31403,18.08089,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Stora Blecktornsparken','parc_exterior','Stockholm','Stockholms Kommun',NULL,'Stora Blecktornsparken, Stockholm',59.30711,18.08722,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Sockerskålen','parc_exterior','Stockholm','Stockholms Kommun',NULL,'Sockerskålen, Stockholm',59.3089,18.04944,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Vasaparkens parklek','parc_exterior','Stockholm','Stockholms Kommun',NULL,'Vasaparkens parklek, Stockholm',59.33968,18.04151,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Junotäppan','parc_exterior','Stockholm','Stockholms Kommun',NULL,'Junotäppan, Stockholm',59.32354,18.07193,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Sankt Paulsparken','parc_exterior','Stockholm','Stockholms Kommun',NULL,'Sankt Paulsparken, Stockholm',59.31765,18.06077,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Vårflodsparken','parc_exterior','Stockholm','Stockholms Kommun',NULL,'Vårflodsparken, Stockholm',59.286,18.06068,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Vårflodsparken (2)','parc_exterior','Stockholm','Stockholms Kommun',NULL,'Vårflodsparken, Stockholm',59.28599,18.06074,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Skånegläntans parklek','parc_exterior','Stockholm','Stockholms Kommun',NULL,'Skånegläntans parklek, Stockholm',59.31134,18.07041,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Magnus Ladulås plats','parc_exterior','Jönköping','Jönköpings Kommun',NULL,'Magnus Ladulås plats, Jönköping',57.78135,14.1679,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Byaparken','parc_exterior','Stångby','Lunds Kommun',NULL,'Byaparken, Stångby',55.75197,13.19668,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Borgarparken','parc_exterior','Lund','Lunds Kommun',NULL,'Borgarparken, Lund',55.72353,13.2086,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Borgarparken (2)','parc_exterior','Lund','Lunds Kommun',NULL,'Borgarparken, Lund',55.72351,13.2086,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Slottsskogsvallens entrépark','parc_exterior','Göteborg','Göteborgs stad',NULL,'Slottsskogsvallens entrépark, Göteborg',57.67914,11.94055,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Slottsskogsvallens entrépark (2)','parc_exterior','Göteborg','Göteborgs stad',NULL,'Slottsskogsvallens entrépark, Göteborg',57.67911,11.94071,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Svanesunds GIF Gymnastik & Fitness','parc_exterior','Svanesund','Orust',NULL,'Svanesunds GIF Gymnastik & Fitness, Svanesund',58.14406,11.81082,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Balderskolan','parc_exterior','Staffanstorp','Staffanstorps Kommun',NULL,'Balderskolan, Staffanstorp',55.64425,13.21298,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Juryn','parc_exterior','Stångby','Lunds Kommun',NULL,'Juryn, Stångby',55.72851,13.21228,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Lilla Bantorget','parc_exterior','Stockholm','Stockholms Kommun',NULL,'Lilla Bantorget, Stockholm',59.33517,18.0517,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Bulltofta rekreationsområde','parc_exterior','Arlöv','Burlövs Kommun',NULL,'Bulltofta rekreationsområde, Arlöv',55.59809,13.06527,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Bulltofta rekreationsområde (2)','parc_exterior','Arlöv','Burlövs Kommun',NULL,'Bulltofta rekreationsområde, Arlöv',55.59812,13.0655,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Nobelparken','parc_exterior','Lund','Lunds Kommun',NULL,'Nobelparken, Lund',55.72164,13.23475,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Nobelparken (2)','parc_exterior','Lund','Lunds Kommun',NULL,'Nobelparken, Lund',55.72158,13.23476,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Pilvingen','parc_exterior','Älta','Nacka Kommun',NULL,'Pilvingen, Älta',59.26718,18.12858,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Sätraplan','parc_exterior','Kinna','Marks Kommun',NULL,'Sätraplan, Kinna',57.50716,12.69416,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Malmparken','parc_exterior','Sollentuna','Sollentuna Kommun',NULL,'Malmparken, Sollentuna',59.42708,17.94715,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Malmparken (2)','parc_exterior','Sollentuna','Sollentuna Kommun',NULL,'Malmparken, Sollentuna',59.427,17.94724,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Adolfsbergsskolan','parc_exterior','Sundbyberg','Sundbybergs Kommun',NULL,'Adolfsbergsskolan, Sundbyberg',59.35807,17.95377,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Ranka','parc_exterior','Gustavsberg','Värmdö Kommun',NULL,'Ranka, Gustavsberg',59.32065,18.3864,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Soltrappan','parc_exterior','Lomma','Lomma Kommun',NULL,'Soltrappan, Lomma',55.67685,13.06556,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Soltrappan (2)','parc_exterior','Lomma','Lomma Kommun',NULL,'Soltrappan, Lomma',55.67686,13.06546,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Prästängsskolan','parc_exterior','Stångby','Lunds Kommun',NULL,'Prästängsskolan, Stångby',55.75488,13.19516,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Stensmedjan','parc_exterior','Trollhättan','Trollhättan',NULL,'Stensmedjan, Trollhättan',58.2797,12.28778,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Rosendals skola','parc_exterior','Uppsala','Uppsala Kommun',NULL,'Rosendals skola, Uppsala',59.83512,17.62869,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Rosendals skola (2)','parc_exterior','Uppsala','Uppsala Kommun',NULL,'Rosendals skola, Uppsala',59.83512,17.62879,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Ljungdalaskolan','parc_exterior','Hässleholm','Hässleholms Kommun',NULL,'Ljungdalaskolan, Hässleholm',56.17202,13.79471,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Kattegattgymnasiet','parc_exterior','Halmstad','Halmstads Kommun',NULL,'Kattegattgymnasiet, Halmstad',56.66831,12.84735,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Kattegattgymnasiet (2)','parc_exterior','Halmstad','Halmstads Kommun',NULL,'Kattegattgymnasiet, Halmstad',56.66832,12.84725,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Habo Camping & Stugby','parc_exterior','Bankeryd','Jönköpings Kommun',NULL,'Habo Camping & Stugby, Bankeryd',57.87822,14.11042,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Habo Camping & Stugby (2)','parc_exterior','Bankeryd','Jönköpings Kommun',NULL,'Habo Camping & Stugby, Bankeryd',57.87822,14.11042,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Skogsborgsskolan','parc_exterior','Katrineholm','Katrineholms Kommun',NULL,'Skogsborgsskolan, Katrineholm',58.98743,16.20021,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Skogsborgsskolan (2)','parc_exterior','Katrineholm','Katrineholms Kommun',NULL,'Skogsborgsskolan, Katrineholm',58.98735,16.20017,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Skogsborgsskolan (3)','parc_exterior','Katrineholm','Katrineholms Kommun',NULL,'Skogsborgsskolan, Katrineholm',58.98679,16.19948,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Stenbocksskolan','parc_exterior','Ulricehamn','Ulricehamns Kommun',NULL,'Stenbocksskolan, Ulricehamn',57.78922,13.41742,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Olinsgymnasiet Tibro','parc_exterior','Tibro','Tibro Kommun',NULL,'Olinsgymnasiet Tibro, Tibro',58.41886,14.16763,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Kajvägen 13','parc_exterior','Ludvika','Ludvika Kommun',NULL,'Kajvägen 13, Ludvika',60.15118,15.18186,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Fengersfors IK','parc_exterior','Dals Långed','Bengtsfors Kommun',NULL,'Fengersfors IK, Dals Långed',58.99678,12.46225,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Hellas Tennis parkering','parc_exterior','Stockholm','Stockholms Kommun',NULL,'Hellas Tennis parkering, Stockholm',59.30503,18.07134,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Boulebarstore','parc_exterior','Stockholm','Stockholms Kommun',NULL,'Boulebarstore, Stockholm',59.31189,18.02645,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Aimo Park','parc_exterior','Uppsala','Uppsala Kommun',NULL,'Aimo Park, Uppsala',59.84772,17.63346,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Norco-hallen','parc_exterior','Norrköping','Norrköpings Kommun',NULL,'IF Norcopensarna Fridtuna, Norrköping',58.5789,16.12376,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Köpings Arena','parc_exterior','Köping','Köpings Kommun',NULL,'Svenska Bordtennisförbundet, Köping',59.50816,15.98542,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Mosstorpsparken','parc_exterior','Enebyberg','Täby Kommun',NULL,'Mosstorpsparken, Enebyberg',59.43188,18.05603,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Restaurang Professorn - Restaurang/Bar Universitetet','parc_exterior','Bergshamra','Solna Kommun',NULL,'Restaurang Professorn - Restaurang/Bar Universitetet, Bergshamra',59.37002,18.06309,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Björkhallen','parc_exterior','Knivsta','Knivsta muncipality',NULL,'Knivsta',59.70909,17.7313,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Sjögemagasinet','parc_exterior','Vikingstad','Linköpings Kommun',NULL,'Vikingstad',58.36732,15.37022,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Innovitaskolan Enskede','parc_exterior','Stockholm','Stockholms Kommun',NULL,'Innovitaskolan Enskede, Stockholm',59.28582,18.08431,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Vibyskolan','parc_exterior','Sollentuna','Sollentuna Kommun',NULL,'Vibyskolan, Sollentuna',59.45812,17.8906,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Vibyskolan (2)','parc_exterior','Sollentuna','Sollentuna Kommun',NULL,'Vibyskolan, Sollentuna',59.45818,17.89061,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Ektorpsringen','parc_exterior','Norrköping','Norrköpings Kommun',NULL,'Ektorpsringen, Norrköping',58.57794,16.17005,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Åbyparken','parc_exterior','Jordbro','Haninge Kommun',NULL,'Åbyparken, Jordbro',59.12713,18.10494,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Hammarbyskolan södra','parc_exterior','Nacka','Nacka Kommun',NULL,'Hammarbyskolan södra, Nacka',59.29076,18.0988,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Hammarbyskolan södra (2)','parc_exterior','Nacka','Nacka Kommun',NULL,'Hammarbyskolan södra, Nacka',59.29071,18.09849,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Stora torg','parc_exterior','Eslöv','Eslövs Kommun',NULL,'Stora torg, Eslöv',55.83878,13.30392,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Plikta','parc_exterior','Göteborg','Göteborgs stad',NULL,'Plikta, Göteborg',57.68926,11.9459,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis Edsbergsskolan','parc_exterior','Sollentuna','Sollentuna Kommun',NULL,'Edsbergsskolan, Sollentuna',59.44456,17.96478,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Dina','parc_exterior','Braås','Växjö Kommun',NULL,'Dina Arena - Padel i Klavreström, Braås',57.13671,15.13392,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis APCOA','parc_exterior','Jakobsberg','Järfälla kommun',NULL,'APCOA, Jakobsberg',59.42166,17.83235,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Bordtennis APCOA (2)','parc_exterior','Jakobsberg','Järfälla kommun',NULL,'APCOA, Jakobsberg',59.42174,17.83244,1,true,false,NULL,NULL,ARRAY['exterior'],true,false)
) AS v(name,type,city,county,sector,address,lat,lng,tables_count,free_access,night_lighting,hours,description,tags,approved,verified)
JOIN cities c ON c.country_code='SE' AND c.name=v.city
ON CONFLICT (name,city_id) DO NOTHING;
COMMIT;
