-- UA — Ukraine — 161 venues, 54 cities
-- Idempotent: safe to run multiple times. Source: OpenStreetMap via Overture Maps + GeoNames.
-- STAGED: cities active=false, expansion_status='community_review' (hidden in-app until activated — see DEPLOYMENT.md). Venues approved=true.
BEGIN;
INSERT INTO countries (code,name,active) VALUES ('UA','Ukraine',true) ON CONFLICT (code) DO NOTHING;
INSERT INTO cities (name,country_code,country_name,admin_area,county,lat,lng,zoom,active,expansion_status) VALUES
  ('Berkovets','UA','Ukraine','Kyiv City','Sviatoshynskyi Raion',50.49449,30.37008,12,false,'community_review'),
  ('Bezliudivka','UA','Ukraine','Kharkiv','Kharkiv Raion',49.86787,36.28347,12,false,'community_review'),
  ('Bortnychi','UA','Ukraine','Kyiv City','Darnytsia Raion',50.38489,30.69542,12,false,'community_review'),
  ('Boryspil','UA','Ukraine','Kyiv Oblast','Borispol’skiy Rayon',50.35269,30.95501,12,false,'community_review'),
  ('Brovary','UA','Ukraine','Kyiv Oblast','Brovary Raion',50.51809,30.80671,12,false,'community_review'),
  ('Bykivnia','UA','Ukraine','Kyiv City','Desnianskyi Raion',50.47292,30.67139,12,false,'community_review'),
  ('Cherkasy','UA','Ukraine','Cherkasy','Cherkasy Raion',49.44452,32.05738,12,false,'community_review'),
  ('Desna','UA','Ukraine','Vinnytsia','Vinnytsya Raion',49.28166,28.54034,12,false,'community_review'),
  ('Donetsk','UA','Ukraine','Donetsk','Donetsk Raion',48.023,37.80224,12,false,'community_review'),
  ('Dubliany','UA','Ukraine','Lviv','Lvivskyi Raion',49.90411,24.08637,12,false,'community_review'),
  ('Feodosiya','UA','Ukraine','Crimea','Feodosiya Raion',45.03199,35.38153,12,false,'community_review'),
  ('Ivano-Frankivsk','UA','Ukraine','Ivano-Frankivsk','Ivano-Frankivskyi Raion',48.92312,24.71248,12,false,'community_review'),
  ('Kharkiv','UA','Ukraine','Kharkiv','Kharkiv Raion',49.98177,36.25475,12,false,'community_review'),
  ('Kopychyntsi','UA','Ukraine','Ternopil','Chortkiv Raion',49.103,25.91164,12,false,'community_review'),
  ('Kramatorsk','UA','Ukraine','Donetsk','Kramatorskyi Raion',48.73106,37.56779,12,false,'community_review'),
  ('Kropyvnytskyi','UA','Ukraine','Kirovohrad','Kropyvnytskyy Raion',48.50834,32.26618,12,false,'community_review'),
  ('Kryvyy Rih','UA','Ukraine','Dnipropetrovsk','Kryvyy Rih Raion',47.90572,33.39404,12,false,'community_review'),
  ('Kulynychi','UA','Ukraine','Kharkiv','Kharkiv Raion',49.98178,36.38283,12,false,'community_review'),
  ('Kyiv','UA','Ukraine','Kyiv City','Kyiv City',50.45466,30.5238,12,false,'community_review'),
  ('Lviv','UA','Ukraine','Lviv','Lvivskyi Raion',49.83826,24.02324,12,false,'community_review'),
  ('Lymanka','UA','Ukraine','Odesa','Odeskyi Raion',46.38564,30.67736,12,false,'community_review'),
  ('Mala Danylivka','UA','Ukraine','Kharkiv','Kharkiv Raion',50.06198,36.16787,12,false,'community_review'),
  ('Motyzhyn','UA','Ukraine','Kyiv Oblast','Buchanskyi Raion',50.38776,29.92359,12,false,'community_review'),
  ('Mynkivtsi','UA','Ukraine','Khmelnytskyi','Kamyanets-Podilskyy Raion',48.85358,27.10879,12,false,'community_review'),
  ('Novi Kodaky','UA','Ukraine','Dnipropetrovsk','Dnipro rural raion',48.48667,34.95639,12,false,'community_review'),
  ('Poltava','UA','Ukraine','Poltava','Poltava Raion',49.58925,34.55367,12,false,'community_review'),
  ('Pustomyty','UA','Ukraine','Lviv','Lvivskyi Raion',49.71687,23.90677,12,false,'community_review'),
  ('Rozsoshentsi','UA','Ukraine','Poltava','Poltava Raion',49.54094,34.50565,12,false,'community_review'),
  ('Saperna Slobidka','UA','Ukraine','Kyiv City','Holosiiv Raion',50.40077,30.5349,12,false,'community_review'),
  ('Sevastopol','UA','Ukraine','Sevastopol City','Sevastopol City',44.60795,33.52134,12,false,'community_review'),
  ('Shevchenka','UA','Ukraine','Kyiv City','Podilskyi Raion',50.51891,30.4352,12,false,'community_review'),
  ('Shyroke','UA','Ukraine','Donetsk','Donetsk Raion',47.95735,38.2316,12,false,'community_review'),
  ('Siedove','UA','Ukraine','Donetsk','Kalmiuskyi Raion',47.0787,38.15368,12,false,'community_review'),
  ('Simferopol','UA','Ukraine','Crimea','Simferopol Raion',44.95719,34.11079,12,false,'community_review'),
  ('Siverskodonetsk','UA','Ukraine','Luhansk','Sievierodonetskyi Raion',48.94628,38.48624,12,false,'community_review'),
  ('Sknyliv','UA','Ukraine','Lviv','Lvivskyi Raion',49.8,23.95,12,false,'community_review'),
  ('Slavuta','UA','Ukraine','Khmelnytskyi','Shepetivka Raion',50.29609,26.86613,12,false,'community_review'),
  ('Sokilnyky','UA','Ukraine','Lviv','Lvivskyi Raion',49.7816,23.98152,12,false,'community_review'),
  ('Solnechnogorskoye','UA','Ukraine','Crimea','Miskyi okruh Yalta',44.74722,34.53999,12,false,'community_review'),
  ('Stayky','UA','Ukraine','Kyiv Oblast','Obukhiv Raion',50.07818,30.9038,12,false,'community_review'),
  ('Stryi','UA','Ukraine','Lviv','Stryys’ka Mis’krada',49.26103,23.84845,12,false,'community_review'),
  ('Sumy','UA','Ukraine','Sumy','Sumskyi Raion',50.91741,34.79906,12,false,'community_review'),
  ('Trostyanets','UA','Ukraine','Sumy','Okhtyrskiy Rayon',50.48478,34.96567,12,false,'community_review'),
  ('Tsarychanka','UA','Ukraine','Dnipropetrovsk','Dnipro rural raion',48.94186,34.48601,12,false,'community_review'),
  ('Vasylkiv','UA','Ukraine','Kyiv Oblast','Obukhiv Raion',50.18693,30.31346,12,false,'community_review'),
  ('Vinnytsya','UA','Ukraine','Vinnytsia','Vinnytsya Raion',49.2322,28.46871,12,false,'community_review'),
  ('Vorzel','UA','Ukraine','Kyiv Oblast','Buchanskyi Raion',50.5444,30.15305,12,false,'community_review'),
  ('Vyshhorod','UA','Ukraine','Kyiv Oblast','Vyshgorodskiy Rayon',50.58476,30.4898,12,false,'community_review'),
  ('Vysokyi','UA','Ukraine','Kharkiv','Kharkiv Raion',49.89419,36.12384,12,false,'community_review'),
  ('Zaporizhzhya','UA','Ukraine','Zaporizhzhia','Zaporizhzhya Raion',47.85167,35.11714,12,false,'community_review'),
  ('Zatoka','UA','Ukraine','Odesa','Bilhorod-Dnistrovskyy Raion',46.07016,30.46265,12,false,'community_review'),
  ('Zdorivka','UA','Ukraine','Kyiv Oblast','Obukhiv Raion',50.19857,30.25303,12,false,'community_review'),
  ('Zhulyany','UA','Ukraine','Kyiv City','Solomianka Rayon',50.39428,30.44057,12,false,'community_review'),
  ('Zubra','UA','Ukraine','Lviv','Lvivskyi Raion',49.76397,24.05079,12,false,'community_review')
ON CONFLICT (country_code,name) DO NOTHING;
INSERT INTO venues (name,type,city,city_id,county,sector,address,lat,lng,tables_count,free_access,night_lighting,hours,description,tags,approved,verified,submitted_by)
SELECT v.name,v.type,v.city,c.id,v.county::text,v.sector::text,v.address,v.lat::double precision,v.lng::double precision,v.tables_count::int,v.free_access::boolean,v.night_lighting::boolean,v.hours::text,v.description::text,v.tags::text[],v.approved::boolean,v.verified::boolean,NULL
FROM (VALUES
  ('Настільний теніс Пансіонат "Металург"','parc_exterior','Siedove','Kalmiuskyi Raion',NULL,'Пансіонат "Металург", Siedove',47.09143,38.18035,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Шпиль','parc_exterior','Lymanka','Odeskyi Raion',NULL,'Ділянка № 3 КП ЖКС "Чорноморський", Lymanka',46.39136,30.72091,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Русанівська набережна','parc_exterior','Kyiv','Kyiv City',NULL,'Русанівська набережна, Kyiv',50.43971,30.59052,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс','parc_exterior','Mynkivtsi','Kamyanets-Podilskyy Raion',NULL,'Миньковецька ЗОШ І-ІІІ ст., Mynkivtsi',48.85015,27.10924,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Тренировочная площадка для собак','parc_exterior','Bortnychi','Darnytsia Raion',NULL,'Тренировочная площадка для собак, Bortnychi',50.41476,30.63783,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Squatland','parc_exterior','Bortnychi','Darnytsia Raion',NULL,'Squatland, Bortnychi',50.42018,30.64208,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Дельфин-Аква (2)','parc_exterior','Bykivnia','Desnianskyi Raion',NULL,'Дельфин-Аква, Bykivnia',50.45658,30.63106,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Теніс Dream','parc_exterior','Shevchenka','Podilskyi Raion',NULL,'Arena Store, Shevchenka',50.50792,30.4982,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Допомога','parc_exterior','Stryi','Stryys’ka Mis’krada',NULL,'FitCurves, Stryi',49.26057,23.85976,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс','parc_exterior','Vinnytsya','Vinnytsya Raion',NULL,'Vinnytsya',49.21527,28.43752,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Сквер "Юність"','parc_exterior','Brovary','Brovary Raion',NULL,'Сквер "Юність", Brovary',50.5207,30.79613,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Голосіївський парк імені Максима Рильського','parc_exterior','Saperna Slobidka','Holosiiv Raion',NULL,'Голосіївський парк імені Максима Рильського, Saperna Slobidka',50.38754,30.50035,1,true,false,'24/7',NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Мікрорайон 338','parc_exterior','Mala Danylivka','Kharkiv Raion',NULL,'Мікрорайон 338, Mala Danylivka',50.06069,36.20773,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Мікрорайон 338 (2)','parc_exterior','Mala Danylivka','Kharkiv Raion',NULL,'Мікрорайон 338, Mala Danylivka',50.06159,36.20836,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Парк XIX ст.','parc_exterior','Pustomyty','Lvivskyi Raion',NULL,'Парк XIX ст., Pustomyty',49.71703,23.90385,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Парк "Учкуевка"','parc_exterior','Sevastopol','Sevastopol City',NULL,'Парк "Учкуевка", Sevastopol',44.64261,33.54081,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Теннис','parc_exterior','Kropyvnytskyi','Kropyvnytskyy Raion',NULL,'One Way Kropyvnytskyi, Kropyvnytskyi',48.50844,32.26431,1,true,false,'10:00-22:00',NULL,ARRAY['exterior'],true,false),
  ('Мастер','parc_exterior','Kyiv','Kyiv City',NULL,'Rentor, Kyiv',50.44513,30.49319,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс "СК "Ринг"/Ring SC"','parc_exterior','Ivano-Frankivsk','Ivano-Frankivskyi Raion',NULL,'"СК "Ринг"/Ring SC", Ivano-Frankivsk',48.94324,24.74685,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Парк Акважур','parc_exterior','Kharkiv','Kharkiv Raion',NULL,'Парк Акважур, Kharkiv',50.02449,36.31526,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Цистерна','parc_exterior','Lviv','Lvivskyi Raion',NULL,'Цистерна, Lviv',49.81721,24.00198,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Цистерна (2)','parc_exterior','Lviv','Lvivskyi Raion',NULL,'Цистерна, Lviv',49.81723,24.00191,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Сквер ім. генерала М.Шаповала','parc_exterior','Kyiv','Kyiv City',NULL,'Сквер ім. генерала М.Шаповала, Kyiv',50.43775,30.47702,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Школа Бойового Гопака Шаблезуб','parc_exterior','Sokilnyky','Lvivskyi Raion',NULL,'Школа Бойового Гопака Шаблезуб, Sokilnyky',49.79708,24.02011,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Золота ракетка','parc_exterior','Slavuta','Shepetivka Raion',NULL,'Slavuta',50.2938,26.87081,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс UNIT.City','parc_exterior','Kyiv','Kyiv City',NULL,'UNIT.City, Kyiv',50.46878,30.46155,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс UNIT.City (2)','parc_exterior','Kyiv','Kyiv City',NULL,'UNIT.City, Kyiv',50.46877,30.46153,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Гімназія "Міленіум" № 318','parc_exterior','Zhulyany','Solomianka Rayon',NULL,'Гімназія "Міленіум" № 318, Zhulyany',50.41489,30.46773,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс ЖК "The Lakes"','parc_exterior','Saperna Slobidka','Holosiiv Raion',NULL,'ЖК "The Lakes", Saperna Slobidka',50.40954,30.50626,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс ЖК Паркове місто','parc_exterior','Shevchenka','Podilskyi Raion',NULL,'ЖК Паркове місто, Shevchenka',50.51197,30.44698,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс ЖК Паркове місто (2)','parc_exterior','Shevchenka','Podilskyi Raion',NULL,'ЖК Паркове місто, Shevchenka',50.51197,30.44702,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Левандівський парк','parc_exterior','Lviv','Lvivskyi Raion',NULL,'Левандівський парк, Lviv',49.84554,23.97836,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Міський парк','parc_exterior','Kopychyntsi','Chortkiv Raion',NULL,'Міський парк, Kopychyntsi',49.10542,25.90304,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Міський парк (2)','parc_exterior','Kopychyntsi','Chortkiv Raion',NULL,'Міський парк, Kopychyntsi',49.1054,25.90307,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Блік','parc_exterior','Zatoka','Bilhorod-Dnistrovskyy Raion',NULL,'Блік, Zatoka',46.08141,30.47968,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс ЖК «Квіти Львова»','parc_exterior','Zubra','Lvivskyi Raion',NULL,'ЖК «Квіти Львова», Zubra',49.7862,24.02437,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Хотянівка','parc_exterior','Vyshhorod','Vyshgorodskiy Rayon',NULL,'Хотянівка, Vyshhorod',50.60157,30.56844,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс','parc_exterior','Motyzhyn','Buchanskyi Raion',NULL,'Етнографічний комплекс «Українське село», Motyzhyn',50.44521,30.04601,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Visa Up','parc_exterior','Sknyliv','Lvivskyi Raion',NULL,'Visa Up, Sknyliv',49.80434,23.9828,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Скверик біля костелу Ольги та Єлизавети','parc_exterior','Lviv','Lvivskyi Raion',NULL,'Скверик біля костелу Ольги та Єлизавети, Lviv',49.83616,24.00533,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Зупинка «Хімічна»','parc_exterior','Lviv','Lvivskyi Raion',NULL,'Зупинка «Хімічна», Lviv',49.85485,24.02147,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Visa Up (2)','parc_exterior','Sknyliv','Lvivskyi Raion',NULL,'Visa Up, Sknyliv',49.8059,23.98379,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Зупинка  Гординських','parc_exterior','Lviv','Lvivskyi Raion',NULL,'Зупинка  Гординських, Lviv',49.82566,23.99731,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Клуб настільного тенісу','parc_exterior','Zhulyany','Solomianka Rayon',NULL,'Zhulyany',50.42455,30.47737,1,true,false,'Mo-Fr 08:00-22:00; Sa 13:00-21:00; Su 08:00-21:00',NULL,ARRAY['exterior'],true,false),
  ('Table tennis','parc_exterior','Vorzel','Buchanskyi Raion',NULL,'Vorzel',50.53937,30.15455,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Стадіон Лісотехнічного університету','parc_exterior','Lviv','Lvivskyi Raion',NULL,'Стадіон Лісотехнічного університету, Lviv',49.8247,24.00483,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Ліцей №11','parc_exterior','Ivano-Frankivsk','Ivano-Frankivskyi Raion',NULL,'Ліцей №11, Ivano-Frankivsk',48.91996,24.71793,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Парк "Хімік"','parc_exterior','Vinnytsya','Vinnytsya Raion',NULL,'Парк "Хімік", Vinnytsya',49.24429,28.50252,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Вуличний стіл для гри в настільний теніс пінг-понг','parc_exterior','Saperna Slobidka','Holosiiv Raion',NULL,'ЖК Seven, Saperna Slobidka',50.39874,30.61226,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Парк ім. Маяковського','parc_exterior','Kulynychi','Kharkiv Raion',NULL,'Парк ім. Маяковського, Kulynychi',49.95309,36.37211,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Комсомольский парк','parc_exterior','Feodosiya','Feodosiya Raion',NULL,'Комсомольский парк, Feodosiya',45.04639,35.38277,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс ЖК Вишеньки','parc_exterior','Ivano-Frankivsk','Ivano-Frankivskyi Raion',NULL,'ЖК Вишеньки, Ivano-Frankivsk',48.93194,24.70188,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Алея Каштанів','parc_exterior','Sokilnyky','Lvivskyi Raion',NULL,'Алея Каштанів, Sokilnyky',49.80187,23.98913,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс СВіТ - Спорядження Військове і Туристичне','parc_exterior','Sknyliv','Lvivskyi Raion',NULL,'СВіТ - Спорядження Військове і Туристичне, Sknyliv',49.81222,23.97938,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Клуб настільного тенісу QUIKS','parc_exterior','Saperna Slobidka','Holosiiv Raion',NULL,'Совки, Saperna Slobidka',50.4071,30.49041,1,false,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Проект Сад','parc_exterior','Zhulyany','Solomianka Rayon',NULL,'Проект Сад, Zhulyany',50.37847,30.47364,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Солом''янський ладшафтний парк (2)','parc_exterior','Kyiv','Kyiv City',NULL,'Солом''янський ладшафтний парк, Kyiv',50.42473,30.48522,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Школа №13','parc_exterior','Cherkasy','Cherkasy Raion',NULL,'Школа №13, Cherkasy',49.40862,32.0932,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Школа №13 (2)','parc_exterior','Cherkasy','Cherkasy Raion',NULL,'Школа №13, Cherkasy',49.40855,32.09312,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Школа №13 (3)','parc_exterior','Cherkasy','Cherkasy Raion',NULL,'Школа №13, Cherkasy',49.40848,32.09304,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Школа №13 (4)','parc_exterior','Cherkasy','Cherkasy Raion',NULL,'Школа №13, Cherkasy',49.40842,32.09295,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс ЖК «Family Park»','parc_exterior','Rozsoshentsi','Poltava Raion',NULL,'ЖК «Family Park», Rozsoshentsi',49.54806,34.51522,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс ЖК «Family Park» (2)','parc_exterior','Rozsoshentsi','Poltava Raion',NULL,'ЖК «Family Park», Rozsoshentsi',49.54809,34.51525,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Школа №5','parc_exterior','Novi Kodaky','Dnipro rural raion',NULL,'Школа №5, Novi Kodaky',48.46379,34.97917,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Школа №2','parc_exterior','Vysokyi','Kharkiv Raion',NULL,'Школа №2, Vysokyi',49.89668,36.11856,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Школа №27','parc_exterior','Desna','Vinnytsya Raion',NULL,'Школа №27, Desna',49.2453,28.53956,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Парк ім. Маяковського (2)','parc_exterior','Kulynychi','Kharkiv Raion',NULL,'Парк ім. Маяковського, Kulynychi',49.95104,36.37526,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Парк ім. Маяковського (3)','parc_exterior','Kulynychi','Kharkiv Raion',NULL,'Парк ім. Маяковського, Kulynychi',49.95114,36.3753,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Парк ім. Маяковського (4)','parc_exterior','Kulynychi','Kharkiv Raion',NULL,'Парк ім. Маяковського, Kulynychi',49.95312,36.37213,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Парк ім. Маяковського (5)','parc_exterior','Kulynychi','Kharkiv Raion',NULL,'Парк ім. Маяковського, Kulynychi',49.95314,36.37215,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Харківський ліцей №11 імені Данила Дідіка','parc_exterior','Kulynychi','Kharkiv Raion',NULL,'Харківський ліцей №11 імені Данила Дідіка, Kulynychi',49.96243,36.32505,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Метеоріт','parc_exterior','Kharkiv','Kharkiv Raion',NULL,'YOLOschool, Kharkiv',49.99073,36.29003,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Центральний Парк','parc_exterior','Zdorivka','Obukhiv Raion',NULL,'Центральний Парк, Zdorivka',50.22288,30.23456,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Speedo Ukraine','parc_exterior','Saperna Slobidka','Holosiiv Raion',NULL,'Speedo Ukraine, Saperna Slobidka',50.40467,30.61004,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Площадка для выгула собак','parc_exterior','Mala Danylivka','Kharkiv Raion',NULL,'Площадка для выгула собак, Mala Danylivka',50.03124,36.21784,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Армада','parc_exterior','Zaporizhzhya','Zaporizhzhya Raion',NULL,'KTK Komondog, Zaporizhzhya',47.83936,35.12389,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Парк "Хімік" (2)','parc_exterior','Vinnytsya','Vinnytsya Raion',NULL,'Парк "Хімік", Vinnytsya',49.24431,28.50256,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Сквер Назарія Гринцевича','parc_exterior','Vinnytsya','Vinnytsya Raion',NULL,'Сквер Назарія Гринцевича, Vinnytsya',49.24397,28.49274,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Гідропарк','parc_exterior','Kyiv','Kyiv City',NULL,'Гідропарк, Kyiv',50.4439,30.5726,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Гідропарк (2)','parc_exterior','Kyiv','Kyiv City',NULL,'Гідропарк, Kyiv',50.44417,30.57263,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Гідропарк (3)','parc_exterior','Kyiv','Kyiv City',NULL,'Гідропарк, Kyiv',50.44426,30.57351,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Гідропарк (4)','parc_exterior','Kyiv','Kyiv City',NULL,'Гідропарк, Kyiv',50.44355,30.57166,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Гідропарк (6)','parc_exterior','Kyiv','Kyiv City',NULL,'Гідропарк, Kyiv',50.44385,30.57201,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Гідропарк (8)','parc_exterior','Kyiv','Kyiv City',NULL,'Гідропарк, Kyiv',50.44442,30.57384,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Гідропарк (9)','parc_exterior','Kyiv','Kyiv City',NULL,'Гідропарк, Kyiv',50.44438,30.57331,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс 1-й Мікрорайон','parc_exterior','Mala Danylivka','Kharkiv Raion',NULL,'1-й Мікрорайон, Mala Danylivka',50.03221,36.2271,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Клуб настільного тенісу "Старт"','parc_exterior','Kyiv','Kyiv City',NULL,'Старт, Kyiv',50.45493,30.48256,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Кирилівський гай','parc_exterior','Shevchenka','Podilskyi Raion',NULL,'Кирилівський гай, Shevchenka',50.47834,30.45587,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Орлятко','parc_exterior','Zhulyany','Solomianka Rayon',NULL,'Орлятко, Zhulyany',50.4432,30.42782,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Стіл для настільного теннісу','parc_exterior','Bykivnia','Desnianskyi Raion',NULL,'Стіл для настільного теннісу, Bykivnia',50.50425,30.60011,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс ЖМ Патріотика','parc_exterior','Bortnychi','Darnytsia Raion',NULL,'ЖМ Патріотика, Bortnychi',50.38857,30.6269,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс 11-й мікрорайон','parc_exterior','Bortnychi','Darnytsia Raion',NULL,'11-й мікрорайон, Bortnychi',50.39294,30.65008,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Верстатобудівний сквер','parc_exterior','Berkovets','Sviatoshynskyi Raion',NULL,'Верстатобудівний сквер, Berkovets',50.47032,30.40989,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Верстатобудівний сквер (2)','parc_exterior','Berkovets','Sviatoshynskyi Raion',NULL,'Верстатобудівний сквер, Berkovets',50.47032,30.40999,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс 9-й мікрорайон Оболоні','parc_exterior','Shevchenka','Podilskyi Raion',NULL,'9-й мікрорайон Оболоні, Shevchenka',50.51569,30.5055,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Selfish Club','parc_exterior','Stayky','Obukhiv Raion',NULL,'Selfish Club, Stayky',50.13886,30.89376,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Середня загальноосвітня школа №68','parc_exterior','Sknyliv','Lvivskyi Raion',NULL,'Середня загальноосвітня школа №68, Sknyliv',49.8272,23.95743,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Середня загальноосвітня школа №68 (2)','parc_exterior','Sknyliv','Lvivskyi Raion',NULL,'Середня загальноосвітня школа №68, Sknyliv',49.82705,23.95662,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс ЖК "Варшавський-2"','parc_exterior','Shevchenka','Podilskyi Raion',NULL,'ЖК "Варшавський-2", Shevchenka',50.49864,30.42121,1,false,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Школа №13','parc_exterior','Siverskodonetsk','Sievierodonetskyi Raion',NULL,'Школа №13, Siverskodonetsk',48.94067,38.50228,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Лідер','parc_exterior','Shevchenka','Podilskyi Raion',NULL,'2-й мікрорайон Виноградаря, Shevchenka',50.51435,30.42151,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Гідропарк (5)','parc_exterior','Kyiv','Kyiv City',NULL,'Гідропарк, Kyiv',50.44342,30.57115,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Гідропарк (7)','parc_exterior','Kyiv','Kyiv City',NULL,'Гідропарк, Kyiv',50.44404,30.57231,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Тенісний стіл','parc_exterior','Kramatorsk','Kramatorskyi Raion',NULL,'Тенісний стіл, Kramatorsk',48.74467,37.5864,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Лагерь МЭИ «Алушта»','parc_exterior','Solnechnogorskoye','Miskyi okruh Yalta',NULL,'Лагерь МЭИ «Алушта», Solnechnogorskoye',44.72325,34.4824,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс ЗОШ №22 І-ІІІ ступенів','parc_exterior','Sumy','Sumskyi Raion',NULL,'ЗОШ №22 І-ІІІ ступенів, Sumy',50.93997,34.76862,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Ліцей №25','parc_exterior','Ivano-Frankivsk','Ivano-Frankivskyi Raion',NULL,'Ліцей №25, Ivano-Frankivsk',48.93466,24.75277,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Парк імені Федора Мершавцева','parc_exterior','Kryvyy Rih','Kryvyy Rih Raion',NULL,'Парк імені Федора Мершавцева, Kryvyy Rih',47.89761,33.32948,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Ділянка № 3 КП ЖКС "Чорноморський"','parc_exterior','Lymanka','Odeskyi Raion',NULL,'Ділянка № 3 КП ЖКС "Чорноморський", Lymanka',46.39504,30.72026,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Ділянка № 3 КП ЖКС "Чорноморський" (2)','parc_exterior','Lymanka','Odeskyi Raion',NULL,'Ділянка № 3 КП ЖКС "Чорноморський", Lymanka',46.39441,30.72023,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Ділянка № 3 КП ЖКС "Чорноморський" (3)','parc_exterior','Lymanka','Odeskyi Raion',NULL,'Ділянка № 3 КП ЖКС "Чорноморський", Lymanka',46.39473,30.72024,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Актівіті зона','parc_exterior','Kyiv','Kyiv City',NULL,'Актівіті зона, Kyiv',50.46025,30.49182,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Харківський ліцей №106 імені В. О. Кисіля','parc_exterior','Kharkiv','Kharkiv Raion',NULL,'Харківський ліцей №106 імені В. О. Кисіля, Kharkiv',50.016,36.21142,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс 2-й мікрорайон Оболоні','parc_exterior','Kyiv','Kyiv City',NULL,'2-й мікрорайон Оболоні, Kyiv',50.49546,30.50632,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс 1-й мікрорайон Оболоні','parc_exterior','Kyiv','Kyiv City',NULL,'1-й мікрорайон Оболоні, Kyiv',50.49205,30.51413,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс 10-й мікрорайон Оболоні','parc_exterior','Shevchenka','Podilskyi Raion',NULL,'10-й мікрорайон Оболоні, Shevchenka',50.51364,30.51006,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Жилой комплекс «Кристалл»','parc_exterior','Feodosiya','Feodosiya Raion',NULL,'Жилой комплекс «Кристалл», Feodosiya',45.0572,35.38099,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Солом''янський ладшафтний парк','parc_exterior','Kyiv','Kyiv City',NULL,'Солом''янський ладшафтний парк, Kyiv',50.42786,30.48794,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс 625-й мікрорайон','parc_exterior','Kulynychi','Kharkiv Raion',NULL,'625-й мікрорайон, Kulynychi',49.98563,36.3584,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Харківський ліцей №32','parc_exterior','Kulynychi','Kharkiv Raion',NULL,'Харківський ліцей №32, Kulynychi',49.95617,36.3483,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Харківська гімназія №145','parc_exterior','Kulynychi','Kharkiv Raion',NULL,'Харківська гімназія №145, Kulynychi',49.9831,36.3532,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Харківська гімназія №145 (2)','parc_exterior','Kulynychi','Kharkiv Raion',NULL,'Харківська гімназія №145, Kulynychi',49.98367,36.35275,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Спортивна школа №6','parc_exterior','Kharkiv','Kharkiv Raion',NULL,'Спортивна школа №6, Kharkiv',49.94236,36.31782,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Так само настільні ігри','parc_exterior','Shyroke','Donetsk Raion',NULL,'Так само настільні ігри, Shyroke',47.93911,38.29105,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Парк-Готель "Древній Град"','parc_exterior','Dubliany','Lvivskyi Raion',NULL,'Парк-Готель "Древній Град", Dubliany',49.895,24.12579,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Парк имени Юрия Гагарина','parc_exterior','Simferopol','Simferopol Raion',NULL,'Парк имени Юрия Гагарина, Simferopol',44.96475,34.09873,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Парк Юрьева','parc_exterior','Kulynychi','Kharkiv Raion',NULL,'Парк Юрьева, Kulynychi',49.95751,36.3215,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Парк Юрьева (2)','parc_exterior','Kulynychi','Kharkiv Raion',NULL,'Парк Юрьева, Kulynychi',49.95749,36.32165,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Fram Equipment','parc_exterior','Bykivnia','Desnianskyi Raion',NULL,'Fram Equipment, Bykivnia',50.45047,30.62099,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Бродвей на Харьковском','parc_exterior','Bortnychi','Darnytsia Raion',NULL,'Бродвей на Харьковском, Bortnychi',50.40742,30.65926,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс М. Хрещатик','parc_exterior','Bykivnia','Desnianskyi Raion',NULL,'М. Хрещатик, Bykivnia',50.47409,30.62369,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Спортивный комплекс "Мотор Сич"','parc_exterior','Zaporizhzhya','Zaporizhzhya Raion',NULL,'Спортивный комплекс "Мотор Сич", Zaporizhzhya',47.83111,35.20728,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Русановская набережная 14/1','parc_exterior','Kyiv','Kyiv City',NULL,'Русановская набережная 14/1, Kyiv',50.44031,30.59376,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Лавочка біля Труша','parc_exterior','Lviv','Lvivskyi Raion',NULL,'Лавочка біля Труша, Lviv',49.8256,24.03627,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Лавочка біля Труша (2)','parc_exterior','Lviv','Lvivskyi Raion',NULL,'Лавочка біля Труша, Lviv',49.82552,24.0364,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Вилюр','parc_exterior','Donetsk','Donetsk Raion',NULL,'Donetsk',47.97824,37.79171,1,true,false,'11:00-24:00',NULL,ARRAY['exterior'],true,false),
  ('Факел','parc_exterior','Sumy','Sumskyi Raion',NULL,'Sumy',50.92528,34.78957,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Міський парк культури та відпочинку ім. Кожедуба','parc_exterior','Sumy','Sumskyi Raion',NULL,'Міський парк культури та відпочинку ім. Кожедуба, Sumy',50.89436,34.79814,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Національний комплекс «Експоцентр України» (ВДНГ)','parc_exterior','Zhulyany','Solomianka Rayon',NULL,'Національний комплекс «Експоцентр України» (ВДНГ), Zhulyany',50.37411,30.47645,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Павленківський парк','parc_exterior','Poltava','Poltava Raion',NULL,'Павленківський парк, Poltava',49.5998,34.53505,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Павленківський парк (2)','parc_exterior','Poltava','Poltava Raion',NULL,'Павленківський парк, Poltava',49.59979,34.53498,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Новокодацький парк','parc_exterior','Novi Kodaky','Dnipro rural raion',NULL,'Новокодацький парк, Novi Kodaky',48.48648,34.9442,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Новокодацький парк (2)','parc_exterior','Novi Kodaky','Dnipro rural raion',NULL,'Новокодацький парк, Novi Kodaky',48.4865,34.94423,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Школа №21','parc_exterior','Ivano-Frankivsk','Ivano-Frankivskyi Raion',NULL,'Школа №21, Ivano-Frankivsk',48.91166,24.71367,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс ЖК Seven','parc_exterior','Saperna Slobidka','Holosiiv Raion',NULL,'ЖК Seven, Saperna Slobidka',50.39862,30.61232,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Харківський ліцей №47','parc_exterior','Mala Danylivka','Kharkiv Raion',NULL,'Харківський ліцей №47, Mala Danylivka',50.03715,36.23073,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Стадіон школи №40','parc_exterior','Sknyliv','Lvivskyi Raion',NULL,'Стадіон школи №40, Sknyliv',49.81884,23.97456,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Пінг-понг','parc_exterior','Brovary','Brovary Raion',NULL,'Пінг-понг, Brovary',50.50468,30.78753,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Школа №28','parc_exterior','Shevchenka','Podilskyi Raion',NULL,'Школа №28, Shevchenka',50.47761,30.43535,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Школа №28 (2)','parc_exterior','Shevchenka','Podilskyi Raion',NULL,'Школа №28, Shevchenka',50.47763,30.43526,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Парк імені П.І.Чайковського','parc_exterior','Trostyanets','Okhtyrskiy Rayon',NULL,'Парк імені П.І.Чайковського, Trostyanets',50.472,34.95451,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс ЖК «Банківський 2»','parc_exterior','Boryspil','Borispol’skiy Rayon',NULL,'ЖК «Банківський 2», Boryspil',50.35884,30.94757,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс ДОК "Лісова казка"','parc_exterior','Tsarychanka','Dnipro rural raion',NULL,'ДОК "Лісова казка", Tsarychanka',48.91545,34.48811,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс ЖК Підвисоцький','parc_exterior','Saperna Slobidka','Holosiiv Raion',NULL,'ЖК Підвисоцький, Saperna Slobidka',50.41076,30.54246,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Iванова гора','parc_exterior','Poltava','Poltava Raion',NULL,'Iванова гора, Poltava',49.58382,34.56668,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Дельфин-Аква','parc_exterior','Bykivnia','Desnianskyi Raion',NULL,'Дельфин-Аква, Bykivnia',50.45518,30.62981,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Дитячий майданчик','parc_exterior','Vasylkiv','Obukhiv Raion',NULL,'Дитячий майданчик, Vasylkiv',50.18986,30.2995,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс','parc_exterior','Kharkiv','Kharkiv Raion',NULL,'Настільний теніс, Kharkiv',50.02648,36.233,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс','parc_exterior','Bezliudivka','Kharkiv Raion',NULL,'Настільний теніс, Bezliudivka',49.91466,36.2713,1,true,true,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс ЖК "Резиденція"','parc_exterior','Kharkiv','Kharkiv Raion',NULL,'ЖК "Резиденція", Kharkiv',50.02133,36.22888,1,true,false,NULL,NULL,ARRAY['exterior'],true,false),
  ('Настільний теніс Стадіон школи №109','parc_exterior','Kharkiv','Kharkiv Raion',NULL,'Стадіон школи №109, Kharkiv',50.0179,36.22027,1,true,false,NULL,NULL,ARRAY['exterior'],true,false)
) AS v(name,type,city,county,sector,address,lat,lng,tables_count,free_access,night_lighting,hours,description,tags,approved,verified)
JOIN cities c ON c.country_code='UA' AND c.name=v.city
ON CONFLICT (name,city_id) DO NOTHING;
COMMIT;
