import { StyleSheet } from 'react-native';
import type { ThemeColors } from '../theme';
import { Fonts, FontSize, FontWeight, Radius, Shadows, Spacing } from '../theme';

export function createStyles(colors: ThemeColors) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.bg,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: colors.bgAlt,
      height: 52,
      paddingHorizontal: Spacing.md,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      ...Shadows.bar,
    },
    headerTitle: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xxl,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    adminBadge: {
      backgroundColor: colors.primaryPale,
      borderRadius: 8,
      paddingVertical: 2,
      paddingHorizontal: 6,
    },
    adminBadgeText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
      color: colors.primaryMid,
    },
    tabBar: {
      flexDirection: 'row',
      backgroundColor: colors.bgAlt,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    tab: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 12,
      gap: 6,
      borderBottomWidth: 2,
      borderBottomColor: 'transparent',
    },
    tabActive: {
      borderBottomColor: colors.primary,
    },
    tabText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.semibold,
      color: colors.textFaint,
    },
    tabTextActive: {
      color: colors.text,
    },
    tabBadge: {
      backgroundColor: colors.redDeep,
      borderRadius: 10,
      minWidth: 20,
      height: 20,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 5,
    },
    tabBadgeText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
      color: colors.textOnPrimary,
    },
    scroll: {
      flex: 1,
    },
    statsRow: {
      flexDirection: 'row',
      gap: Spacing.xs,
      padding: Spacing.md,
      paddingBottom: Spacing.sm,
    },
    statCard: {
      flex: 1,
      alignItems: 'center',
      borderRadius: Radius.md,
      padding: 10,
      gap: 2,
      ...Shadows.sm,
    },
    statValue: {
      fontFamily: Fonts.heading,
      fontSize: 22,
      fontWeight: FontWeight.extrabold,
    },
    statLabel: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.medium,
      color: colors.textMuted,
    },
    secLabel: {
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm,
      paddingBottom: Spacing.xs,
    },
    secLabelText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
      color: colors.textFaint,
      letterSpacing: 1,
    },
    modList: {
      paddingHorizontal: Spacing.md,
      gap: 10,
    },
    modCard: {
      backgroundColor: colors.bgAlt,
      borderRadius: 12,
      padding: 14,
      gap: 10,
      borderWidth: 1.5,
      borderColor: colors.amber,
      ...Shadows.sm,
    },
    modTop: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    modTitle: {
      fontFamily: Fonts.body,
      fontSize: FontSize.lg,
      fontWeight: FontWeight.semibold,
      color: colors.text,
      flex: 1,
    },
    modBadge: {
      backgroundColor: colors.amberPale,
      borderRadius: 8,
      paddingVertical: 2,
      paddingHorizontal: Spacing.xs,
    },
    modBadgeText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.semibold,
      color: colors.accent,
    },
    modMeta: {
      fontFamily: Fonts.body,
      fontSize: FontSize.base,
      color: colors.textFaint,
    },
    modActions: {
      flexDirection: 'row',
      gap: Spacing.xs,
    },
    approveBtn: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primary,
      borderRadius: 8,
      height: 36,
      gap: 6,
      ...Shadows.md,
    },
    approveBtnText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.base,
      fontWeight: FontWeight.semibold,
      color: colors.textOnPrimary,
    },
    editBtn: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 8,
      height: 36,
      gap: 6,
      borderWidth: 1,
      borderColor: colors.border,
    },
    editBtnText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.base,
      fontWeight: FontWeight.semibold,
      color: colors.textMuted,
    },
    rejectBtn: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 8,
      height: 36,
      gap: 6,
      borderWidth: 1,
      borderColor: colors.redBorder,
      ...Shadows.md,
    },
    rejectBtnText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.base,
      fontWeight: FontWeight.semibold,
      color: colors.red,
    },
    venueSearchWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.bgAlt,
      borderRadius: Radius.md,
      marginHorizontal: Spacing.md,
      marginTop: Spacing.md,
      paddingHorizontal: 12,
      height: 42,
      gap: 8,
      borderWidth: 1,
      borderColor: colors.border,
    },
    venueSearchInput: {
      flex: 1,
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      color: colors.text,
      padding: 0,
    },
    venueList: {
      paddingHorizontal: Spacing.md,
      paddingTop: Spacing.sm,
      gap: 8,
      paddingBottom: Spacing.md,
    },
    venueCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.bgAlt,
      borderRadius: Radius.md,
      padding: 12,
      borderWidth: 1,
      borderColor: colors.border,
      ...Shadows.sm,
    },
    venueInfo: {
      flex: 1,
      gap: 2,
    },
    venueName: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.semibold,
      color: colors.text,
    },
    venueMeta: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      color: colors.textFaint,
    },
    venueActions: {
      flexDirection: 'row',
      gap: Spacing.xs,
    },
    venueEditBtn: {
      width: 36,
      height: 36,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
    },
    venueDeleteBtn: {
      width: 36,
      height: 36,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.redBorder,
    },
    flagList: {
      paddingHorizontal: Spacing.md,
      gap: 10,
    },
    flagCard: {
      backgroundColor: colors.bgAlt,
      borderRadius: 12,
      padding: 14,
      gap: 10,
      borderWidth: 1.5,
      borderColor: colors.red,
      ...Shadows.sm,
    },
    flagTop: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    flagInfo: {
      gap: 2,
    },
    flagAuthor: {
      fontFamily: Fonts.body,
      fontSize: FontSize.lg,
      fontWeight: FontWeight.semibold,
      color: colors.text,
    },
    flagMeta: {
      fontFamily: Fonts.body,
      fontSize: FontSize.base,
      color: colors.textFaint,
    },
    flagBadge: {
      backgroundColor: colors.redPale,
      borderRadius: 8,
      paddingVertical: 2,
      paddingHorizontal: 8,
    },
    flagBadgeText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.semibold,
      color: colors.red,
    },
    flagText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontStyle: 'italic',
      color: colors.textMuted,
    },
    flagActions: {
      flexDirection: 'row',
      gap: Spacing.xs,
    },
    keepBtn: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 8,
      height: 36,
      gap: 6,
      borderWidth: 1,
      borderColor: colors.border,
      ...Shadows.md,
    },
    keepBtnText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.base,
      fontWeight: FontWeight.semibold,
      color: colors.textMuted,
    },
    deleteBtn: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.redDeep,
      borderRadius: 8,
      height: 36,
      gap: 6,
      ...Shadows.md,
    },
    deleteBtnText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.base,
      fontWeight: FontWeight.semibold,
      color: colors.textOnPrimary,
    },
    // Edit modal
    modalOverlay: {
      flex: 1,
      backgroundColor: colors.overlay,
      justifyContent: 'flex-end',
      alignItems: 'center',
    },
    modalSheet: {
      backgroundColor: colors.bgAlt,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      width: '100%',
      maxWidth: 430,
      maxHeight: '85%',
      paddingBottom: Spacing.xl,
      ...Shadows.lg,
    },
    modalHandle: {
      alignItems: 'center',
      paddingVertical: 10,
    },
    modalHandleBar: {
      width: 36,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.border,
    },
    modalTitle: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xxl,
      fontWeight: FontWeight.bold,
      color: colors.text,
      paddingHorizontal: Spacing.lg,
      marginBottom: Spacing.md,
    },
    modalScroll: {
      // flexShrink:1 lets the ScrollView take whatever space remains inside
      // the modalSheet (capped at 85% of the screen) without pushing the
      // pinned action row off the bottom — required on web/desktop where the
      // sheet has a real bounded height. On native it just falls through.
      flexShrink: 1,
    },
    modalScrollContent: {
      paddingHorizontal: Spacing.lg,
      paddingBottom: Spacing.md,
    },
    modalField: {
      gap: 6,
      marginBottom: Spacing.md,
    },
    modalLabel: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      fontWeight: FontWeight.semibold,
      color: colors.textFaint,
      letterSpacing: 0.7,
    },
    modalInput: {
      backgroundColor: colors.bg,
      borderRadius: Radius.md,
      height: 44,
      paddingHorizontal: 12,
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      color: colors.text,
      borderWidth: 1,
      borderColor: colors.border,
    },
    modalTypeRow: {
      flexDirection: 'row',
      gap: Spacing.xs,
    },
    modalTypeBtn: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.bg,
      borderRadius: Radius.md,
      height: 44,
      borderWidth: 1,
      borderColor: colors.border,
    },
    modalTypeBtnActive: {
      backgroundColor: colors.primaryPale,
      borderColor: colors.primaryDim,
    },
    modalTypeBtnText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      color: colors.textMuted,
    },
    modalTypeBtnTextActive: {
      color: colors.primaryMid,
      fontWeight: FontWeight.semibold,
    },
    modalActions: {
      flexDirection: 'row',
      gap: Spacing.sm,
      paddingHorizontal: Spacing.lg,
      paddingTop: Spacing.md,
    },
    modalCancelBtn: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 12,
      height: 48,
      borderWidth: 1,
      borderColor: colors.border,
    },
    modalCancelText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.lg,
      fontWeight: FontWeight.semibold,
      color: colors.textMuted,
    },
    modalSaveBtn: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primary,
      borderRadius: 12,
      height: 48,
      ...Shadows.md,
    },
    modalSaveText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.lg,
      fontWeight: FontWeight.bold,
      color: colors.textOnPrimary,
    },
    // Reject confirmation sheet — narrower than the edit sheet (no scroll
    // body, just title + message + 2 buttons), so it auto-sizes to content
    // instead of capping at 85% screen height.
    confirmSheet: {
      backgroundColor: colors.bgAlt,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      width: '100%',
      maxWidth: 430,
      paddingBottom: Spacing.xl,
      ...Shadows.lg,
    },
    confirmBody: {
      paddingHorizontal: Spacing.lg,
      paddingBottom: Spacing.md,
      gap: 6,
    },
    confirmVenueName: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.semibold,
      color: colors.text,
    },
    confirmMessage: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      color: colors.textMuted,
      lineHeight: 20,
    },
    confirmRejectBtn: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.red,
      borderRadius: 12,
      height: 48,
      ...Shadows.md,
    },
    confirmRejectText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.lg,
      fontWeight: FontWeight.bold,
      color: colors.textOnPrimary,
    },
  });
}
