import { StyleSheet } from 'react-native';
import type { ThemeColors } from '../theme';
import { Fonts, FontSize, FontWeight, Radius, Shadows, Spacing } from '../theme';

export function createStyles(colors: ThemeColors, isDark: boolean) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.bg,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: isDark ? colors.bgAlt : colors.primary,
      paddingVertical: 10,
      minHeight: 52,
      paddingHorizontal: Spacing.md,
      ...Shadows.bar,
    },
    headerTitle: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xxl,
      fontWeight: FontWeight.bold,
      color: isDark ? colors.text : colors.textOnPrimary,
    },
    topTabs: {
      flexDirection: 'row',
      padding: Spacing.sm,
      gap: Spacing.xs,
      backgroundColor: colors.bg,
    },
    topTab: {
      flex: 1,
      alignItems: 'center',
      paddingVertical: 11,
      borderRadius: Radius.sm,
      backgroundColor: colors.bgMuted,
    },
    topTabActive: {
      backgroundColor: colors.text,
    },
    topTabText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.lg,
      fontWeight: FontWeight.semibold,
      color: colors.textMuted,
    },
    topTabTextActive: {
      color: colors.bgAlt,
    },
    scroll: {
      flex: 1,
    },
    scrollContent: {
      padding: Spacing.md,
      gap: Spacing.md,
      paddingBottom: Spacing.xxl,
    },
    sectionHeader: {
      gap: 4,
    },
    centeredHeader: {
      alignItems: 'center',
    },
    sectionTitle: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xl,
      fontWeight: FontWeight.bold,
      color: colors.text,
      textAlign: 'center',
    },
    sectionCopy: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      color: colors.textMuted,
      textAlign: 'center',
    },
    trackPicker: {
      gap: Spacing.xs,
    },
    trackPickerRow: {
      flexDirection: 'row',
      gap: Spacing.xs,
    },
    trackChip: {
      flex: 1,
      minHeight: 72,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 4,
      borderRadius: Radius.sm,
      borderWidth: 1,
      borderColor: colors.borderLight,
      backgroundColor: colors.bgAlt,
      paddingHorizontal: 4,
      paddingVertical: 8,
    },
    trackChipText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    trackChipTextActive: {
      color: colors.textOnPrimary,
    },
    trackChipMeta: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.medium,
      color: colors.textFaint,
    },
    trackChipMetaActive: {
      color: colors.textOnPrimary,
    },
    heroCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
      borderWidth: 1,
      borderRadius: Radius.md,
      padding: Spacing.md,
      backgroundColor: colors.bgAlt,
      ...Shadows.sm,
    },
    heroIcon: {
      width: 54,
      height: 54,
      borderRadius: Radius.sm,
      alignItems: 'center',
      justifyContent: 'center',
    },
    heroCopy: {
      flex: 1,
      gap: 3,
    },
    heroTitle: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xxl,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    heroDesc: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      color: colors.textMuted,
    },
    statusPill: {
      borderRadius: Radius.sm,
      paddingHorizontal: 9,
      paddingVertical: 6,
      backgroundColor: colors.bgMuted,
    },
    statusPillText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    progressPanel: {
      alignSelf: 'stretch',
      gap: Spacing.sm,
      borderRadius: Radius.md,
      backgroundColor: colors.bgAlt,
      padding: Spacing.md,
      borderWidth: 1,
      borderColor: colors.borderLight,
    },
    progressHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: Spacing.sm,
    },
    eyebrow: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
      color: colors.textFaint,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    progressTitle: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.display,
      fontWeight: FontWeight.bold,
      color: colors.text,
      marginTop: 2,
    },
    progressCount: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.display,
      fontWeight: FontWeight.bold,
    },
    progressBar: {
      height: 10,
      borderRadius: 5,
      overflow: 'hidden',
      backgroundColor: colors.bgMuted,
    },
    progressFill: {
      height: 10,
      borderRadius: 5,
    },
    progressHint: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      color: colors.textMuted,
    },
    masteryPanel: {
      gap: Spacing.sm,
      borderRadius: Radius.md,
      backgroundColor: isDark ? colors.bgAlt : colors.text,
      padding: Spacing.md,
      borderWidth: 1,
      borderColor: isDark ? colors.primaryDim : colors.text,
      ...Shadows.md,
    },
    masteryTop: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: Spacing.sm,
    },
    masteryTitle: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xxl,
      fontWeight: FontWeight.bold,
      color: isDark ? colors.text : colors.bgAlt,
      marginTop: 2,
    },
    masteryScore: {
      alignItems: 'flex-end',
    },
    masteryScoreValue: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.display,
      fontWeight: FontWeight.bold,
      color: colors.primaryLight,
    },
    masteryScoreLabel: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
      color: isDark ? colors.textMuted : colors.bgMuted,
    },
    masteryStats: {
      flexDirection: 'row',
      gap: Spacing.xs,
    },
    masteryStat: {
      flex: 1,
      borderRadius: Radius.sm,
      backgroundColor: isDark ? colors.bgMuted : '#ffffff18',
      padding: Spacing.sm,
      gap: 2,
    },
    masteryStatValue: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xl,
      fontWeight: FontWeight.bold,
      color: isDark ? colors.text : colors.bgAlt,
    },
    masteryStatLabel: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
      color: isDark ? colors.textMuted : colors.bgMuted,
    },
    approvalPanel: {
      gap: Spacing.sm,
      borderRadius: Radius.md,
      backgroundColor: colors.bgAlt,
      padding: Spacing.md,
      borderWidth: 1,
      borderColor: colors.borderLight,
    },
    approvalCard: {
      flexDirection: 'row',
      gap: Spacing.sm,
      borderRadius: Radius.sm,
      backgroundColor: colors.bg,
      padding: Spacing.sm,
      borderWidth: 1,
      borderColor: colors.borderLight,
    },
    approvalIcon: {
      width: 38,
      height: 38,
      borderRadius: Radius.sm,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.greenDeep,
    },
    approvalCopy: {
      flex: 1,
      gap: 6,
    },
    approvalTitle: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xl,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    approvalMeta: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      color: colors.textMuted,
    },
    challengeGrid: {
      gap: Spacing.sm,
    },
    challengeCard: {
      position: 'relative',
      overflow: 'hidden',
      minHeight: 146,
      justifyContent: 'space-between',
      borderRadius: Radius.md,
      backgroundColor: colors.bgAlt,
      padding: Spacing.lg,
      borderWidth: 1,
      borderColor: colors.borderLight,
      ...Shadows.sm,
    },
    challengeGlow: {
      position: 'absolute',
      top: -34,
      right: -28,
      width: 118,
      height: 118,
      borderRadius: 59,
      opacity: isDark ? 0.26 : 0.72,
    },
    challengeCardTop: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: Spacing.sm,
    },
    challengeIcon: {
      width: 38,
      height: 38,
      borderRadius: Radius.sm,
      alignItems: 'center',
      justifyContent: 'center',
    },
    verificationPill: {
      borderRadius: Radius.sm,
      backgroundColor: colors.bgMuted,
      paddingHorizontal: 9,
      paddingVertical: 6,
    },
    verificationPillText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
      color: colors.textMuted,
    },
    challengeTitle: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xxl,
      fontWeight: FontWeight.bold,
      color: colors.text,
      paddingRight: Spacing.sm,
      lineHeight: 23,
    },
    challengeFooter: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    challengeCta: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.bold,
    },
    challengeAccent: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      height: 4,
    },
    currentCard: {
      borderRadius: Radius.md,
      backgroundColor: colors.bgAlt,
      borderWidth: 1,
      padding: Spacing.lg,
      gap: Spacing.sm,
      ...Shadows.md,
    },
    currentTitle: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.display,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    verificationPanel: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
      borderRadius: Radius.md,
      backgroundColor: colors.bgMuted,
      padding: Spacing.sm,
    },
    verificationIcon: {
      width: 42,
      height: 42,
      borderRadius: Radius.sm,
      alignItems: 'center',
      justifyContent: 'center',
    },
    verificationCopy: {
      flex: 1,
      gap: 2,
    },
    verificationLabel: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
      color: colors.textFaint,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    verificationValue: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xl,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    verificationNote: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      color: colors.textMuted,
    },
    validationPicker: {
      gap: Spacing.sm,
      borderRadius: Radius.md,
      backgroundColor: colors.bgMuted,
      padding: Spacing.sm,
    },
    validationPickerTitle: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      fontWeight: FontWeight.bold,
      color: colors.text,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    choiceList: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: Spacing.xs,
    },
    choicePill: {
      borderRadius: Radius.sm,
      borderWidth: 1,
      borderColor: colors.borderLight,
      backgroundColor: colors.bgAlt,
      paddingHorizontal: Spacing.sm,
      paddingVertical: 8,
    },
    choicePillText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      fontWeight: FontWeight.semibold,
      color: colors.text,
    },
    actions: {
      flexDirection: 'row',
      alignItems: 'stretch',
      gap: 10,
      marginTop: Spacing.xs,
    },
    secondaryButton: {
      flex: 0.72,
      minHeight: 52,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 7,
      borderRadius: Radius.sm,
      borderWidth: 1,
      borderColor: colors.borderLight,
      paddingHorizontal: 12,
      paddingVertical: 13,
      backgroundColor: colors.bgAlt,
      ...Shadows.sm,
    },
    secondaryButtonText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.bold,
      color: colors.text,
      textAlign: 'center',
      lineHeight: 18,
    },
    compactButton: {
      flex: 0.84,
      minHeight: 52,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      borderRadius: Radius.sm,
      borderWidth: 1,
      borderColor: colors.borderLight,
      paddingHorizontal: 9,
      paddingVertical: 12,
      backgroundColor: colors.bgAlt,
      ...Shadows.sm,
    },
    lockButton: {
      backgroundColor: colors.bgMuted,
    },
    compactButtonText: {
      flexShrink: 1,
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      fontWeight: FontWeight.bold,
      color: colors.text,
      textAlign: 'center',
      lineHeight: 16,
    },
    primaryButton: {
      flex: 1.48,
      minHeight: 52,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      borderRadius: Radius.sm,
      paddingHorizontal: 14,
      paddingVertical: 13,
      ...Shadows.sm,
    },
    primaryButtonText: {
      flexShrink: 1,
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.bold,
      color: colors.textOnPrimary,
      textAlign: 'center',
      lineHeight: 18,
    },
    disabledButton: {
      opacity: 0.68,
    },
    cooldownPanel: {
      minHeight: 184,
      gap: Spacing.md,
      borderRadius: Radius.md,
      borderWidth: 1,
      borderColor: colors.borderLight,
      backgroundColor: colors.bgAlt,
      padding: Spacing.md,
      marginTop: Spacing.xs,
      ...Shadows.sm,
    },
    cooldownTableWrap: {
      alignSelf: 'center',
      width: 230,
      height: 92,
      alignItems: 'center',
      justifyContent: 'flex-end',
    },
    cooldownTable: {
      width: 178,
      height: 64,
      borderRadius: Radius.sm,
      backgroundColor: colors.bgMuted,
      borderWidth: 1,
      borderColor: colors.borderLight,
      alignItems: 'center',
      justifyContent: 'center',
      transform: [{ perspective: 220 }, { rotateX: '54deg' }],
      ...Shadows.sm,
    },
    cooldownTableNet: {
      position: 'absolute',
      top: 4,
      bottom: 4,
      width: 2,
      borderRadius: 1,
      opacity: 0.84,
    },
    cooldownBall: {
      position: 'absolute',
      left: 106,
      top: 18,
      width: 18,
      height: 18,
      borderRadius: 9,
      borderWidth: 1,
      borderColor: isDark ? '#FFFFFF' : colors.borderLight,
      backgroundColor: '#FFFFFF',
      ...Shadows.sm,
    },
    cooldownBallShadow: {
      position: 'absolute',
      left: 103,
      bottom: 15,
      width: 24,
      height: 7,
      borderRadius: 4,
      backgroundColor: isDark ? '#00000055' : '#00000022',
    },
    cooldownInfoRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
    },
    cooldownCopy: {
      flex: 1,
      minWidth: 0,
      gap: 6,
    },
    cooldownTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: 6,
    },
    cooldownTitle: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xl,
      fontWeight: FontWeight.bold,
      color: colors.text,
      lineHeight: 22,
    },
    cooldownText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.semibold,
      color: colors.text,
      lineHeight: 19,
    },
    cooldownTimerPill: {
      minWidth: 66,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: Radius.sm,
      borderWidth: 1,
      backgroundColor: colors.bgMuted,
      paddingVertical: 8,
      paddingHorizontal: 9,
      gap: 6,
    },
    cooldownTimer: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xxl,
      fontWeight: FontWeight.bold,
      lineHeight: 28,
    },
    cooldownTimerTrack: {
      width: 44,
      height: 4,
      borderRadius: 2,
      overflow: 'hidden',
      backgroundColor: isDark ? colors.bg : colors.borderLight,
    },
    cooldownTimerFill: {
      height: 4,
      borderRadius: 2,
    },
    badgeFeature: {
      overflow: 'hidden',
      gap: Spacing.md,
      borderRadius: Radius.md,
      backgroundColor: colors.bgAlt,
      padding: Spacing.lg,
      borderWidth: 1,
      borderColor: colors.borderLight,
      ...Shadows.md,
    },
    badgeFeatureTop: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
    },
    badgeFeatureIcon: {
      width: 62,
      height: 62,
      borderRadius: Radius.sm,
      alignItems: 'center',
      justifyContent: 'center',
      ...Shadows.sm,
    },
    badgeFeatureIconHalo: {
      position: 'absolute',
      width: 46,
      height: 46,
      borderRadius: 23,
      borderWidth: 1,
      borderColor: '#FFFFFF55',
    },
    badgeFeatureCopy: {
      flex: 1,
      gap: 3,
    },
    badgeFeatureTitle: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.display,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    badgeFeatureDesc: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      color: colors.textMuted,
    },
    badgeFeatureCount: {
      borderRadius: Radius.sm,
      paddingVertical: 8,
      paddingHorizontal: 10,
    },
    badgeFeatureCountText: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.lg,
      fontWeight: FontWeight.bold,
    },
    milestoneRow: {
      flexDirection: 'row',
      gap: Spacing.xs,
      alignSelf: 'stretch',
    },
    milestone: {
      flex: 1,
      alignItems: 'center',
      gap: 6,
      borderRadius: Radius.sm,
      borderWidth: 1,
      borderColor: colors.borderLight,
      backgroundColor: colors.bg,
      paddingVertical: 12,
      paddingHorizontal: 6,
      ...Shadows.sm,
    },
    milestoneMedalWrap: {
      width: 34,
      height: 34,
      borderRadius: Radius.sm,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.bgMuted,
    },
    milestoneLabel: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    milestoneCount: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      color: colors.textFaint,
      textAlign: 'center',
    },
    wonGrid: {
      gap: Spacing.sm,
    },
    wonCard: {
      overflow: 'hidden',
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.md,
      borderRadius: Radius.md,
      backgroundColor: colors.bgAlt,
      padding: Spacing.lg,
      borderWidth: 1,
      borderColor: colors.borderLight,
      ...Shadows.md,
    },
    wonIcon: {
      width: 56,
      height: 56,
      borderRadius: Radius.sm,
      alignItems: 'center',
      justifyContent: 'center',
      ...Shadows.sm,
    },
    wonIconHalo: {
      position: 'absolute',
      width: 42,
      height: 42,
      borderRadius: 21,
      borderWidth: 1,
      borderColor: '#FFFFFF55',
    },
    wonTierSeal: {
      position: 'absolute',
      right: -5,
      bottom: -5,
      width: 24,
      height: 24,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: colors.borderLight,
    },
    wonCopy: {
      flex: 1,
      gap: 2,
    },
    wonTitle: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xl,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    wonTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: Spacing.xs,
    },
    wonMeta: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    wonDateRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
    },
    wonSubMeta: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      color: colors.textFaint,
    },
    newBadgePill: {
      borderRadius: Radius.sm,
      paddingHorizontal: 8,
      paddingVertical: 4,
    },
    newBadgePillText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
    },
    emptyPanel: {
      alignItems: 'center',
      gap: 8,
      borderRadius: Radius.md,
      backgroundColor: colors.bgAlt,
      padding: Spacing.xl,
      borderWidth: 1,
      borderColor: colors.borderLight,
    },
    emptyTitle: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xl,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    emptyText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      color: colors.textMuted,
      textAlign: 'center',
    },
    modalOverlay: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(0,0,0,0.42)',
      padding: Spacing.lg,
    },
    badgeEarnedSheet: {
      width: '100%',
      maxWidth: 420,
      alignItems: 'center',
      gap: Spacing.sm,
      borderRadius: Radius.md,
      backgroundColor: colors.bgAlt,
      padding: Spacing.xl,
      borderWidth: 1,
      borderColor: colors.borderLight,
      ...Shadows.lg,
    },
    badgeEarnedIcon: {
      width: 74,
      height: 74,
      borderRadius: Radius.md,
      alignItems: 'center',
      justifyContent: 'center',
      ...Shadows.md,
    },
    badgeEarnedTitle: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.bold,
      color: colors.textFaint,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    badgeEarnedName: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.display,
      fontWeight: FontWeight.bold,
      color: colors.text,
      textAlign: 'center',
    },
    badgeEarnedCopy: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      color: colors.textMuted,
      textAlign: 'center',
      lineHeight: 20,
    },
    badgeEarnedActions: {
      flexDirection: 'row',
      gap: Spacing.sm,
      alignSelf: 'stretch',
      marginTop: Spacing.sm,
    },
    badgeEarnedSecondary: {
      flex: 1,
      minHeight: 48,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: Radius.sm,
      borderWidth: 1,
      borderColor: colors.borderLight,
      paddingHorizontal: Spacing.sm,
    },
    badgeEarnedSecondaryText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.bold,
      color: colors.text,
      textAlign: 'center',
    },
    badgeEarnedPrimary: {
      flex: 1,
      minHeight: 48,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 7,
      borderRadius: Radius.sm,
      paddingHorizontal: Spacing.sm,
      ...Shadows.sm,
    },
    badgeEarnedPrimaryText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.bold,
      color: colors.textOnPrimary,
      textAlign: 'center',
    },
  });
}
