import { StyleSheet } from 'react-native';
import type { ThemeColors } from '../theme';
import { Fonts, FontSize, FontWeight, Radius, Shadows, Spacing } from '../theme';

export function createSelectStyles(colors: ThemeColors) {
  return StyleSheet.create({
    field: {
      gap: 6,
    },
    label: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      fontWeight: FontWeight.semibold,
      color: colors.textMuted,
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    inputWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      height: 46,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.bgAlt,
      paddingHorizontal: Spacing.sm,
      gap: Spacing.xs,
    },
    inputValue: {
      flex: 1,
      fontFamily: Fonts.body,
      fontSize: FontSize.lg,
      color: colors.text,
    },
    placeholder: {
      color: colors.textFaint,
    },
    inputDisabled: {
      opacity: 0.55,
      backgroundColor: colors.bgMuted,
    },
    sheetContent: {
      flex: 1,
      minHeight: 0,
    },
    webBackdrop: {
      flex: 1,
      justifyContent: 'flex-end',
      alignItems: 'center',
    },
    webSheet: {
      width: '100%',
      maxWidth: 430,
      height: '70%',
      maxHeight: 560,
      minHeight: 320,
      borderTopLeftRadius: Radius.xl,
      borderTopRightRadius: Radius.xl,
      paddingTop: Spacing.sm,
      overflow: 'hidden',
    },
    sheetHeader: {
      paddingHorizontal: Spacing.md,
      paddingTop: 4,
      paddingBottom: Spacing.sm,
      gap: Spacing.sm,
    },
    sheetTitle: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xl,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    sheetSearch: {
      height: 44,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.bg,
      paddingHorizontal: Spacing.sm,
      fontFamily: Fonts.body,
      fontSize: FontSize.lg,
      color: colors.text,
    },
    optionList: {
      flex: 1,
      minHeight: 0,
    },
    optionListContent: {
      paddingBottom: 24,
    },
    optionRow: {
      minHeight: 42,
      justifyContent: 'center',
      paddingVertical: 10,
      paddingHorizontal: Spacing.sm,
      borderBottomWidth: 1,
      borderBottomColor: colors.borderLight,
    },
    optionRowPressed: {
      backgroundColor: colors.primaryPale,
    },
    optionText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      color: colors.text,
    },
    emptyOption: {
      paddingVertical: Spacing.md,
      paddingHorizontal: Spacing.sm,
      textAlign: 'center',
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      color: colors.textFaint,
    },
    colorSelect: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.bgMuted,
      paddingVertical: 6,
      paddingHorizontal: 8,
      minHeight: 32,
      maxWidth: 132,
    },
    colorSelectDot: {
      width: 11,
      height: 11,
      borderRadius: 6,
      borderWidth: 1,
      borderColor: colors.border,
    },
    colorSelectText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.base,
      fontWeight: FontWeight.semibold,
      color: colors.text,
      textTransform: 'capitalize',
    },
    colorPickerBackdrop: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.overlayLight,
      padding: Spacing.lg,
    },
    colorPickerPanel: {
      width: '100%',
      maxWidth: 320,
      maxHeight: '72%',
      borderRadius: Radius.lg,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.bgAlt,
      padding: Spacing.sm,
      ...Shadows.md,
    },
    colorPickerScroll: {
      maxHeight: 260,
    },
    colorPickerGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      paddingBottom: 2,
    },
    colorChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 7,
      flexGrow: 1,
      flexBasis: '46%',
      minHeight: 40,
      borderRadius: 999,
      borderWidth: 1,
      borderBottomColor: colors.borderLight,
      borderColor: colors.borderLight,
      backgroundColor: colors.bgMuted,
      paddingVertical: 7,
      paddingHorizontal: 9,
    },
    colorChipActive: {
      borderColor: colors.primaryDim,
      backgroundColor: colors.primaryPale,
    },
    colorChipSwatch: {
      width: 20,
      height: 20,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: colors.border,
    },
    colorChipText: {
      flex: 1,
      fontFamily: Fonts.body,
      fontSize: FontSize.base,
      fontWeight: FontWeight.medium,
      color: colors.textMuted,
      textTransform: 'capitalize',
    },
    colorChipTextActive: {
      color: colors.primary,
      fontWeight: FontWeight.bold,
    },
  });
}

export function createStyles(colors: ThemeColors) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.bg,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: colors.bgAlt,
      minHeight: 64,
      paddingHorizontal: Spacing.md,
      paddingVertical: 8,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      ...Shadows.bar,
    },
    backButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerSpacer: {
      width: 40,
      height: 40,
    },
    headerCopy: {
      flex: 1,
      minWidth: 0,
      alignItems: 'center',
      paddingHorizontal: Spacing.sm,
    },
    headerTitle: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xl,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    hero: {
      alignItems: 'flex-start',
      marginHorizontal: Spacing.md,
      marginTop: Spacing.md,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.borderLight,
      backgroundColor: colors.bgAlt,
      paddingVertical: Spacing.lg,
      paddingHorizontal: Spacing.md,
      ...Shadows.md,
    },
    heroCopy: {
      gap: 6,
    },
    heroTitle: {
      fontFamily: Fonts.heading,
      fontSize: 28,
      fontWeight: FontWeight.extrabold,
      color: colors.text,
    },
    heroText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.lg,
      lineHeight: 21,
      color: colors.textMuted,
    },
    tabs: {
      flexDirection: 'row',
      gap: 4,
      alignSelf: 'center',
      width: '100%',
      maxWidth: 680,
      paddingHorizontal: Spacing.md,
      paddingTop: Spacing.sm,
      paddingBottom: Spacing.md,
      backgroundColor: colors.bg,
      borderRadius: 999,
    },
    tab: {
      flex: 1,
      alignItems: 'center',
      borderRadius: 999,
      paddingVertical: 10,
      borderWidth: 1,
      borderColor: colors.borderLight,
      backgroundColor: colors.bgAlt,
    },
    tabActive: {
      backgroundColor: colors.primaryPale,
      borderColor: colors.primaryDim,
    },
    tabText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.semibold,
      color: colors.textMuted,
    },
    tabTextActive: {
      color: colors.primary,
    },
    scroll: {
      flex: 1,
    },
    content: {
      alignSelf: 'center',
      width: '100%',
      maxWidth: 680,
      paddingHorizontal: Spacing.md,
      gap: Spacing.md,
    },
    inlineError: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xs,
      marginHorizontal: Spacing.md,
      marginBottom: Spacing.sm,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.redBorder,
      backgroundColor: colors.redPale,
      padding: Spacing.sm,
    },
    inlineErrorText: {
      flex: 1,
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.medium,
      color: colors.red,
    },
    group: {
      gap: Spacing.md,
      backgroundColor: colors.bgAlt,
      borderRadius: Radius.lg,
      borderWidth: 1,
      borderColor: colors.borderLight,
      padding: Spacing.lg,
      ...Shadows.sm,
    },
    groupHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
    },
    groupIcon: {
      width: 44,
      height: 44,
      borderRadius: Radius.md,
      alignItems: 'center',
      justifyContent: 'center',
      ...Shadows.sm,
    },
    groupTitleWrap: {
      flex: 1,
      gap: 2,
    },
    groupTitle: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.lg,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    groupSubtitle: {
      fontFamily: Fonts.body,
      fontSize: FontSize.base,
      color: colors.textFaint,
    },
    playerProfileGroup: {
      gap: Spacing.sm,
      borderColor: colors.borderLight,
      backgroundColor: colors.bgAlt,
      padding: Spacing.md,
    },
    playerProfileHeader: {
      alignItems: 'flex-start',
      paddingBottom: Spacing.sm,
      borderBottomWidth: 1,
      borderBottomColor: colors.borderLight,
    },
    playerProfileAvatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primaryPale,
      borderWidth: 1,
      borderColor: colors.primaryDim,
      ...Shadows.sm,
    },
    playerProfileAvatarText: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.lg,
      fontWeight: FontWeight.bold,
      color: colors.primary,
    },
    playerProfileControls: {
      gap: Spacing.sm,
    },
    inlineHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    inputLabel: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      fontWeight: FontWeight.semibold,
      color: colors.textMuted,
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    colorGroup: {
      gap: 10,
      backgroundColor: colors.bgAlt,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.borderLight,
      padding: Spacing.md,
      ...Shadows.sm,
    },
    colorRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    colorChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
      paddingVertical: 9,
      paddingHorizontal: 11,
      backgroundColor: colors.bgMuted,
    },
    colorChipActive: {
      borderColor: colors.primary,
      backgroundColor: colors.primaryPale,
    },
    colorDot: {
      width: 12,
      height: 12,
      borderRadius: 6,
      borderWidth: 1,
      borderColor: colors.border,
    },
    colorText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.medium,
      color: colors.textMuted,
      textTransform: 'capitalize',
    },
    colorTextActive: {
      color: colors.primary,
      fontWeight: FontWeight.semibold,
    },
    segmentGroup: {
      gap: 7,
    },
    segmentRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 7,
    },
    segment: {
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.border,
      paddingVertical: 8,
      paddingHorizontal: 11,
      backgroundColor: colors.bgMuted,
    },
    segmentActive: {
      backgroundColor: colors.primaryPale,
      borderColor: colors.primaryDim,
    },
    segmentText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.medium,
      color: colors.textMuted,
    },
    segmentTextActive: {
      color: colors.primary,
      fontWeight: FontWeight.semibold,
    },
    saveButton: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 48,
      borderRadius: Radius.md,
      backgroundColor: colors.primary,
      paddingHorizontal: Spacing.md,
      ...Shadows.md,
    },
    saveButtonDisabled: {
      opacity: 0.55,
    },
    saveButtonText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.lg,
      fontWeight: FontWeight.bold,
      color: colors.textOnPrimary,
    },
    savePanel: {
      gap: Spacing.md,
      borderRadius: Radius.lg,
      borderWidth: 1,
      borderColor: colors.primaryDim,
      backgroundColor: colors.bgAlt,
      padding: Spacing.md,
      ...Shadows.md,
    },
    savePanelDock: {
      marginTop: Spacing.xs,
      marginBottom: Spacing.lg,
    },
    savePanelCopy: {
      gap: 4,
    },
    savePanelTitle: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.lg,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    savePanelText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      color: colors.textMuted,
      lineHeight: 19,
    },
    savePanelActions: {
      flexDirection: 'row',
      gap: Spacing.sm,
    },
    resetButton: {
      flex: 1,
      minHeight: 48,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: Radius.md,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.bgMuted,
      paddingHorizontal: Spacing.sm,
    },
    resetButtonText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.bold,
      color: colors.textMuted,
    },
    previewCard: {
      gap: Spacing.md,
      borderRadius: Radius.lg,
      borderWidth: 1,
      borderColor: colors.primaryDim,
      backgroundColor: colors.primaryPale,
      padding: Spacing.md,
      ...Shadows.md,
    },
    previewCardCompact: {
      marginTop: Spacing.xs,
    },
    previewHeader: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      gap: Spacing.sm,
    },
    previewTitleWrap: {
      alignItems: 'center',
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.primaryDim,
      backgroundColor: colors.primaryPale,
      paddingVertical: 9,
      paddingHorizontal: Spacing.lg,
      alignSelf: 'center',
      ...Shadows.sm,
    },
    previewEyebrow: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xl,
      fontWeight: FontWeight.extrabold,
      color: colors.primary,
      letterSpacing: 0,
    },
    previewTitle: {
      marginTop: 2,
      fontFamily: Fonts.heading,
      fontSize: FontSize.xl,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    previewLines: {
      gap: 8,
    },
    previewLine: {
      gap: 3,
      borderRadius: Radius.sm,
      borderWidth: 1,
      borderColor: colors.borderLight,
      backgroundColor: colors.bgAlt,
      padding: Spacing.sm,
    },
    previewLineLabelWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    previewLineLabel: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
      color: colors.textMuted,
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    previewLineValue: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.semibold,
      color: colors.text,
      lineHeight: 20,
    },
    warningBox: {
      flexDirection: 'row',
      gap: 8,
      borderRadius: Radius.sm,
      borderWidth: 1,
      borderColor: colors.amberDeep,
      backgroundColor: colors.amberPale,
      padding: Spacing.sm,
    },
    warningText: {
      flex: 1,
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      color: colors.textMuted,
      lineHeight: 18,
    },
    equipmentCard: {
      gap: Spacing.sm,
      backgroundColor: colors.bgAlt,
      borderRadius: Radius.md,
      borderWidth: 1,
      borderColor: colors.borderLight,
      padding: Spacing.md,
      ...Shadows.sm,
    },
    currentCard: {
      borderColor: colors.borderLight,
      backgroundColor: colors.bgAlt,
    },
    cardHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: Spacing.sm,
    },
    cardTitleBlock: {
      flex: 1,
      gap: 3,
    },
    cardEyebrow: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      fontWeight: FontWeight.semibold,
      color: colors.textFaint,
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    cardTitle: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xl,
      fontWeight: FontWeight.bold,
      color: colors.text,
      marginTop: 2,
    },
    setupHero: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
      borderRadius: Radius.md,
      borderWidth: 1,
      borderColor: colors.borderLight,
      backgroundColor: colors.bgMuted,
      padding: Spacing.sm,
    },
    bladeIcon: {
      width: 40,
      height: 40,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: colors.primaryDim,
      backgroundColor: colors.primaryPale,
    },
    setupHeroCopy: {
      flex: 1,
      gap: 2,
      minWidth: 0,
    },
    bladeLabel: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
      color: colors.textFaint,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    bladeValue: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.semibold,
      color: colors.text,
    },
    detailGrid: {
      gap: 8,
    },
    detailTile: {
      gap: 2,
      borderRadius: Radius.sm,
      borderWidth: 1,
      borderColor: colors.borderLight,
      backgroundColor: colors.bg,
      padding: Spacing.sm,
    },
    detailTileHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    tinyColorDot: {
      width: 9,
      height: 9,
      borderRadius: 5,
      borderWidth: 1,
      borderColor: colors.border,
    },
    detailLabel: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      fontWeight: FontWeight.semibold,
      color: colors.textMuted,
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    detailValue: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.semibold,
      color: colors.text,
    },
    metaRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    metaPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      borderRadius: 999,
      backgroundColor: colors.bgMuted,
      paddingVertical: 6,
      paddingHorizontal: 9,
      borderWidth: 1,
      borderColor: colors.borderLight,
    },
    metaPillText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.base,
      fontWeight: FontWeight.semibold,
      color: colors.textMuted,
    },
    metaPillIconText: {
      fontFamily: Fonts.heading,
      fontSize: 11,
      fontWeight: FontWeight.bold,
      color: colors.primaryMid,
      lineHeight: 13,
    },
    sectionTitle: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.lg,
      fontWeight: FontWeight.bold,
      color: colors.textMuted,
      marginTop: Spacing.xs,
    },
    historyHeader: {
      gap: 2,
      marginTop: Spacing.sm,
    },
    historyEmpty: {
      borderRadius: Radius.md,
      borderWidth: 1,
      borderColor: colors.borderLight,
      backgroundColor: colors.bgAlt,
      padding: Spacing.md,
    },
    emptyState: {
      alignItems: 'center',
      gap: Spacing.xs,
      backgroundColor: colors.bgAlt,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.borderLight,
      padding: Spacing.lg,
      ...Shadows.sm,
    },
    emptyTitle: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xl,
      fontWeight: FontWeight.bold,
      color: colors.text,
      textAlign: 'center',
    },
    emptyText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      color: colors.textFaint,
      textAlign: 'center',
    },
    secondaryButton: {
      marginTop: Spacing.xs,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.primaryDim,
      backgroundColor: colors.primaryPale,
      paddingVertical: 9,
      paddingHorizontal: Spacing.md,
    },
    secondaryButtonText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.semibold,
      color: colors.primary,
    },
  });
}
