import { StyleSheet } from 'react-native';
import type { ThemeColors } from '../theme';
import { Fonts, FontSize, FontWeight, Radius, Shadows, Spacing } from '../theme';

export function createSelectStyles(colors: ThemeColors) {
  return StyleSheet.create({
    field: {
      gap: 6,
    },
    label: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      fontWeight: FontWeight.semibold,
      color: colors.textMuted,
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    inputWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      height: 46,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.bgAlt,
      paddingHorizontal: Spacing.sm,
      gap: Spacing.xs,
    },
    inputValue: {
      flex: 1,
      fontFamily: Fonts.body,
      fontSize: FontSize.lg,
      color: colors.text,
    },
    placeholder: {
      color: colors.textFaint,
    },
    inputDisabled: {
      opacity: 0.55,
      backgroundColor: colors.bgMuted,
    },
    dropdownBackdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: colors.overlayLight,
    },
    sheetContent: {
      flex: 1,
    },
    webBackdrop: {
      flex: 1,
      justifyContent: 'flex-end',
      alignItems: 'center',
    },
    webSheet: {
      width: '100%',
      maxWidth: 430,
      maxHeight: '70%',
      minHeight: 320,
      borderTopLeftRadius: Radius.xl,
      borderTopRightRadius: Radius.xl,
      paddingTop: Spacing.sm,
      overflow: 'hidden',
    },
    sheetHeader: {
      paddingHorizontal: Spacing.md,
      paddingTop: 4,
      paddingBottom: Spacing.sm,
      gap: Spacing.sm,
    },
    sheetTitle: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xl,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    sheetSearch: {
      height: 44,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.bg,
      paddingHorizontal: Spacing.sm,
      fontFamily: Fonts.body,
      fontSize: FontSize.lg,
      color: colors.text,
    },
    optionRow: {
      minHeight: 42,
      justifyContent: 'center',
      paddingVertical: 10,
      paddingHorizontal: Spacing.sm,
      borderBottomWidth: 1,
      borderBottomColor: colors.borderLight,
    },
    optionRowPressed: {
      backgroundColor: colors.primaryPale,
    },
    optionText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      color: colors.text,
    },
    emptyOption: {
      paddingVertical: Spacing.md,
      paddingHorizontal: Spacing.sm,
      textAlign: 'center',
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      color: colors.textFaint,
    },
    colorSelect: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.bgMuted,
      paddingVertical: 7,
      paddingHorizontal: 9,
      minHeight: 34,
    },
    colorSelectDot: {
      width: 11,
      height: 11,
      borderRadius: 6,
      borderWidth: 1,
      borderColor: colors.border,
    },
    colorSelectText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.base,
      fontWeight: FontWeight.semibold,
      color: colors.text,
      textTransform: 'capitalize',
    },
    colorDropdown: {
      position: 'absolute',
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.bgAlt,
      overflow: 'hidden',
      elevation: 16,
      ...Shadows.sm,
    },
    colorOption: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      minHeight: 38,
      paddingVertical: 9,
      paddingHorizontal: 10,
      borderBottomWidth: 1,
      borderBottomColor: colors.borderLight,
    },
    colorOptionActive: {
      backgroundColor: colors.primaryPale,
    },
    colorOptionText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.medium,
      color: colors.textMuted,
      textTransform: 'capitalize',
    },
    colorOptionTextActive: {
      color: colors.primary,
      fontWeight: FontWeight.bold,
    },
  });
}

export function createStyles(colors: ThemeColors) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.bg,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: colors.bgAlt,
      height: 52,
      paddingHorizontal: Spacing.md,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      ...Shadows.bar,
    },
    headerTitle: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xxl,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    hero: {
      alignItems: 'flex-start',
      marginHorizontal: Spacing.md,
      marginTop: Spacing.md,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.borderLight,
      backgroundColor: colors.bgAlt,
      paddingVertical: Spacing.lg,
      paddingHorizontal: Spacing.md,
      ...Shadows.md,
    },
    heroCopy: {
      gap: 6,
    },
    heroTitle: {
      fontFamily: Fonts.heading,
      fontSize: 28,
      fontWeight: FontWeight.extrabold,
      color: colors.text,
    },
    heroText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.lg,
      lineHeight: 21,
      color: colors.textMuted,
    },
    tabs: {
      flexDirection: 'row',
      gap: 8,
      paddingHorizontal: Spacing.md,
      paddingTop: Spacing.sm,
      paddingBottom: Spacing.md,
      backgroundColor: colors.bg,
    },
    tab: {
      flex: 1,
      alignItems: 'center',
      borderRadius: 8,
      paddingVertical: 10,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.bgAlt,
      ...Shadows.sm,
    },
    tabActive: {
      backgroundColor: colors.primaryPale,
      borderColor: colors.primaryDim,
    },
    tabText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.semibold,
      color: colors.textMuted,
    },
    tabTextActive: {
      color: colors.primary,
    },
    scroll: {
      flex: 1,
    },
    content: {
      paddingHorizontal: Spacing.md,
      gap: Spacing.md,
    },
    inlineError: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xs,
      marginHorizontal: Spacing.md,
      marginBottom: Spacing.sm,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.redBorder,
      backgroundColor: colors.redPale,
      padding: Spacing.sm,
    },
    inlineErrorText: {
      flex: 1,
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.medium,
      color: colors.red,
    },
    group: {
      gap: Spacing.md,
      backgroundColor: colors.bgAlt,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.borderLight,
      padding: Spacing.md,
      ...Shadows.sm,
    },
    groupHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
    },
    groupIcon: {
      width: 38,
      height: 38,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      ...Shadows.sm,
    },
    groupTitleWrap: {
      flex: 1,
      gap: 2,
    },
    groupTitle: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xl,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    groupSubtitle: {
      fontFamily: Fonts.body,
      fontSize: FontSize.base,
      color: colors.textFaint,
    },
    inlineHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    inputLabel: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      fontWeight: FontWeight.semibold,
      color: colors.textMuted,
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    colorGroup: {
      gap: 10,
      backgroundColor: colors.bgAlt,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.borderLight,
      padding: Spacing.md,
      ...Shadows.sm,
    },
    colorRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    colorChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
      paddingVertical: 9,
      paddingHorizontal: 11,
      backgroundColor: colors.bgMuted,
    },
    colorChipActive: {
      borderColor: colors.primary,
      backgroundColor: colors.primaryPale,
    },
    colorDot: {
      width: 12,
      height: 12,
      borderRadius: 6,
      borderWidth: 1,
      borderColor: colors.border,
    },
    colorText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.medium,
      color: colors.textMuted,
      textTransform: 'capitalize',
    },
    colorTextActive: {
      color: colors.primary,
      fontWeight: FontWeight.semibold,
    },
    segmentGroup: {
      gap: 8,
    },
    segmentRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    segment: {
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
      paddingVertical: 10,
      paddingHorizontal: 12,
      backgroundColor: colors.bgMuted,
    },
    segmentActive: {
      backgroundColor: colors.primaryPale,
      borderColor: colors.primaryDim,
    },
    segmentText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.medium,
      color: colors.textMuted,
    },
    segmentTextActive: {
      color: colors.primary,
      fontWeight: FontWeight.semibold,
    },
    saveButton: {
      alignItems: 'center',
      justifyContent: 'center',
      height: 52,
      borderRadius: 8,
      backgroundColor: colors.primary,
      ...Shadows.md,
    },
    saveButtonDisabled: {
      opacity: 0.55,
    },
    saveButtonText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.lg,
      fontWeight: FontWeight.bold,
      color: colors.textOnPrimary,
    },
    equipmentCard: {
      gap: Spacing.md,
      backgroundColor: colors.bgAlt,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.borderLight,
      padding: Spacing.md,
      ...Shadows.sm,
    },
    currentCard: {
      borderColor: colors.primaryDim,
      backgroundColor: colors.primaryPale,
    },
    cardHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: Spacing.sm,
    },
    cardTitleBlock: {
      flex: 1,
      gap: 3,
    },
    cardEyebrow: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      fontWeight: FontWeight.semibold,
      color: colors.textFaint,
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    cardTitle: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xxl,
      fontWeight: FontWeight.bold,
      color: colors.text,
      marginTop: 2,
    },
    cardSubtitle: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.medium,
      color: colors.textMuted,
    },
    latestPill: {
      borderRadius: 8,
      backgroundColor: colors.primary,
      paddingVertical: 4,
      paddingHorizontal: 8,
    },
    latestText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      fontWeight: FontWeight.bold,
      color: colors.textOnPrimary,
    },
    bladeStrip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.primaryDim,
      backgroundColor: colors.bgAlt,
      padding: Spacing.sm,
    },
    bladeIcon: {
      width: 36,
      height: 36,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primaryPale,
    },
    bladeTextWrap: {
      flex: 1,
      gap: 2,
    },
    bladeLabel: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
      color: colors.textFaint,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    bladeValue: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.semibold,
      color: colors.text,
    },
    detailGrid: {
      flexDirection: 'row',
      gap: Spacing.sm,
    },
    detailTile: {
      flex: 1,
      gap: 3,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.borderLight,
      backgroundColor: colors.bgAlt,
      padding: Spacing.sm,
    },
    detailTileHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    tinyColorDot: {
      width: 9,
      height: 9,
      borderRadius: 5,
      borderWidth: 1,
      borderColor: colors.border,
    },
    detailLabel: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      fontWeight: FontWeight.semibold,
      color: colors.textMuted,
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    detailValue: {
      fontFamily: Fonts.body,
      fontSize: FontSize.lg,
      fontWeight: FontWeight.semibold,
      color: colors.text,
    },
    metaRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    metaPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      borderRadius: 8,
      backgroundColor: colors.bgMuted,
      paddingVertical: 7,
      paddingHorizontal: 9,
      borderWidth: 1,
      borderColor: colors.borderLight,
    },
    metaPillText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.base,
      fontWeight: FontWeight.semibold,
      color: colors.textMuted,
    },
    metaPillIconText: {
      fontFamily: Fonts.heading,
      fontSize: 11,
      fontWeight: FontWeight.bold,
      color: colors.primaryMid,
      lineHeight: 13,
    },
    sectionTitle: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.semibold,
      color: colors.textMuted,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
      marginTop: Spacing.xs,
    },
    emptyState: {
      alignItems: 'center',
      gap: Spacing.xs,
      backgroundColor: colors.bgAlt,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.borderLight,
      padding: Spacing.lg,
      ...Shadows.sm,
    },
    emptyTitle: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xl,
      fontWeight: FontWeight.bold,
      color: colors.text,
      textAlign: 'center',
    },
    emptyText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      color: colors.textFaint,
      textAlign: 'center',
    },
    secondaryButton: {
      marginTop: Spacing.xs,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.primaryDim,
      backgroundColor: colors.primaryPale,
      paddingVertical: 9,
      paddingHorizontal: Spacing.md,
    },
    secondaryButtonText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.semibold,
      color: colors.primary,
    },
  });
}
