import { StyleSheet } from 'react-native';
import type { ThemeColors } from '../theme';
import { Fonts, FontSize, FontWeight, Spacing, Radius, Shadows } from '../theme';

export function createStyles(colors: ThemeColors, isDark: boolean) {
  const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.bg,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: isDark ? colors.bgAlt : colors.primary,
      paddingVertical: 10,
      paddingHorizontal: Spacing.md,
      minHeight: 52,
      ...Shadows.bar,
    },
    headerTitle: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xxl,
      fontWeight: FontWeight.bold,
      color: isDark ? colors.text : colors.textOnPrimary,
    },
    headerRight: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xs,
    },
    headerCityBtn: {
      maxWidth: 120,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: 8,
      paddingVertical: 5,
      borderRadius: Radius.sm,
      backgroundColor: isDark ? colors.bgMuted : '#ffffff22',
    },
    headerCityText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      fontWeight: FontWeight.semibold,
      color: isDark ? colors.text : colors.textOnPrimary,
    },
    headerBack: {
      padding: 4,
      marginLeft: -4,
    },
    headerSpacer: {
      width: 34,
    },
    detailContent: {
      paddingHorizontal: 20,
      paddingTop: Spacing.md,
    },
    detailLoading: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    fab: {
      position: 'absolute',
      bottom: 24,
      right: 20,
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: colors.accentBright,
      alignItems: 'center',
      justifyContent: 'center',
      ...Shadows.lg,
    },
    scroll: {
      flex: 1,
    },
    cityContextCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 9,
      marginHorizontal: Spacing.md,
      marginTop: Spacing.sm,
      marginBottom: Spacing.xs,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: isDark ? colors.borderLight : colors.primaryDim,
      backgroundColor: isDark ? colors.bgAlt : colors.primaryPale,
      paddingVertical: 8,
      paddingHorizontal: 10,
    },
    cityContextIcon: {
      width: 32,
      height: 32,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primary,
    },
    cityContextCopy: {
      flex: 1,
      minWidth: 0,
    },
    cityContextTitle: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.lg,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    tabs: {
      flexDirection: 'row',
      paddingHorizontal: Spacing.md,
    },
    tab: {
      flex: 1,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    tabActive: {
      borderBottomWidth: 2,
      borderBottomColor: colors.accentBright,
    },
    tabText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.lg,
      color: colors.textFaint,
    },
    tabTextActive: {
      fontWeight: FontWeight.semibold,
      color: colors.accentBright,
    },
    eventsList: {
      padding: Spacing.md,
      paddingTop: Spacing.sm,
      gap: Spacing.sm,
    },
    readyChallengeBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
      marginHorizontal: Spacing.md,
      marginTop: Spacing.sm,
      borderRadius: Radius.md,
      borderWidth: 1,
      padding: Spacing.sm,
      backgroundColor: colors.bgAlt,
      ...Shadows.md,
    },
    readyChallengeIcon: {
      width: 38,
      height: 38,
      borderRadius: Radius.sm,
      alignItems: 'center',
      justifyContent: 'center',
    },
    readyChallengeCopy: {
      flex: 1,
      gap: 2,
    },
    readyChallengeTitle: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
      color: colors.textMuted,
    },
    readyChallengeText: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.lg,
      fontWeight: FontWeight.bold,
      lineHeight: 18,
      color: colors.text,
    },
    eventCard: {
      padding: Spacing.md,
      gap: Spacing.sm,
    },
    eventTop: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    eventDateWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xs,
    },
    eventDate: {
      fontFamily: Fonts.body,
      fontSize: FontSize.lg,
      fontWeight: FontWeight.semibold,
      color: colors.text,
    },
    eventBadge: {
      borderRadius: Radius.md,
      paddingVertical: 3,
      paddingHorizontal: Spacing.xs,
    },
    eventBadgeText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      fontWeight: FontWeight.semibold,
    },
    eventMid: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
    },
    eventLocation: {
      flex: 1,
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      color: colors.textMuted,
    },
    eventBot: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    avatarStack: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    stackAvatar: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 2,
      borderColor: colors.bgAlt,
    },
    stackInitials: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
      color: colors.textOnPrimary,
    },
    attendeesText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      color: colors.textFaint,
      marginLeft: Spacing.xs,
    },
    joinBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      borderRadius: Radius.md,
      paddingVertical: 8,
      paddingHorizontal: Spacing.md,
      gap: 6,
      ...Shadows.sm,
    },
    joinedBtn: {
      backgroundColor: colors.primary,
      ...Shadows.md,
    },
    notJoinedBtn: {
      borderWidth: 1.5,
      borderColor: colors.primary,
    },
    joinText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.base,
      fontWeight: FontWeight.semibold,
    },
    joinedText: {
      color: colors.textOnPrimary,
    },
    notJoinedText: {
      color: colors.primary,
    },
    amaturNavSection: {
      marginBottom: Spacing.md,
      gap: 10,
    },
    amaturNavRow: {
      flexDirection: 'row',
      gap: Spacing.xs,
    },
    amaturNavBtn: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.bgMuted,
      borderRadius: Radius.sm,
      height: 32,
      gap: 5,
    },
    amaturNavBtnText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.base,
      fontWeight: FontWeight.semibold,
      color: colors.text,
    },
    amaturMapWrap: {
      borderRadius: Radius.md,
      overflow: 'hidden',
      marginBottom: Spacing.md,
      height: 160,
    },
    amaturMap: {
      width: '100%',
      height: '100%',
    },
    amaturSpotsRow: {
      flexDirection: 'row',
      gap: 6,
    },
    amaturSpotChip: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.bgMuted,
      borderRadius: Radius.sm,
      paddingVertical: 3,
      paddingHorizontal: 8,
      gap: 4,
    },
    amaturSpotLabel: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.semibold,
      color: colors.textFaint,
    },
    amaturSpotValue: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    amaturSpotsDetail: {
      backgroundColor: colors.bgMuted,
      borderRadius: Radius.md,
      padding: Spacing.sm,
      gap: 6,
      marginBottom: Spacing.md,
    },
    amaturSpotDetailRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    amaturSpotDetailLabel: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.semibold,
      color: colors.text,
    },
    amaturSpotDetailValue: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      color: colors.textMuted,
    },
    amaturCatRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 4,
    },
    amaturCatText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      color: colors.textMuted,
    },
    amaturAttribution: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      color: colors.textFaint,
      textAlign: 'center',
      paddingVertical: Spacing.md,
    },
    challengeSectionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: Spacing.sm,
    },
    challengeHeaderLeft: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    challengeHeaderTitle: {
      marginBottom: 0,
    },
    challengeCountPill: {
      minWidth: 22,
      paddingHorizontal: 7,
      paddingVertical: 2,
      borderRadius: 999,
      backgroundColor: colors.primaryPale,
      alignItems: 'center',
      justifyContent: 'center',
    },
    challengeCountPillText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
      color: colors.primary,
    },
    challengeAddIconBtn: {
      width: 34,
      height: 34,
      borderRadius: Radius.sm,
      borderWidth: 1,
      borderColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.bgAlt,
    },
    challengeAddPill: {
      minHeight: 34,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      borderRadius: Radius.sm,
      borderWidth: 1,
      borderColor: colors.primary,
      backgroundColor: colors.primaryPale,
      paddingHorizontal: 10,
      paddingVertical: 7,
      flexShrink: 0,
    },
    challengeAddPillText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      fontWeight: FontWeight.bold,
      color: colors.primary,
    },
    challengeSectionHint: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      color: colors.textMuted,
      marginTop: 6,
    },
    challengeEmptyState: {
      marginTop: Spacing.sm,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      borderRadius: Radius.md,
      borderWidth: 1,
      borderColor: colors.borderLight,
      backgroundColor: colors.bgAlt,
      paddingVertical: Spacing.lg,
      paddingHorizontal: Spacing.md,
    },
    challengeEmptyIcon: {
      width: 40,
      height: 40,
      borderRadius: 999,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primaryPale,
    },
    challengeEmptyTitle: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      color: colors.textMuted,
      textAlign: 'center',
    },
    challengeEmptyCta: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      fontWeight: FontWeight.bold,
      color: colors.primary,
      marginTop: 2,
    },
    eventChallengePicker: {
      gap: Spacing.md,
      borderRadius: Radius.md,
      backgroundColor: colors.bgAlt,
      padding: Spacing.sm,
      marginTop: Spacing.sm,
      borderWidth: 1,
      borderColor: colors.borderLight,
      ...Shadows.sm,
    },
    eventChallengePickerIntro: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
      borderRadius: Radius.sm,
      backgroundColor: colors.bgMuted,
      padding: Spacing.sm,
    },
    eventChallengeIntroIcon: {
      width: 32,
      height: 32,
      borderRadius: Radius.sm,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.bgAlt,
    },
    eventChallengeIntroCopy: {
      flex: 1,
      gap: 2,
    },
    eventChallengeIntroTitle: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.lg,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    eventChallengeIntroText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      color: colors.textMuted,
      lineHeight: 18,
    },
    eventChallengeCurrentWrap: {
      gap: Spacing.sm,
    },
    eventChallengeTrackGrid: {
      gap: Spacing.xs,
    },
    eventChallengeTrackRow: {
      flexDirection: 'row',
      gap: Spacing.xs,
    },
    eventChallengeTrack: {
      flex: 1,
      minHeight: 86,
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      borderRadius: Radius.sm,
      borderWidth: 1,
      borderColor: colors.borderLight,
      backgroundColor: colors.bg,
      paddingHorizontal: 5,
      paddingVertical: 12,
      ...Shadows.sm,
    },
    eventChallengeTrackIcon: {
      width: 36,
      height: 36,
      borderRadius: Radius.sm,
      alignItems: 'center',
      justifyContent: 'center',
    },
    eventChallengeTrackText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
      color: colors.textMuted,
      textAlign: 'center',
      width: '100%',
    },
    eventChallengeChoiceList: {
      gap: Spacing.xs,
    },
    eventChallengeChoice: {
      overflow: 'hidden',
      borderRadius: Radius.sm,
      backgroundColor: colors.bg,
      borderWidth: 1,
      borderColor: colors.borderLight,
      padding: Spacing.md,
      gap: Spacing.xs,
    },
    eventChallengeChoiceFeatured: {
      borderColor: colors.primary,
      backgroundColor: colors.bg,
    },
    eventChallengeChoiceTop: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: Spacing.sm,
    },
    eventChallengeChoiceTitle: {
      flex: 1,
      fontFamily: Fonts.heading,
      fontSize: FontSize.lg,
      fontWeight: FontWeight.bold,
      color: colors.text,
      lineHeight: 21,
    },
    eventChallengeChoiceBadge: {
      borderRadius: Radius.sm,
      backgroundColor: colors.bgMuted,
      paddingHorizontal: 7,
      paddingVertical: 4,
    },
    eventChallengeChoiceBadgeText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
      color: colors.textMuted,
    },
    eventChallengeChoiceCta: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      fontWeight: FontWeight.bold,
      color: colors.primary,
    },
    eventChallengeList: {
      gap: Spacing.sm,
      marginTop: Spacing.sm,
    },
    eventChallengeCard: {
      borderRadius: Radius.md,
      backgroundColor: colors.bgAlt,
      borderWidth: 1,
      borderColor: colors.borderLight,
      padding: Spacing.md,
      gap: Spacing.sm,
      ...Shadows.sm,
    },
    eventChallengeCardTop: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: Spacing.sm,
    },
    eventChallengeIcon: {
      width: 42,
      height: 42,
      borderRadius: 21,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'transparent',
      overflow: 'hidden',
      flexShrink: 0,
    },
    eventChallengeCardCopy: {
      flex: 1,
      gap: 5,
      minWidth: 0,
    },
    eventChallengeCardTitleRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: Spacing.xs,
    },
    eventChallengeCardTitle: {
      flex: 1,
      fontFamily: Fonts.heading,
      fontSize: FontSize.lg,
      fontWeight: FontWeight.bold,
      color: colors.text,
      lineHeight: 22,
    },
    eventChallengeTrackPill: {
      flexShrink: 0,
      borderRadius: Radius.sm,
      backgroundColor: colors.bgMuted,
      paddingHorizontal: 7,
      paddingVertical: 4,
    },
    eventChallengeTrackPillText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
      color: colors.textMuted,
    },
    eventChallengeCardMeta: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      color: colors.textMuted,
      lineHeight: 18,
    },
    eventAwardBtn: {
      alignItems: 'center',
      borderRadius: Radius.sm,
      backgroundColor: colors.greenDeep,
      paddingVertical: 10,
    },
    eventAwardBtnText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.bold,
      color: colors.textOnPrimary,
    },
    eventChallengeStatus: {
      alignSelf: 'flex-start',
      borderRadius: Radius.sm,
      paddingHorizontal: 9,
      paddingVertical: 5,
    },
    eventChallengePending: {
      backgroundColor: colors.amberPale,
    },
    eventChallengeAwarded: {
      backgroundColor: colors.primaryPale,
    },
    eventChallengeStatusText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    disabledChallenge: {
      opacity: 0.65,
    },
  });

  /* ===== Bottom Sheet (modal) styles ===== */
  const ms = StyleSheet.create({
    overlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.4)',
      justifyContent: 'flex-end',
      alignItems: 'center',
    },
    sheet: {
      backgroundColor: colors.bgAlt,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      paddingHorizontal: 20,
      maxHeight: '85%',
      width: '100%',
      maxWidth: 430,
      ...Shadows.lg,
    },
    handleWrap: {
      alignItems: 'center',
      paddingVertical: 10,
    },
    handle: {
      width: 36,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.border,
    },
    titleRow: {
      alignItems: 'center',
      gap: Spacing.sm,
      marginBottom: Spacing.md,
    },
    title: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xxxl,
      fontWeight: FontWeight.bold,
      color: colors.text,
      textAlign: 'center',
      alignSelf: 'stretch',
    },
    titleBadge: {
      alignSelf: 'center',
    },
    heroDescription: {
      borderRadius: Radius.md,
      borderWidth: 1,
      borderColor: colors.borderLight,
      backgroundColor: colors.bgMuted,
      paddingVertical: Spacing.sm,
      paddingHorizontal: Spacing.md,
      marginBottom: Spacing.md,
    },
    heroDescriptionText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.lg,
      color: colors.text,
      lineHeight: 22,
    },
    heroParticipants: {
      borderRadius: Radius.md,
      borderWidth: 1,
      borderColor: colors.borderLight,
      backgroundColor: colors.bgAlt,
      padding: Spacing.sm,
      marginBottom: Spacing.md,
      gap: Spacing.sm,
    },
    heroParticipantsHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: Spacing.sm,
    },
    heroParticipantsLoading: {
      alignSelf: 'flex-start',
      marginVertical: 4,
    },
    heroAvatarRail: {
      gap: 10,
      paddingRight: Spacing.sm,
    },
    heroParticipantItem: {
      width: 54,
      alignItems: 'center',
      gap: 5,
    },
    heroAvatar: {
      width: 38,
      height: 38,
      borderRadius: 19,
      borderWidth: 1,
      borderColor: colors.bgAlt,
      alignItems: 'center',
      justifyContent: 'center',
    },
    heroAvatarFriend: {
      borderColor: colors.primary,
    },
    heroAvatarText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
      color: colors.textOnPrimary,
    },
    heroParticipantName: {
      width: 54,
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.semibold,
      color: colors.textMuted,
      textAlign: 'center',
    },
    heroParticipantsLabel: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
      color: colors.textMuted,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    heroParticipantsValue: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.lg,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    infoBlock: {
      gap: 10,
      marginBottom: Spacing.lg,
    },
    infoRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    infoText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.lg,
      color: colors.textMuted,
      flex: 1,
    },
    durationChip: {
      flexDirection: 'row',
      alignItems: 'center',
      flexShrink: 0,
      gap: 4,
      backgroundColor: colors.bgMuted,
      borderRadius: Radius.sm,
      paddingVertical: 2,
      paddingHorizontal: 8,
      marginLeft: 'auto',
    },
    durationChipText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      fontWeight: FontWeight.semibold,
      color: colors.textFaint,
    },
    section: {
      marginBottom: Spacing.lg,
    },
    sectionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 10,
    },
    sectionTitle: {
      fontFamily: Fonts.body,
      fontSize: FontSize.lg,
      fontWeight: FontWeight.bold,
      color: colors.text,
      marginBottom: 6,
    },
    countBadge: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.semibold,
      color: colors.accentBright,
      marginBottom: 6,
    },
    showMoreText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.semibold,
      color: colors.primary,
      marginTop: 4,
    },
    emptyText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      color: colors.textFaint,
      fontStyle: 'italic',
    },
    participantList: {
      gap: Spacing.xs,
    },
    pRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingVertical: 4,
    },
    pAvatar: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    pAvatarFriend: {
      backgroundColor: colors.purpleMid,
    },
    pInitials: {
      fontFamily: Fonts.body,
      fontSize: FontSize.base,
      fontWeight: FontWeight.bold,
      color: colors.textOnPrimary,
    },
    pHScroll: {
      marginHorizontal: -4,
    },
    pHScrollContent: {
      gap: Spacing.sm,
      paddingHorizontal: 4,
    },
    pHItem: {
      alignItems: 'center',
      width: 52,
    },
    pHName: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      color: colors.textMuted,
      marginTop: 4,
      textAlign: 'center',
    },
    pOrgBadge: {
      position: 'absolute',
      bottom: -2,
      right: -2,
      width: 14,
      height: 14,
      borderRadius: 7,
      backgroundColor: colors.bgAlt,
      alignItems: 'center',
      justifyContent: 'center',
    },
    pInfo: {
      flex: 1,
    },
    pName: {
      fontFamily: Fonts.body,
      fontSize: FontSize.lg,
      fontWeight: FontWeight.medium,
      color: colors.text,
    },
    pBadge: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      color: colors.textFaint,
    },
    updateInline: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      backgroundColor: colors.bgMuted,
      borderRadius: Radius.md,
      marginBottom: Spacing.md,
      paddingLeft: Spacing.sm,
      paddingVertical: 4,
    },
    updateInlineInput: {
      flex: 1,
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      color: colors.text,
      maxHeight: 80,
      paddingVertical: 6,
    },
    updateInlineBtn: {
      padding: 10,
    },
    actions: {
      flexDirection: 'row',
      gap: 10,
      marginTop: 4,
    },
    actionBtn: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: Radius.lg,
      paddingVertical: 14,
      gap: 8,
    },
    actionJoin: {
      backgroundColor: colors.primary,
    },
    actionLeave: {
      backgroundColor: colors.redPale,
      borderWidth: 1,
      borderColor: colors.red,
    },
    actionSecondary: {
      backgroundColor: colors.primaryPale,
      borderWidth: 1,
      borderColor: colors.primary,
    },
    actionSecondaryText: {
      color: colors.primary,
    },
    feedbackSection: {
      marginTop: Spacing.md,
      gap: Spacing.xs,
    },
    feedbackSummary: {
      flexDirection: 'row',
      gap: Spacing.md,
      marginBottom: Spacing.xs,
    },
    feedbackStat: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      fontWeight: FontWeight.semibold,
      color: colors.primaryMid,
    },
    feedbackCard: {
      backgroundColor: colors.bg,
      borderRadius: Radius.sm,
      padding: Spacing.sm,
      gap: 4,
      borderWidth: 1,
      borderColor: colors.borderLight,
    },
    feedbackHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    feedbackName: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      fontWeight: FontWeight.semibold,
      color: colors.text,
    },
    feedbackRating: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      color: colors.accent,
    },
    feedbackBody: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      color: colors.textMuted,
    },
    dangerZone: {
      marginTop: 20,
      paddingTop: 16,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.borderLight,
      gap: 4,
    },
    dangerBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      paddingVertical: 10,
      paddingHorizontal: Spacing.md,
      backgroundColor: colors.redPale,
      borderWidth: 1,
      borderColor: colors.red,
      borderRadius: Radius.md,
    },
    dangerBtnText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.base,
      fontWeight: FontWeight.semibold,
      color: colors.red,
    },
    confirmOverlay: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(0,0,0,0.48)',
      padding: Spacing.lg,
    },
    confirmCard: {
      width: '100%',
      maxWidth: 380,
      borderRadius: Radius.lg,
      borderWidth: 1,
      borderColor: colors.borderLight,
      backgroundColor: colors.bgAlt,
      padding: Spacing.lg,
      alignItems: 'center',
      gap: Spacing.sm,
      ...Shadows.lg,
    },
    confirmIcon: {
      width: 50,
      height: 50,
      borderRadius: 25,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 2,
    },
    confirmIconSafe: {
      backgroundColor: colors.primaryPale,
    },
    confirmIconDanger: {
      backgroundColor: colors.redPale,
    },
    confirmTitle: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xxl,
      fontWeight: FontWeight.bold,
      color: colors.text,
      textAlign: 'center',
    },
    confirmText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      color: colors.textMuted,
      lineHeight: 21,
      textAlign: 'center',
    },
    confirmActions: {
      flexDirection: 'row',
      gap: Spacing.sm,
      marginTop: Spacing.sm,
      alignSelf: 'stretch',
    },
    confirmBtn: {
      flex: 1,
      minHeight: 46,
      borderRadius: Radius.md,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: Spacing.md,
    },
    confirmCancelBtn: {
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.bg,
    },
    confirmPrimaryBtn: {
      backgroundColor: colors.primary,
    },
    confirmDangerBtn: {
      backgroundColor: colors.red,
    },
    confirmCancelText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    confirmPrimaryText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.bold,
      color: colors.textOnPrimary,
    },
    actionText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.lg,
      fontWeight: FontWeight.semibold,
    },
    actionJoinText: {
      color: colors.textOnPrimary,
    },
    actionLeaveText: {
      color: colors.red,
    },
    closeBtn: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: Radius.md,
      paddingVertical: 8,
      borderWidth: 1,
      borderColor: colors.border,
    },
    closeBtnText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.lg,
      fontWeight: FontWeight.semibold,
      color: colors.textMuted,
    },
  });

  return { styles, ms };
}
