import { StyleSheet } from 'react-native';
import type { ThemeColors } from '../theme';
import { Fonts, FontSize, FontWeight, Radius, Shadows, Spacing } from '../theme';

export function createStyles(colors: ThemeColors) {
  const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.bg,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: colors.bgAlt,
      height: 52,
      paddingHorizontal: Spacing.md,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      ...Shadows.bar,
    },
    headerTitle: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xxl,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    inviteBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.primary,
      borderRadius: 16,
      paddingVertical: 6,
      paddingHorizontal: Spacing.sm,
      gap: 6,
      ...Shadows.md,
    },
    inviteBtnText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.semibold,
      color: colors.textOnPrimary,
    },
    scroll: {
      flex: 1,
    },
    searchWrap: {
      padding: Spacing.sm,
      paddingHorizontal: Spacing.md,
    },
    searchBar: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.bgMuted,
      borderRadius: Radius.md,
      height: 40,
      paddingHorizontal: Spacing.sm,
      gap: Spacing.xs,
      ...Shadows.sm,
    },
    searchInput: {
      flex: 1,
      fontFamily: Fonts.body,
      fontSize: FontSize.lg,
      color: colors.text,
      height: 40,
      padding: 0,
    },
    tabs: {
      flexDirection: 'row',
      paddingHorizontal: Spacing.md,
    },
    tab: {
      flex: 1,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    tabActive: {
      borderBottomWidth: 2,
      borderBottomColor: colors.primary,
    },
    tabText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.lg,
      color: colors.textFaint,
    },
    tabTextActive: {
      fontWeight: FontWeight.semibold,
      color: colors.primary,
    },
    section: {
      paddingHorizontal: Spacing.md,
      paddingTop: Spacing.md,
      paddingBottom: Spacing.xs,
      gap: 10,
    },
    sectionLabel: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.semibold,
      color: colors.textMuted,
    },
    inviteCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.purplePale,
      borderRadius: 12,
      padding: Spacing.sm,
      gap: Spacing.sm,
      borderWidth: 1,
      borderColor: colors.purpleMid,
      ...Shadows.sm,
    },
    inviteAvatar: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
    },
    inviteInitials: {
      fontFamily: Fonts.body,
      fontSize: FontSize.lg,
      fontWeight: FontWeight.bold,
      color: colors.textOnPrimary,
    },
    inviteInfo: {
      flex: 1,
      gap: 2,
    },
    inviteName: {
      fontFamily: Fonts.body,
      fontSize: FontSize.lg,
      fontWeight: FontWeight.semibold,
      color: colors.text,
    },
    inviteMutual: {
      fontFamily: Fonts.body,
      fontSize: FontSize.base,
      color: colors.textFaint,
    },
    inviteActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xs,
    },
    acceptBtn: {
      backgroundColor: colors.primary,
      borderRadius: 16,
      paddingVertical: 6,
      paddingHorizontal: 14,
    },
    acceptText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.base,
      fontWeight: FontWeight.semibold,
      color: colors.textOnPrimary,
    },
    friendsLabel: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingBottom: Spacing.xs,
    },
    onlineCount: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xxs,
    },
    onlineDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: colors.primaryLight,
    },
    onlineText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.base,
      fontWeight: FontWeight.medium,
      color: colors.primaryLight,
    },
    friendRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 10,
      paddingHorizontal: Spacing.sm,
      gap: Spacing.sm,
    },
    friendAvatarWrap: {
      width: 44,
      height: 44,
    },
    friendAvatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      alignItems: 'center',
      justifyContent: 'center',
    },
    friendInitials: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xl,
      fontWeight: FontWeight.bold,
      color: colors.textOnPrimary,
    },
    friendOnlineDot: {
      position: 'absolute',
      bottom: 0,
      right: 0,
      width: 12,
      height: 12,
      borderRadius: 6,
      backgroundColor: colors.primaryLight,
      borderWidth: 2,
      borderColor: colors.bg,
    },
    friendInfo: {
      flex: 1,
      gap: 2,
    },
    friendName: {
      fontFamily: Fonts.body,
      fontSize: FontSize.lg,
      fontWeight: FontWeight.semibold,
      color: colors.text,
    },
    friendStatus: {
      fontFamily: Fonts.body,
      fontSize: FontSize.base,
      color: colors.textFaint,
    },
    playingDot: {
      position: 'absolute',
      bottom: 0,
      right: 0,
      width: 14,
      height: 14,
      borderRadius: 7,
      backgroundColor: colors.primaryLight,
      borderWidth: 2,
      borderColor: colors.bg,
    },
    playingVenue: {
      fontFamily: Fonts.body,
      fontSize: FontSize.base,
      fontWeight: FontWeight.medium,
      color: colors.primaryMid,
    },
    playingTime: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      color: colors.textFaint,
    },
    playingBadge: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colors.primaryPale,
      alignItems: 'center',
      justifyContent: 'center',
    },
    playingBadgeText: {
      fontSize: FontSize.xl,
    },
    addBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.primary,
      borderRadius: 16,
      paddingVertical: 6,
      paddingHorizontal: Spacing.sm,
      gap: Spacing.xxs,
    },
    addBtnText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.base,
      fontWeight: FontWeight.semibold,
      color: colors.textOnPrimary,
    },
    sentBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xxs,
      paddingVertical: 6,
      paddingHorizontal: Spacing.sm,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
    },
    sentText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      fontWeight: FontWeight.medium,
      color: colors.textFaint,
    },
    shareSection: {
      padding: Spacing.md,
      paddingTop: Spacing.sm,
    },
    shareCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.primaryPale,
      borderRadius: 12,
      padding: Spacing.md,
      gap: Spacing.sm,
      borderWidth: 1,
      borderColor: colors.primaryDim,
    },
    shareIconWrap: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    shareInfo: {
      flex: 1,
      gap: 2,
    },
    shareTitle: {
      fontFamily: Fonts.body,
      fontSize: FontSize.lg,
      fontWeight: FontWeight.semibold,
      color: colors.text,
    },
    shareDesc: {
      fontFamily: Fonts.body,
      fontSize: FontSize.base,
      color: colors.textMuted,
    },
  });

  const im = StyleSheet.create({
    overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'flex-end', alignItems: 'center' },
    sheet: { backgroundColor: colors.bgAlt, borderTopLeftRadius: 20, borderTopRightRadius: 20, paddingHorizontal: 20, paddingBottom: 32, width: '100%', maxWidth: 430, ...Shadows.lg },
    handleWrap: { alignItems: 'center', paddingVertical: 10 },
    handle: { width: 36, height: 4, borderRadius: 2, backgroundColor: colors.border },
    title: { fontFamily: Fonts.heading, fontSize: FontSize.xxl, fontWeight: FontWeight.bold, color: colors.text, marginBottom: Spacing.xxs },
    desc: { fontFamily: Fonts.body, fontSize: FontSize.md, color: colors.textFaint, marginBottom: Spacing.md },
    inputRow: { marginBottom: Spacing.sm },
    input: { borderWidth: 1.5, borderColor: colors.border, borderRadius: Radius.md, padding: 14, fontFamily: Fonts.body, fontSize: FontSize.xl, color: colors.text },
    resultRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.xs, marginBottom: Spacing.sm, paddingHorizontal: Spacing.xxs },
    resultText: { fontFamily: Fonts.body, fontSize: FontSize.md, fontWeight: FontWeight.medium },
    actions: { flexDirection: 'row', gap: 10, marginTop: 4 },
    cancelBtn: { flex: 1, alignItems: 'center', justifyContent: 'center', borderRadius: Radius.lg, paddingVertical: 14, borderWidth: 1, borderColor: colors.border },
    cancelText: { fontFamily: Fonts.body, fontSize: FontSize.lg, fontWeight: FontWeight.semibold, color: colors.textMuted },
    sendBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', borderRadius: Radius.lg, paddingVertical: 14, backgroundColor: colors.primary, gap: 6 },
    sendBtnDisabled: { opacity: 0.5 },
    sendText: { fontFamily: Fonts.body, fontSize: FontSize.lg, fontWeight: FontWeight.semibold, color: colors.textOnPrimary },
  });

  return { styles, im };
}
