import { Platform, StyleSheet } from 'react-native';
import type { ThemeColors } from '../theme';
import { Fonts, FontSize, FontWeight, Radius, Shadows, Spacing } from '../theme';

export function createStyles(colors: ThemeColors, isDark: boolean) {
  const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.black,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: isDark ? colors.bgAlt : colors.primary,
      paddingVertical: 10,
      paddingHorizontal: Spacing.md,
      minHeight: 52,
      ...Shadows.bar,
    },
    headerTitle: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xxl,
      fontWeight: FontWeight.bold,
      color: isDark ? colors.text : colors.textOnPrimary,
    },
    headerCenter: {
      flex: 1,
      alignItems: 'center',
    },
    cityPicker: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: isDark ? colors.bgMuted : '#ffffff18',
      borderRadius: 100,
      paddingVertical: 5,
      paddingHorizontal: 12,
      gap: 6,
      ...Shadows.sm,
    },
    cityText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.medium,
      color: isDark ? colors.text : colors.textOnPrimary,
    },
    addBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.accentBright,
      borderRadius: Spacing.xs,
      paddingVertical: 5,
      paddingHorizontal: 10,
      gap: Spacing.xxs,
    },
    addBtnText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.base,
      fontWeight: FontWeight.semibold,
      color: colors.textOnPrimary,
    },
    loginBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.accentBright,
      borderRadius: 8,
      paddingVertical: 5,
      paddingHorizontal: 10,
      gap: 4,
      ...Shadows.md,
    },
    mapContainer: {
      flex: 1,
      position: 'relative',
      backgroundColor: colors.mapBg,
    },
    legend: {
      position: 'absolute',
      top: 12,
      left: 12,
      padding: 10,
      gap: 6,
    },
    legendRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    legendDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
    },
    legendMarker: {
      width: 22,
      height: 22,
      borderRadius: 11,
      borderWidth: 2,
      borderColor: colors.bgAlt,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.2,
      shadowRadius: 2,
      elevation: 2,
    },
    legendIcon: {
      fontSize: 10,
      lineHeight: 13,
    },
    legendText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      color: colors.textMuted,
    },
    nearMeBtn: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.bgAlt,
      alignItems: 'center',
      justifyContent: 'center',
      ...Shadows.lg,
    },
    nearMeBtnActive: {
      backgroundColor: colors.primary,
    },
    searchRow: {
      flexDirection: 'row',
      paddingHorizontal: Spacing.md,
      gap: Spacing.xs,
    },
    searchBar: {
      flexDirection: 'row',
      alignItems: 'center',
      height: 34,
      paddingHorizontal: Spacing.sm,
      gap: Spacing.xs,
    },
    searchInput: {
      flex: 1,
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      color: colors.text,
      padding: 0,
    },
    searchText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      color: colors.textFaint,
    },
    filtersScroll: {
      flexGrow: 0,
    },
    filtersRow: {
      flexDirection: 'row',
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.xs,
      gap: Spacing.xs,
    },
    filterChip: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.bgAlt,
      borderRadius: 100,
      height: 32,
      paddingHorizontal: Spacing.sm,
      gap: Spacing.xxs,
      ...Shadows.sm,
    },
    filterChipActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
      ...Shadows.md,
    },
    filterText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.base,
      fontWeight: FontWeight.medium,
      color: colors.text,
    },
    addChip: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.accentBright,
      borderRadius: Radius.md,
      paddingVertical: 5,
      paddingHorizontal: Spacing.sm,
      gap: Spacing.xxs,
      ...Shadows.md,
    },
    addChipText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.base,
      fontWeight: FontWeight.semibold,
      color: colors.textOnPrimary,
    },
    filterTextActive: {
      color: colors.textOnPrimary,
      fontWeight: FontWeight.semibold,
    },
    listHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.xxs,
    },
    listHeaderText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      fontWeight: FontWeight.medium,
      color: colors.textFaint,
    },
    friendsOnline: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xxs,
    },
    friendsDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
    },
    friendsText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      color: colors.purpleMid,
    },
    offlineBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 14,
      paddingVertical: 6,
      backgroundColor: colors.amberPale,
      borderBottomWidth: 1,
      borderBottomColor: colors.amberDeep,
    },
    offlineText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      color: colors.textFaint,
    },
    venueList: {
      flex: 1,
      paddingHorizontal: Spacing.sm,
    },
    venueCard: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: Spacing.sm,
      paddingHorizontal: Spacing.md,
      gap: Spacing.sm,
    },
    venueCardHighlight: {
      borderLeftWidth: 3,
      borderLeftColor: colors.primaryLight + '30',
    },
    venueLeft: {
      flex: 1,
      gap: Spacing.xxs,
    },
    venueName: {
      fontFamily: Fonts.body,
      fontSize: FontSize.lg,
      fontWeight: FontWeight.semibold,
      color: colors.text,
    },
    venueMeta: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    venueType: {
      fontFamily: Fonts.body,
      fontSize: FontSize.base,
      color: colors.textMuted,
    },
    venueMetaSep: {
      fontFamily: Fonts.body,
      fontSize: FontSize.base,
      color: colors.textFaint,
    },
    venueTables: {
      fontFamily: Fonts.body,
      fontSize: FontSize.base,
      color: colors.textMuted,
    },
    conditionDot: {
      width: 7,
      height: 7,
      borderRadius: 3.5,
    },
    venueCondition: {
      fontFamily: Fonts.body,
      fontSize: FontSize.base,
      fontWeight: FontWeight.medium,
    },
    venueRight: {
      alignItems: 'flex-end',
      gap: Spacing.xxs,
    },
    distanceBadge: {
      backgroundColor: colors.bluePale,
      borderRadius: Spacing.xxs,
      paddingVertical: Spacing.xxs,
      paddingHorizontal: Spacing.xs,
    },
    distanceText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.base,
      fontWeight: FontWeight.medium,
      color: colors.blue,
    },
    venueStars: {
      fontFamily: Fonts.body,
      fontSize: FontSize.base,
      fontWeight: FontWeight.medium,
      color: colors.accent,
    },
  });

  /* -- Custom map pin -- */
  const pinStyles = StyleSheet.create({
    outer: {
      alignItems: 'center',
    },
    wrap: {
      width: 30,
      height: 30,
      borderRadius: 15,
      borderWidth: 2.5,
      borderColor: colors.bgAlt,
      alignItems: 'center',
      justifyContent: 'center',
      ...Platform.select({
        ios: { shadowColor: colors.shadow, shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.25, shadowRadius: 3 },
        android: { elevation: 4 },
      }),
    },
    icon: {
      fontSize: 13,
      lineHeight: 16,
    },
    friendBadge: {
      position: 'absolute',
      top: -4,
      right: -4,
      width: 16,
      height: 16,
      borderRadius: 8,
      backgroundColor: colors.purpleMid,
      borderWidth: 1.5,
      borderColor: colors.bgAlt,
      alignItems: 'center',
      justifyContent: 'center',
    },
    friendBadgeIcon: {
      fontSize: 8,
      lineHeight: 10,
    },
    arrow: {
      width: 0,
      height: 0,
      borderLeftWidth: 6,
      borderRightWidth: 6,
      borderTopWidth: 7,
      borderLeftColor: 'transparent',
      borderRightColor: 'transparent',
      borderTopColor: colors.bgAlt,
      marginTop: -1,
    },
    callout: {
      backgroundColor: colors.bgAlt,
      borderRadius: Radius.md,
      padding: 10,
      minWidth: 140,
      maxWidth: 220,
      ...Platform.select({
        ios: { shadowColor: colors.shadow, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.15, shadowRadius: 6 },
        android: { elevation: 4 },
      }),
    },
    calloutTitle: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.semibold,
      color: colors.text,
      marginBottom: 2,
    },
    calloutSub: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      color: colors.textFaint,
    },
  });

  return { styles, pinStyles };
}
