import { StyleSheet } from 'react-native';
import type { ThemeColors } from '../theme';
import { Fonts, FontSize, FontWeight, Shadows, Spacing } from '../theme';

export function createStyles(colors: ThemeColors) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.bg,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: colors.bgAlt,
      height: 52,
      paddingHorizontal: Spacing.md,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      ...Shadows.bar,
    },
    headerTitle: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xxl,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    statsCard: {
      marginHorizontal: Spacing.md,
      marginTop: Spacing.sm,
      backgroundColor: colors.bgAlt,
      borderRadius: 12,
      padding: Spacing.sm,
      borderWidth: 1,
      borderColor: colors.borderLight,
      ...Shadows.sm,
    },
    periodRowCenter: {
      flexDirection: 'row',
      justifyContent: 'center',
      gap: 6,
      marginBottom: Spacing.sm,
    },
    periodBtn: {
      paddingVertical: 5,
      paddingHorizontal: 10,
      borderRadius: 14,
      backgroundColor: colors.bgMuted,
      borderWidth: 1,
      borderColor: colors.border,
    },
    periodBtnActive: {
      backgroundColor: colors.primaryPale,
      borderColor: colors.primaryDim,
    },
    periodText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      fontWeight: FontWeight.medium,
      color: colors.textMuted,
    },
    periodTextActive: {
      color: colors.primary,
      fontWeight: FontWeight.semibold,
    },
    scroll: {
      flex: 1,
    },
    statsRow: {
      flexDirection: 'row',
      gap: 6,
    },
    statPill: {
      flex: 1,
      alignItems: 'center',
      borderRadius: 12,
      paddingVertical: Spacing.sm,
      paddingHorizontal: 4,
      gap: Spacing.xxs,
      ...Shadows.sm,
    },
    statValue: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xxl,
      fontWeight: FontWeight.extrabold,
    },
    statLabel: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      fontWeight: FontWeight.medium,
      color: colors.textMuted,
    },
    calCard: {
      marginHorizontal: Spacing.md,
      marginTop: Spacing.xs,
      marginBottom: Spacing.sm,
      backgroundColor: colors.bgAlt,
      borderRadius: 12,
      padding: Spacing.sm,
      borderWidth: 1,
      borderColor: colors.borderLight,
      ...Shadows.sm,
    },
    calHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: Spacing.xs,
    },
    calNavBtn: {
      padding: 4,
    },
    calMonthTitle: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.lg,
      fontWeight: FontWeight.bold,
      color: colors.text,
      textTransform: 'capitalize',
    },
    calWeekdayRow: {
      flexDirection: 'row',
      marginBottom: 6,
    },
    calWeekday: {
      flex: 1,
      textAlign: 'center',
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.semibold,
      color: colors.textFaint,
      letterSpacing: 0.2,
    },
    calWeekRow: {
      flexDirection: 'row',
    },
    calDayCell: {
      flex: 1,
      alignItems: 'center',
      paddingVertical: 2,
    },
    calDay: {
      alignItems: 'center',
      justifyContent: 'center',
      width: 36,
      height: 44,
      borderRadius: 12,
    },
    calDayToday: {
      backgroundColor: colors.primaryPale,
    },
    calDayPlayed: {
      backgroundColor: colors.amberPale,
    },
    calDayText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      color: colors.text,
    },
    calDayTodayText: {
      fontWeight: FontWeight.bold,
      color: colors.primaryMid,
    },
    calDayOutsideText: {
      color: colors.textFaint,
      opacity: 0.5,
    },
    calDayFutureText: {
      color: colors.textFaint,
    },
    calDaySelectedText: {
      fontWeight: FontWeight.bold,
    },
    dayDetail: {
      marginHorizontal: Spacing.md,
      marginBottom: Spacing.sm,
      backgroundColor: colors.bgAlt,
      borderRadius: 12,
      padding: Spacing.sm,
      borderWidth: 1,
      borderColor: colors.borderLight,
      ...Shadows.sm,
    },
    dayDetailHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: Spacing.xs,
    },
    dayDetailTitle: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.bold,
      color: colors.text,
      textTransform: 'capitalize',
    },
    dayDetailTotal: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.md,
      fontWeight: FontWeight.bold,
      color: colors.accent,
    },
    dayDetailEmpty: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      color: colors.textFaint,
      textAlign: 'center',
      paddingVertical: Spacing.sm,
    },
    dayDetailRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: Spacing.xs,
      gap: Spacing.sm,
      borderTopWidth: 1,
      borderTopColor: colors.borderLight,
    },
    dayDetailIcon: {
      width: 30,
      height: 30,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
    },
    dayDetailInfo: {
      flex: 1,
      gap: 1,
    },
    dayDetailName: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.semibold,
      color: colors.text,
    },
    dayDetailMeta: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      color: colors.textFaint,
    },
    streakBar: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.xs,
      gap: Spacing.xs,
    },
    streakText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.semibold,
      color: colors.accent,
    },
    timeline: {
      paddingHorizontal: Spacing.md,
      paddingTop: Spacing.sm,
    },
    dayLabel: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: Spacing.xs,
      gap: Spacing.xs,
    },
    dayDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
    },
    dayText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.bold,
      color: colors.textMuted,
    },
    entry: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: Spacing.sm,
      paddingLeft: Spacing.md,
      gap: Spacing.sm,
      borderBottomWidth: 1,
      borderBottomColor: colors.borderLight,
      borderLeftWidth: 2,
      borderLeftColor: colors.borderLight,
      ...Shadows.sm,
    },
    entryIcon: {
      width: 36,
      height: 36,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
    },
    entryInfo: {
      flex: 1,
      gap: 2,
    },
    entryTitle: {
      fontFamily: Fonts.body,
      fontSize: FontSize.lg,
      fontWeight: FontWeight.semibold,
      color: colors.text,
    },
    entryDetails: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xs,
    },
    entryTime: {
      fontFamily: Fonts.body,
      fontSize: FontSize.base,
      color: colors.textFaint,
    },
    entryDot: {
      fontFamily: Fonts.body,
      fontSize: FontSize.base,
      color: colors.textFaint,
    },
    entryDuration: {
      fontFamily: Fonts.body,
      fontSize: FontSize.base,
      color: colors.textFaint,
    },
    entryFriends: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    entryFriendsText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      color: colors.purpleMid,
    },
    loadMore: {
      alignItems: 'center',
      paddingVertical: Spacing.md,
    },
    loadMoreBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.bgMuted,
      borderRadius: 20,
      paddingVertical: Spacing.xs,
      paddingHorizontal: Spacing.lg,
      gap: 6,
      borderWidth: 1,
      borderColor: colors.border,
      ...Shadows.md,
    },
    loadMoreText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.medium,
      color: colors.textMuted,
    },
  });
}
