import { StyleSheet } from 'react-native';
import type { ThemeColors } from '../theme';
import { Fonts, FontSize, FontWeight, Radius, Shadows, Spacing } from '../theme';

export function createStyles(colors: ThemeColors, isDark: boolean) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.bg,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: isDark ? colors.bgAlt : colors.primary,
      paddingVertical: 10,
      minHeight: 52,
      paddingHorizontal: Spacing.md,
      ...Shadows.bar,
    },
    headerTitle: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xxl,
      fontWeight: FontWeight.bold,
      color: isDark ? colors.text : colors.textOnPrimary,
    },
    scroll: {
      flex: 1,
    },

    /* ── Hero ── */
    profileSummaryCard: {
      marginHorizontal: Spacing.md,
      marginTop: Spacing.md,
      borderRadius: Radius.lg,
      backgroundColor: isDark ? '#123B24' : '#14532D',
      borderWidth: 1,
      borderColor: isDark ? '#27633F' : '#0F4525',
      paddingVertical: Spacing.sm,
      paddingHorizontal: Spacing.md,
      gap: Spacing.sm,
      ...Shadows.sm,
    },
    identityHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
    },
    identityHeaderIcon: {
      width: 44,
      height: 44,
      borderRadius: Radius.sm,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(255,255,255,0.14)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.24)',
      ...Shadows.sm,
    },
    identityHeaderIconText: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xl,
      fontWeight: FontWeight.bold,
      color: colors.textOnPrimary,
    },
    identityHeaderCopy: {
      flex: 1,
      minWidth: 0,
      gap: 2,
    },
    summaryName: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xl,
      fontWeight: FontWeight.bold,
      color: colors.textOnPrimary,
    },
    summaryHandle: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      color: 'rgba(255,255,255,0.76)',
    },
    summaryProgressRow: {
      flexDirection: 'column',
      alignItems: 'flex-end',
      gap: 4,
      flexShrink: 0,
    },
    summaryDivider: {
      height: 1,
      backgroundColor: 'rgba(255,255,255,0.14)',
    },
    summaryEditButton: {
      width: 28,
      height: 28,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(255,255,255,0.12)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.18)',
      flexShrink: 0,
    },
    summaryPlayRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
      minHeight: 28,
    },
    summaryPlayPills: {
      flex: 1,
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: 6,
    },
    summaryPlayEmpty: {
      flex: 1,
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      color: 'rgba(255,255,255,0.72)',
    },
    summaryGoalChip: {
      borderRadius: 999,
      paddingVertical: 3,
      paddingHorizontal: 8,
      backgroundColor: 'rgba(255,255,255,0.12)',
    },
    summarySkillChip: {
      backgroundColor: 'rgba(0,0,0,0.18)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.14)',
    },
    summaryGoalChipText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.semibold,
      color: colors.textOnPrimary,
    },
    challengeChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      backgroundColor: 'rgba(255,255,255,0.13)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.17)',
      borderRadius: 999,
      paddingVertical: 3,
      paddingHorizontal: 8,
    },
    challengeChipText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.semibold,
      color: colors.textOnPrimary,
    },
    /* ── F050: weekly streak flame chip (warm pale tint, mirrors challengeChip) ── */
    streakChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      backgroundColor: 'rgba(255,255,255,0.12)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.17)',
      borderRadius: 999,
      paddingVertical: 3,
      paddingHorizontal: 8,
    },
    streakChipText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.semibold,
      color: colors.textOnPrimary,
    },
    streakOverlay: {
      flex: 1,
      backgroundColor: colors.overlayHeavy,
      alignItems: 'center',
      justifyContent: 'center',
      padding: Spacing.xl,
    },
    streakCard: {
      width: '100%',
      maxWidth: 360,
      borderRadius: Radius.md,
      backgroundColor: colors.bgAlt,
      borderWidth: 1,
      borderColor: colors.borderLight,
      padding: Spacing.lg,
      gap: Spacing.md,
      ...Shadows.lg,
    },
    streakCardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xs,
    },
    streakCardTitle: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xl,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    streakStatRow: {
      flexDirection: 'row',
      gap: Spacing.sm,
    },
    streakStat: {
      flex: 1,
      borderRadius: Radius.sm,
      backgroundColor: colors.bgMuted,
      paddingVertical: Spacing.sm,
      paddingHorizontal: Spacing.xs,
      alignItems: 'center',
      gap: 2,
    },
    streakStatValue: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xxxl,
      fontWeight: FontWeight.bold,
      color: colors.primary,
    },
    streakStatLabel: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.semibold,
      color: colors.textMuted,
    },
    streakHint: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      color: colors.textMuted,
      lineHeight: 18,
    },
    /* ── F053: milestones strip (earned chips + next-locked ghost) ── */
    milestoneChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      backgroundColor: colors.bgMuted,
      borderRadius: 999,
      paddingVertical: 5,
      paddingHorizontal: 10,
    },
    milestoneChipText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.semibold,
      color: colors.primary,
    },
    milestoneGhostChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      backgroundColor: colors.bgMuted,
      borderRadius: 999,
      paddingVertical: 5,
      paddingHorizontal: 10,
      borderWidth: 1,
      borderColor: colors.borderLight,
      borderStyle: 'dashed',
    },
    milestoneGhostText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.semibold,
      color: colors.textMuted,
    },
    identityDetailGrid: {
      gap: Spacing.sm,
    },
    identityPanel: {
      borderRadius: Radius.sm,
      backgroundColor: colors.bgMuted,
      borderWidth: 1,
      borderColor: colors.borderLight,
      padding: Spacing.sm,
      gap: Spacing.xs,
    },
    panelTitle: {
      flex: 1,
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    equipmentCardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: Spacing.xs,
    },
    equipmentEditText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      fontWeight: FontWeight.bold,
      color: colors.primary,
    },
    profileEquipmentCard: {
      gap: Spacing.xs,
      borderRadius: Radius.sm,
      backgroundColor: 'transparent',
    },
    equipmentMetaRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
    },
    equipmentMetaPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      borderRadius: Radius.sm,
      backgroundColor: colors.bgAlt,
      paddingVertical: 5,
      paddingHorizontal: 7,
    },
    equipmentMetaText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    equipmentMetaTextIcon: {
      fontFamily: Fonts.heading,
      fontSize: 11,
      fontWeight: FontWeight.bold,
      color: colors.primaryMid,
      lineHeight: 13,
    },
    equipmentBladeRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xs,
      borderRadius: Radius.sm,
      backgroundColor: colors.bgAlt,
      padding: Spacing.xs,
    },
    equipmentBladeIcon: {
      width: 32,
      height: 32,
      borderRadius: Radius.sm,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primaryPale,
    },
    equipmentCopy: {
      flex: 1,
      minWidth: 0,
      gap: 2,
    },
    equipmentLabel: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
      color: colors.textFaint,
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    equipmentValue: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      fontWeight: FontWeight.bold,
      color: colors.text,
      lineHeight: 15,
    },
    equipmentRubberGrid: {
      flexDirection: 'row',
      gap: Spacing.xs,
    },
    equipmentRubberTile: {
      flex: 1,
      minWidth: 0,
      gap: 3,
      borderRadius: Radius.sm,
      backgroundColor: colors.bgAlt,
      padding: Spacing.xs,
    },
    emptyEquipmentCard: {
      minHeight: 120,
      alignItems: 'center',
      justifyContent: 'center',
      gap: Spacing.xs,
      borderRadius: Radius.sm,
      borderWidth: 1,
      borderColor: colors.borderLight,
      backgroundColor: colors.bgMuted,
      padding: Spacing.sm,
    },
    identityCard: {
      marginHorizontal: Spacing.md,
      borderRadius: Radius.md,
      backgroundColor: colors.bgAlt,
      borderWidth: 1,
      borderColor: colors.borderLight,
      padding: Spacing.md,
      gap: Spacing.sm,
      ...Shadows.md,
    },
    identityTop: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
    },
    identityIcon: {
      width: 52,
      height: 52,
      borderRadius: Radius.sm,
      alignItems: 'center',
      justifyContent: 'center',
      ...Shadows.sm,
    },
    identityCopy: {
      flex: 1,
      gap: 2,
    },
    eyebrow: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
      color: colors.textFaint,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    identityTitle: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xxl,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    identityMeta: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      color: colors.textMuted,
    },
    levelPill: {
      borderRadius: Radius.sm,
      paddingHorizontal: 8,
      paddingVertical: 5,
    },
    levelPillText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
    },
    progressTrack: {
      height: 9,
      borderRadius: 5,
      backgroundColor: colors.bgMuted,
      overflow: 'hidden',
    },
    progressFill: {
      height: 9,
      borderRadius: 5,
    },
    identityStats: {
      flexDirection: 'row',
      gap: Spacing.xs,
    },
    identityStat: {
      flex: 1,
      borderRadius: Radius.sm,
      backgroundColor: colors.bgMuted,
      padding: Spacing.sm,
      gap: 2,
    },
    identityStatValue: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xxl,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    identityStatLabel: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.semibold,
      color: colors.textFaint,
    },
    latestBadgeRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      borderRadius: Radius.sm,
      backgroundColor: colors.bgMuted,
      paddingHorizontal: Spacing.sm,
      paddingVertical: 9,
    },
    latestBadgeText: {
      flex: 1,
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.semibold,
      color: colors.text,
    },
    identityHint: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      color: colors.textMuted,
      lineHeight: 18,
    },
    identityCta: {
      minHeight: 46,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      borderRadius: Radius.sm,
      backgroundColor: colors.primary,
      paddingHorizontal: Spacing.md,
      ...Shadows.sm,
    },
    identityCtaText: {
      flexShrink: 1,
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.bold,
      color: colors.textOnPrimary,
      textAlign: 'center',
    },
    statsRow: {
      flexDirection: 'row',
      gap: Spacing.xs,
      paddingHorizontal: Spacing.md,
      paddingTop: Spacing.md,
    },
    statCard: {
      flex: 1,
      borderRadius: Radius.md,
      backgroundColor: colors.bgAlt,
      borderWidth: 1,
      borderColor: colors.borderLight,
      paddingVertical: Spacing.sm,
      paddingHorizontal: Spacing.xs,
      alignItems: 'center',
      gap: 3,
    },
    statValue: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xxl,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    statLabel: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.semibold,
      color: colors.textFaint,
      textAlign: 'center',
    },

    /* ── Sections ── */
    section: {
      paddingHorizontal: Spacing.md,
      paddingTop: Spacing.lg,
      gap: 10,
    },
    /* ── TT Wrapped banner (F054) ── */
    playerOverviewCard: {
      marginHorizontal: Spacing.md,
      marginTop: Spacing.sm,
      gap: Spacing.sm,
    },
    playerOverviewHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
    },
    playerOverviewIcon: {
      width: 48,
      height: 48,
      borderRadius: Radius.md,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primaryPale,
      flexShrink: 0,
    },
    playerOverviewHeaderCopy: {
      flex: 1,
      minWidth: 0,
      gap: 2,
    },
    playerOverviewEyebrow: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
      color: colors.primary,
      textTransform: 'uppercase',
      letterSpacing: 1.2,
    },
    playerOverviewTitle: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xl,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    playerOverviewSubtitle: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      color: colors.textMuted,
      lineHeight: 17,
    },
    playerOverviewEditButton: {
      width: 38,
      height: 38,
      borderRadius: 19,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primaryPale,
      borderWidth: 1,
      borderColor: colors.primaryDim,
      flexShrink: 0,
    },
    playerOverviewPills: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      gap: Spacing.xs,
    },
    playerOverviewPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      maxWidth: '100%',
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.borderLight,
      backgroundColor: colors.bgMuted,
      paddingVertical: 4,
      paddingHorizontal: 8,
    },
    playerOverviewPillText: {
      flexShrink: 1,
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
      color: colors.textMuted,
    },
    playerOverviewGhostPill: {
      borderStyle: 'dashed',
    },
    playerOverviewGhostText: {
      flexShrink: 1,
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
      color: colors.textFaint,
    },
    playerOverviewMilestones: {
      paddingHorizontal: 2,
    },
    playerOverviewMilestonesHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: Spacing.sm,
    },
    playerOverviewMilestoneRow: {
      flexDirection: 'row',
      flexWrap: 'nowrap',
      gap: Spacing.xs,
    },
    playerOverviewMilestonePill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      maxWidth: '100%',
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.borderLight,
      backgroundColor: colors.bgMuted,
      paddingVertical: 4,
      paddingHorizontal: 8,
      flexShrink: 1,
    },
    playerOverviewMilestoneText: {
      flexShrink: 1,
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
    },
    playerOverviewVenueRow: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: Spacing.sm,
      paddingVertical: 9,
      paddingHorizontal: 2,
      borderTopWidth: 1,
      borderBottomWidth: 1,
      borderColor: colors.borderLight,
    },
    playerOverviewVenueMain: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
      flex: 1,
      minWidth: 0,
      minHeight: 42,
    },
    playerOverviewVenueIcon: {
      width: 30,
      height: 30,
      borderRadius: 999,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primaryPale,
      flexShrink: 0,
    },
    playerOverviewVenueCopy: {
      flex: 1,
      minWidth: 0,
      gap: 2,
    },
    playerOverviewVenueAction: {
      width: 28,
      height: 28,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primaryPale,
      borderWidth: 1,
      borderColor: colors.primaryDim,
      flexShrink: 0,
    },
    playerOverviewVenueTitle: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      fontWeight: FontWeight.semibold,
      color: colors.text,
      lineHeight: 17,
    },
    playerOverviewVenueSuggestion: {
      maxWidth: '100%',
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.primary,
      backgroundColor: colors.primaryPale,
      paddingVertical: 5,
      paddingHorizontal: 8,
      marginLeft: 40,
    },
    playerOverviewVenueSuggestionText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
      color: colors.primary,
    },
    playerOverviewDivider: {
      height: 1,
      backgroundColor: colors.borderLight,
    },
    playerOverviewMetricRow: {
      flexDirection: 'column',
      gap: Spacing.sm,
    },
    playerOverviewRatingPanel: {
      position: 'relative',
      overflow: 'hidden',
      gap: Spacing.xs,
      borderRadius: Radius.md,
      backgroundColor: isDark ? colors.bgMuted : '#F8FBF8',
      borderWidth: 1,
      borderColor: isDark ? colors.border : colors.primaryDim,
      paddingVertical: Spacing.sm,
      paddingHorizontal: Spacing.md,
    },
    playerOverviewRatingHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: Spacing.sm,
    },
    playerOverviewRatingScore: {
      width: 118,
      flexShrink: 0,
      gap: 2,
    },
    playerOverviewRatingLine: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      gap: Spacing.sm,
      flexWrap: 'wrap',
    },
    playerOverviewRatingValue: {
      fontFamily: Fonts.heading,
      fontSize: 34,
      lineHeight: 36,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    playerOverviewRatingBadges: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 4,
      justifyContent: 'flex-start',
      minWidth: 0,
    },
    playerOverviewRatingBadge: {
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.borderLight,
      backgroundColor: colors.bgAlt,
      paddingVertical: 4,
      paddingHorizontal: 8,
    },
    playerOverviewRatingBadgeText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
      color: colors.textMuted,
    },
    playerOverviewRatingSpark: {
      flex: 1,
      minWidth: 0,
      height: 76,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: Radius.md,
      backgroundColor: isDark ? '#06140b' : '#ffffff',
      borderWidth: 1,
      borderColor: isDark ? colors.borderLight : colors.primaryDim,
      overflow: 'hidden',
    },
    playerOverviewRatingCta: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 7,
      alignSelf: 'stretch',
      minHeight: 42,
      borderRadius: Radius.md,
      borderWidth: 1,
      borderColor: isDark ? '#27633F' : colors.primaryMid,
      backgroundColor: isDark ? '#14532D' : colors.primary,
      paddingVertical: Spacing.xs,
      paddingHorizontal: Spacing.md,
      ...Shadows.sm,
    },
    playerOverviewRatingCtaIcon: {
      width: 20,
      height: 20,
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
    },
    playerOverviewRatingCtaText: {
      flex: 1,
      textAlign: 'center',
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      fontWeight: FontWeight.bold,
      color: colors.textOnPrimary,
    },
    playerOverviewMetric: {
      minWidth: 0,
      gap: 2,
      borderRadius: Radius.sm,
      backgroundColor: colors.bgMuted,
      borderWidth: 1,
      borderColor: colors.borderLight,
      padding: Spacing.sm,
      minHeight: 86,
    },
    playerOverviewMatchMetric: {
      minHeight: 0,
    },
    playerOverviewRivalsMetric: {
      minHeight: 72,
    },
    playerOverviewRecordRow: {
      flexDirection: 'row',
      alignItems: 'stretch',
      gap: Spacing.xs,
      marginTop: 2,
    },
    playerOverviewRecordItem: {
      flex: 1,
      minWidth: 0,
      borderRadius: Radius.sm,
      borderWidth: 1,
      borderColor: colors.borderLight,
      backgroundColor: colors.bgAlt,
      paddingVertical: 6,
      paddingHorizontal: 7,
      gap: 1,
    },
    playerOverviewRecordValue: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xl,
      lineHeight: 24,
      fontWeight: FontWeight.bold,
    },
    playerOverviewRecordLabel: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.semibold,
      color: colors.textMuted,
    },
    playerOverviewMatchStrip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
      paddingVertical: 7,
      paddingHorizontal: 2,
    },
    playerOverviewRecordCompact: {
      flexDirection: 'row',
      alignItems: 'baseline',
      flex: 1,
      minWidth: 0,
      gap: 5,
    },
    playerOverviewRecordDivider: {
      width: 1,
      height: 18,
      backgroundColor: colors.borderLight,
      marginHorizontal: 3,
    },
    playerOverviewMetricLabel: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
      color: colors.textFaint,
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    playerOverviewMetricValue: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xxl,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    playerOverviewMetricMeta: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.semibold,
      color: colors.textMuted,
    },
    playerOverviewSparkline: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: Spacing.sm,
    },
    playerOverviewDeltas: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'flex-end',
      gap: 4,
      flex: 1,
    },
    playerOverviewDelta: {
      borderRadius: 999,
      paddingHorizontal: 7,
      paddingVertical: 2,
    },
    playerOverviewDeltaText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
    },
    playerOverviewRivalsPanel: {
      gap: Spacing.xs,
      borderRadius: Radius.sm,
      backgroundColor: colors.bgMuted,
      borderWidth: 1,
      borderColor: colors.borderLight,
      padding: Spacing.sm,
    },
    playerOverviewRivalsHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: Spacing.sm,
    },
    playerOverviewRivalsList: {
      gap: Spacing.xs,
    },
    playerOverviewRivalRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
      borderRadius: Radius.sm,
      backgroundColor: colors.bgAlt,
      padding: Spacing.xs,
    },
    playerOverviewRivalCopy: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
      flex: 1,
      minWidth: 0,
    },
    playerOverviewRivalRank: {
      width: 28,
      height: 28,
      borderRadius: Radius.sm,
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
      backgroundColor: colors.primaryPale,
    },
    playerOverviewRivalRankText: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.sm,
      fontWeight: FontWeight.bold,
      color: colors.primary,
    },
    playerOverviewRivalsMore: {
      minHeight: 34,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 5,
      borderRadius: Radius.sm,
      borderWidth: 1,
      borderColor: colors.primaryDim,
      backgroundColor: colors.primaryPale,
      paddingVertical: 7,
      paddingHorizontal: 10,
      marginTop: 2,
    },
    playerOverviewRivalsMoreText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
      color: colors.primary,
    },
    playerOverviewChallengeButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.primary,
      backgroundColor: colors.primaryPale,
      flexShrink: 0,
    },
    playerOverviewChallengeButtonDisabled: {
      borderColor: colors.borderLight,
      backgroundColor: colors.bgMuted,
    },
    playerOverviewChallengeText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
      color: colors.primary,
    },

    wrappedBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.md,
      marginHorizontal: Spacing.md,
      marginTop: Spacing.lg,
      paddingVertical: Spacing.md,
      paddingHorizontal: Spacing.md,
      backgroundColor: colors.primaryPale,
      borderRadius: Radius.lg,
      borderWidth: 1,
      borderColor: colors.primaryDim,
      ...Shadows.sm,
    },
    wrappedBannerIcon: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.bgAlt,
    },
    wrappedBannerCopy: { flex: 1, gap: 2 },
    wrappedBannerTitle: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.lg,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    wrappedBannerSubtitle: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      color: colors.primary,
      fontWeight: FontWeight.semibold,
    },
    sectionTitle: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.semibold,
      color: colors.textMuted,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },

    /* ── Nav Links ── */
    navRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: Spacing.sm,
      gap: Spacing.sm,
      borderBottomWidth: 1,
      borderBottomColor: colors.borderLight,
    },
    navIcon: {
      width: 36,
      height: 36,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    navLabel: {
      flex: 1,
      fontFamily: Fonts.body,
      fontSize: 15,
      fontWeight: FontWeight.medium,
      color: colors.text,
    },
    adminPill: {
      backgroundColor: colors.primaryPale,
      borderRadius: 8,
      paddingVertical: 2,
      paddingHorizontal: 6,
      marginRight: 4,
    },
    adminPillText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
      color: colors.primaryMid,
    },

    /* ── Logout ── */
    logoutRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 14,
      gap: Spacing.xs,
      backgroundColor: colors.redPale,
      borderRadius: Radius.md,
      borderWidth: 1,
      borderColor: colors.redBorder,
    },
    logoutText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.lg,
      fontWeight: FontWeight.medium,
      color: colors.red,
    },
  });
}
