import { StyleSheet } from 'react-native';
import type { ThemeColors } from '../theme';
import { Fonts, FontSize, FontWeight, Radius, Shadows, Spacing } from '../theme';

export function createStyles(colors: ThemeColors, isDark: boolean) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.bg,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: isDark ? colors.bgAlt : colors.primary,
      paddingVertical: 10,
      minHeight: 52,
      paddingHorizontal: Spacing.md,
      ...Shadows.bar,
    },
    headerTitle: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xxl,
      fontWeight: FontWeight.bold,
      color: isDark ? colors.text : colors.textOnPrimary,
    },
    scroll: {
      flex: 1,
    },

    /* ── Hero ── */
    profileSummaryCard: {
      marginHorizontal: Spacing.md,
      marginTop: Spacing.md,
      borderRadius: Radius.md,
      backgroundColor: isDark ? colors.bgAlt : colors.bg,
      borderWidth: 1,
      borderColor: colors.borderLight,
      padding: Spacing.md,
      gap: Spacing.md,
      ...Shadows.md,
    },
    identityHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
    },
    identityHeaderIcon: {
      width: 44,
      height: 44,
      borderRadius: Radius.sm,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primary,
      ...Shadows.sm,
    },
    identityHeaderIconText: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xl,
      fontWeight: FontWeight.bold,
      color: colors.textOnPrimary,
    },
    identityHeaderCopy: {
      flex: 1,
      minWidth: 0,
      gap: 2,
    },
    summaryName: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xxl,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    summaryHandle: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      color: colors.textMuted,
    },
    identityMetaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: Spacing.xs,
      marginTop: 2,
    },
    challengeChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      backgroundColor: colors.primaryPale,
      borderRadius: 999,
      paddingVertical: 3,
      paddingHorizontal: 8,
    },
    challengeChipText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.semibold,
      color: colors.primary,
    },
    identityDetailGrid: {
      gap: Spacing.sm,
    },
    identityPanel: {
      borderRadius: Radius.sm,
      backgroundColor: colors.bgMuted,
      borderWidth: 1,
      borderColor: colors.borderLight,
      padding: Spacing.sm,
      gap: Spacing.xs,
    },
    panelTitle: {
      flex: 1,
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    equipmentCardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: Spacing.xs,
    },
    equipmentEditText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      fontWeight: FontWeight.bold,
      color: colors.primary,
    },
    profileEquipmentCard: {
      gap: Spacing.xs,
      borderRadius: Radius.sm,
      backgroundColor: 'transparent',
    },
    equipmentMetaRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
    },
    equipmentMetaPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      borderRadius: Radius.sm,
      backgroundColor: colors.bgAlt,
      paddingVertical: 5,
      paddingHorizontal: 7,
    },
    equipmentMetaText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    equipmentMetaTextIcon: {
      fontFamily: Fonts.heading,
      fontSize: 11,
      fontWeight: FontWeight.bold,
      color: colors.primaryMid,
      lineHeight: 13,
    },
    equipmentBladeRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xs,
      borderRadius: Radius.sm,
      backgroundColor: colors.bgAlt,
      padding: Spacing.xs,
    },
    equipmentBladeIcon: {
      width: 32,
      height: 32,
      borderRadius: Radius.sm,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primaryPale,
    },
    equipmentCopy: {
      flex: 1,
      minWidth: 0,
      gap: 2,
    },
    equipmentLabel: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
      color: colors.textFaint,
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    equipmentValue: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      fontWeight: FontWeight.bold,
      color: colors.text,
      lineHeight: 15,
    },
    equipmentRubberGrid: {
      flexDirection: 'row',
      gap: Spacing.xs,
    },
    equipmentRubberTile: {
      flex: 1,
      minWidth: 0,
      gap: 3,
      borderRadius: Radius.sm,
      backgroundColor: colors.bgAlt,
      padding: Spacing.xs,
    },
    emptyEquipmentCard: {
      minHeight: 120,
      alignItems: 'center',
      justifyContent: 'center',
      gap: Spacing.xs,
      borderRadius: Radius.sm,
      borderWidth: 1,
      borderColor: colors.borderLight,
      backgroundColor: colors.bgMuted,
      padding: Spacing.sm,
    },
    identityCard: {
      marginHorizontal: Spacing.md,
      borderRadius: Radius.md,
      backgroundColor: colors.bgAlt,
      borderWidth: 1,
      borderColor: colors.borderLight,
      padding: Spacing.md,
      gap: Spacing.sm,
      ...Shadows.md,
    },
    identityTop: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
    },
    identityIcon: {
      width: 52,
      height: 52,
      borderRadius: Radius.sm,
      alignItems: 'center',
      justifyContent: 'center',
      ...Shadows.sm,
    },
    identityCopy: {
      flex: 1,
      gap: 2,
    },
    eyebrow: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
      color: colors.textFaint,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    identityTitle: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xxl,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    identityMeta: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      color: colors.textMuted,
    },
    levelPill: {
      borderRadius: Radius.sm,
      paddingHorizontal: 8,
      paddingVertical: 5,
    },
    levelPillText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
    },
    progressTrack: {
      height: 9,
      borderRadius: 5,
      backgroundColor: colors.bgMuted,
      overflow: 'hidden',
    },
    progressFill: {
      height: 9,
      borderRadius: 5,
    },
    identityStats: {
      flexDirection: 'row',
      gap: Spacing.xs,
    },
    identityStat: {
      flex: 1,
      borderRadius: Radius.sm,
      backgroundColor: colors.bgMuted,
      padding: Spacing.sm,
      gap: 2,
    },
    identityStatValue: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xxl,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    identityStatLabel: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.semibold,
      color: colors.textFaint,
    },
    latestBadgeRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      borderRadius: Radius.sm,
      backgroundColor: colors.bgMuted,
      paddingHorizontal: Spacing.sm,
      paddingVertical: 9,
    },
    latestBadgeText: {
      flex: 1,
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.semibold,
      color: colors.text,
    },
    identityHint: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      color: colors.textMuted,
      lineHeight: 18,
    },
    identityCta: {
      minHeight: 46,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      borderRadius: Radius.sm,
      backgroundColor: colors.primary,
      paddingHorizontal: Spacing.md,
      ...Shadows.sm,
    },
    identityCtaText: {
      flexShrink: 1,
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.bold,
      color: colors.textOnPrimary,
      textAlign: 'center',
    },
    statsRow: {
      flexDirection: 'row',
      gap: Spacing.xs,
      paddingHorizontal: Spacing.md,
      paddingTop: Spacing.md,
    },
    statCard: {
      flex: 1,
      borderRadius: Radius.md,
      backgroundColor: colors.bgAlt,
      borderWidth: 1,
      borderColor: colors.borderLight,
      paddingVertical: Spacing.sm,
      paddingHorizontal: Spacing.xs,
      alignItems: 'center',
      gap: 3,
    },
    statValue: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xxl,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    statLabel: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.semibold,
      color: colors.textFaint,
      textAlign: 'center',
    },

    /* ── Sections ── */
    section: {
      paddingHorizontal: Spacing.md,
      paddingTop: Spacing.lg,
      gap: 10,
    },
    sectionTitle: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.semibold,
      color: colors.textMuted,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },

    /* ── Nav Links ── */
    navRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: Spacing.sm,
      gap: Spacing.sm,
      borderBottomWidth: 1,
      borderBottomColor: colors.borderLight,
    },
    navIcon: {
      width: 36,
      height: 36,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    navLabel: {
      flex: 1,
      fontFamily: Fonts.body,
      fontSize: 15,
      fontWeight: FontWeight.medium,
      color: colors.text,
    },
    adminPill: {
      backgroundColor: colors.primaryPale,
      borderRadius: 8,
      paddingVertical: 2,
      paddingHorizontal: 6,
      marginRight: 4,
    },
    adminPillText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.bold,
      color: colors.primaryMid,
    },

    /* ── Logout ── */
    logoutRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 14,
      gap: Spacing.xs,
      backgroundColor: colors.redPale,
      borderRadius: Radius.md,
      borderWidth: 1,
      borderColor: colors.redBorder,
    },
    logoutText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.lg,
      fontWeight: FontWeight.medium,
      color: colors.red,
    },
  });
}
