import { StyleSheet } from 'react-native';
import type { ThemeColors } from '../theme';
import { Fonts, FontSize, FontWeight, Radius, Shadows, Spacing } from '../theme';

export function createStyles(colors: ThemeColors) {
  const cm = StyleSheet.create({
    overlay: { flex: 1, backgroundColor: colors.overlayHeavy, justifyContent: 'flex-end', alignItems: 'center' },
    sheet: { backgroundColor: colors.bgAlt, borderTopLeftRadius: 20, borderTopRightRadius: 20, paddingHorizontal: 20, paddingBottom: 32, width: '100%', maxWidth: 430, ...Shadows.lg },
    handleWrap: { alignItems: 'center', paddingVertical: 10 },
    handle: { width: 36, height: 4, borderRadius: 2, backgroundColor: colors.border },
    title: { fontFamily: Fonts.heading, fontSize: FontSize.xxl, fontWeight: FontWeight.bold, color: colors.text, marginBottom: Spacing.md },
    options: { gap: Spacing.xs },
    optionBtn: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, backgroundColor: colors.bg, borderRadius: Radius.md, padding: 14, borderWidth: 1, borderColor: colors.borderLight, ...Shadows.sm },
    optionText: { fontFamily: Fonts.body, fontSize: 15, fontWeight: FontWeight.medium, color: colors.text },
    customSection: { gap: 12 },
    customLabel: { fontFamily: Fonts.body, fontSize: FontSize.md, fontWeight: FontWeight.semibold, color: colors.textMuted },
    input: { borderWidth: 1.5, borderColor: colors.border, borderRadius: Radius.md, padding: Spacing.sm, fontFamily: Fonts.body, fontSize: FontSize.xl, color: colors.text, backgroundColor: colors.bgAlt },
    timeRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.xs },
    timeInput: { flex: 1, textAlign: 'center' },
    timeSep: { fontFamily: Fonts.heading, fontSize: 22, fontWeight: FontWeight.bold, color: colors.text },
    customActions: { flexDirection: 'row', gap: 10, marginTop: 4 },
    backBtn: { flex: 1, alignItems: 'center', justifyContent: 'center', borderRadius: Radius.lg, paddingVertical: 14, borderWidth: 1, borderColor: colors.border },
    backBtnText: { fontFamily: Fonts.body, fontSize: FontSize.lg, fontWeight: FontWeight.semibold, color: colors.textMuted },
    confirmBtn: { flex: 1, alignItems: 'center', justifyContent: 'center', borderRadius: Radius.lg, paddingVertical: 14, backgroundColor: colors.primary, ...Shadows.md },
    confirmBtnText: { fontFamily: Fonts.body, fontSize: FontSize.lg, fontWeight: FontWeight.semibold, color: colors.textOnPrimary },
  });

  const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.bg,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: colors.bgAlt,
      height: 52,
      paddingHorizontal: Spacing.md,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      ...Shadows.bar,
    },
    backBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    backText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.lg,
      fontWeight: FontWeight.medium,
      color: colors.textMuted,
    },
    headerActions: {
      flexDirection: 'row',
      gap: Spacing.sm,
    },
    scroll: {
      flex: 1,
    },
    photoStrip: {
      backgroundColor: colors.bgMid,
      position: 'relative',
      overflow: 'hidden',
    },
    photoPlaceholder: {
      flex: 1,
      backgroundColor: colors.bgMuted,
    },
    dotsRow: {
      position: 'absolute',
      bottom: 12,
      left: 0,
      right: 0,
      flexDirection: 'row',
      justifyContent: 'center',
      gap: 6,
    },
    dot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: colors.textOnPrimary,
      opacity: 0.4,
    },
    dotActive: {
      opacity: 1,
      width: 8,
      height: 8,
      borderRadius: 4,
    },
    addPhotoBtn: {
      position: 'absolute',
      bottom: 12,
      right: 12,
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      ...Shadows.lg,
    },
    photoCount: {
      position: 'absolute',
      bottom: 12,
      left: 12,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.overlayHeavy,
      borderRadius: 100,
      paddingVertical: 4,
      paddingHorizontal: 10,
      gap: 4,
    },
    photoCountText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      color: colors.textOnPrimary,
    },
    venueInfo: {
      padding: Spacing.md,
      gap: 14,
    },
    infoTop: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    infoTitleGroup: {
      flex: 1,
      gap: 6,
    },
    infoTitle: {
      fontFamily: Fonts.heading,
      fontSize: FontSize.xxxl,
      fontWeight: FontWeight.bold,
      color: colors.text,
    },
    infoBadges: {
      flexDirection: 'row',
      gap: 6,
    },
    badgeVerified: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.primaryPale,
      borderRadius: 100,
      paddingVertical: 2,
      paddingHorizontal: 8,
      gap: 4,
    },
    badgeVerifiedText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.semibold,
      color: colors.primaryMid,
    },
    badgeFree: {
      backgroundColor: colors.bluePale,
      borderRadius: 100,
      paddingVertical: 2,
      paddingHorizontal: 8,
    },
    badgeFreeText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.xs,
      fontWeight: FontWeight.semibold,
      color: colors.blue,
    },
    infoRating: {
      alignItems: 'flex-end',
      gap: 2,
    },
    ratingStars: {
      fontFamily: Fonts.body,
      fontSize: FontSize.lg,
      color: colors.accent,
    },
    ratingCount: {
      fontFamily: Fonts.body,
      fontSize: FontSize.base,
      color: colors.textFaint,
    },
    divider: {
      height: 1,
      backgroundColor: colors.bgMid,
    },
    infoGrid: {
      gap: 10,
    },
    infoRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    infoRowText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      color: colors.textMuted,
    },
    championRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: colors.amberPale,
      borderRadius: Radius.md,
      padding: 10,
      borderWidth: 1,
      borderColor: colors.amberDeep,
    },
    championText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.medium,
      color: colors.accent,
      flex: 1,
    },
    evalBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primaryPale,
      borderRadius: Radius.md,
      height: 38,
      gap: 8,
      borderWidth: 1,
      borderColor: colors.primaryDim,
      ...Shadows.sm,
    },
    evalText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.semibold,
      color: colors.primaryMid,
    },
    friendsSection: {
      backgroundColor: colors.purplePale,
      padding: Spacing.md,
      gap: 10,
      ...Shadows.sm,
    },
    friendsTitle: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    friendsTitleText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.semibold,
      color: colors.purple,
    },
    checkinRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    checkinAvatar: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: colors.purpleMid,
      alignItems: 'center',
      justifyContent: 'center',
    },
    checkinInitials: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.bold,
      color: colors.textOnPrimary,
    },
    checkinInfo: {
      gap: 1,
    },
    checkinName: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.semibold,
      color: colors.text,
    },
    checkinTime: {
      fontFamily: Fonts.body,
      fontSize: FontSize.sm,
      color: colors.textFaint,
    },
    checkinBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.purple,
      borderRadius: Radius.md,
      height: 40,
      gap: 8,
      ...Shadows.md,
    },
    checkinBtnText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.semibold,
      color: colors.textOnPrimary,
    },
    activeCheckinWrap: {
      gap: Spacing.xs,
    },
    activeCheckinInfo: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xs,
      backgroundColor: colors.primaryPale,
      borderRadius: Radius.md,
      padding: Spacing.sm,
      borderWidth: 1,
      borderColor: colors.primaryDim,
    },
    activeCheckinText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.medium,
      color: colors.primaryMid,
      flex: 1,
    },
    checkoutBtn: {
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: Radius.md,
      height: 40,
      borderWidth: 1.5,
      borderColor: colors.red,
      backgroundColor: colors.redPale,
    },
    checkoutBtnText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.semibold,
      color: colors.red,
    },
    directionsSection: {
      padding: Spacing.md,
      gap: 10,
    },
    directionsTitle: {
      fontFamily: Fonts.body,
      fontSize: FontSize.lg,
      fontWeight: FontWeight.semibold,
      color: colors.text,
    },
    directionsRow: {
      flexDirection: 'row',
      gap: Spacing.xs,
    },
    dirGoogle: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.bgAlt,
      borderRadius: Radius.md,
      height: 40,
      gap: 6,
      ...Shadows.sm,
    },
    dirGoogleText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.base,
      fontWeight: FontWeight.semibold,
      color: colors.text,
    },
    dirOther: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.bgAlt,
      borderRadius: Radius.md,
      height: 40,
      ...Shadows.sm,
    },
    dirOtherText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.base,
      fontWeight: FontWeight.semibold,
      color: colors.text,
    },
    reviewsSection: {
      backgroundColor: colors.bgAlt,
      padding: Spacing.md,
      gap: Spacing.sm,
      borderTopWidth: 1,
      borderTopColor: colors.borderLight,
    },
    reviewsHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    reviewsTitle: {
      fontFamily: Fonts.body,
      fontSize: FontSize.lg,
      fontWeight: FontWeight.semibold,
      color: colors.text,
    },
    writeReviewBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.primaryPale,
      borderRadius: 8,
      paddingVertical: 6,
      paddingHorizontal: Spacing.sm,
      gap: Spacing.xxs,
      borderWidth: 1,
      borderColor: colors.primaryDim,
      ...Shadows.sm,
    },
    writeReviewText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.base,
      fontWeight: FontWeight.semibold,
      color: colors.primaryMid,
    },
    reviewCard: {
      padding: Spacing.sm,
      gap: Spacing.xs,
    },
    reviewTop: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    reviewAuthor: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      fontWeight: FontWeight.semibold,
      color: colors.text,
    },
    reviewStars: {
      fontFamily: Fonts.body,
      fontSize: FontSize.base,
      color: colors.accent,
    },
    reviewText: {
      fontFamily: Fonts.body,
      fontSize: FontSize.md,
      color: colors.textMuted,
      lineHeight: 13 * 1.45,
    },
    reviewDate: {
      fontFamily: Fonts.body,
      fontSize: 11,
      color: colors.textFaint,
    },
  });

  return { cm, styles };
}
