-- Seed catalog into public.challenges
-- Generated from challenge_catalog_category_codes.json

insert into public.challenges (code, legacy_code, category, title, verification_type)
values
  ('CRF001', 'BRZ004', 'craft_player'::public.challenge_category, 'Play a session longer than two hours', 'other'::public.verification_type),
  ('CRF002', 'BRZ005', 'craft_player'::public.challenge_category, 'Be as fairplay as Timo Boll', 'self'::public.verification_type),
  ('CRF003', 'BRZ011', 'craft_player'::public.challenge_category, 'Play 3 matches in one day', 'other'::public.verification_type),
  ('CRF004', 'BRZ013', 'craft_player'::public.challenge_category, 'Try a new rubber or paddle', 'other'::public.verification_type),
  ('CRF005', 'BRZ014', 'craft_player'::public.challenge_category, 'Warm up properly before a match', 'self'::public.verification_type),
  ('CRF006', 'BRZ017', 'craft_player'::public.challenge_category, 'Play a full set without arguing any point', 'self'::public.verification_type),
  ('CRF007', 'BRZ020', 'craft_player'::public.challenge_category, 'Do 20 shadow swings before a match', 'self'::public.verification_type),
  ('CRF008', 'BRZ024', 'craft_player'::public.challenge_category, 'Play one match without checking your phone', 'self'::public.verification_type),
  ('CRF009', 'BRZ147', 'craft_player'::public.challenge_category, 'Use a reset routine between 5 consecutive points', 'self'::public.verification_type),
  ('CRF010', 'SLV003', 'craft_player'::public.challenge_category, 'Play a set with your non-dominant hand', 'other'::public.verification_type),
  ('CRF011', 'SLV019', 'craft_player'::public.challenge_category, 'Win 5 points in a row', 'other'::public.verification_type),
  ('CRF012', 'SLV033', 'craft_player'::public.challenge_category, 'Play a set without looking at the score', 'self'::public.verification_type),
  ('CRF013', 'SLV034', 'craft_player'::public.challenge_category, 'Play a match using only 50% power', 'other'::public.verification_type),
  ('CRF014', 'SLV137', 'craft_player'::public.challenge_category, 'Play a set without a direct serve or receive error', 'self'::public.verification_type),
  ('CRF015', 'SLV147', 'craft_player'::public.challenge_category, 'Win 2 points in deuce situations during one match', 'other'::public.verification_type),
  ('CRF016', 'GLD001', 'craft_player'::public.challenge_category, 'Win 11-0', 'other'::public.verification_type),
  ('CRF017', 'GLD002', 'craft_player'::public.challenge_category, 'Win against Paul (comeback 0-2 → 3-2)', 'other'::public.verification_type),
  ('CRF018', 'GLD005', 'craft_player'::public.challenge_category, 'Full match only backhand', 'other'::public.verification_type),
  ('CRF019', 'GLD009', 'craft_player'::public.challenge_category, 'Win 3 matches in a row', 'other'::public.verification_type),
  ('CRF020', 'GLD010', 'craft_player'::public.challenge_category, 'Comeback from 0-2', 'other'::public.verification_type),
  ('CRF021', 'GLD014', 'craft_player'::public.challenge_category, 'Beat higher-rated player', 'other'::public.verification_type),
  ('CRF022', 'GLD015', 'craft_player'::public.challenge_category, 'Match without unforced errors', 'self'::public.verification_type),
  ('CRF023', 'GLD016', 'craft_player'::public.challenge_category, 'Win match 3-0', 'other'::public.verification_type),
  ('CRF024', 'GLD017', 'craft_player'::public.challenge_category, 'Win 5 matches in one day', 'other'::public.verification_type),
  ('CRF025', 'GLD019', 'craft_player'::public.challenge_category, 'Come back 5-10 → win set', 'other'::public.verification_type),
  ('CRF026', 'GLD020', 'craft_player'::public.challenge_category, 'Win final deciding set', 'other'::public.verification_type),
  ('CRF027', 'GLD021', 'craft_player'::public.challenge_category, 'Play blindfolded for 3 points', 'other'::public.verification_type),
  ('CRF028', 'GLD026', 'craft_player'::public.challenge_category, 'Whisper instead of talking for a full match', 'self'::public.verification_type),
  ('CRF029', 'GLD027', 'craft_player'::public.challenge_category, 'Play with music blasting in headphones', 'other'::public.verification_type),
  ('CRF030', 'GLD033', 'craft_player'::public.challenge_category, 'Let your opponent serve twice every point', 'self'::public.verification_type),
  ('CRF031', 'GLD138', 'craft_player'::public.challenge_category, 'Win a set from 8-8 or later without making an unforced error', 'self'::public.verification_type),
  ('CRF032', 'GLD145', 'craft_player'::public.challenge_category, 'Use a reset or timeout routine and come back to win a close match', 'other'::public.verification_type),
  ('CRF033', 'GLD146', 'craft_player'::public.challenge_category, 'Win a game after losing the first two points', 'other'::public.verification_type),
  ('SPN001', 'BRZ101', 'spin_artist'::public.challenge_category, 'Maintain a backspin rally of 10 shots', 'self'::public.verification_type),
  ('SPN002', 'BRZ102', 'spin_artist'::public.challenge_category, 'Land 5 controlled topspins against a passive block', 'self'::public.verification_type),
  ('SPN003', 'BRZ103', 'spin_artist'::public.challenge_category, 'Successfully return 5 sidespin serves', 'self'::public.verification_type),
  ('SPN004', 'BRZ136', 'spin_artist'::public.challenge_category, 'Place 5 backspin balls to a chosen target zone', 'self'::public.verification_type),
  ('SPN005', 'BRZ140', 'spin_artist'::public.challenge_category, 'Play one short push then one long push successfully 5 times', 'self'::public.verification_type),
  ('SPN006', 'SLV101', 'spin_artist'::public.challenge_category, 'Place 8 backspin shots alternately short and long', 'self'::public.verification_type),
  ('SPN007', 'SLV102', 'spin_artist'::public.challenge_category, 'Maintain a topspin rally of 15 shots', 'self'::public.verification_type),
  ('SPN008', 'SLV103', 'spin_artist'::public.challenge_category, 'Return sidespin serves with controlled placement 5 times', 'self'::public.verification_type),
  ('SPN009', 'SLV133', 'spin_artist'::public.challenge_category, 'Land 5 forehand topspins to 2 different target zones', 'self'::public.verification_type),
  ('SPN010', 'SLV145', 'spin_artist'::public.challenge_category, 'Change spin type during a rally and stay in the point', 'other'::public.verification_type),
  ('SPN011', 'GLD101', 'spin_artist'::public.challenge_category, 'Win a rally using at least 2 different spin types', 'other'::public.verification_type),
  ('SPN012', 'GLD102', 'spin_artist'::public.challenge_category, 'Win 3 points using topspin attacks under pressure', 'other'::public.verification_type),
  ('SPN013', 'GLD133', 'spin_artist'::public.challenge_category, 'Win a set by controlling the short game and opening first', 'other'::public.verification_type),
  ('SPN014', 'GLD142', 'spin_artist'::public.challenge_category, 'Win a rally with a counterloop from both forehand and backhand sides in one match', 'other'::public.verification_type),
  ('ATK001', 'BRZ110', 'first_attack_burst'::public.challenge_category, 'Win a point within first 3 shots', 'other'::public.verification_type),
  ('ATK002', 'BRZ111', 'first_attack_burst'::public.challenge_category, 'Execute 3 successful third-ball attacks', 'self'::public.verification_type),
  ('ATK003', 'BRZ134', 'first_attack_burst'::public.challenge_category, 'Open the rally with topspin after 2 pushes', 'self'::public.verification_type),
  ('ATK004', 'BRZ141', 'first_attack_burst'::public.challenge_category, 'Start the attack after receiving a long serve', 'self'::public.verification_type),
  ('ATK005', 'BRZ144', 'first_attack_burst'::public.challenge_category, 'Win a point by attacking the opponent’s elbow', 'other'::public.verification_type),
  ('ATK006', 'SLV110', 'first_attack_burst'::public.challenge_category, 'Win 3 points using serve + attack combination', 'other'::public.verification_type),
  ('ATK007', 'SLV111', 'first_attack_burst'::public.challenge_category, 'Land 5 controlled opening loops', 'self'::public.verification_type),
  ('ATK008', 'SLV134', 'first_attack_burst'::public.challenge_category, 'Win a point by attacking the wide forehand on the third ball', 'other'::public.verification_type),
  ('ATK009', 'SLV138', 'first_attack_burst'::public.challenge_category, 'Execute 3 successful backhand openings against backspin', 'self'::public.verification_type),
  ('ATK010', 'SLV139', 'first_attack_burst'::public.challenge_category, 'Serve short and win the point after a long return', 'other'::public.verification_type),
  ('ATK011', 'SLV144', 'first_attack_burst'::public.challenge_category, 'Win a point by attacking the opponent’s elbow', 'other'::public.verification_type),
  ('ATK012', 'GLD110', 'first_attack_burst'::public.challenge_category, 'Win 5 points directly from third-ball attack', 'other'::public.verification_type),
  ('ATK013', 'GLD111', 'first_attack_burst'::public.challenge_category, 'Win a set using aggressive first attacks', 'other'::public.verification_type),
  ('ATK014', 'GLD132', 'first_attack_burst'::public.challenge_category, 'Win 3 points using a serve + third-ball + fifth-ball pattern', 'other'::public.verification_type),
  ('ATK015', 'GLD135', 'first_attack_burst'::public.challenge_category, 'Win a point with a counterloop after the rally has already opened', 'other'::public.verification_type),
  ('ATK016', 'GLD140', 'first_attack_burst'::public.challenge_category, 'Win 3 points by attacking after a short receive exchange', 'other'::public.verification_type),
  ('FTW001', 'BRZ120', 'footwork_engine'::public.challenge_category, 'Complete 10 controlled side-to-side movements', 'self'::public.verification_type),
  ('FTW002', 'BRZ121', 'footwork_engine'::public.challenge_category, 'Return to ready position after every shot for 1 rally', 'self'::public.verification_type),
  ('FTW003', 'BRZ135', 'footwork_engine'::public.challenge_category, 'Serve and recover to ready position correctly 5 times', 'self'::public.verification_type),
  ('FTW004', 'BRZ139', 'footwork_engine'::public.challenge_category, 'Alternate 8 controlled placements from forehand to backhand', 'self'::public.verification_type),
  ('FTW005', 'BRZ144', 'footwork_engine'::public.challenge_category, 'Stay in a low ready stance for one full rally', 'self'::public.verification_type),
  ('FTW006', 'BRZ145', 'footwork_engine'::public.challenge_category, 'Backhand counter — 10 in a row', 'self'::public.verification_type),
  ('FTW007', 'BRZ146', 'footwork_engine'::public.challenge_category, 'Forehand counter — 10 in a row', 'self'::public.verification_type),
  ('FTW008', 'SLV120', 'footwork_engine'::public.challenge_category, 'Execute 3 successful pivot attacks', 'self'::public.verification_type),
  ('FTW009', 'SLV121', 'footwork_engine'::public.challenge_category, 'Maintain movement during a 10-shot rally', 'self'::public.verification_type),
  ('FTW010', 'SLV135', 'footwork_engine'::public.challenge_category, 'Pivot to attack and recover back into the rally successfully', 'self'::public.verification_type),
  ('FTW011', 'SLV141', 'footwork_engine'::public.challenge_category, 'Open with backhand topspin and recover to ready position', 'self'::public.verification_type),
  ('FTW012', 'SLV148', 'footwork_engine'::public.challenge_category, 'Maintain a forehand-backhand transition rally of 12 shots', 'self'::public.verification_type),
  ('FTW013', 'GLD120', 'footwork_engine'::public.challenge_category, 'Win 3 points using active footwork positioning', 'other'::public.verification_type),
  ('FTW014', 'GLD121', 'footwork_engine'::public.challenge_category, 'Recover position and win 3 extended rallies', 'other'::public.verification_type),
  ('DEF001', 'BRZ130', 'table_guardian'::public.challenge_category, 'Successfully block 5 shots in a row', 'self'::public.verification_type),
  ('DEF002', 'BRZ131', 'table_guardian'::public.challenge_category, 'Return 5 balls using defensive chop', 'self'::public.verification_type),
  ('DEF003', 'BRZ137', 'table_guardian'::public.challenge_category, 'Block 5 attacking balls back to the middle', 'self'::public.verification_type),
  ('DEF004', 'BRZ142', 'table_guardian'::public.challenge_category, 'Block 5 balls in a row back to the middle', 'self'::public.verification_type),
  ('DEF005', 'SLV130', 'table_guardian'::public.challenge_category, 'Block 10 shots in a rally', 'self'::public.verification_type),
  ('DEF006', 'SLV131', 'table_guardian'::public.challenge_category, 'Return 3 attacks using defensive lobs', 'self'::public.verification_type),
  ('DEF007', 'SLV136', 'table_guardian'::public.challenge_category, 'Block 6 balls deep while changing direction at least once', 'self'::public.verification_type),
  ('DEF008', 'SLV143', 'table_guardian'::public.challenge_category, 'Stay in the rally through 3 consecutive attacking balls', 'other'::public.verification_type),
  ('DEF009', 'GLD130', 'table_guardian'::public.challenge_category, 'Win 3 points by transitioning from defense to attack', 'other'::public.verification_type),
  ('DEF010', 'GLD131', 'table_guardian'::public.challenge_category, 'Win a point after defending with 3+ lobs', 'other'::public.verification_type),
  ('DEF011', 'GLD137', 'table_guardian'::public.challenge_category, 'Defend 3 attacks and then win the point with a counterattack', 'other'::public.verification_type),
  ('DEF012', 'GLD143', 'table_guardian'::public.challenge_category, 'Absorb both short and deep pressure in one rally, then win the point', 'other'::public.verification_type),
  ('SRV001', 'BRZ010', 'serve_lab'::public.challenge_category, 'Hold several balls in your pocket to serve as fast as Felix Lebrun', 'self'::public.verification_type),
  ('SRV002', 'BRZ023', 'serve_lab'::public.challenge_category, 'Learn and try one new serve', 'self'::public.verification_type),
  ('SRV003', 'BRZ039', 'serve_lab'::public.challenge_category, 'Serve 5 legal serves in a row', 'self'::public.verification_type),
  ('SRV004', 'BRZ132', 'serve_lab'::public.challenge_category, 'Serve 3 short balls that bounce twice on the opponent’s side', 'other'::public.verification_type),
  ('SRV005', 'BRZ138', 'serve_lab'::public.challenge_category, 'Land 5 short serves to the backhand half', 'self'::public.verification_type),
  ('SRV006', 'BRZ139', 'serve_lab'::public.challenge_category, 'Alternate 8 controlled placements from forehand to backhand', 'self'::public.verification_type),
  ('SRV007', 'SLV001', 'serve_lab'::public.challenge_category, 'Win a set serving only with the backhand', 'other'::public.verification_type),
  ('SRV008', 'SLV002', 'serve_lab'::public.challenge_category, 'Two consecutive successful tomahawk serves', 'self'::public.verification_type),
  ('SRV009', 'SLV009', 'serve_lab'::public.challenge_category, 'Attempt and win the point with a ghost serve', 'other'::public.verification_type),
  ('SRV010', 'SLV011', 'serve_lab'::public.challenge_category, 'Serve a reverse pendulum like Fan Zhendong', 'self'::public.verification_type),
  ('SRV011', 'SLV013', 'serve_lab'::public.challenge_category, 'Attempt a Ding Ning signature serve', 'self'::public.verification_type),
  ('SRV012', 'SLV016', 'serve_lab'::public.challenge_category, 'Do a very high toss service like Hugo Calderano', 'self'::public.verification_type),
  ('SRV013', 'SLV018', 'serve_lab'::public.challenge_category, 'Win a set using only long serves', 'other'::public.verification_type),
  ('SRV014', 'SLV020', 'serve_lab'::public.challenge_category, 'Successfully execute 3 different serves in one set', 'other'::public.verification_type),
  ('SRV015', 'SLV023', 'serve_lab'::public.challenge_category, 'Play a full set without missing a serve', 'other'::public.verification_type),
  ('SRV016', 'SLV032', 'serve_lab'::public.challenge_category, 'Only use serves you’ve never practiced', 'self'::public.verification_type),
  ('SRV017', 'GLD003', 'serve_lab'::public.challenge_category, 'Serve + pivot forehand like Ma Long', 'other'::public.verification_type),
  ('SRV018', 'GLD011', 'serve_lab'::public.challenge_category, 'Perfect serve set (no lost serve points)', 'other'::public.verification_type),
  ('SRV019', 'GLD012', 'serve_lab'::public.challenge_category, 'Win using 3 serve types', 'other'::public.verification_type),
  ('SRV020', 'GLD018', 'serve_lab'::public.challenge_category, 'Win using only one serve', 'other'::public.verification_type),
  ('SRV021', 'GLD136', 'serve_lab'::public.challenge_category, 'Win 3 points using a surprise long serve as the setup', 'other'::public.verification_type),
  ('SRV022', 'GLD139', 'serve_lab'::public.challenge_category, 'Win points using 3 different serve patterns in one match', 'other'::public.verification_type),
  ('SRV023', 'GLD148', 'serve_lab'::public.challenge_category, 'Win a set using a planned serve, receive, and first-attack pattern', 'other'::public.verification_type),
  ('CMP001', 'BRZ015', 'competitor'::public.challenge_category, 'Win a point with a simple push rally', 'other'::public.verification_type),
  ('CMP002', 'BRZ016', 'competitor'::public.challenge_category, 'Successfully return 5 serves in a row', 'self'::public.verification_type),
  ('CMP003', 'BRZ019', 'competitor'::public.challenge_category, 'Bounce the ball on your paddle 50 times without dropping', 'self'::public.verification_type),
  ('CMP004', 'BRZ033', 'competitor'::public.challenge_category, 'Forehand drive — 10 in a row', 'self'::public.verification_type),
  ('CMP005', 'BRZ034', 'competitor'::public.challenge_category, 'Backhand drive — 10 in a row', 'self'::public.verification_type),
  ('CMP006', 'BRZ035', 'competitor'::public.challenge_category, 'Forehand push — 10 in a row', 'self'::public.verification_type),
  ('CMP007', 'BRZ036', 'competitor'::public.challenge_category, 'Backhand push — 10 in a row', 'self'::public.verification_type),
  ('CMP008', 'BRZ037', 'competitor'::public.challenge_category, 'Block — 5 balls in a row on the table', 'self'::public.verification_type),
  ('CMP009', 'BRZ038', 'competitor'::public.challenge_category, 'Finish a high ball with a smash', 'other'::public.verification_type),
  ('CMP010', 'BRZ040', 'competitor'::public.challenge_category, 'Return 5 basic serves in a row', 'self'::public.verification_type),
  ('CMP011', 'BRZ133', 'competitor'::public.challenge_category, 'Alternate forehand and backhand drives for 8 shots', 'other'::public.verification_type),
  ('CMP012', 'BRZ145', 'competitor'::public.challenge_category, 'Backhand counter — 10 in a row', 'self'::public.verification_type),
  ('CMP013', 'BRZ146', 'competitor'::public.challenge_category, 'Forehand counter — 10 in a row', 'self'::public.verification_type),
  ('CMP014', 'BRZ147', 'competitor'::public.challenge_category, 'Use a reset routine between 5 consecutive points', 'self'::public.verification_type),
  ('CMP015', 'SLV004', 'competitor'::public.challenge_category, 'Win against a chopper', 'other'::public.verification_type),
  ('CMP016', 'SLV005', 'competitor'::public.challenge_category, 'Do a successful chop-block', 'other'::public.verification_type),
  ('CMP017', 'SLV010', 'competitor'::public.challenge_category, 'Win a point with an Adriana Diaz punch', 'other'::public.verification_type),
  ('CMP018', 'SLV012', 'competitor'::public.challenge_category, 'Do a forehand chop-block like Bernadette Szocs', 'other'::public.verification_type),
  ('CMP019', 'SLV014', 'competitor'::public.challenge_category, 'Attempt a Lin Yun-Ru backhand flip', 'other'::public.verification_type),
  ('CMP020', 'SLV015', 'competitor'::public.challenge_category, 'Perform a forehand flick like Ovidiu Ionescu', 'other'::public.verification_type),
  ('CMP021', 'SLV017', 'competitor'::public.challenge_category, 'Win the point defending with lobs like Simon Gauzy', 'other'::public.verification_type),
  ('CMP022', 'SLV021', 'competitor'::public.challenge_category, 'Win a point with a third ball attack', 'other'::public.verification_type),
  ('CMP023', 'SLV022', 'competitor'::public.challenge_category, 'Win a rally of 10+ shots', 'other'::public.verification_type),
  ('CMP024', 'SLV024', 'competitor'::public.challenge_category, 'Win a point with a backhand down the line', 'other'::public.verification_type),
  ('CMP025', 'SLV025', 'competitor'::public.challenge_category, 'Win a point with a forehand down the line', 'other'::public.verification_type),
  ('CMP026', 'SLV026', 'competitor'::public.challenge_category, 'Win a point using only pushes', 'other'::public.verification_type),
  ('CMP027', 'SLV027', 'competitor'::public.challenge_category, 'Successfully receive heavy spin 5 times', 'other'::public.verification_type),
  ('CMP028', 'SLV028', 'competitor'::public.challenge_category, 'Perform 3 successful flicks', 'self'::public.verification_type),
  ('CMP029', 'SLV029', 'competitor'::public.challenge_category, 'Win a point after fast serve + third ball', 'other'::public.verification_type),
  ('CMP030', 'SLV030', 'competitor'::public.challenge_category, 'Try to win a point without using spin', 'other'::public.verification_type),
  ('CMP031', 'SLV031', 'competitor'::public.challenge_category, 'Play a mirror match (copy your opponent’s style)', 'other'::public.verification_type),
  ('CMP032', 'SLV036', 'competitor'::public.challenge_category, 'Open with a forehand topspin against backspin', 'other'::public.verification_type),
  ('CMP033', 'SLV037', 'competitor'::public.challenge_category, 'Open with a backhand topspin against backspin', 'other'::public.verification_type),
  ('CMP034', 'SLV038', 'competitor'::public.challenge_category, 'Forehand flick a short ball to win the point', 'other'::public.verification_type),
  ('CMP035', 'SLV039', 'competitor'::public.challenge_category, 'Backhand flick a short ball to start the attack', 'other'::public.verification_type),
  ('CMP036', 'GLD004', 'competitor'::public.challenge_category, 'Truls Moregard chop-block sequence', 'other'::public.verification_type),
  ('CMP037', 'GLD006', 'competitor'::public.challenge_category, 'Forehand all around table like Quadri Aruna', 'other'::public.verification_type),
  ('CMP038', 'GLD013', 'competitor'::public.challenge_category, 'Perfect third ball attacks', 'other'::public.verification_type),
  ('CMP039', 'GLD034', 'competitor'::public.challenge_category, 'Win a point with a banana flick receive', 'other'::public.verification_type),
  ('CMP040', 'GLD035', 'competitor'::public.challenge_category, 'Counter-topspin — 3 balls in a row', 'other'::public.verification_type),
  ('CMP041', 'GLD036', 'competitor'::public.challenge_category, 'Backhand loop against backspin to start the rally', 'other'::public.verification_type),
  ('CMP042', 'GLD037', 'competitor'::public.challenge_category, 'Step around and win with a forehand loop from the backhand corner', 'other'::public.verification_type),
  ('CMP043', 'GLD038', 'competitor'::public.challenge_category, 'Win a point with a forehand sidespin loop', 'other'::public.verification_type),
  ('CMP044', 'GLD039', 'competitor'::public.challenge_category, 'Win a point with a backhand sidespin flick', 'other'::public.verification_type),
  ('CMP045', 'GLD040', 'competitor'::public.challenge_category, 'Fish from mid-distance and turn defense into attack', 'other'::public.verification_type),
  ('CMP046', 'GLD041', 'competitor'::public.challenge_category, 'Counter-smash and win the point', 'other'::public.verification_type),
  ('CMP047', 'GLD101', 'competitor'::public.challenge_category, 'Win a rally using at least 2 different spin types', 'other'::public.verification_type),
  ('CMP048', 'GLD102', 'competitor'::public.challenge_category, 'Win 3 points using topspin attacks under pressure', 'other'::public.verification_type),
  ('CMP049', 'GLD133', 'competitor'::public.challenge_category, 'Win a set by controlling the short game and opening first', 'other'::public.verification_type),
  ('CMP050', 'GLD142', 'competitor'::public.challenge_category, 'Win a rally with a counterloop from both forehand and backhand sides in one match', 'other'::public.verification_type),
  ('CMP051', 'GLD147', 'competitor'::public.challenge_category, 'Win a point that includes short game, opening attack, and counter phase', 'other'::public.verification_type),
  ('EXP001', 'BRZ001', 'explorer'::public.challenge_category, 'Play at any indoor venue', 'self'::public.verification_type),
  ('EXP002', 'BRZ002', 'explorer'::public.challenge_category, 'Play at any outdoor venue', 'self'::public.verification_type),
  ('EXP003', 'BRZ003', 'explorer'::public.challenge_category, 'Check-in at two locations in the same day', 'self'::public.verification_type),
  ('EXP004', 'BRZ009', 'explorer'::public.challenge_category, 'Register in a local tournament', 'self'::public.verification_type),
  ('EXP005', 'BRZ012', 'explorer'::public.challenge_category, 'Play with a new opponent', 'other'::public.verification_type),
  ('EXP006', 'BRZ018', 'explorer'::public.challenge_category, 'Record one rally on video', 'self'::public.verification_type),
  ('EXP007', 'BRZ021', 'explorer'::public.challenge_category, 'Play a lefty vs righty friendly match', 'other'::public.verification_type),
  ('EXP008', 'BRZ022', 'explorer'::public.challenge_category, 'Compliment your opponent after every set', 'other'::public.verification_type),
  ('EXP009', 'BRZ025', 'explorer'::public.challenge_category, 'Let your opponent choose your serves for one set', 'other'::public.verification_type),
  ('EXP010', 'BRZ026', 'explorer'::public.challenge_category, 'Record and post your best rally', 'self'::public.verification_type),
  ('EXP011', 'BRZ027', 'explorer'::public.challenge_category, 'Let a beginner coach you for one set', 'other'::public.verification_type),
  ('EXP012', 'BRZ028', 'explorer'::public.challenge_category, 'High-five your opponent after every point', 'other'::public.verification_type),
  ('EXP013', 'BRZ029', 'explorer'::public.challenge_category, 'Film a pro intro video of yourself', 'self'::public.verification_type),
  ('EXP014', 'BRZ030', 'explorer'::public.challenge_category, 'Teach someone a skill you learned', 'self'::public.verification_type),
  ('EXP015', 'BRZ031', 'explorer'::public.challenge_category, 'Add a new location on TTPortal', 'self'::public.verification_type),
  ('EXP016', 'BRZ032', 'explorer'::public.challenge_category, 'Invite a friend on TTPortal', 'self'::public.verification_type),
  ('EXP017', 'SLV146', 'explorer'::public.challenge_category, 'Play a best-of-three match with a friend', 'other'::public.verification_type),
  ('EXP018', 'SLV147', 'explorer'::public.challenge_category, 'Win 2 points in deuce situations during one match', 'other'::public.verification_type),
  ('EXP019', 'GLD028', 'explorer'::public.challenge_category, 'Let the crowd decide your tactics', 'other'::public.verification_type),
  ('EXP020', 'GLD030', 'explorer'::public.challenge_category, 'Play doubles with a stranger', 'other'::public.verification_type),
  ('EXP021', 'GLD144', 'explorer'::public.challenge_category, 'Beat two different opponents in the same session', 'other'::public.verification_type)
on conflict (code) do update set
  legacy_code = excluded.legacy_code,
  category = excluded.category,
  title = excluded.title,
  verification_type = excluded.verification_type,
  updated_at = now();

update public.challenges
set title_key = 'badgeChallenge_' || code
where title_key is null
  and code ~ '^(CRF|SPN|ATK|FTW|DEF|SRV|CMP|EXP)[0-9]{3}$';

-- Optional sanity checks
select category, count(*) as challenge_count
from public.challenges
group by category
order by category;

select verification_type, count(*) as challenge_count
from public.challenges
group by verification_type
order by verification_type;
