BEGIN;

CREATE TABLE IF NOT EXISTS public.equipment_catalog_manufacturers (
  category TEXT NOT NULL CHECK (category IN ('blade', 'rubber')),
  manufacturer_id TEXT NOT NULL,
  name TEXT NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (category, manufacturer_id)
);

CREATE TABLE IF NOT EXISTS public.equipment_catalog_models (
  category TEXT NOT NULL CHECK (category IN ('blade', 'rubber')),
  manufacturer_id TEXT NOT NULL,
  model TEXT NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (category, manufacturer_id, model),
  FOREIGN KEY (category, manufacturer_id)
    REFERENCES public.equipment_catalog_manufacturers(category, manufacturer_id)
    ON DELETE CASCADE
);

ALTER TABLE public.equipment_catalog_manufacturers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.equipment_catalog_models ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can read equipment catalog manufacturers" ON public.equipment_catalog_manufacturers;
CREATE POLICY "Anyone can read equipment catalog manufacturers"
  ON public.equipment_catalog_manufacturers
  FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Anyone can read equipment catalog models" ON public.equipment_catalog_models;
CREATE POLICY "Anyone can read equipment catalog models"
  ON public.equipment_catalog_models
  FOR SELECT
  USING (true);

CREATE INDEX IF NOT EXISTS idx_equipment_catalog_models_lookup
  ON public.equipment_catalog_models(category, manufacturer_id, sort_order);

DELETE FROM public.equipment_catalog_models WHERE category IN ('blade', 'rubber');
DELETE FROM public.equipment_catalog_manufacturers WHERE category IN ('blade', 'rubber');

INSERT INTO public.equipment_catalog_manufacturers (category, manufacturer_id, name, sort_order)
VALUES
  ('blade', 'butterfly', 'Butterfly', 0),
  ('blade', 'stiga', 'STIGA', 1),
  ('blade', 'dhs', 'DHS', 2),
  ('blade', 'donic', 'DONIC', 3),
  ('blade', 'andro', 'andro', 4),
  ('blade', 'tibhar', 'TIBHAR', 5),
  ('blade', 'xiom', 'XIOM', 6),
  ('blade', 'yasaka', 'Yasaka', 7),
  ('blade', 'nittaku', 'Nittaku', 8),
  ('blade', 'victas', 'VICTAS', 9),
  ('blade', 'joola', 'JOOLA', 10),
  ('blade', 'gewo', 'GEWO', 11),
  ('blade', 'cornilleau', 'Cornilleau', 12),
  ('blade', 'friendship-729', 'Friendship / 729', 13),
  ('blade', 'double-fish', 'Double Fish', 14),
  ('blade', 'dr-neubauer', 'Dr. Neubauer', 15),
  ('blade', 'der-materialspezialist', 'Der Materialspezialist', 16),
  ('blade', 'spinlord', 'SpinLord', 17),
  ('blade', 'sauer-troeger', 'Sauer & Tröger', 18),
  ('blade', 'hallmark', 'Hallmark', 19),
  ('blade', 'palio', 'Palio', 20),
  ('rubber', 'butterfly', 'Butterfly', 0),
  ('rubber', 'stiga', 'STIGA', 1),
  ('rubber', 'dhs', 'DHS', 2),
  ('rubber', 'donic', 'DONIC', 3),
  ('rubber', 'andro', 'andro', 4),
  ('rubber', 'tibhar', 'TIBHAR', 5),
  ('rubber', 'xiom', 'XIOM', 6),
  ('rubber', 'yasaka', 'Yasaka', 7),
  ('rubber', 'nittaku', 'Nittaku', 8),
  ('rubber', 'victas', 'VICTAS', 9),
  ('rubber', 'joola', 'JOOLA', 10),
  ('rubber', 'cornilleau', 'Cornilleau', 11),
  ('rubber', 'gewo', 'GEWO', 12),
  ('rubber', 'double-fish', 'Double Fish', 13),
  ('rubber', 'friendship-729', 'Friendship / 729', 14),
  ('rubber', 'dr-neubauer', 'Dr. Neubauer', 15),
  ('rubber', 'der-materialspezialist', 'Der Materialspezialist', 16),
  ('rubber', 'spinlord', 'SpinLord', 17),
  ('rubber', 'sauer-troeger', 'Sauer & Tröger', 18),
  ('rubber', 'hallmark', 'Hallmark', 19),
  ('rubber', 'palio', 'Palio', 20)
ON CONFLICT (category, manufacturer_id) DO UPDATE
SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order;

INSERT INTO public.equipment_catalog_models (category, manufacturer_id, model, sort_order)
VALUES
  ('blade', 'butterfly', 'Viscaria', 0),
  ('blade', 'butterfly', 'Viscaria Super ALC', 1),
  ('blade', 'butterfly', 'Timo Boll ALC', 2),
  ('blade', 'butterfly', 'Timo Boll ZLC', 3),
  ('blade', 'butterfly', 'Timo Boll Spirit', 4),
  ('blade', 'butterfly', 'Innerforce Layer ALC', 5),
  ('blade', 'butterfly', 'Innerforce Layer ZLC', 6),
  ('blade', 'butterfly', 'Harimoto Innerforce ALC', 7),
  ('blade', 'butterfly', 'Harimoto Innerforce ZLC', 8),
  ('blade', 'butterfly', 'Zhang Jike ALC', 9),
  ('blade', 'butterfly', 'Zhang Jike Super ZLC', 10),
  ('blade', 'butterfly', 'Lin Gaoyuan ALC', 11),
  ('blade', 'butterfly', 'Lin Yun-Ju Super ZLC', 12),
  ('blade', 'butterfly', 'Jun Mizutani Super ZLC', 13),
  ('blade', 'butterfly', 'Fan Zhendong ALC', 14),
  ('blade', 'butterfly', 'Korbel', 15),
  ('blade', 'butterfly', 'Korbel SK7', 16),
  ('blade', 'butterfly', 'Primorac', 17),
  ('blade', 'butterfly', 'SK7 Classic', 18),
  ('blade', 'butterfly', 'Primorac Carbon', 19),
  ('blade', 'butterfly', 'Boll CAF', 20),
  ('blade', 'butterfly', 'Timo Boll ZLF', 21),
  ('blade', 'butterfly', 'Fan Zhendong Super ZLC', 22),
  ('blade', 'butterfly', 'Petr Korbel Japan', 23),
  ('blade', 'butterfly', 'Grubba', 24),
  ('blade', 'butterfly', 'Schlager Carbon', 25),
  ('blade', 'butterfly', 'Maze ALC', 26),
  ('blade', 'butterfly', 'Keyshot', 27),
  ('blade', 'butterfly', 'Keyshot Light', 28),
  ('blade', 'butterfly', 'Sardius', 29),
  ('blade', 'butterfly', 'Gergely', 30),
  ('blade', 'butterfly', 'Amultart ZLC', 31),
  ('blade', 'butterfly', 'Photino', 32),
  ('blade', 'butterfly', 'Hadraw VR', 33),
  ('blade', 'butterfly', 'Hadraw SK', 34),
  ('blade', 'butterfly', 'Innerforce Layer ZLF', 35),
  ('blade', 'butterfly', 'Innerforce Layer CAF', 36),
  ('blade', 'butterfly', 'Zhang Jike ZLC', 37),
  ('blade', 'butterfly', 'Boll Forte', 38),
  ('blade', 'butterfly', 'Boll Allround', 39),
  ('blade', 'butterfly', 'Fan Zhendong ZLC', 40),
  ('blade', 'butterfly', 'Ovtcharov Innerforce ALC', 41),
  ('blade', 'butterfly', 'Garaydia ALC', 42),
  ('blade', 'butterfly', 'Garaydia ZLC', 43),
  ('blade', 'butterfly', 'Garaydia T5000', 44),
  ('blade', 'butterfly', 'Mizutani Jun ZLC', 45),
  ('blade', 'butterfly', 'Mizutani Jun Super ZLC', 46),
  ('blade', 'butterfly', 'Liu Shiwen', 47),
  ('blade', 'butterfly', 'Liu Shiwen ZLF', 48),
  ('blade', 'butterfly', 'Apolonia ZLC', 49),
  ('blade', 'butterfly', 'Franziska Innerforce ZLC', 50),
  ('blade', 'butterfly', 'Franziska Innerforce ALC', 51),
  ('blade', 'butterfly', 'Franziska Innerforce CAF', 52),
  ('blade', 'butterfly', 'Revoldia CNF', 53),
  ('blade', 'butterfly', 'Innerforce Layer Super ZLC', 54),
  ('blade', 'butterfly', 'Lin Yun-Ju Innerforce Super ZLC', 55),
  ('blade', 'butterfly', 'BalsaCarbo X5 22', 56),
  ('blade', 'butterfly', 'BalsaCarbo X5 24', 57),
  ('blade', 'butterfly', 'BalsaCarbo X5 29', 58),
  ('blade', 'butterfly', 'BalsaCarbo X7 22', 59),
  ('blade', 'butterfly', 'BalsaCarbo X7 29', 60),
  ('blade', 'butterfly', 'Kumpuru', 61),
  ('blade', 'butterfly', 'Nakama S-2', 62),
  ('blade', 'butterfly', 'Nakama P-1', 63),
  ('blade', 'butterfly', 'Nakama J-1', 64),
  ('blade', 'butterfly', 'Iolite Neo', 65),
  ('blade', 'butterfly', 'Kiso Hinoki V', 66),
  ('blade', 'butterfly', 'Kiso Hinoki VII', 67),
  ('blade', 'butterfly', 'Matsushita Pro Model', 68),
  ('blade', 'butterfly', 'Diode Pro', 69),
  ('blade', 'butterfly', 'Defence II', 70),
  ('blade', 'butterfly', 'Innershield Layer ZLF', 71),
  ('blade', 'butterfly', 'Innershield Layer ZLC', 72),
  ('blade', 'stiga', 'Allround Classic', 0),
  ('blade', 'stiga', 'Offensive Classic', 1),
  ('blade', 'stiga', 'Infinity VPS V', 2),
  ('blade', 'stiga', 'Clipper Wood', 3),
  ('blade', 'stiga', 'Clipper CR', 4),
  ('blade', 'stiga', 'Cybershape Carbon', 5),
  ('blade', 'stiga', 'Cybershape Wood', 6),
  ('blade', 'stiga', 'Dynasty Carbon', 7),
  ('blade', 'stiga', 'Inspira CCF', 8),
  ('blade', 'stiga', 'Arctic Wood', 9),
  ('blade', 'stiga', 'Energy Wood WRB', 10),
  ('blade', 'stiga', 'Nostalgic VII', 11),
  ('blade', 'stiga', 'Rosewood NCT VII', 12),
  ('blade', 'stiga', 'Maplewood NCT VII', 13),
  ('blade', 'stiga', 'Ebenholz NCT VII', 14),
  ('blade', 'stiga', 'Legacy Carbon', 15),
  ('blade', 'stiga', 'Cybershape Clipper', 16),
  ('blade', 'stiga', 'Cybershape Carbon CWT', 17),
  ('blade', 'stiga', 'Cybershape Carbon CWT Truls Edition', 18),
  ('blade', 'stiga', 'Pure CWT', 19),
  ('blade', 'stiga', 'Pure Cybershape CWT', 20),
  ('blade', 'stiga', 'Offensive Classic Carbon', 21),
  ('blade', 'stiga', 'Clipper CC', 22),
  ('blade', 'stiga', 'Clipper WRB', 23),
  ('blade', 'stiga', 'Allround Evolution', 24),
  ('blade', 'stiga', 'Offensive NCT', 25),
  ('blade', 'stiga', 'Carbonado 45', 26),
  ('blade', 'stiga', 'Carbonado 90', 27),
  ('blade', 'stiga', 'Dynasty Carbon Xu Xin Edition', 28),
  ('blade', 'stiga', 'Rosewood NCT V', 29),
  ('blade', 'stiga', 'Ebenholz NCT V', 30),
  ('blade', 'stiga', 'Nostalgic Offensive', 31),
  ('blade', 'stiga', 'Nostalgic Allround', 32),
  ('blade', 'stiga', 'Allround Classic WRB', 33),
  ('blade', 'stiga', 'Allround Classic Carbon', 34),
  ('blade', 'stiga', 'Offensive Classic WRB', 35),
  ('blade', 'stiga', 'Offensive Classic CR', 36),
  ('blade', 'stiga', 'Clipper Classic', 37),
  ('blade', 'stiga', 'Clipper CR WRB', 38),
  ('blade', 'stiga', 'Infinity VPS V Diamond Touch', 39),
  ('blade', 'stiga', 'Infinity VPS V Xu Xin Edition', 40),
  ('blade', 'stiga', 'Intensity NCT', 41),
  ('blade', 'stiga', 'Hybrid Wood', 42),
  ('blade', 'stiga', 'Azalea Allround', 43),
  ('blade', 'stiga', 'Azalea Offensive', 44),
  ('blade', 'stiga', 'Azalea Carbon', 45),
  ('blade', 'stiga', 'Nostalgic Offensive VII', 46),
  ('blade', 'stiga', 'Nostalgic Allround Wood', 47),
  ('blade', 'stiga', 'Nostalgic Offensive Carbon', 48),
  ('blade', 'stiga', 'Carbonado 145', 49),
  ('blade', 'stiga', 'Carbonado 190', 50),
  ('blade', 'stiga', 'Tube Allround', 51),
  ('blade', 'stiga', 'Tube Offensive', 52),
  ('blade', 'stiga', 'Tube Carbo', 53),
  ('blade', 'stiga', 'Optimum Sync', 54),
  ('blade', 'stiga', 'Optimum Plus', 55),
  ('blade', 'stiga', 'Rosewood XO', 56),
  ('blade', 'stiga', 'Defensive Classic', 57),
  ('blade', 'stiga', 'Defensive Pro', 58),
  ('blade', 'dhs', 'Hurricane Long 5', 0),
  ('blade', 'dhs', 'Hurricane Long 3', 1),
  ('blade', 'dhs', 'Hurricane King', 2),
  ('blade', 'dhs', 'W968', 3),
  ('blade', 'dhs', 'W3010', 4),
  ('blade', 'dhs', 'PG7', 5),
  ('blade', 'dhs', 'Power G7', 6),
  ('blade', 'dhs', 'N301', 7),
  ('blade', 'dhs', '301X', 8),
  ('blade', 'dhs', 'Fang Bo Carbon', 9),
  ('blade', 'dhs', 'Ma Long Carbon', 10),
  ('blade', 'dhs', 'T685', 11),
  ('blade', 'dhs', 'Hurricane Long 5X', 12),
  ('blade', 'dhs', 'Hurricane Hao 2', 13),
  ('blade', 'dhs', 'Hurricane Hao 3', 14),
  ('blade', 'dhs', 'Hurricane Long 2', 15),
  ('blade', 'dhs', 'Power G5', 16),
  ('blade', 'dhs', 'Power G6', 17),
  ('blade', 'dhs', 'PG3', 18),
  ('blade', 'dhs', '301', 19),
  ('blade', 'dhs', '301Z', 20),
  ('blade', 'dhs', 'Fang Bo B2', 21),
  ('blade', 'dhs', 'Bo Carbon', 22),
  ('blade', 'dhs', 'Wind 301', 23),
  ('blade', 'dhs', 'Wind 302', 24),
  ('blade', 'dhs', 'Wind 303', 25),
  ('blade', 'dhs', 'W997', 26),
  ('blade', 'dhs', 'Hurricane 301', 27),
  ('blade', 'dhs', 'Hurricane 301T', 28),
  ('blade', 'dhs', 'Hurricane 301X', 29),
  ('blade', 'dhs', 'Hurricane 301Z', 30),
  ('blade', 'dhs', 'Hurricane King 2', 31),
  ('blade', 'dhs', 'Power G8', 32),
  ('blade', 'dhs', 'Power G9', 33),
  ('blade', 'dhs', 'H-WL', 34),
  ('blade', 'dhs', 'H-WLX', 35),
  ('blade', 'dhs', 'N301 National', 36),
  ('blade', 'dhs', 'W968 National', 37),
  ('blade', 'dhs', 'W968 Provincial', 38),
  ('blade', 'dhs', '506', 39),
  ('blade', 'dhs', '506X', 40),
  ('blade', 'dhs', 'B506', 41),
  ('blade', 'dhs', 'PG2', 42),
  ('blade', 'dhs', 'PG8', 43),
  ('blade', 'dhs', 'M301', 44),
  ('blade', 'dhs', 'R301', 45),
  ('blade', 'dhs', 'T5002', 46),
  ('blade', 'dhs', 'T5003', 47),
  ('blade', 'donic', 'Original True Carbon', 0),
  ('blade', 'donic', 'Ovtcharov Original Carbon', 1),
  ('blade', 'donic', 'Ovtcharov Senso V1', 2),
  ('blade', 'donic', 'Waldner Senso Carbon', 3),
  ('blade', 'donic', 'Waldner Allplay', 4),
  ('blade', 'donic', 'Appelgren Allplay', 5),
  ('blade', 'donic', 'Persson Powerplay', 6),
  ('blade', 'donic', 'Persson Power Allround', 7),
  ('blade', 'donic', 'Waldner Exclusive AR+', 8),
  ('blade', 'donic', 'Defplay Inner Carbon', 9),
  ('blade', 'donic', 'Original Exclusive Carbon', 10),
  ('blade', 'donic', 'Dotec True Carbon Inner', 11),
  ('blade', 'donic', 'Waldner Dotec AR', 12),
  ('blade', 'donic', 'Waldner Dotec Carbon', 13),
  ('blade', 'donic', 'Ovtcharov No.1', 14),
  ('blade', 'donic', 'Ovtcharov No.1 Senso', 15),
  ('blade', 'donic', 'Burn OFF-', 16),
  ('blade', 'donic', 'Burn OFF', 17),
  ('blade', 'donic', 'Epox Power Carbon', 18),
  ('blade', 'donic', 'Persson Exclusive OFF', 19),
  ('blade', 'donic', 'Original Senso V1', 20),
  ('blade', 'donic', 'Appelgren Dotec Control', 21),
  ('blade', 'donic', 'Waldner Dotec AR+', 22),
  ('blade', 'donic', 'Waldner Dotec OFF', 23),
  ('blade', 'donic', 'Waldner Dotec Carbon Senso', 24),
  ('blade', 'donic', 'Waldner Legend Carbon', 25),
  ('blade', 'donic', 'Waldner Legend', 26),
  ('blade', 'donic', 'Waldner Black Devil CB', 27),
  ('blade', 'donic', 'Waldner Diablo Senso', 28),
  ('blade', 'donic', 'Persson Dotec OFF', 29),
  ('blade', 'donic', 'Persson Dotec OFF+', 30),
  ('blade', 'donic', 'Defplay Senso', 31),
  ('blade', 'donic', 'Defplay Classic Senso', 32),
  ('blade', 'donic', 'Burn AR', 33),
  ('blade', 'donic', 'Burn ALL+', 34),
  ('blade', 'donic', 'Carbospeed', 35),
  ('blade', 'donic', 'Epox Offensive', 36),
  ('blade', 'donic', 'Epox Control', 37),
  ('blade', 'donic', 'Ovtcharov Dotec OFF', 38),
  ('blade', 'donic', 'Original Dotec Carbon', 39),
  ('blade', 'donic', 'Anders Lind Hexa Carbon', 40),
  ('blade', 'donic', 'New Impuls 6.5', 41),
  ('blade', 'donic', 'New Impuls 7.0', 42),
  ('blade', 'donic', 'Balsa Carbo Fleece', 43),
  ('blade', 'donic', 'Esprit', 44),
  ('blade', 'donic', 'Power Allround', 45),
  ('blade', 'andro', 'Timber 5 OFF', 0),
  ('blade', 'andro', 'Timber 7 OFF', 1),
  ('blade', 'andro', 'Synteliac VCO OFF', 2),
  ('blade', 'andro', 'Treiber OFF', 3),
  ('blade', 'andro', 'Gauzy BL7 OFF', 4),
  ('blade', 'andro', 'Gauzy HL CO', 5),
  ('blade', 'andro', 'Ligna OFF', 6),
  ('blade', 'andro', 'Ligna ALL', 7),
  ('blade', 'andro', 'Wanokiwami Ren', 8),
  ('blade', 'andro', 'Gauzy SL OFF', 9),
  ('blade', 'andro', 'Synteliac ZCO OFF/S', 10),
  ('blade', 'andro', 'Treiber CI OFF', 11),
  ('blade', 'andro', 'Kinetic Supreme OFF', 12),
  ('blade', 'andro', 'Kinetic CF OFF', 13),
  ('blade', 'andro', 'Super Core Cell OFF', 14),
  ('blade', 'andro', 'Treiber FO OFF/S', 15),
  ('blade', 'andro', 'Ligna CO OFF', 16),
  ('blade', 'andro', 'Gauzy BL5 ALL', 17),
  ('blade', 'andro', 'Timber 5 ALL/S', 18),
  ('blade', 'andro', 'Timber 5 DEF', 19),
  ('blade', 'andro', 'Timber 7 ALL/S', 20),
  ('blade', 'andro', 'Treiber CO OFF/S', 21),
  ('blade', 'andro', 'Treiber K OFF', 22),
  ('blade', 'andro', 'Treiber H OFF', 23),
  ('blade', 'andro', 'Treiber FI OFF', 24),
  ('blade', 'andro', 'Synteliac ZCI OFF', 25),
  ('blade', 'andro', 'Synteliac VCI OFF', 26),
  ('blade', 'andro', 'Ligna ALL+', 27),
  ('blade', 'andro', 'Ligna OFF/S', 28),
  ('blade', 'andro', 'Novacell OFF/S', 29),
  ('blade', 'andro', 'Kanter FO ALL/S', 30),
  ('blade', 'andro', 'Kanter CO ALL/S', 31),
  ('blade', 'andro', 'Temper Tech All+', 32),
  ('blade', 'andro', 'Temper Tech Off', 33),
  ('blade', 'andro', 'Super Core Cell All+', 34),
  ('blade', 'andro', 'Super Core Carbon Light OFF+', 35),
  ('blade', 'andro', 'Wanokiwami Midori', 36),
  ('blade', 'tibhar', 'Stratus Power Wood', 0),
  ('blade', 'tibhar', 'Samsonov Force Pro', 1),
  ('blade', 'tibhar', 'Samsonov Force Pro Black Edition', 2),
  ('blade', 'tibhar', 'Samsonov Alpha', 3),
  ('blade', 'tibhar', 'Samsonov Premium Contact', 4),
  ('blade', 'tibhar', 'Felix Lebrun Hyper Carbon', 5),
  ('blade', 'tibhar', 'Alexis Lebrun OFF', 6),
  ('blade', 'tibhar', 'IV-S', 7),
  ('blade', 'tibhar', 'Defense Plus', 8),
  ('blade', 'tibhar', 'Samsonov Force Pro Blue', 9),
  ('blade', 'tibhar', 'Samsonov Carbon', 10),
  ('blade', 'tibhar', 'Stratus Samsonov Carbon', 11),
  ('blade', 'tibhar', 'IV-L', 12),
  ('blade', 'tibhar', 'IV-S SGS', 13),
  ('blade', 'tibhar', 'Defense Plus S', 14),
  ('blade', 'tibhar', 'Samsonov Stratus Carbon', 15),
  ('blade', 'tibhar', 'Stratus Power Carbon', 16),
  ('blade', 'tibhar', 'Stratus Power Defence', 17),
  ('blade', 'tibhar', 'Dynamic J7', 18),
  ('blade', 'tibhar', 'Dynamic JC', 19),
  ('blade', 'tibhar', 'Dynamic AC', 20),
  ('blade', 'tibhar', 'Fortino Pro DC Inside', 21),
  ('blade', 'tibhar', 'Fortino Pro DC Outside', 22),
  ('blade', 'tibhar', 'Fortino Force', 23),
  ('blade', 'tibhar', 'Fortino Performance', 24),
  ('blade', 'tibhar', 'Nicoleta Struse Master', 25),
  ('blade', 'tibhar', 'Felix Lebrun OFF-', 26),
  ('blade', 'tibhar', 'Felix Lebrun ALL', 27),
  ('blade', 'tibhar', 'Alexis Lebrun Krypto Carbon', 28),
  ('blade', 'tibhar', 'Samsonov Pure Wood', 29),
  ('blade', 'tibhar', 'Powerwood', 30),
  ('blade', 'tibhar', 'Status Power Wood', 31),
  ('blade', 'tibhar', 'Status Carbon', 32),
  ('blade', 'tibhar', 'Black Gold', 33),
  ('blade', 'tibhar', 'Balsa Fibretec 75', 34),
  ('blade', 'tibhar', 'Balsa Fibretec 50', 35),
  ('blade', 'tibhar', 'Defence Pro', 36),
  ('blade', 'xiom', 'HAL Hugo Calderano', 0),
  ('blade', 'xiom', 'Ice Cream AZX', 1),
  ('blade', 'xiom', 'Ice Cream AZXi', 2),
  ('blade', 'xiom', 'Hayabusa ZLX', 3),
  ('blade', 'xiom', 'Hayabusa ZXI', 4),
  ('blade', 'xiom', '36.5 ALX', 5),
  ('blade', 'xiom', '36.5 ALXi', 6),
  ('blade', 'xiom', 'Allround S', 7),
  ('blade', 'xiom', 'Offensive S', 8),
  ('blade', 'xiom', 'Custom Inner Carbon', 9),
  ('blade', 'xiom', 'Stradivarius', 10),
  ('blade', 'xiom', 'Ignito', 11),
  ('blade', 'xiom', 'Vega Pro Blade', 12),
  ('blade', 'xiom', 'Vega Tour', 13),
  ('blade', 'xiom', 'Hayabusa OFF Pro', 14),
  ('blade', 'xiom', 'Feel ZX3', 15),
  ('blade', 'xiom', 'Feel ZX2', 16),
  ('blade', 'xiom', 'Feel SX', 17),
  ('blade', 'xiom', 'Feel HX', 18),
  ('blade', 'xiom', 'Feel AX', 19),
  ('blade', 'xiom', 'Solo', 20),
  ('blade', 'xiom', 'Diva', 21),
  ('blade', 'xiom', 'Jazz', 22),
  ('blade', 'xiom', 'Control 3', 23),
  ('blade', 'xiom', 'Control 5', 24),
  ('blade', 'xiom', 'Novus Extreme S', 25),
  ('blade', 'xiom', 'Hayabusa ZL Pro', 26),
  ('blade', 'xiom', 'Hayabusa Arylate', 27),
  ('blade', 'xiom', 'Ice Cream AX', 28),
  ('blade', 'xiom', 'Ice Cream AZ', 29),
  ('blade', 'xiom', '36.5 FX', 30),
  ('blade', 'xiom', '36.5 SX', 31),
  ('blade', 'xiom', 'TMXi', 32),
  ('blade', 'xiom', 'TMX Pro', 33),
  ('blade', 'xiom', 'Cho Daeseong TMXi', 34),
  ('blade', 'xiom', 'Fuga', 35),
  ('blade', 'yasaka', 'Ma Lin Extra Offensive', 0),
  ('blade', 'yasaka', 'Sweden Extra', 1),
  ('blade', 'yasaka', 'Sweden Classic', 2),
  ('blade', 'yasaka', 'Falck Carbon', 3),
  ('blade', 'yasaka', 'Alnade', 4),
  ('blade', 'yasaka', 'Goiabao 5', 5),
  ('blade', 'yasaka', 'Atletico Power', 6),
  ('blade', 'yasaka', 'Atletico Speed', 7),
  ('blade', 'yasaka', 'Ma Lin Carbon', 8),
  ('blade', 'yasaka', 'Extra Offensive 7 Power', 9),
  ('blade', 'yasaka', 'Sweden Defensive', 10),
  ('blade', 'yasaka', 'Silver Line All Wood', 11),
  ('blade', 'yasaka', 'Silver Carbon', 12),
  ('blade', 'yasaka', 'Dynamix 17', 13),
  ('blade', 'yasaka', 'Ma Lin Soft Carbon', 14),
  ('blade', 'yasaka', 'Ma Lin Extra Special', 15),
  ('blade', 'yasaka', 'Ma Lin Carbon 3D', 16),
  ('blade', 'yasaka', 'Galaxya', 17),
  ('blade', 'yasaka', 'Galaxya Carbon', 18),
  ('blade', 'yasaka', 'Silver 9 Wood', 19),
  ('blade', 'yasaka', 'Silver 9 Carbon', 20),
  ('blade', 'yasaka', 'Alnade Inner', 21),
  ('blade', 'yasaka', 'Extra 3D', 22),
  ('blade', 'yasaka', 'Max Wood', 23),
  ('blade', 'yasaka', 'Falck W7', 24),
  ('blade', 'yasaka', 'Falck Carbon Special', 25),
  ('blade', 'yasaka', 'Battle Balsa', 26),
  ('blade', 'yasaka', 'Synergy', 27),
  ('blade', 'yasaka', 'Jet Impact', 28),
  ('blade', 'yasaka', 'Hovering Dragon', 29),
  ('blade', 'nittaku', 'Acoustic', 0),
  ('blade', 'nittaku', 'Violin', 1),
  ('blade', 'nittaku', 'Septear', 2),
  ('blade', 'nittaku', 'Septear Lead', 3),
  ('blade', 'nittaku', 'Latika', 4),
  ('blade', 'nittaku', 'Barwell', 5),
  ('blade', 'nittaku', 'Ludeack', 6),
  ('blade', 'nittaku', 'Ludeack Power', 7),
  ('blade', 'nittaku', 'Hina Hayata H2', 8),
  ('blade', 'nittaku', 'Rutis', 9),
  ('blade', 'nittaku', 'Rutis Revo', 10),
  ('blade', 'nittaku', 'Acoustic Carbon', 11),
  ('blade', 'nittaku', 'Violin Carbon', 12),
  ('blade', 'nittaku', 'Septear Feel', 13),
  ('blade', 'nittaku', 'Ludeack Fleet', 14),
  ('blade', 'nittaku', 'Flyatt Carbon', 15),
  ('blade', 'nittaku', 'Adelie', 16),
  ('blade', 'nittaku', 'Tornado King', 17),
  ('blade', 'nittaku', 'Acoustic G-Revision', 18),
  ('blade', 'nittaku', 'Violin G-Revision', 19),
  ('blade', 'nittaku', 'Rutis Power', 20),
  ('blade', 'nittaku', 'Rutis Carbon', 21),
  ('blade', 'nittaku', 'So-Ten', 22),
  ('blade', 'nittaku', 'Mima Ito Carbon', 23),
  ('blade', 'nittaku', 'Mima Ito ZLF', 24),
  ('blade', 'nittaku', 'Latika 7', 25),
  ('blade', 'nittaku', 'Tornado King Speed', 26),
  ('blade', 'nittaku', 'Tornado King Power', 27),
  ('blade', 'nittaku', 'Resoud', 28),
  ('blade', 'nittaku', 'Ma Long 5', 29),
  ('blade', 'nittaku', 'Ma Long 7', 30),
  ('blade', 'nittaku', 'Walnut Carbon', 31),
  ('blade', 'nittaku', 'Musko', 32),
  ('blade', 'nittaku', 'S-CZ', 33),
  ('blade', 'nittaku', 'S-5', 34),
  ('blade', 'nittaku', 'S-3', 35),
  ('blade', 'victas', 'Koji Matsushita', 0),
  ('blade', 'victas', 'Koji Matsushita Offensive', 1),
  ('blade', 'victas', 'SWAT', 2),
  ('blade', 'victas', 'Fire Fall FC', 3),
  ('blade', 'victas', 'ZX-Gear In', 4),
  ('blade', 'victas', 'ZX-Gear Out', 5),
  ('blade', 'victas', 'Dyna Seven', 6),
  ('blade', 'victas', 'ZX-Gear Fiber', 7),
  ('blade', 'victas', 'ZX-Gear Fiber OFF-', 8),
  ('blade', 'victas', 'Fire Fall AC', 9),
  ('blade', 'victas', 'Fire Fall VC', 10),
  ('blade', 'victas', 'SWAT Power', 11),
  ('blade', 'victas', 'Liam Pitchford', 12),
  ('blade', 'victas', 'Liam Pitchford Power', 13),
  ('blade', 'victas', 'Euro Feeling Offensive', 14),
  ('blade', 'victas', 'Euro Classic ALL+', 15),
  ('blade', 'victas', 'Koki Niwa', 16),
  ('blade', 'victas', 'Koki Niwa Wood', 17),
  ('blade', 'victas', 'Koki Niwa ZC', 18),
  ('blade', 'victas', 'Koki Niwa SZC', 19),
  ('blade', 'victas', 'Matsushita Special', 20),
  ('blade', 'victas', 'Black Balsa 3.0', 21),
  ('blade', 'victas', 'Black Balsa 5.0', 22),
  ('blade', 'victas', 'Black Balsa 7.0', 23),
  ('blade', 'victas', 'Double Extra', 24),
  ('blade', 'victas', 'Dyna Five Soft', 25),
  ('blade', 'victas', 'Spectrol Wood', 26),
  ('blade', 'victas', 'Balsa 4.5', 27),
  ('blade', 'victas', 'Balsa 6.5', 28),
  ('blade', 'victas', 'Balsa 8.5', 29),
  ('blade', 'joola', 'Rosskopf Classic', 0),
  ('blade', 'joola', 'Fever', 1),
  ('blade', 'joola', 'Hugo Calderano KLC', 2),
  ('blade', 'joola', 'Hugo Calderano KLC Inner', 3),
  ('blade', 'joola', 'Vyzaryz Trinity', 4),
  ('blade', 'joola', 'Nobilis PBO-c', 5),
  ('blade', 'joola', 'Tezzo Warrior', 6),
  ('blade', 'joola', 'Baseline ALL', 7),
  ('blade', 'joola', 'Baseline OFF', 8),
  ('blade', 'joola', 'Vyzaryz Freeze', 9),
  ('blade', 'joola', 'Rossi Emotion', 10),
  ('blade', 'joola', 'Rossi Force', 11),
  ('blade', 'joola', 'Aruna OFF', 12),
  ('blade', 'joola', 'Aruna Hinoki', 13),
  ('blade', 'joola', 'Tezzo Guardian', 14),
  ('blade', 'joola', 'Vyzaryz Hybrid', 15),
  ('blade', 'joola', 'Vyzaryz Inferno', 16),
  ('blade', 'joola', 'Vyzaryz CMD', 17),
  ('blade', 'joola', 'Nobilis ZLC', 18),
  ('blade', 'joola', 'Chen Weixing', 19),
  ('blade', 'joola', 'Rosskopf Emotion', 20),
  ('blade', 'joola', 'Rosskopf Fire', 21),
  ('blade', 'joola', 'Rosskopf Smash', 22),
  ('blade', 'joola', 'Guo 3C', 23),
  ('blade', 'joola', 'Santoru KL-c Inner', 24),
  ('blade', 'joola', 'Santoru KL-c', 25),
  ('blade', 'joola', 'Scorpius', 26),
  ('blade', 'joola', 'Toni Hold White Spot', 27),
  ('blade', 'joola', 'Allround', 28),
  ('blade', 'gewo', 'Aruna Hinoki Carbon', 0),
  ('blade', 'gewo', 'Aruna Hinoki X Carbon', 1),
  ('blade', 'gewo', 'Balsa Carbon 375', 2),
  ('blade', 'gewo', 'Balsa Carbon 575', 3),
  ('blade', 'gewo', 'Zoom Pro OFF-', 4),
  ('blade', 'gewo', 'Power Allround', 5),
  ('blade', 'gewo', 'Aruna Carbon OFF', 6),
  ('blade', 'gewo', 'Balsa Carbon 775', 7),
  ('blade', 'gewo', 'Zoom Balance OFF', 8),
  ('blade', 'gewo', 'Zoom Pro OFF', 9),
  ('blade', 'gewo', 'Power Control', 10),
  ('blade', 'gewo', 'Exclusiv Carbon', 11),
  ('blade', 'gewo', 'Aurum Carbon', 12),
  ('blade', 'gewo', 'Hybrid Carbon M/2', 13),
  ('blade', 'gewo', 'Balsa Carbon 375 XL', 14),
  ('blade', 'gewo', 'Balsa Carbon 575 XL', 15),
  ('blade', 'cornilleau', 'Aero All', 0),
  ('blade', 'cornilleau', 'Aero Off', 1),
  ('blade', 'cornilleau', 'Hinotec All+', 2),
  ('blade', 'cornilleau', 'Hinotec Off', 3),
  ('blade', 'cornilleau', 'Hinotec Off+', 4),
  ('blade', 'cornilleau', 'Aero Carbon', 5),
  ('blade', 'cornilleau', 'Hinotec Off-', 6),
  ('blade', 'cornilleau', 'Perform 500', 7),
  ('blade', 'cornilleau', 'Perform 800', 8),
  ('blade', 'cornilleau', 'Perform 900', 9),
  ('blade', 'friendship-729', 'Battle 2 Arylate Carbon', 0),
  ('blade', 'friendship-729', 'Blue Arylate Carbon', 1),
  ('blade', 'friendship-729', 'Yellow Arylate Carbon', 2),
  ('blade', 'friendship-729', 'V-6', 3),
  ('blade', 'friendship-729', 'L-5', 4),
  ('blade', 'friendship-729', 'V-5', 5),
  ('blade', 'friendship-729', 'V-7', 6),
  ('blade', 'friendship-729', 'Z-1', 7),
  ('blade', 'friendship-729', 'Z-2', 8),
  ('blade', 'friendship-729', 'Bomb', 9),
  ('blade', 'friendship-729', 'Bomb Carbon', 10),
  ('blade', 'friendship-729', 'Dynasty Hinoki', 11),
  ('blade', 'friendship-729', 'Black ALC', 12),
  ('blade', 'friendship-729', 'Yellow ZLC', 13),
  ('blade', 'friendship-729', 'Blue ZLC', 14),
  ('blade', 'double-fish', 'Carbon 8', 0),
  ('blade', 'double-fish', 'Carbon 9', 1),
  ('blade', 'double-fish', 'Volant King 2', 2),
  ('blade', 'double-fish', 'SW-1', 3),
  ('blade', 'double-fish', 'SW-2', 4),
  ('blade', 'double-fish', 'DF 7A', 5),
  ('blade', 'double-fish', 'DF 8A', 6),
  ('blade', 'double-fish', 'Carbon King', 7),
  ('blade', 'double-fish', 'Volant Phoenix', 8),
  ('blade', 'double-fish', 'Volant Ace', 9),
  ('blade', 'double-fish', 'Volant King 1', 10),
  ('blade', 'double-fish', 'Double 9 Star', 11),
  ('blade', 'double-fish', 'Carbon 7', 12),
  ('blade', 'dr-neubauer', 'Matador', 0),
  ('blade', 'dr-neubauer', 'Matador Texa', 1),
  ('blade', 'dr-neubauer', 'Titan', 2),
  ('blade', 'dr-neubauer', 'Grand Master', 3),
  ('blade', 'dr-neubauer', 'Barricade DEF', 4),
  ('blade', 'dr-neubauer', 'Bulldog', 5),
  ('blade', 'dr-neubauer', 'High Technology Plus', 6),
  ('blade', 'dr-neubauer', 'Kung Fu', 7),
  ('blade', 'dr-neubauer', 'World Champion', 8),
  ('blade', 'dr-neubauer', 'Special', 9),
  ('blade', 'dr-neubauer', 'Combination Effect', 10),
  ('blade', 'dr-neubauer', 'Firewall Plus', 11),
  ('blade', 'der-materialspezialist', 'Wizard', 0),
  ('blade', 'der-materialspezialist', 'Terminator', 1),
  ('blade', 'der-materialspezialist', 'Diabolic', 2),
  ('blade', 'der-materialspezialist', 'Phoenix', 3),
  ('blade', 'der-materialspezialist', 'Predator', 4),
  ('blade', 'der-materialspezialist', 'Firewall Plus', 5),
  ('blade', 'der-materialspezialist', 'Excalibur', 6),
  ('blade', 'der-materialspezialist', 'Broadsword', 7),
  ('blade', 'der-materialspezialist', 'Shock', 8),
  ('blade', 'der-materialspezialist', 'Destroyer', 9),
  ('blade', 'spinlord', 'Ultra Balsa', 0),
  ('blade', 'spinlord', 'Ultra Carbon', 1),
  ('blade', 'spinlord', 'Ultra Offensive', 2),
  ('blade', 'spinlord', 'Ultra Allround', 3),
  ('blade', 'spinlord', 'Defender', 4),
  ('blade', 'spinlord', 'Carbon Classic', 5),
  ('blade', 'spinlord', 'Ultra Hinoki', 6),
  ('blade', 'spinlord', 'Ultra Hinoki Carbon', 7),
  ('blade', 'spinlord', 'Marder Blade', 8),
  ('blade', 'spinlord', 'Keiler Blade', 9),
  ('blade', 'sauer-troeger', 'Black & White', 0),
  ('blade', 'sauer-troeger', 'Noir', 1),
  ('blade', 'sauer-troeger', 'Zeus', 2),
  ('blade', 'sauer-troeger', 'Unicorn', 3),
  ('blade', 'sauer-troeger', 'Hipster', 4),
  ('blade', 'sauer-troeger', 'Kaspar', 5),
  ('blade', 'sauer-troeger', 'Piet', 6),
  ('blade', 'sauer-troeger', 'Durian', 7),
  ('blade', 'sauer-troeger', 'Makai', 8),
  ('blade', 'hallmark', 'Aurora', 0),
  ('blade', 'hallmark', 'Combination', 1),
  ('blade', 'hallmark', 'Carbon Precision', 2),
  ('blade', 'hallmark', 'Strategy', 3),
  ('blade', 'hallmark', 'Enigma', 4),
  ('blade', 'hallmark', 'Mirage', 5),
  ('blade', 'hallmark', 'Instinct', 6),
  ('blade', 'hallmark', 'Precision', 7),
  ('blade', 'palio', 'Master 2', 0),
  ('blade', 'palio', 'Energy 03', 1),
  ('blade', 'palio', 'Legend', 2),
  ('blade', 'palio', 'Allround Classic', 3),
  ('blade', 'palio', 'Offensive 5 Wood', 4),
  ('blade', 'palio', 'Expert 2', 5),
  ('blade', 'palio', 'Way 001', 6),
  ('blade', 'palio', 'Way 002', 7),
  ('blade', 'palio', 'Way 003', 8),
  ('blade', 'palio', 'Cat', 9),
  ('blade', 'palio', 'Cat Carbon', 10),
  ('blade', 'palio', 'TNT-1', 11),
  ('blade', 'palio', 'Hadou', 12),
  ('blade', 'palio', 'B52', 13),
  ('rubber', 'butterfly', 'Dignics 09C', 0),
  ('rubber', 'butterfly', 'Dignics 05', 1),
  ('rubber', 'butterfly', 'Dignics 64', 2),
  ('rubber', 'butterfly', 'Dignics 80', 3),
  ('rubber', 'butterfly', 'Tenergy 05', 4),
  ('rubber', 'butterfly', 'Tenergy 05 FX', 5),
  ('rubber', 'butterfly', 'Tenergy 19', 6),
  ('rubber', 'butterfly', 'Tenergy 64', 7),
  ('rubber', 'butterfly', 'Tenergy 80', 8),
  ('rubber', 'butterfly', 'Rozena', 9),
  ('rubber', 'butterfly', 'Sriver', 10),
  ('rubber', 'butterfly', 'Glayzer 09C', 11),
  ('rubber', 'butterfly', 'Glayzer', 12),
  ('rubber', 'butterfly', 'Bryce Highspeed', 13),
  ('rubber', 'butterfly', 'Feint Long III', 14),
  ('rubber', 'butterfly', 'Ilius B', 15),
  ('rubber', 'butterfly', 'Dignics 64 FX', 16),
  ('rubber', 'butterfly', 'Dignics 80 FX', 17),
  ('rubber', 'butterfly', 'Tenergy 05 Hard', 18),
  ('rubber', 'butterfly', 'Aibiss', 19),
  ('rubber', 'butterfly', 'Bryce', 20),
  ('rubber', 'butterfly', 'Bryce FX', 21),
  ('rubber', 'butterfly', 'Bryce Speed', 22),
  ('rubber', 'butterfly', 'Roundell', 23),
  ('rubber', 'butterfly', 'Roundell Hard', 24),
  ('rubber', 'butterfly', 'Roundell Soft', 25),
  ('rubber', 'butterfly', 'Sriver EL', 26),
  ('rubber', 'butterfly', 'Sriver FX', 27),
  ('rubber', 'butterfly', 'Sriver G3', 28),
  ('rubber', 'butterfly', 'Sriver G3 FX', 29),
  ('rubber', 'butterfly', 'Sriver G3 Hard', 30),
  ('rubber', 'butterfly', 'Tackifire Drive', 31),
  ('rubber', 'butterfly', 'Tackifire Special', 32),
  ('rubber', 'butterfly', 'SpinArt', 33),
  ('rubber', 'butterfly', 'Feint AG', 34),
  ('rubber', 'butterfly', 'Feint Long II', 35),
  ('rubber', 'butterfly', 'Ilius S', 36),
  ('rubber', 'butterfly', 'Orthodox', 37),
  ('rubber', 'butterfly', 'Challenger Attack', 38),
  ('rubber', 'butterfly', 'Tenergy 25', 39),
  ('rubber', 'butterfly', 'Tenergy 25 FX', 40),
  ('rubber', 'butterfly', 'Tenergy 80 FX', 41),
  ('rubber', 'butterfly', 'Tenergy 64 FX', 42),
  ('rubber', 'butterfly', 'Tenergy 19 FX', 43),
  ('rubber', 'butterfly', 'Dignics 05 FX', 44),
  ('rubber', 'butterfly', 'Flextra', 45),
  ('rubber', 'butterfly', 'Impartial XS', 46),
  ('rubber', 'butterfly', 'Impartial XB', 47),
  ('rubber', 'stiga', 'DNA Platinum XH', 0),
  ('rubber', 'stiga', 'DNA Platinum H', 1),
  ('rubber', 'stiga', 'DNA Platinum M', 2),
  ('rubber', 'stiga', 'DNA Pro H', 3),
  ('rubber', 'stiga', 'DNA Pro M', 4),
  ('rubber', 'stiga', 'DNA Pro S', 5),
  ('rubber', 'stiga', 'DNA Hybrid H', 6),
  ('rubber', 'stiga', 'DNA Hybrid M', 7),
  ('rubber', 'stiga', 'DNA Hybrid XH', 8),
  ('rubber', 'stiga', 'DNA Hybrid 55', 9),
  ('rubber', 'stiga', 'Mantra Pro H', 10),
  ('rubber', 'stiga', 'Mantra Pro M', 11),
  ('rubber', 'stiga', 'Mantra Pro XH', 12),
  ('rubber', 'stiga', 'Mantra Sound', 13),
  ('rubber', 'stiga', 'Mantra Control', 14),
  ('rubber', 'stiga', 'Star Future S', 15),
  ('rubber', 'stiga', 'DNA Dragon Grip', 16),
  ('rubber', 'stiga', 'DNA Dragon Power 57.5', 17),
  ('rubber', 'stiga', 'DNA Platinum S', 18),
  ('rubber', 'stiga', 'DNA Platinum XS', 19),
  ('rubber', 'stiga', 'DNA Pro XH', 20),
  ('rubber', 'stiga', 'DNA Hybrid S', 21),
  ('rubber', 'stiga', 'DNA Hybrid MH', 22),
  ('rubber', 'stiga', 'DNA Dragon Power 52.5', 23),
  ('rubber', 'stiga', 'Mantra H', 24),
  ('rubber', 'stiga', 'Mantra M', 25),
  ('rubber', 'stiga', 'Mantra S', 26),
  ('rubber', 'stiga', 'Calibra LT', 27),
  ('rubber', 'stiga', 'Calibra LT Spin', 28),
  ('rubber', 'stiga', 'Calibra LT Sound', 29),
  ('rubber', 'stiga', 'Calibra Tour H', 30),
  ('rubber', 'stiga', 'Calibra Tour M', 31),
  ('rubber', 'stiga', 'Calibra Tour S', 32),
  ('rubber', 'stiga', 'Airoc M', 33),
  ('rubber', 'stiga', 'Airoc S', 34),
  ('rubber', 'stiga', 'Genesis M', 35),
  ('rubber', 'stiga', 'Genesis S', 36),
  ('rubber', 'stiga', 'Boost TC', 37),
  ('rubber', 'stiga', 'Boost TS', 38),
  ('rubber', 'stiga', 'Boost TX', 39),
  ('rubber', 'stiga', 'Magna TC II', 40),
  ('rubber', 'stiga', 'Neos Tacky', 41),
  ('rubber', 'stiga', 'Neos Sound', 42),
  ('rubber', 'stiga', 'Vertical 20', 43),
  ('rubber', 'stiga', 'Clippa', 44),
  ('rubber', 'stiga', 'Chop & Drive', 45),
  ('rubber', 'stiga', 'Innova Ultra Light', 46),
  ('rubber', 'stiga', 'Symmetry', 47),
  ('rubber', 'stiga', 'Star Grip', 48),
  ('rubber', 'stiga', 'Royal Five', 49),
  ('rubber', 'dhs', 'Hurricane 3 Neo', 0),
  ('rubber', 'dhs', 'Hurricane 3', 1),
  ('rubber', 'dhs', 'Hurricane 3-50', 2),
  ('rubber', 'dhs', 'Hurricane 8', 3),
  ('rubber', 'dhs', 'Hurricane 8-80', 4),
  ('rubber', 'dhs', 'Skyline 2 Neo', 5),
  ('rubber', 'dhs', 'Skyline 3 Neo', 6),
  ('rubber', 'dhs', 'TinArc 3', 7),
  ('rubber', 'dhs', 'TinArc 5', 8),
  ('rubber', 'dhs', 'Goldarc 5', 9),
  ('rubber', 'dhs', 'Goldarc 8', 10),
  ('rubber', 'dhs', 'PF4', 11),
  ('rubber', 'dhs', 'G888', 12),
  ('rubber', 'dhs', 'C8', 13),
  ('rubber', 'dhs', 'Hurricane 9', 14),
  ('rubber', 'dhs', 'Hurricane 3 National', 15),
  ('rubber', 'dhs', 'Hurricane 2', 16),
  ('rubber', 'dhs', 'Hurricane 2 Neo', 17),
  ('rubber', 'dhs', 'Hurricane 2 National', 18),
  ('rubber', 'dhs', 'Hurricane 3 Neo Provincial', 19),
  ('rubber', 'dhs', 'Hurricane 3 Neo Blue Sponge', 20),
  ('rubber', 'dhs', 'Hurricane 3 Provincial', 21),
  ('rubber', 'dhs', 'Hurricane 3 National Blue Sponge', 22),
  ('rubber', 'dhs', 'Hurricane 8 Mid Hard', 23),
  ('rubber', 'dhs', 'Skyline 2', 24),
  ('rubber', 'dhs', 'Skyline 3', 25),
  ('rubber', 'dhs', 'Skyline 2 Provincial', 26),
  ('rubber', 'dhs', 'Skyline 3 Provincial', 27),
  ('rubber', 'dhs', 'Skyline 2 National', 28),
  ('rubber', 'dhs', 'Skyline 3 National', 29),
  ('rubber', 'dhs', 'Skyline 2 Blue Sponge', 30),
  ('rubber', 'dhs', 'Skyline 3 Blue Sponge', 31),
  ('rubber', 'dhs', 'TinArc', 32),
  ('rubber', 'dhs', 'TinArc 2', 33),
  ('rubber', 'dhs', 'Goldarc 8 50', 34),
  ('rubber', 'dhs', 'PF4-50', 35),
  ('rubber', 'dhs', 'PF4 Soft', 36),
  ('rubber', 'dhs', 'G555', 37),
  ('rubber', 'dhs', 'G666', 38),
  ('rubber', 'dhs', 'G777', 39),
  ('rubber', 'dhs', 'Cloud & Fog 3', 40),
  ('rubber', 'dhs', 'Cloud & Fog 3 National', 41),
  ('rubber', 'dhs', 'Dipper', 42),
  ('rubber', 'dhs', 'Hurricane 5', 43),
  ('rubber', 'dhs', 'NEO Skyline 2', 44),
  ('rubber', 'dhs', 'NEO Skyline 3', 45),
  ('rubber', 'dhs', 'C7', 46),
  ('rubber', 'dhs', '651', 47),
  ('rubber', 'dhs', '652', 48),
  ('rubber', 'dhs', '6522', 49),
  ('rubber', 'donic', 'Bluestar A1', 0),
  ('rubber', 'donic', 'Bluestar A2', 1),
  ('rubber', 'donic', 'Bluestar A3', 2),
  ('rubber', 'donic', 'Bluegrip C1', 3),
  ('rubber', 'donic', 'Bluegrip C2', 4),
  ('rubber', 'donic', 'Bluegrip J1', 5),
  ('rubber', 'donic', 'Bluegrip J2', 6),
  ('rubber', 'donic', 'Bluestorm Z1', 7),
  ('rubber', 'donic', 'Bluestorm Z2', 8),
  ('rubber', 'donic', 'Bluestorm Z3', 9),
  ('rubber', 'donic', 'Bluefire M1', 10),
  ('rubber', 'donic', 'Bluefire M2', 11),
  ('rubber', 'donic', 'Bluefire JP 01', 12),
  ('rubber', 'donic', 'Acuda S1', 13),
  ('rubber', 'donic', 'Baracuda', 14),
  ('rubber', 'donic', 'Vario', 15),
  ('rubber', 'donic', 'Desto F3', 16),
  ('rubber', 'donic', 'Spike P1', 17),
  ('rubber', 'donic', 'Bluestar A1 Turbo', 18),
  ('rubber', 'donic', 'Bluegrip C3', 19),
  ('rubber', 'donic', 'Bluegrip J3', 20),
  ('rubber', 'donic', 'Bluegrip S1', 21),
  ('rubber', 'donic', 'Bluegrip S2', 22),
  ('rubber', 'donic', 'Bluestorm Z1 Turbo', 23),
  ('rubber', 'donic', 'Bluestorm Z2 Turbo', 24),
  ('rubber', 'donic', 'Bluefire M3', 25),
  ('rubber', 'donic', 'Bluefire JP 02', 26),
  ('rubber', 'donic', 'Bluefire JP 03', 27),
  ('rubber', 'donic', 'Bluefire Big Slam', 28),
  ('rubber', 'donic', 'Acuda S2', 29),
  ('rubber', 'donic', 'Acuda S3', 30),
  ('rubber', 'donic', 'Acuda Blue P1', 31),
  ('rubber', 'donic', 'Acuda Blue P2', 32),
  ('rubber', 'donic', 'Acuda Blue P3', 33),
  ('rubber', 'donic', 'Baracuda Big Slam', 34),
  ('rubber', 'donic', 'Coppa X1', 35),
  ('rubber', 'donic', 'Coppa X2', 36),
  ('rubber', 'donic', 'Coppa X3', 37),
  ('rubber', 'donic', 'Coppa Jo Gold', 38),
  ('rubber', 'donic', 'Vario Soft', 39),
  ('rubber', 'donic', 'Slice 40 CD', 40),
  ('rubber', 'donic', 'Desto F1', 41),
  ('rubber', 'donic', 'Desto F2', 42),
  ('rubber', 'donic', 'Quattro', 43),
  ('rubber', 'donic', 'Liga', 44),
  ('rubber', 'donic', 'Baxster F1-A', 45),
  ('rubber', 'donic', 'Baxster P7', 46),
  ('rubber', 'donic', 'Piranja CD', 47),
  ('rubber', 'donic', 'Alligator Def', 48),
  ('rubber', 'donic', 'Alligator Combi', 49),
  ('rubber', 'donic', 'Sonex JP Gold', 50),
  ('rubber', 'andro', 'NUZN 55', 0),
  ('rubber', 'andro', 'NUZN 50', 1),
  ('rubber', 'andro', 'NUZN 48', 2),
  ('rubber', 'andro', 'NUZN 45', 3),
  ('rubber', 'andro', 'Rasanter C53', 4),
  ('rubber', 'andro', 'Rasanter C48', 5),
  ('rubber', 'andro', 'Rasanter C45', 6),
  ('rubber', 'andro', 'Rasanter R53', 7),
  ('rubber', 'andro', 'Rasanter R48', 8),
  ('rubber', 'andro', 'Rasanter V47', 9),
  ('rubber', 'andro', 'Rasanter V42', 10),
  ('rubber', 'andro', 'Hexer Powergrip', 11),
  ('rubber', 'andro', 'Hexer Grip', 12),
  ('rubber', 'andro', 'Hexer Duro', 13),
  ('rubber', 'andro', 'HY-Q 48', 14),
  ('rubber', 'andro', 'HY-Q 42', 15),
  ('rubber', 'andro', 'Good!', 16),
  ('rubber', 'andro', 'Rasanter C50', 17),
  ('rubber', 'andro', 'Rasanter C37', 18),
  ('rubber', 'andro', 'Rasanter R37', 19),
  ('rubber', 'andro', 'Rasanter R42', 20),
  ('rubber', 'andro', 'Rasanter R45', 21),
  ('rubber', 'andro', 'Rasanter R50', 22),
  ('rubber', 'andro', 'Rasanter V37', 23),
  ('rubber', 'andro', 'Rasanter V52', 24),
  ('rubber', 'andro', 'Hexer', 25),
  ('rubber', 'andro', 'Hexer Plus', 26),
  ('rubber', 'andro', 'Hexer Powersponge', 27),
  ('rubber', 'andro', 'Hexer Pips+', 28),
  ('rubber', 'andro', 'Blowfish', 29),
  ('rubber', 'andro', 'Shifter', 30),
  ('rubber', 'andro', 'Shifter Powersponge', 31),
  ('rubber', 'andro', 'Good! Sound', 32),
  ('rubber', 'andro', 'Impuls Speed', 33),
  ('rubber', 'andro', 'Plaxon 400', 34),
  ('rubber', 'andro', 'Plaxon 450', 35),
  ('rubber', 'andro', 'Plaxon 525', 36),
  ('rubber', 'andro', 'Roxon 330', 37),
  ('rubber', 'andro', 'Roxon 450', 38),
  ('rubber', 'andro', 'Roxon 500 Pro', 39),
  ('rubber', 'andro', 'GTT 40', 40),
  ('rubber', 'andro', 'GTT 45', 41),
  ('rubber', 'andro', 'GTT 50', 42),
  ('rubber', 'tibhar', 'Hybrid K3', 0),
  ('rubber', 'tibhar', 'Hybrid K3 Pro', 1),
  ('rubber', 'tibhar', 'Hybrid K3 FX', 2),
  ('rubber', 'tibhar', 'Hybrid MK', 3),
  ('rubber', 'tibhar', 'Hybrid MK FX', 4),
  ('rubber', 'tibhar', 'Evolution MX-P', 5),
  ('rubber', 'tibhar', 'Evolution MX-P50', 6),
  ('rubber', 'tibhar', 'Evolution EL-P', 7),
  ('rubber', 'tibhar', 'Evolution FX-P', 8),
  ('rubber', 'tibhar', 'Evolution MX-D', 9),
  ('rubber', 'tibhar', 'Evolution EL-D', 10),
  ('rubber', 'tibhar', 'Evolution FX-D', 11),
  ('rubber', 'tibhar', 'Evolution MX-S', 12),
  ('rubber', 'tibhar', 'Aurus Prime', 13),
  ('rubber', 'tibhar', 'Genius', 14),
  ('rubber', 'tibhar', 'Grass D.TecS', 15),
  ('rubber', 'tibhar', 'Speedy Soft D.Tecs', 16),
  ('rubber', 'tibhar', 'Hybrid K1 Plus', 17),
  ('rubber', 'tibhar', 'Hybrid K1', 18),
  ('rubber', 'tibhar', 'Hybrid K1J', 19),
  ('rubber', 'tibhar', 'Hybrid K2', 20),
  ('rubber', 'tibhar', 'Aurus', 21),
  ('rubber', 'tibhar', 'Aurus Soft', 22),
  ('rubber', 'tibhar', 'Aurus Sound', 23),
  ('rubber', 'tibhar', 'Aurus Select', 24),
  ('rubber', 'tibhar', 'Nimbus', 25),
  ('rubber', 'tibhar', 'Nimbus Sound', 26),
  ('rubber', 'tibhar', 'Genius Sound', 27),
  ('rubber', 'tibhar', 'Genius Optimum', 28),
  ('rubber', 'tibhar', 'Genius Optimum Sound', 29),
  ('rubber', 'tibhar', 'Sinus', 30),
  ('rubber', 'tibhar', 'Sinus Alpha', 31),
  ('rubber', 'tibhar', 'Quantum X Pro', 32),
  ('rubber', 'tibhar', 'Quantum X Pro Soft', 33),
  ('rubber', 'tibhar', 'Quantum SFX', 34),
  ('rubber', 'tibhar', 'Quantum VP', 35),
  ('rubber', 'tibhar', '5Q VIP', 36),
  ('rubber', 'tibhar', '5Q Sound', 37),
  ('rubber', 'tibhar', 'Grip-S Europe', 38),
  ('rubber', 'tibhar', 'Grip-S', 39),
  ('rubber', 'tibhar', 'Rapid', 40),
  ('rubber', 'tibhar', 'Rapid Soft', 41),
  ('rubber', 'tibhar', 'Rapid Speed', 42),
  ('rubber', 'tibhar', 'Speedy Spin', 43),
  ('rubber', 'tibhar', 'Grass', 44),
  ('rubber', 'tibhar', 'Grass Ultra', 45),
  ('rubber', 'tibhar', 'Super Defense', 46),
  ('rubber', 'tibhar', 'Super Defense 40', 47),
  ('rubber', 'tibhar', 'Grass Ultra Pro', 48),
  ('rubber', 'tibhar', 'Speedy Soft', 49),
  ('rubber', 'tibhar', 'Speedy Soft XD', 50),
  ('rubber', 'xiom', 'Jekyll & Hyde C57.5', 0),
  ('rubber', 'xiom', 'Jekyll & Hyde C55.0', 1),
  ('rubber', 'xiom', 'Jekyll & Hyde C52.5', 2),
  ('rubber', 'xiom', 'Jekyll & Hyde V52.5', 3),
  ('rubber', 'xiom', 'Jekyll & Hyde V47.5', 4),
  ('rubber', 'xiom', 'Omega 8 Pro', 5),
  ('rubber', 'xiom', 'Omega 8 Hybrid', 6),
  ('rubber', 'xiom', 'Omega 8 Euro', 7),
  ('rubber', 'xiom', 'Omega 8 China', 8),
  ('rubber', 'xiom', 'Omega VII Tour i', 9),
  ('rubber', 'xiom', 'Omega VII Pro', 10),
  ('rubber', 'xiom', 'Omega VII Asia', 11),
  ('rubber', 'xiom', 'Vega Pro', 12),
  ('rubber', 'xiom', 'Vega Europe', 13),
  ('rubber', 'xiom', 'Vega Japan', 14),
  ('rubber', 'xiom', 'Vega Asia', 15),
  ('rubber', 'xiom', 'Vega Intro', 16),
  ('rubber', 'xiom', 'Tau 3', 17),
  ('rubber', 'xiom', 'Musa I', 18),
  ('rubber', 'xiom', 'Dragon Grip', 19),
  ('rubber', 'xiom', 'Omega 9 Pro', 20),
  ('rubber', 'xiom', 'Jekyll & Hyde Z52.5', 21),
  ('rubber', 'xiom', 'Jekyll & Hyde H52.5', 22),
  ('rubber', 'xiom', 'Omega VII Tour', 23),
  ('rubber', 'xiom', 'Omega VII Euro', 24),
  ('rubber', 'xiom', 'Omega V Tour', 25),
  ('rubber', 'xiom', 'Omega V Pro', 26),
  ('rubber', 'xiom', 'Omega V Asia', 27),
  ('rubber', 'xiom', 'Omega V Euro', 28),
  ('rubber', 'xiom', 'Omega IV Pro', 29),
  ('rubber', 'xiom', 'Omega IV Asia', 30),
  ('rubber', 'xiom', 'Omega IV Elite', 31),
  ('rubber', 'xiom', 'Vega X', 32),
  ('rubber', 'xiom', 'Vega X Europe', 33),
  ('rubber', 'xiom', 'Vega Asia DF', 34),
  ('rubber', 'xiom', 'Vega Elite', 35),
  ('rubber', 'xiom', 'Vega Def', 36),
  ('rubber', 'xiom', 'Tau', 37),
  ('rubber', 'xiom', 'Tau II', 38),
  ('rubber', 'xiom', 'Musa II', 39),
  ('rubber', 'xiom', 'Musa III', 40),
  ('rubber', 'xiom', 'Sigma II Pro', 41),
  ('rubber', 'xiom', 'Sigma II Europe', 42),
  ('rubber', 'xiom', 'Sigma II Asia', 43),
  ('rubber', 'xiom', 'Sigma III Pro', 44),
  ('rubber', 'xiom', 'Sigma III Europe', 45),
  ('rubber', 'xiom', 'Feel ZX', 46),
  ('rubber', 'xiom', 'Omega 9 Euro', 47),
  ('rubber', 'xiom', 'Omega 9 Asia', 48),
  ('rubber', 'yasaka', 'Mark V', 0),
  ('rubber', 'yasaka', 'Mark V GPS', 1),
  ('rubber', 'yasaka', 'Rakza 7', 2),
  ('rubber', 'yasaka', 'Rakza 7 Soft', 3),
  ('rubber', 'yasaka', 'Rakza 7 Hard', 4),
  ('rubber', 'yasaka', 'Rakza 9', 5),
  ('rubber', 'yasaka', 'Rakza X', 6),
  ('rubber', 'yasaka', 'Rakza XX', 7),
  ('rubber', 'yasaka', 'Rakza Z', 8),
  ('rubber', 'yasaka', 'Rakza Z Extra Hard', 9),
  ('rubber', 'yasaka', 'Anti Power', 10),
  ('rubber', 'yasaka', 'Original Extra HG', 11),
  ('rubber', 'yasaka', 'Original XHG', 12),
  ('rubber', 'yasaka', 'Phantom 0012', 13),
  ('rubber', 'yasaka', 'Rakza Z Soft', 14),
  ('rubber', 'yasaka', 'Mark V HPS', 15),
  ('rubber', 'yasaka', 'Mark V AD', 16),
  ('rubber', 'yasaka', 'Rakza 7 Hybrid', 17),
  ('rubber', 'yasaka', 'Rakza X Soft', 18),
  ('rubber', 'yasaka', 'Rakza XTR', 19),
  ('rubber', 'yasaka', 'Rakza PO', 20),
  ('rubber', 'yasaka', 'Rakza 9 Soft', 21),
  ('rubber', 'yasaka', 'Rakza XTR Soft', 22),
  ('rubber', 'yasaka', 'Rakza 10', 23),
  ('rubber', 'yasaka', 'Rigan', 24),
  ('rubber', 'yasaka', 'Rigan Spin', 25),
  ('rubber', 'yasaka', 'Xtend', 26),
  ('rubber', 'yasaka', 'Xtend HS', 27),
  ('rubber', 'yasaka', 'Pryde 30', 28),
  ('rubber', 'yasaka', 'Pryde 40', 29),
  ('rubber', 'yasaka', 'Shining Dragon', 30),
  ('rubber', 'yasaka', 'Original Extra', 31),
  ('rubber', 'yasaka', 'Phantom 0011', 32),
  ('rubber', 'yasaka', 'Phantom 0018', 33),
  ('rubber', 'yasaka', 'Anti Power Special', 34),
  ('rubber', 'yasaka', 'Extend HS', 35),
  ('rubber', 'yasaka', 'Rising Dragon', 36),
  ('rubber', 'yasaka', 'Mark V XS', 37),
  ('rubber', 'yasaka', 'Mark V M2', 38),
  ('rubber', 'nittaku', 'Fastarc G-1', 0),
  ('rubber', 'nittaku', 'Fastarc C-1', 1),
  ('rubber', 'nittaku', 'Fastarc S-1', 2),
  ('rubber', 'nittaku', 'Hammond Z2', 3),
  ('rubber', 'nittaku', 'Hammond', 4),
  ('rubber', 'nittaku', 'Factive', 5),
  ('rubber', 'nittaku', 'Hurricane Pro 3 Turbo Orange', 6),
  ('rubber', 'nittaku', 'Hurricane Pro 3 Turbo Blue', 7),
  ('rubber', 'nittaku', 'Moristo SP', 8),
  ('rubber', 'nittaku', 'Moristo SP AX', 9),
  ('rubber', 'nittaku', 'Do Knuckle', 10),
  ('rubber', 'nittaku', 'Wallest', 11),
  ('rubber', 'nittaku', 'Genextion', 12),
  ('rubber', 'nittaku', 'Renanos Hold', 13),
  ('rubber', 'nittaku', 'Fastarc P-1', 14),
  ('rubber', 'nittaku', 'Fastarc H-1', 15),
  ('rubber', 'nittaku', 'Fastarc B-1', 16),
  ('rubber', 'nittaku', 'Hammond Pro Beta', 17),
  ('rubber', 'nittaku', 'Hammond FA', 18),
  ('rubber', 'nittaku', 'Moristo DF', 19),
  ('rubber', 'nittaku', 'Renanos Bright', 20),
  ('rubber', 'nittaku', 'Renanos Soft', 21),
  ('rubber', 'nittaku', 'Flyatt', 22),
  ('rubber', 'nittaku', 'Flyatt Spin', 23),
  ('rubber', 'nittaku', 'Narucross EX Hard', 24),
  ('rubber', 'nittaku', 'Narucross EX Soft', 25),
  ('rubber', 'nittaku', 'Sieger PK50', 26),
  ('rubber', 'nittaku', 'Sieger PK50 FX', 27),
  ('rubber', 'nittaku', 'Sieger PK50 Hard', 28),
  ('rubber', 'nittaku', 'PK50', 29),
  ('rubber', 'nittaku', 'PK50 FX', 30),
  ('rubber', 'nittaku', 'Hurricane Pro 2', 31),
  ('rubber', 'nittaku', 'Hurricane Pro 3', 32),
  ('rubber', 'nittaku', 'Magic Carbon', 33),
  ('rubber', 'nittaku', 'Refoma', 34),
  ('rubber', 'nittaku', 'Beautry', 35),
  ('rubber', 'nittaku', 'Ares', 36),
  ('rubber', 'nittaku', 'Mima Ito M-50', 37),
  ('rubber', 'nittaku', 'Hammond Power', 38),
  ('rubber', 'nittaku', 'Moristo SP 44', 39),
  ('rubber', 'nittaku', 'Wallest One', 40),
  ('rubber', 'nittaku', 'Do Knuckle Super Soft', 41),
  ('rubber', 'victas', 'V > 20 Double Extra', 0),
  ('rubber', 'victas', 'V > 22 Double Extra', 1),
  ('rubber', 'victas', 'V > 15 Extra', 2),
  ('rubber', 'victas', 'V > 15 Limber', 3),
  ('rubber', 'victas', 'V > 11 Extra', 4),
  ('rubber', 'victas', 'V > 01', 5),
  ('rubber', 'victas', 'Ventus Extra', 6),
  ('rubber', 'victas', 'Ventus Limber', 7),
  ('rubber', 'victas', 'Ventus Regular', 8),
  ('rubber', 'victas', 'Triple Double Extra', 9),
  ('rubber', 'victas', 'VO > 102', 10),
  ('rubber', 'victas', 'VO > 101', 11),
  ('rubber', 'victas', 'Curl P1V', 12),
  ('rubber', 'victas', 'Curl P4V', 13),
  ('rubber', 'victas', 'Curl P5V', 14),
  ('rubber', 'victas', 'Spinpips D3', 15),
  ('rubber', 'victas', 'V > 03', 16),
  ('rubber', 'victas', 'V > 20 Extra', 17),
  ('rubber', 'victas', 'V > 15 Stiff', 18),
  ('rubber', 'victas', 'V > 01 Stiff', 19),
  ('rubber', 'victas', 'V > 01 Limber', 20),
  ('rubber', 'victas', 'V > 01 Extra', 21),
  ('rubber', 'victas', 'Ventus Stiff', 22),
  ('rubber', 'victas', 'Triple Extra', 23),
  ('rubber', 'victas', 'Triple Regular', 24),
  ('rubber', 'victas', 'VS > 401', 25),
  ('rubber', 'victas', 'VS > 402 Double Extra', 26),
  ('rubber', 'victas', 'Spectol', 27),
  ('rubber', 'victas', 'Spectol S1', 28),
  ('rubber', 'victas', 'Spectol S2', 29),
  ('rubber', 'victas', 'Spectol S3', 30),
  ('rubber', 'victas', 'VO > 103', 31),
  ('rubber', 'victas', 'Spinpips D1', 32),
  ('rubber', 'victas', 'Spinpips D2', 33),
  ('rubber', 'victas', 'Spinpips D2 Plus', 34),
  ('rubber', 'victas', 'Curl P2V', 35),
  ('rubber', 'victas', 'Curl P3V', 36),
  ('rubber', 'victas', 'Regular Alpha', 37),
  ('rubber', 'victas', 'Regular', 38),
  ('rubber', 'victas', 'Limber', 39),
  ('rubber', 'victas', 'Ventus Spin', 40),
  ('rubber', 'victas', 'VJ > 07 Regular', 41),
  ('rubber', 'victas', 'VJ > 07 Stiff', 42),
  ('rubber', 'victas', 'VJ > 07 Limber', 43),
  ('rubber', 'joola', 'Dynaryz ZGR', 0),
  ('rubber', 'joola', 'Dynaryz ACC', 1),
  ('rubber', 'joola', 'Dynaryz AGR', 2),
  ('rubber', 'joola', 'Rhyzen Fire', 3),
  ('rubber', 'joola', 'Rhyzen Ice', 4),
  ('rubber', 'joola', 'Rhyzen CMD', 5),
  ('rubber', 'joola', 'Tronix ACC', 6),
  ('rubber', 'joola', 'Tronix ZGR', 7),
  ('rubber', 'joola', 'Rhyzer 48', 8),
  ('rubber', 'joola', 'Rhyzer 43', 9),
  ('rubber', 'joola', 'Micron', 10),
  ('rubber', 'joola', 'Express Ultra', 11),
  ('rubber', 'joola', 'Tango Ultra', 12),
  ('rubber', 'joola', 'CWX', 13),
  ('rubber', 'joola', 'Octopus', 14),
  ('rubber', 'joola', 'Dynaryz CMD', 15),
  ('rubber', 'joola', 'Dynaryz Inferno', 16),
  ('rubber', 'joola', 'Tronix CMD', 17),
  ('rubber', 'joola', 'Rhyzen ZGR', 18),
  ('rubber', 'joola', 'Rhyzen ICE Max', 19),
  ('rubber', 'joola', 'Rhyzer Pro 45', 20),
  ('rubber', 'joola', 'Rhyzer Pro 50', 21),
  ('rubber', 'joola', 'Rhyzm', 22),
  ('rubber', 'joola', 'Rhyzm-P', 23),
  ('rubber', 'joola', 'Rhyzm-Tech', 24),
  ('rubber', 'joola', 'Maxxx 400', 25),
  ('rubber', 'joola', 'Maxxx 450', 26),
  ('rubber', 'joola', 'Maxxx 500', 27),
  ('rubber', 'joola', 'Maxxx P', 28),
  ('rubber', 'joola', 'Golden Tango', 29),
  ('rubber', 'joola', 'Golden Tango PS', 30),
  ('rubber', 'joola', 'Golden Tango XH', 31),
  ('rubber', 'joola', 'Energy X-tra', 32),
  ('rubber', 'joola', 'Samba', 33),
  ('rubber', 'joola', 'Samba Plus', 34),
  ('rubber', 'joola', 'Zack', 35),
  ('rubber', 'joola', 'Zack Plus', 36),
  ('rubber', 'joola', 'Explode', 37),
  ('rubber', 'joola', 'Explosion Extreme', 38),
  ('rubber', 'joola', 'X-plode Sensitive', 39),
  ('rubber', 'joola', 'Phyzic', 40),
  ('rubber', 'joola', 'Phyzic 375', 41),
  ('rubber', 'joola', 'Micron 48', 42),
  ('rubber', 'joola', 'Octopus Prime', 43),
  ('rubber', 'cornilleau', 'Target Pro GT H47', 0),
  ('rubber', 'cornilleau', 'Target Pro GT M43', 1),
  ('rubber', 'cornilleau', 'Target Pro GT X51', 2),
  ('rubber', 'cornilleau', 'Target Pro XD 52.5', 3),
  ('rubber', 'cornilleau', 'Target Pro XD 47.5', 4),
  ('rubber', 'cornilleau', 'Drive Spin', 5),
  ('rubber', 'cornilleau', 'Drive Intens', 6),
  ('rubber', 'cornilleau', 'Pilot Advance', 7),
  ('rubber', 'cornilleau', 'Pulse Racer', 8),
  ('rubber', 'cornilleau', 'Start Up Evo', 9),
  ('rubber', 'cornilleau', 'Target Pro GT S39', 10),
  ('rubber', 'cornilleau', 'Target Pro XD 60', 11),
  ('rubber', 'cornilleau', 'Target Pro GT-X12', 12),
  ('rubber', 'cornilleau', 'Pilot Fast', 13),
  ('rubber', 'cornilleau', 'Pilot Power', 14),
  ('rubber', 'cornilleau', 'Pilot Sound', 15),
  ('rubber', 'cornilleau', 'Pilot Pulse', 16),
  ('rubber', 'cornilleau', 'Pilot Control', 17),
  ('rubber', 'cornilleau', 'Perform 500', 18),
  ('rubber', 'cornilleau', 'Perform 800', 19),
  ('rubber', 'cornilleau', 'Perform 900', 20),
  ('rubber', 'cornilleau', 'Softbat', 21),
  ('rubber', 'cornilleau', 'Advance', 22),
  ('rubber', 'cornilleau', 'Tacteo Spin', 23),
  ('rubber', 'cornilleau', 'Tacteo Drive', 24),
  ('rubber', 'gewo', 'Nexxus EL Pro 48', 0),
  ('rubber', 'gewo', 'Nexxus EL Pro 43', 1),
  ('rubber', 'gewo', 'Nexxus XT Pro 50', 2),
  ('rubber', 'gewo', 'Nexxus XT Pro 43', 3),
  ('rubber', 'gewo', 'Nexxus SuperSelect 45', 4),
  ('rubber', 'gewo', 'Nexxus SuperSelect 50', 5),
  ('rubber', 'gewo', 'Hype EL Pro 47.5', 6),
  ('rubber', 'gewo', 'Hype XT Pro 50', 7),
  ('rubber', 'gewo', 'Codexx Pro 52', 8),
  ('rubber', 'gewo', 'Codexx EF Pro 54', 9),
  ('rubber', 'gewo', 'Inventus XT Pro 47.5', 10),
  ('rubber', 'gewo', 'Inventus EL Pro 47.5', 11),
  ('rubber', 'gewo', 'Elaxxon eFT 45.0', 12),
  ('rubber', 'gewo', 'Elaxxon eFT 50.0', 13),
  ('rubber', 'gewo', 'Codexx Pro 50', 14),
  ('rubber', 'gewo', 'Nexxus EL Pro 38', 15),
  ('rubber', 'gewo', 'Nexxus EL Pro 53 Hard', 16),
  ('rubber', 'gewo', 'Nexxus XT Pro 48', 17),
  ('rubber', 'gewo', 'Nexxus XT Pro 53 Hard', 18),
  ('rubber', 'gewo', 'Nexxus SuperSelect 40', 19),
  ('rubber', 'gewo', 'Nexxus SuperSelect 53', 20),
  ('rubber', 'gewo', 'Hype KR Pro 47.5', 21),
  ('rubber', 'gewo', 'Hype XT Pro 47.5', 22),
  ('rubber', 'gewo', 'Hype EL Pro 40.0', 23),
  ('rubber', 'gewo', 'Codexx Pro 53', 24),
  ('rubber', 'gewo', 'Codexx Pro 54', 25),
  ('rubber', 'gewo', 'Codexx EL Pro 52', 26),
  ('rubber', 'gewo', 'Codexx EF Pro 52', 27),
  ('rubber', 'gewo', 'Inventus XT Pro 50.0', 28),
  ('rubber', 'gewo', 'Inventus XT Pro 52.5', 29),
  ('rubber', 'gewo', 'Inventus EL Pro 37.5', 30),
  ('rubber', 'gewo', 'Inventus EL Pro 42.5', 31),
  ('rubber', 'gewo', 'Elaxxon eFT 40.0', 32),
  ('rubber', 'gewo', 'Elaxxon eFT 48.0', 33),
  ('rubber', 'gewo', 'eTEC SuperSoft', 34),
  ('rubber', 'gewo', 'eTEC Hard', 35),
  ('rubber', 'gewo', 'NanoFlex FT40', 36),
  ('rubber', 'gewo', 'NanoFlex FT45', 37),
  ('rubber', 'gewo', 'NanoFlex FT48', 38),
  ('rubber', 'gewo', 'Neoflexx eFT 45', 39),
  ('rubber', 'gewo', 'Neoflexx eFT 48', 40),
  ('rubber', 'gewo', 'Neoflexx eFT 50', 41),
  ('rubber', 'gewo', 'Proton Neo 325', 42),
  ('rubber', 'gewo', 'Proton Neo 375', 43),
  ('rubber', 'gewo', 'Proton Neo 450', 44),
  ('rubber', 'double-fish', 'Volant Phoenix 1', 0),
  ('rubber', 'double-fish', 'Volant Phoenix 2', 1),
  ('rubber', 'double-fish', 'Volant Phoenix Soft', 2),
  ('rubber', 'double-fish', 'Super 999T', 3),
  ('rubber', 'double-fish', '555', 4),
  ('rubber', 'double-fish', '815A', 5),
  ('rubber', 'double-fish', '1615', 6),
  ('rubber', 'double-fish', 'C7', 7),
  ('rubber', 'double-fish', 'Volant Phoenix 3', 8),
  ('rubber', 'double-fish', 'Volant Phoenix Hard', 9),
  ('rubber', 'double-fish', 'Volant Phoenix Medium', 10),
  ('rubber', 'double-fish', 'Volant Phoenix Tacky', 11),
  ('rubber', 'double-fish', 'Volant Phoenix 4', 12),
  ('rubber', 'double-fish', '218', 13),
  ('rubber', 'double-fish', '218 Spin', 14),
  ('rubber', 'double-fish', '388A-4', 15),
  ('rubber', 'double-fish', '388C-1', 16),
  ('rubber', 'double-fish', '388D-1', 17),
  ('rubber', 'double-fish', 'Double Fish 1615A', 18),
  ('rubber', 'double-fish', 'Double Fish 1615C', 19),
  ('rubber', 'double-fish', '8338', 20),
  ('rubber', 'double-fish', '8338-1', 21),
  ('rubber', 'double-fish', '999T', 22),
  ('rubber', 'friendship-729', '729 Friendship', 0),
  ('rubber', 'friendship-729', '729 FX', 1),
  ('rubber', 'friendship-729', '729 Super FX', 2),
  ('rubber', 'friendship-729', 'Battle II', 3),
  ('rubber', 'friendship-729', 'Battle II Provincial', 4),
  ('rubber', 'friendship-729', 'Battle III', 5),
  ('rubber', 'friendship-729', 'Bloom Power', 6),
  ('rubber', 'friendship-729', 'Focus III Snipe', 7),
  ('rubber', 'friendship-729', 'Presto Spin', 8),
  ('rubber', 'friendship-729', 'New Cream', 9),
  ('rubber', 'friendship-729', 'Geospin Tacky', 10),
  ('rubber', 'friendship-729', 'Cross', 11),
  ('rubber', 'friendship-729', 'Battle II National', 12),
  ('rubber', 'friendship-729', '729-2', 13),
  ('rubber', 'friendship-729', '729-5', 14),
  ('rubber', 'friendship-729', '729 Faster', 15),
  ('rubber', 'friendship-729', '729 Higher', 16),
  ('rubber', 'friendship-729', '729 Cream', 17),
  ('rubber', 'friendship-729', '729-08', 18),
  ('rubber', 'friendship-729', '729 Aurora', 19),
  ('rubber', 'friendship-729', '729 Focus III', 20),
  ('rubber', 'friendship-729', '729 Focus III Snipe 3', 21),
  ('rubber', 'friendship-729', '729 Battle', 22),
  ('rubber', 'friendship-729', 'Battle II Blue Sponge', 23),
  ('rubber', 'friendship-729', 'Battle II Orange Sponge', 24),
  ('rubber', 'friendship-729', 'Battle II Provincial Blue Sponge', 25),
  ('rubber', 'friendship-729', 'Battle II National Blue Sponge', 26),
  ('rubber', 'friendship-729', 'Battle III Provincial', 27),
  ('rubber', 'friendship-729', 'Battle III National', 28),
  ('rubber', 'friendship-729', 'Bloom', 29),
  ('rubber', 'friendship-729', 'Bloom Spin', 30),
  ('rubber', 'friendship-729', 'Bloom Speed', 31),
  ('rubber', 'friendship-729', 'Presto Speed', 32),
  ('rubber', 'friendship-729', 'Presto Max', 33),
  ('rubber', 'friendship-729', 'GeoSpin', 34),
  ('rubber', 'friendship-729', 'Cross Transcend', 35),
  ('rubber', 'friendship-729', 'Super FX Lightening', 36),
  ('rubber', 'friendship-729', 'FX-C', 37),
  ('rubber', 'friendship-729', '802', 38),
  ('rubber', 'friendship-729', '802-1', 39),
  ('rubber', 'friendship-729', '802-40', 40),
  ('rubber', 'friendship-729', '563', 41),
  ('rubber', 'friendship-729', '755', 42),
  ('rubber', 'friendship-729', '837', 43),
  ('rubber', 'friendship-729', '388D-1', 44),
  ('rubber', 'friendship-729', '388C-1', 45),
  ('rubber', 'friendship-729', '388D', 46),
  ('rubber', 'friendship-729', 'Mystery', 47),
  ('rubber', 'friendship-729', 'Master', 48),
  ('rubber', 'friendship-729', 'RITC 2000', 49),
  ('rubber', 'friendship-729', 'Faster 1', 50),
  ('rubber', 'friendship-729', 'Higher Transcend', 51),
  ('rubber', 'dr-neubauer', 'Killer Pro', 0),
  ('rubber', 'dr-neubauer', 'Aggressor Evo', 1),
  ('rubber', 'dr-neubauer', 'Trouble Maker', 2),
  ('rubber', 'dr-neubauer', 'Desperado Reloaded', 3),
  ('rubber', 'dr-neubauer', 'Buffalo', 4),
  ('rubber', 'dr-neubauer', 'A-B-S 3', 5),
  ('rubber', 'dr-neubauer', 'Best Anti', 6),
  ('rubber', 'dr-neubauer', 'Dominance Spin', 7),
  ('rubber', 'dr-neubauer', 'Explosion Pro', 8),
  ('rubber', 'dr-neubauer', 'Super Defense 40', 9),
  ('rubber', 'dr-neubauer', 'Killer Extreme', 10),
  ('rubber', 'dr-neubauer', 'Killer', 11),
  ('rubber', 'dr-neubauer', 'Aggressor', 12),
  ('rubber', 'dr-neubauer', 'Trouble Maker Reloaded', 13),
  ('rubber', 'dr-neubauer', 'Desperado 2', 14),
  ('rubber', 'dr-neubauer', 'Desperado 3', 15),
  ('rubber', 'dr-neubauer', 'Buffalo+', 16),
  ('rubber', 'dr-neubauer', 'A-B-S 2', 17),
  ('rubber', 'dr-neubauer', 'A-B-S', 18),
  ('rubber', 'dr-neubauer', 'Domination', 19),
  ('rubber', 'dr-neubauer', 'Tarantula', 20),
  ('rubber', 'dr-neubauer', 'Tornado Supreme', 21),
  ('rubber', 'dr-neubauer', 'Diamant', 22),
  ('rubber', 'dr-neubauer', 'Grizzly', 23),
  ('rubber', 'dr-neubauer', 'Grizzly ABS', 24),
  ('rubber', 'dr-neubauer', 'Bison', 25),
  ('rubber', 'dr-neubauer', 'Power Attack', 26),
  ('rubber', 'dr-neubauer', 'Special', 27),
  ('rubber', 'dr-neubauer', 'Pistol', 28),
  ('rubber', 'dr-neubauer', 'Elimination Extra Long', 29),
  ('rubber', 'dr-neubauer', 'Screamer', 30),
  ('rubber', 'dr-neubauer', 'Road', 31),
  ('rubber', 'dr-neubauer', 'Explosion', 32),
  ('rubber', 'dr-neubauer', 'Booster SA', 33),
  ('rubber', 'dr-neubauer', 'Piranja Formula TE', 34),
  ('rubber', 'der-materialspezialist', 'Beast', 0),
  ('rubber', 'der-materialspezialist', 'Hellfire X', 1),
  ('rubber', 'der-materialspezialist', 'Transformer', 2),
  ('rubber', 'der-materialspezialist', 'Scandal', 3),
  ('rubber', 'der-materialspezialist', 'Flashback', 4),
  ('rubber', 'der-materialspezialist', 'Spectre', 5),
  ('rubber', 'der-materialspezialist', 'Wizard', 6),
  ('rubber', 'der-materialspezialist', 'Superwall', 7),
  ('rubber', 'der-materialspezialist', 'Power Defence', 8),
  ('rubber', 'der-materialspezialist', 'Spin Parasite', 9),
  ('rubber', 'der-materialspezialist', 'Beast Pro', 10),
  ('rubber', 'der-materialspezialist', 'Hellfire', 11),
  ('rubber', 'der-materialspezialist', 'Cobra', 12),
  ('rubber', 'der-materialspezialist', 'Kamikaze', 13),
  ('rubber', 'der-materialspezialist', 'Sorcerer', 14),
  ('rubber', 'der-materialspezialist', 'Predator', 15),
  ('rubber', 'der-materialspezialist', 'Insider', 16),
  ('rubber', 'der-materialspezialist', 'Firewall Plus', 17),
  ('rubber', 'der-materialspezialist', 'Wildfire', 18),
  ('rubber', 'der-materialspezialist', 'Shockwave', 19),
  ('rubber', 'der-materialspezialist', 'Master Anti', 20),
  ('rubber', 'der-materialspezialist', 'Anti Spin', 21),
  ('rubber', 'der-materialspezialist', 'Slick', 22),
  ('rubber', 'der-materialspezialist', 'Bison', 23),
  ('rubber', 'der-materialspezialist', 'Switch Plus', 24),
  ('rubber', 'der-materialspezialist', 'Gorilla', 25),
  ('rubber', 'spinlord', 'Strahlkraft', 0),
  ('rubber', 'spinlord', 'Keiler', 1),
  ('rubber', 'spinlord', 'Dornenglanz III', 2),
  ('rubber', 'spinlord', 'Gepard', 3),
  ('rubber', 'spinlord', 'Marder IV', 4),
  ('rubber', 'spinlord', 'Marder II', 5),
  ('rubber', 'spinlord', 'Waran III', 6),
  ('rubber', 'spinlord', 'Tanuki', 7),
  ('rubber', 'spinlord', 'Tiger', 8),
  ('rubber', 'spinlord', 'Ageten', 9),
  ('rubber', 'spinlord', 'Warrior', 10),
  ('rubber', 'spinlord', 'Keiler II', 11),
  ('rubber', 'spinlord', 'Dornenglanz', 12),
  ('rubber', 'spinlord', 'Dornenglanz II', 13),
  ('rubber', 'spinlord', 'Marder', 14),
  ('rubber', 'spinlord', 'Marder III', 15),
  ('rubber', 'spinlord', 'Waran', 16),
  ('rubber', 'spinlord', 'Waran II', 17),
  ('rubber', 'spinlord', 'Sternenfall', 18),
  ('rubber', 'spinlord', 'Blitzschlag', 19),
  ('rubber', 'spinlord', 'Sandwind', 20),
  ('rubber', 'spinlord', 'Gipfelsturm', 21),
  ('rubber', 'spinlord', 'Irbis', 22),
  ('rubber', 'spinlord', 'Ozelot', 23),
  ('rubber', 'spinlord', 'Minotaur', 24),
  ('rubber', 'spinlord', 'Leopard', 25),
  ('rubber', 'spinlord', 'Brod', 26),
  ('rubber', 'spinlord', 'Wyvern', 27),
  ('rubber', 'spinlord', 'Stachelfeuer', 28),
  ('rubber', 'sauer-troeger', 'Monkey', 0),
  ('rubber', 'sauer-troeger', 'K.O.', 1),
  ('rubber', 'sauer-troeger', 'H.Z.', 2),
  ('rubber', 'sauer-troeger', 'Hipster', 3),
  ('rubber', 'sauer-troeger', 'Easy P', 4),
  ('rubber', 'sauer-troeger', 'Taurus', 5),
  ('rubber', 'sauer-troeger', 'Zargus', 6),
  ('rubber', 'sauer-troeger', 'Hellfire X', 7),
  ('rubber', 'sauer-troeger', 'Hellfire', 8),
  ('rubber', 'sauer-troeger', 'Hellfire 2', 9),
  ('rubber', 'sauer-troeger', 'Easy P OX', 10),
  ('rubber', 'sauer-troeger', 'Easy P Medium', 11),
  ('rubber', 'sauer-troeger', 'Secret Flow', 12),
  ('rubber', 'sauer-troeger', 'Secret Flow Chop', 13),
  ('rubber', 'sauer-troeger', 'Firestarter', 14),
  ('rubber', 'sauer-troeger', 'Razor', 15),
  ('rubber', 'sauer-troeger', 'Tornado X', 16),
  ('rubber', 'sauer-troeger', 'K.O. Pro', 17),
  ('rubber', 'sauer-troeger', 'Monkey Fast', 18),
  ('rubber', 'hallmark', 'Devil Anti', 0),
  ('rubber', 'hallmark', 'Phoenix', 1),
  ('rubber', 'hallmark', 'Mirage', 2),
  ('rubber', 'hallmark', 'Illusion', 3),
  ('rubber', 'hallmark', 'Clutter', 4),
  ('rubber', 'hallmark', 'Frustration 2', 5),
  ('rubber', 'hallmark', 'Confusion-LP', 6),
  ('rubber', 'hallmark', 'Super Anti', 7),
  ('rubber', 'hallmark', 'Frustration', 8),
  ('rubber', 'hallmark', 'Super Defence', 9),
  ('rubber', 'hallmark', 'Tactics LP', 10),
  ('rubber', 'hallmark', 'Tactics MT', 11),
  ('rubber', 'hallmark', 'Strategy', 12),
  ('rubber', 'hallmark', 'Strategy LP', 13),
  ('rubber', 'hallmark', 'Wonder', 14),
  ('rubber', 'hallmark', 'Phoenix Special', 15),
  ('rubber', 'hallmark', 'Chaos', 16),
  ('rubber', 'hallmark', 'Trickster', 17),
  ('rubber', 'palio', 'CJ8000', 0),
  ('rubber', 'palio', 'CJ8000 Biotech', 1),
  ('rubber', 'palio', 'CJ8000 Extreme Speed', 2),
  ('rubber', 'palio', 'AK47 Blue', 3),
  ('rubber', 'palio', 'AK47 Red', 4),
  ('rubber', 'palio', 'AK47 Yellow', 5),
  ('rubber', 'palio', 'Thor''s', 6),
  ('rubber', 'palio', 'HK1997', 7),
  ('rubber', 'palio', 'Hidden Dragon', 8),
  ('rubber', 'palio', 'CK531A', 9),
  ('rubber', 'palio', 'AK47 Hybrid', 10),
  ('rubber', 'palio', 'CJ8000 Extreme Spin', 11),
  ('rubber', 'palio', 'CJ8000 Loop', 12),
  ('rubber', 'palio', 'AK47 Orange', 13),
  ('rubber', 'palio', 'AK47 Gold', 14),
  ('rubber', 'palio', 'Thor''s Special', 15),
  ('rubber', 'palio', 'Thor''s II', 16),
  ('rubber', 'palio', 'HK1997 Biotech', 17),
  ('rubber', 'palio', 'Hidden Dragon 40+', 18),
  ('rubber', 'palio', 'CK531A Pro', 19),
  ('rubber', 'palio', 'Hadou 35', 20),
  ('rubber', 'palio', 'Hadou 40+', 21),
  ('rubber', 'palio', 'Blitz', 22),
  ('rubber', 'palio', 'Blitz 47', 23),
  ('rubber', 'palio', 'Macro Era 42.5', 24),
  ('rubber', 'palio', 'Macro Era 47.5', 25),
  ('rubber', 'palio', 'Expert 2', 26),
  ('rubber', 'palio', 'Jet & Loop', 27),
  ('rubber', 'palio', 'Jet & Spin', 28),
  ('rubber', 'palio', 'Palio 999', 29),
  ('rubber', 'palio', 'Legend 2', 30),
  ('rubber', 'palio', 'Master', 31),
  ('rubber', 'palio', 'Aces', 32),
  ('rubber', 'palio', 'Hero', 33),
  ('rubber', 'palio', 'Conqueror', 34)
ON CONFLICT (category, manufacturer_id, model) DO UPDATE
SET sort_order = EXCLUDED.sort_order;

CREATE TABLE IF NOT EXISTS public.equipment_history (
  id BIGSERIAL PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  blade_manufacturer_id TEXT NOT NULL,
  blade_manufacturer TEXT NOT NULL,
  blade_model TEXT NOT NULL,
  forehand_rubber_manufacturer_id TEXT NOT NULL,
  forehand_rubber_manufacturer TEXT NOT NULL,
  forehand_rubber_model TEXT NOT NULL,
  forehand_rubber_color TEXT NOT NULL CHECK (forehand_rubber_color IN ('red', 'black', 'pink', 'blue', 'purple', 'green')),
  backhand_rubber_manufacturer_id TEXT NOT NULL,
  backhand_rubber_manufacturer TEXT NOT NULL,
  backhand_rubber_model TEXT NOT NULL,
  backhand_rubber_color TEXT NOT NULL CHECK (backhand_rubber_color IN ('red', 'black')),
  dominant_hand TEXT NOT NULL CHECK (dominant_hand IN ('right', 'left')),
  playing_style TEXT NOT NULL CHECK (playing_style IN ('attacker', 'defender', 'all_rounder')),
  grip TEXT NOT NULL CHECK (grip IN ('shakehand', 'penhold', 'other')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.equipment_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can read their equipment history" ON public.equipment_history;
CREATE POLICY "Users can read their equipment history"
  ON public.equipment_history
  FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their equipment history" ON public.equipment_history;
CREATE POLICY "Users can insert their equipment history"
  ON public.equipment_history
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_equipment_history_user_created
  ON public.equipment_history(user_id, created_at DESC);

COMMIT;

