-- Align Pack 2/3 challenge fallback titles with reviewed i18n source strings.
-- Display still resolves through title_key; this keeps DB exports/fallbacks consistent.

with reviewed_titles(code, title) as (
  values
    ('ATK201', 'Plan a serve and expected return before serving'),
    ('ATK202', 'Serve short, return a push, and play a safe opening'),
    ('ATK203', 'Attack the fourth ball after your opponent opens first'),
    ('ATK204', 'Practice 10 shadow first-attack movements from ready stance'),
    ('ATK205', 'Open safely to the middle instead of going for the line'),
    ('ATK206', 'Return a long serve and start the rally with a controlled topspin'),
    ('ATK207', 'Execute a fifth-ball follow-up after your first attack is blocked'),
    ('ATK208', 'Play one set where every attack starts at 70% power'),
    ('ATK209', 'Win a point by attacking after a passive return'),
    ('ATK210', 'Practice 10 sequences of serve, recovery, and shadow attack'),
    ('ATK211', 'Choose placement before speed on three opening attacks'),
    ('ATK212', 'Force a weak return with serve placement, then attack safely'),
    ('ATK301', 'Practice 10 sequences for returning a serve and making the first attack'),
    ('ATK302', 'Attack safely after your opponent gives you the first long ball'),
    ('ATK303', 'Use a controlled opening to set up the next ball, not finish immediately'),
    ('ATK304', 'Play one set where your first attack always goes to the middle zone'),
    ('ATK305', 'Win a point with a fourth-ball counter after your return is blocked'),
    ('ATK306', 'Start three rallies with a safe opening instead of a risky winner attempt'),
    ('ATK307', 'Use serve placement to earn a predictable block, then continue the attack'),
    ('ATK308', 'Attack once down the line only after first moving the opponent crosscourt'),
    ('CMP201', 'Win a point after choosing a safe target under pressure'),
    ('CMP202', 'Play a set where you track your serve mistakes'),
    ('CMP203', 'Win two points by attacking the middle area or elbow'),
    ('CMP204', 'Win a point after receiving short and keeping the ball low'),
    ('CMP205', 'Play a best-of-three with one tactical goal per set'),
    ('CMP206', 'Save one game point with a planned serve or serve return'),
    ('CMP207', 'Start a set by testing three different placements'),
    ('CMP208', 'Win one point by deliberately slowing the rally down'),
    ('CMP209', 'Play one match and note your most repeated error'),
    ('CMP210', 'Win a point using two placements before the final shot'),
    ('CMP211', 'Play a set where you avoid your favorite risky shot'),
    ('CMP212', 'Adapt your serve return after losing twice to the same serve'),
    ('CMP301', 'Win a point by changing placement after two similar rallies'),
    ('CMP302', 'Track your first three lost points and identify the pattern'),
    ('CMP303', 'Play one set where you avoid giving two easy errors in a row'),
    ('CMP304', 'Win a point by attacking the open court after moving your opponent'),
    ('CMP305', 'Save a point by choosing a safer return'),
    ('CMP306', 'Play a match where you test short, deep, and middle placement early'),
    ('CMP307', 'Win a rally after changing tempo once'),
    ('CMP308', 'Adapt your serve choice after your opponent attacks one serve twice'),
    ('CRF201', 'Write down one tactical lesson after a session'),
    ('CRF202', 'Play one set with a clear breathing routine before each point'),
    ('CRF203', 'Lose a point, reset, and win one of the next two points'),
    ('CRF204', 'Ask your opponent what pattern bothered them most'),
    ('CRF205', 'Play a full match using one simple tactical plan'),
    ('CRF206', 'Change your plan after losing three similar points'),
    ('CRF207', 'Compliment one specific good shot from your opponent'),
    ('CRF208', 'Keep the same serve routine for every serve in one set'),
    ('CRF209', 'Play one set where you choose placement over power'),
    ('CRF210', 'Identify your opponent’s strongest shot during a match'),
    ('CRF211', 'Win a point using patience after choosing not to attack early'),
    ('CRF212', 'Review one recorded rally and name your first mistake'),
    ('CRF301', 'Name your main mistake before starting the next set'),
    ('CRF302', 'Play one set without rushing between points'),
    ('CRF303', 'Ask your opponent for one tactical observation after the match'),
    ('CRF304', 'Change only one tactical variable after losing a set'),
    ('CRF305', 'Win a point after deliberately extending the rally instead of attacking'),
    ('CRF306', 'Play a match where you track whether you lost points from risk or placement'),
    ('CRF307', 'Recover from two net balls or edge balls against you without complaining'),
    ('CRF308', 'Use the same calm routine before every serve return in one set'),
    ('DEF201', 'Block 5 medium-speed attacks with soft hands'),
    ('DEF202', 'Keep 5 defensive balls deep instead of short'),
    ('DEF203', 'Absorb a strong attack and reset the rally once'),
    ('DEF204', 'Change block placement from middle to wide once in a rally'),
    ('DEF205', 'Practice 15 shadow blocks with compact racket movement'),
    ('DEF206', 'Defend one point without panicking after being pushed back'),
    ('DEF207', 'Use a soft block to slow down one fast rally'),
    ('DEF208', 'Return one attack with a deep safety ball instead of a counter'),
    ('DEF209', 'Block one topspin to the opponent’s weaker side'),
    ('DEF210', 'Stay low through a full defensive rally'),
    ('DEF211', 'Practice 10 shadow chop swings with stable balance'),
    ('DEF212', 'Win a point after turning a defensive reset into neutral play'),
    ('DEF301', 'Practice 15 compact block shadow movements without backswing'),
    ('DEF302', 'Block one fast ball softly enough to change the rally speed'),
    ('DEF303', 'Return a wide attack crosscourt with controlled height instead of forcing a winner'),
    ('DEF304', 'Keep three defensive balls deep to prevent an easy smash'),
    ('DEF305', 'Reset one rally by blocking to the middle transition zone'),
    ('DEF306', 'Practice 10 low-stance defensive recovery movements'),
    ('DEF307', 'Use one controlled block to make the attacker move first'),
    ('DEF308', 'Stay calm and continue defending after one strong opponent attack'),
    ('EXP201', 'Play one friendly target game before or after a match'),
    ('EXP202', 'Try a table rotation mini game with at least 3 players'),
    ('EXP203', 'Teach a beginner how to hold the racket safely'),
    ('EXP204', 'Play at a table you have not used before at the same venue'),
    ('EXP205', 'Organize a 10-minute doubles rotation'),
    ('EXP206', 'Ask a new opponent what style they enjoy playing'),
    ('EXP207', 'Play a cooperative rally challenge instead of a match'),
    ('EXP208', 'Create a mini target challenge using safe table objects'),
    ('EXP209', 'Try one mixed-level practice where the stronger player uses less power'),
    ('EXP210', 'Record a short note about a venue’s table quality after playing'),
    ('EXP211', 'Play a doubles point where every player touches the ball during the rally'),
    ('EXP212', 'End a session by naming the most enjoyable rally of the day'),
    ('EXP301', 'Play one cooperative rally where the goal is 20 total contacts'),
    ('EXP302', 'Try a mini target game with a friend after the main session'),
    ('EXP303', 'Invite a player of a different level to one short practice drill'),
    ('EXP304', 'Note one useful detail about a venue that other players should know'),
    ('EXP305', 'Play one doubles rotation where partners switch after each mini game'),
    ('EXP306', 'Try 5 minutes of rally practice with no score, focused only on rhythm'),
    ('EXP307', 'Ask a new playing partner what kind of practice they prefer'),
    ('EXP308', 'End a session by saving one positive note about your progress'),
    ('FTW201', 'Practice 20 shadow side steps without crossing your feet'),
    ('FTW202', 'Complete a two-corner movement drill for 30 seconds'),
    ('FTW203', 'Recover to neutral after three wide balls in one rally'),
    ('FTW204', 'Use small adjustment steps before contacting the ball 5 times'),
    ('FTW205', 'Move wide forehand, recover, then cover middle successfully'),
    ('FTW206', 'Play one rally without standing upright after the first shot'),
    ('FTW207', 'Complete 10 shadow pivot and recovery movements'),
    ('FTW208', 'Switch from backhand corner to forehand corner and stay balanced'),
    ('FTW209', 'Play a controlled rally where every shot includes a recovery step'),
    ('FTW210', 'Do 3 minutes of table-side footwork before playing'),
    ('FTW211', 'React correctly to two random placements from a partner'),
    ('FTW212', 'Finish a rally while balanced after being moved wide'),
    ('FTW301', 'Do 20 split-step timing movements before your partner feeds the ball'),
    ('FTW302', 'Recover to ready position after every serve return for one full receiving game'),
    ('FTW303', 'Move in for a short ball and recover for the next deep ball'),
    ('FTW304', 'Complete a 30-second shadow drill mixing side steps and in-out movement'),
    ('FTW305', 'Keep balance after changing direction twice in one rally'),
    ('FTW306', 'Play one rally where you adjust with small steps before every contact'),
    ('FTW307', 'Cover the middle after being pulled wide and stay in the point'),
    ('FTW308', 'Finish a footwork drill without crossing your legs during lateral movement'),
    ('SPN201', 'Serve 10 backspin serves and rate their shortness'),
    ('SPN202', 'Land 5 slow topspins with high arc to a target zone'),
    ('SPN203', 'Use a soft brush contact instead of power for one rally'),
    ('SPN204', 'Return 3 no-spin serves without lifting the ball too high'),
    ('SPN205', 'Alternate one heavy push and one softer push 5 times'),
    ('SPN206', 'Win a point by changing from heavy spin to soft placement'),
    ('SPN207', 'Practice 20 shadow brush contacts for topspin mechanics'),
    ('SPN208', 'Return one serve by adjusting your racket angle correctly'),
    ('SPN209', 'Land 5 side-topspin shots safely without trying for winners'),
    ('SPN210', 'Make your opponent misread spin once through variation'),
    ('SPN211', 'Keep 8 pushes low over the net with controlled backspin'),
    ('SPN212', 'Win a point after opening with spin, not speed'),
    ('SPN301', 'Practice 15 slow brush loops focusing only on contact quality'),
    ('SPN302', 'Keep 6 pushes low while changing the amount of spin'),
    ('SPN303', 'Win a point by pushing short after your opponent expects long'),
    ('SPN304', 'Return one heavy underspin ball with a safe lifting topspin'),
    ('SPN305', 'Land 5 no-spin control balls to the same target'),
    ('SPN306', 'Make one serve return using touch instead of swing speed'),
    ('SPN307', 'Use sidespin placement to move your opponent off balance once'),
    ('SPN308', 'Alternate topspin and flatter contact for 8 controlled balls'),
    ('SRV201', 'Serve 10 balls with the same toss height'),
    ('SRV202', 'Hit 3 different serve target zones in one practice session'),
    ('SRV203', 'Serve short to forehand twice without missing'),
    ('SRV204', 'Serve long to the elbow and start the rally safely'),
    ('SRV205', 'Use the same serve motion with two different spins'),
    ('SRV206', 'Practice 20 legal ball tosses without serving'),
    ('SRV207', 'Ask your partner to identify your serve spin after 5 serves'),
    ('SRV208', 'Serve to a target and recover before the return crosses the net'),
    ('SRV209', 'Win one point by serving to the opponent''s weaker return side'),
    ('SRV210', 'Play one service game with only two planned serve patterns'),
    ('SRV211', 'Land 5 half-long serves without drifting too long'),
    ('SRV212', 'Force one predictable return through serve placement'),
    ('SRV301', 'Serve 10 times while keeping the ball visible during the toss'),
    ('SRV302', 'Hit the same serve target 3 times in a row'),
    ('SRV303', 'Use one serve to set up a predictable return direction'),
    ('SRV304', 'Practice 10 serve motions without hitting the ball, focusing on rhythm'),
    ('SRV305', 'Play a service game using only short and half-long serves'),
    ('SRV306', 'Ask your partner which serve was hardest to read and record the answer'),
    ('SRV307', 'Serve safely under pressure at 9-9 or later'),
    ('SRV308', 'Practice 5 legal serves from both forehand and backhand service positions')
)
update public.challenges as c
set
  title = reviewed_titles.title,
  updated_at = now()
from reviewed_titles
where c.code = reviewed_titles.code
  and c.title is distinct from reviewed_titles.title;
